### ISSUE TITLE
Making a class table and more

### ISSUE THREAD

**Issue by TheFreyNjord** [stolksdorf/homebrewery#127]
Browser Type:Mozzila
Version: 46.0.1
Operating System: Windows 7

Issue Description: I am attempting to make a class in the Homebrewery, but soon found out that the class table function has the same dimensions as the half table. Is this a bug or were the dimensions not changed? If you have any solution, please send it as fast as possible, as I'd like to get back to using your amazing program. Also, where did you get the background for the pages and may I have a link?

Brew code to reproduce: <div class='classTable wide'>

**Comment by TheFreyNjord** [comment]
Brew code is the <div class='classTable wide'> code.

**Comment by TheFreyNjord** [comment]
<div class='classTable wide'> is the brew code

**Comment by TheFreyNjord** [comment]
the brew code is the 'classTable wide' code.

**Comment by stolksdorf** [comment]
Looks like column spans aren't supported in Firefox. Well that's fun. Makes me question if wide class tables _ever_ worked in Firefox. Weird. 

If you use Chrome it will work. I can't really fix anything, just have to wait for Firefox to implement this CSS feature.

**Comment by TheFreyNjord** [comment]
Thanks man
