### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rob2ee** [stolksdorf/homebrewery#129]
Can you tell me the background color (or pattern).  I want to make a cover page, but I don't want the line at the bottom, just a blank page.

ThanX!

**Comment by stolksdorf** [comment]
Hey man, I was looking through old issues today and it looks like I completely missed yours when you posted it. I'm very sorry. To answer your question (if it's still relevant), you can find a bunch of homebrew resources, including images, [here](https://www.reddit.com/r/UnearthedArcana/comments/3uwxx9/resources_open_to_the_community/)

Or you can just add this style to the top of your brew to remove the line.
```
<style>
.phb::after{
	display:none;
}
</style>
```
