### ISSUE TITLE
Spell List

### ISSUE THREAD

**Issue by PoundTown** [stolksdorf/homebrewery#132]
Nothing major but I did notice when creating a spell list the gold underline does no stay beneath the class name.

---

**Browser Type/Version**: google chrome

**Operating System**: windows 10

**Issue Description**: Gold underline not staying beneath class name in spell list

http://homebrewery.naturalcrit.com/edit/B1eARH4L4

```
PUT YOUR BREW CODE HERE
```

**Related Images** : [IF APPLICABLE]

**Comment by stolksdorf** [comment]
I updated your brew with the fix.
