### ISSUE TITLE
The auto page counter stops counting with many pages.

### ISSUE THREAD

**Issue by RoqueDeicide** [stolksdorf/homebrewery#133]
**Browser Type/Version**: Google Chrome 50.0

**Operating System**: Windows 7 SP1

**Issue Description**: When having more then 3 pages and using the auto counter, the count becomes messed up on all pages beyond the 3rd one. Right now all pages beyond 3rd one show 3 as a page number.

**Comment by RoqueDeicide** [comment]
It looks like the counter is only messed up in Web interface when accessing the brew via edit or share link. When previewing the PDF when exporting the counter seems to work fine.

**Comment by stolksdorf** [comment]
Looks like it's an issue with partial page rendering. Fixed with v2.2.3
