### ISSUE TITLE
Spell Table

### ISSUE THREAD

**Issue by PoundTown** [stolksdorf/homebrewery#134]
The spell table is only filling half the page as opposed to the whole thing.
---

**Browser Type/Version**: Chrome

**Operating System**: Windows 10

**Issue Description**:Spell table only conforming to half the page. 

**Brew code to reproduce**:

```
http://homebrewery.naturalcrit.com/edit/Byfw4ZLPV
```

**Related Images** : [IF APPLICABLE]

**Comment by stolksdorf** [comment]
The nature of CSS columns is that it tries to even out the content evenly between each column. A fix for your problem, while being a bit tedious, is to add a vertical spacing div at the end of the spell list and keep increasing it until you get the results you like. I've updated the brew you provided with an example of this.

**Comment by PoundTown** [comment]
I see. What would need to be done to keep it in such a manner that it looks like the PHB? Is their a way to space it to accomplish this? Would it be possible to adjust the snippet so it ismply adheres to a 4 column layout?

**Comment by stolksdorf** [comment]
I'm not sure what you are asking for. I've already provided a solution to make it look like the PHB as much as possible. What is wrong with it?
