### ISSUE TITLE
Description Boxes

### ISSUE THREAD

**Issue by jvaleur** [stolksdorf/homebrewery#135]
If it is in any way possible, and you have the time, adventure description boxes such as the one attached would be a great addition, for those of us using your genius application to create adventurers. 

Thanks again for your awesome tool :)
![image](https://cloud.githubusercontent.com/assets/19764895/15998188/7f1f0f2a-313c-11e6-83ee-0e2ab87ed2c0.png)

**Comment by stolksdorf** [comment]
This feature was asked for a while ago, check it out #63
