### ISSUE TITLE
My brew seems to have been deleted, getting "application error"" 

### ISSUE THREAD

**Issue by Metalboarder** [stolksdorf/homebrewery#138]
**Browser Type/Version**: [Chrome/ Most recent]

**Operating System**: [Windows 10 32 bit]

**Issue Description**: [Brew not accessible "application error"] the link used to be http://homebrewery.naturalcrit.com/share/SybFKJVkH

**Brew code to reproduce**: none

**Comment by stolksdorf** [comment]
Looks to be working now. From 6:10pm UTC  to 7:10pm UTC there were over 1,500 timeout errors on the server. I am currently investigating why this happened.

**Comment by stolksdorf** [comment]
Related to the database migration I had to do a while back. Fixed.
