### ISSUE TITLE
Wide Creature Stat Blocks Displaying in Single Column (Firefox 47.0)

### ISSUE THREAD

**Issue by SequenceComputing** [stolksdorf/homebrewery#139]
---

**Browser Type/Version**: Firefox 47.0

**Operating System**: Windows 10 :(

**Issue Description**: Wide Creature Stat Blocks are displaying in a single column, tried 7.7cm fix as per here (https://github.com/stolksdorf/homebrewery/issues/102) but couldn't get it to work. 

*Sub-Issue*: Spelling of "Remain": _"While the armor reamin motionless"_

**Brew code to reproduce**:
```
___
___
> ## Necrotic Halitosis Angel
>*Gargantuan fiend, annoying evil*
> ___
> - **Armor Class** 13
> - **Hit Points** 114(1d4 + 5)
> - **Speed** 28ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|11 (+1)|2 (-4)|14 (+2)|17 (+4)|5 (-2)|13 (+2)|
>___
> - **Condition Immunities** groovy, groggy, buzzed
> - **Senses** passive Perception 9
> - **Languages** None
> - **Challenge** 3 (4425 XP)
> ___
> ***False Appearance. *** While the armor reamin motionless, it is indistinguishable from a normal suit of armor.
>
> ***False Appearance. *** While the armor reamin motionless, it is indistinguishable from a normal suit of armor.
>
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
>
> ***Pack Tactics.*** These guys work together. Like super well, you don't even know.
> ### Actions
> ***Open Chin Choke.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Corkscrew Strike.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Gory Body Sweep.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
>
> ***Heel Jawbreaker.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 
```

**Related Images** : http://homebrewery.naturalcrit.com/share/H1bZKELEB

**Comment by stolksdorf** [comment]
Firstly, thanks for back-checking previous issue for a fix. It's stuff like that I really appreciate. Unfortunately your issue is due to a Firefox bug. Firefox doesn't support the CSS3 rule `column-span` which is used to make element span both columns. 

Your brew will render properly in Chrome though. I know that might be inconvenient, but there really isn't anything I can do. Sorry about that.
