### ISSUE TITLE
When opening my link to my page, it opens a blank page. 

### ISSUE THREAD

**Issue by MeditatingMunky** [stolksdorf/homebrewery#140]
**Browser Type/Version**: Chrome

**Operating System**: Window 8

**Issue Description**: I have a few pages I am creating lore and stories as well as variant rules in D&D 5e on here, and I have my links posted in a chat forum on Roll20 for easy access to me and a few fellow gaming buddies. However, in my newest titled "...the Villager...", the link is being buggy. When you click on the link it brings you to a blank "Brew" document without any of the information I have typed out. I am able to recover it by saving the "My Awesome Brew v99" blank, and then opening "Recently Edited" file ("...the Villager...") and it's all there, however I need the link to take me to the desired page. The weird part is even after re-opening the correct page, and updating the link with the current address, it STILL takes me to a blank new Brew page and not "...the Villager..." 

**Brew code to reproduce**:-- ????

```
PUT YOUR BREW CODE HERE Link to the page I am speaking about: 

http://homebrewery.naturalcrit.com/edit/Hyg5MnOrH

**Comment by stolksdorf** [comment]
I can't seem to replicate your issue. If I click the link you provided it takes me to the correct page?

**Comment by phaeren12** [comment]
I have this same issue, but only when trying to open brews on my iphone in Safari.

**Comment by stolksdorf** [comment]
If either of you are still having issues, re-open this with more details please. @phaeren12 the site is target to render properly on chrome on desktop, and I don't do any testing or optimization for mobile.

**Comment by HrabiaVulpes** [comment]
I'd like to comment that I had the exact same problem, but disabling AdBlocker and Ghostery helped (it seems brews are considered ads/spyware/trackers for the purpose of those applications)
