### ISSUE TITLE
Side-by-Side Tables

### ISSUE THREAD

**Issue by slitjen** [stolksdorf/homebrewery#141]
It would be nice to be able to somehow have a side-by-side pair of tables in a given column, like these:
![screenshot 2016-06-21 at 8 09 46 am](https://cloud.githubusercontent.com/assets/19520022/16234844/961f7ce0-3787-11e6-96ec-65581873b885.png)
![screenshot 2016-06-21 at 8 07 10 am](https://cloud.githubusercontent.com/assets/19520022/16234869/a63844ae-3787-11e6-8574-c91951418dfd.png)

**Comment by calculuschild** [comment]
You _can_ do it using regular HTML, but it doesn't look super clean in the source code.  It would be nice to have this built in somehow.  But if you are desperate, you can try something like this:

##### Test Table
<table>
<tr style="background-color:transparent">
<td>
	<table>
    <tr><td>**d4**</td><td style="text-align:center">**Ingredient**</td><td>**Cost**</td></tr>
    <tr><td>1</td><td style="text-align:center">Silver Hibiscus</td><td>10 gp</tr>
    <tr><td>2</td><td style="text-align:center">Cactus Flower</td><td>15 gp</td></tr>
    <tr><td>3</td><td style="text-align:center">Silver Hibiscus</td><td>10 gp</td></tr>
    <tr><td>4</td><td style="text-align:center">Silver Hibiscus</td><td>5 gp</td></tr>
    </table>
</td>
<td>
&nbsp;&nbsp;&nbsp;
</td>
<td>
	<table>
    <tr><td>**d4**</td><td style="text-align:center">**Ingredient**</td><td>**Cost**</td></tr>
    <tr><td>1</td><td style="text-align:center">Silver Hibiscus</td><td>10 gp</tr>
    <tr><td>2</td><td style="text-align:center">Cactus Flower</td><td>15 gp</td></tr>
    <tr><td>3</td><td style="text-align:center">Silver Hibiscus</td><td>10 gp</td></tr>
    <tr><td>4</td><td style="text-align:center">Silver Hibiscus</td><td>5 gp</td></tr>
    </table>
</td>
</tr>
</table>

**Comment by Rahbie** [comment]
I have found a way to do this add the following code into a style tag and then create a div around the info you want (ie <div class='twinTable'> put info here </div>
div.twinTable {-webkit-column-count: 2;-moz-column-count: 2;column-count: 2; -webkit-column-gap: 20px;-moz-column-gap: 20px;column-gap: 20px;}

![image](https://cloud.githubusercontent.com/assets/15053903/17484526/5fffe162-5d58-11e6-8513-5d1b6aa5f95c.png)


![image](https://cloud.githubusercontent.com/assets/15053903/17484512/477efdb2-5d58-11e6-822e-5b086bd01241.png)

**Comment by calculuschild** [comment]
Nice work.  This needs to be added to the official code.  Side-by-side tables would be super nice for keeping things compact, and it's the only thing I can think of off the top of my head that the official PHB has that the Homebrewery doesn't support.

**Comment by stolksdorf** [comment]
I'll have to do some testing, as columns-in-columns tend to create some wonky bugs, but otherwise I like the idea of adding this as a snippet. I'll flag this for when I add another set of features.

**Comment by blackwind1kaze** [comment]
@stolksdorf how would one combine columns for some of the table items?

Example: 4 columns, one row only using 2 of the 4 cells but one of the cells you want to expand across a total of 3 columns.

**Comment by stolksdorf** [comment]
@blackwind1kaze If you want that level of customization you'll have to start looking into doing CSS, specifically the [row span property](http://www.w3schools.com/tags/att_td_rowspan.asp).

**Comment by calculuschild** [comment]
@stolksdorf  This can probably be closed.

**Comment by calculuschild** [comment]
This is already added now. Closing.
