### ISSUE TITLE
Title1 (#) doesn't follow columns 

### ISSUE THREAD

**Issue by manolodantonio** [stolksdorf/homebrewery#143]
**Browser Type/Version**: Chrome 51.0.2704.103 m

**Operating System**: Win7

**Issue Description**: Adding a paragraph with a Title 1 (the one marked with a single # that produces an elaborated capital letter on the paragraph) creates the following issues:

1- the Title1 title+paragraph cannot be pushed to right column with any mean - both paging or column break.
2- T1 paragraph seems treated as enclosed in a double column, page wide div.
3- anything before Title1 paragraph is treated as being in a different 2-column page wide div

I don't know if this behavours are inteded or not, but this prevents the creation of chapters with a left column completely occupied by an image.

**Brew code to reproduce**:

http://homebrewery.naturalcrit.com/edit/HJxUTh-OS

----

Beside this, i wanna strongly thank you for your amazing work. Saves me tons of time for great results!

**Comment by stolksdorf** [comment]
This is actually how it is suppose to behave. Sometimes CSS Columns behave intuitively. I suggest [reading up on them](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts) if you have more trouble. When an element spans both columns (such as `h1`) it separates the top and bottom content from each other, so the top now behaves as two separate columns, balancing the content between the columns.
