### ISSUE TITLE
Suggestion: Able to remove the gold filigree on the bottom on one or more pages

### ISSUE THREAD

**Issue by Tsurumah** [stolksdorf/homebrewery#146]
I was wondering if there's some sort of code I can put in that will remove the bottom gold filigree from a single page. If there's not, would there be a way to make that possible?

**Comment by stolksdorf** [comment]
All pages
```
<style>
    .phb::after{display:none;}
</style>
```

Specific page
```
<style>
   #p2::after{display:none;}
</style>
```
