### ISSUE TITLE
Reference style links don't work across multiple pages

### ISSUE THREAD

**Issue by theoneandonlyflexo** [stolksdorf/homebrewery#148]
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: Chrome 

**Operating System**: Windows 7

**Brew code to reproduce**:

```
## The Issue

Reference style links don't work when the definition and usage are on different pages.

[1]: http://homebrewery.naturalcrit.com (...is the best)

[This link works][1]

\page

[This link doesn't work][1]
```

**Comment by stolksdorf** [comment]
This is due to partial page rendering. The Homebrewery will only render a few visible pages at a time so that very long brews won't slow/crash browsers. Since linking is useful, I added a 'Link to page' snippet that let's you jump to specific pages.
