### ISSUE TITLE
Troubles with Tables

### ISSUE THREAD

**Issue by MorrighuRaven** [stolksdorf/homebrewery#151]
Hello there!

One thing which I noticed with the program is that information just keeps going off of the current page instead of being kicked into the second column, mainly with created charts. It requires a great deal of editing on the creator's part to get this just right, and having a way to automatically have this occur would be greatly handy.

**Comment by stolksdorf** [comment]
Please provide some examples :)

**Comment by stolksdorf** [comment]
Re-open this when you can provide some examples.
