### ISSUE TITLE
Losing Track of documents

### ISSUE THREAD

**Issue by mlenser** [stolksdorf/homebrewery#154]
If I don't bookmark my documents I have no way of finding them again.

I'm in a situation where I bookmarked the output, but can't find the edit page anymore (I searched my history).

http://homebrewery.naturalcrit.com/share/Hk_90p_D is the output.

**Comment by stolksdorf** [comment]
Unfortunately, I can't give out the edit link for a share link. However two options for you.

1. I added a 'Recent brews' nav item. It tracks the last 8 brews you've seen and the last 8 you've edited. Unless you've been creating a ton, you should find it in there. 
1. If you have no luck with that. You can just copy the contents from the share link and start a new brew with that. Not the most elegant solution, but it will work.

**Comment by mlenser** [comment]
I see the list of 8, but it is not included. And I've edited it much more recently.

Really unfortunate that I have to start over. I've had this happen a few times now with different files. :(

**Comment by tandroy** [comment]
You don't have to start over. You have the output.

In the top right corner of the page, there is a link that says Source. Click on that, copy it all, paste it into a new brew, bookmark the page.

**Comment by mlenser** [comment]
Ya, but I've shared the link so I have to go replace all of those URLs.

**Comment by stolksdorf** [comment]
There's also your browser history, which will reach

**Comment by mlenser** [comment]
I tried that. I'll try again on my main PC, but it seems I'll have to take the recreate route.
