### ISSUE TITLE
Additional Ideas

### ISSUE THREAD

**Issue by veo1123** [stolksdorf/homebrewery#156]
Let me start off by saying I absolutely love your site and hope that it improves further. I was thinking that maybe (if it isn't too hard) you could have a feature that lets you publish your work publicly and perhaps put them into categories that you could set up. For example, if I made my own race or class and I wanted people to access that file easily without having to post it into Reddit, there could be a public tab and within that tab it would have different categories such as races, classes, backgrounds, campaigns etc. 

Just an idea I had but I think it would be a great as it would make people want to create more of these as it would be easier for others too see them and they could get some recognition. Idk, let me know what you think of the idea. Thanks :)

**Comment by stolksdorf** [comment]
Thanks for the feedback veo1123. I have thought about a better way to share homebrews but it runs away from you pretty quick.

If we just want to search for some homebrews, we'll need key words and meta data. So I'll need to build new interfaces for users to fill those out and validate them, which is more UI clutter. Also all existing brews won't have this info, so they won't be searchable.

If we want some sort of rating system or voting, we'll need to make accounts, which is a nightmare, more flows for the user to worry about. And ultimately I'm just re-creating reddit. 

I'd rather keep things simple and straightforward. I think too many sites try to do too much. 

That being said, the next tool I'm build _will_ have searching and rating and what not ;)
