### ISSUE TITLE
Idea - Accounts?

### ISSUE THREAD

**Issue by ChosenSeraph** [stolksdorf/homebrewery#157]
Heyo, me again ^^ I am having a ton of fun using your site and want to help by giving you ideas for the site. I was wondering if it was possible to have accounts on the site so you could access all of your homebrew pages without having to write down the edit link and not all of your homebrews together. for example: I'm on my PC and have 10-20 homebrews and i want to take my laptop out of town and keep working on my homebrews but it does not carry them over so i would have to send an edit link for each homebrew to my laptop.

Sorry for any Grammar/Mechanical errors in my typing.

**Comment by stolksdorf** [comment]
I'm glad you are enjoying the site. However building an account system would be as complex, if not more so, than the Homebrewery itself. I've built several account system for other projects and I have no interest in building it again. 

To solve your problem, I suggest just bookmarking the edit links and chrome should sync your bookmarks between machines. That's what I do.

**Comment by ChosenSeraph** [comment]
Hey, there are accounts now! see wasn't so after all (I have no clue how hard it was) lol
