### ISSUE TITLE
Crashing every time i click "Create your own"

### ISSUE THREAD

**Issue by ChosenSeraph** [stolksdorf/homebrewery#159]
**Browser Type/Version**: Google chrome Version 51.0.2704.103 m

**Operating System**: Windows 10

**Issue Description**: I accidentally put too many >>>> next to each other while messing around and now when i click "Create your own" button it crashes the tab. Any way i can fix this?

**Brew code to reproduce**: >>>>>>>>>>>>>>>

**Comment by stolksdorf** [comment]
What a crappy problem.  Here's the fix:

- go to the homepage. right click anywhere and go to 'inspect element'
- Click on the tab 'resources' 
- Expand 'Local Storage' and click 'homebrewery.naturalcrit.com'
-  Right click on 'homebrewery-new' and delete it

Reload the page and you should be fine.

**Comment by ChosenSeraph** [comment]
Ah, i couldn't seem to fix it by going into the resources and deleting the homebrewery-new , but i did fix it by clearing my cookies and cache. but it did get rid of my Recently Viewed/Edited so watch out if anyone sees this.
