### ISSUE TITLE
Different backgrounds?

### ISSUE THREAD

**Issue by Tsurumah** [stolksdorf/homebrewery#160]
Hey, just had an idea. What if there were the other backgrounds, like the gray one from the DMG, for example? 

I haven't even gone looking for a suitable picture yet...

**Comment by stolksdorf** [comment]
If you find an appropriate image you can set this by using the code

```
<style>
.phb{
    background-image : url('...');
}
</style>
```

If you do find one for the DMG please give me a heads up so I can add it as a snippet :)
