### ISSUE TITLE
Formatting Problems with tables

### ISSUE THREAD

**Issue by dndencdm** [stolksdorf/homebrewery#163]
f you are reporting a bug, please fill out the details. If you don't I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: Chrome

**Operating System**: Windows 8

**Issue Description**: For some reason, when I create a table, some of the formatting gets screwy when I export to a PDF.  See attached Notes with tables in them re: Elves on p. 3 and Domain Spell tables on p. 17.  I've also attached the syntax I use.
[Mystara Syntax.docx](https://github.com/stolksdorf/homebrewery/files/392705/Mystara.Syntax.docx)

[Mystara Campaign Supplement.pdf](https://github.com/stolksdorf/homebrewery/files/392704/Mystara.Campaign.Supplement.pdf)

**Brew code to reproduce**:

```
PUT YOUR BREW CODE HERE
```

**Related Images** : [IF APPLICABLE]

**Comment by tarper24** [comment]
Interesting, I copied your entire syntax and reprinted it, and it all looks fine for me.

**Browser:** Google Chrome	51.0.2704.103
**OS:** Windows 10 Pro

To narrow the issue down for you: It only happens in Notes and Tables with Italics as far as I can tell.
It might be fixed, it might not, but could you try exporting it again and see if it is or not?

print(closing);
print("~tarper24");

**Comment by dndencdm** [comment]
Thanks so much.  I would love to try again, but for some reason, Chrome has stopped working altogether.  It won't launch and won't open any web page.  I tried to uninstall and reinstall and having the same problem.  Do you know if anyone else having a problem with Chrome?

**Comment by dndencdm** [comment]
Ok, weird.  I successfully uninstalled and reinstalled Chrome.  I tried again and it appears the issue with italics in tables has righted itself.  Thanks for the assist!
