### ISSUE TITLE
Feature request: table rows sizing control

### ISSUE THREAD

**Issue by Haxxer** [stolksdorf/homebrewery#164]
Great tools, love your work!

The only thing I have qualms with is the fact that tables aren't able to be sized. At the moment, if a string in the table is long enough it will compress the other columns and misaligned the table's formatting. I suggest that the dashes in the table's syntax increases the priority and/or width of a column in order to fix this issue.

Perhaps by using padding percentage per column, or setting the width of the TDs?

Cheers.

**Comment by stolksdorf** [comment]
The table syntax is just standard Markdown, which doesn't allow for changing the table widths. However you can accomplish what you want by writing your tables in HTML using inline styling to control their size. Read up on how to do that [here](http://www.w3schools.com/html/html_tables.asp). Good luck!
