### ISSUE TITLE
Background image broken

### ISSUE THREAD

**Issue by BalarRachi** [stolksdorf/homebrewery#170]
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: [Chrome/Version 52.0.2743.116 m]

**Operating System**: [Windows 10]

**Issue Description**: [I'm trying to add a background image, and when I do, it just shows a broken picture image.]

**Brew code to reproduce**:

```
<img 
  src='http://imgur.com/a/48bcw' 
  style='position:absolute; top:50px; right:30px; width:280px' />
```

**Related Images** : [http://imgur.com/a/48bcw
![shadow assassin](https://cloud.githubusercontent.com/assets/21004808/17641995/1048b1be-60f3-11e6-8679-19d576bfb6b9.png)
]

**Comment by dark12222000** [comment]
That url goes to a page not directly to an image. You likely want http://i.imgur.com/XzhZPN0.jpg instead.

**Comment by stolksdorf** [comment]
Thanks @dark12222000. That should be your issue.
