### ISSUE TITLE
Descriptive Text Boxes Splitting on Column

### ISSUE THREAD

**Issue by zequezz99** [stolksdorf/homebrewery#171]
**Browser Type/Version**: Chrome/52.0.2743.116

**Operating System**: Mac OS 10.11.4

**Issue Description**: Descriptive text boxes are wrapping around the columns strangely

**Related Images** : 
![error](https://cloud.githubusercontent.com/assets/1364186/17696035/ac29d878-6360-11e6-8078-8f73f1368886.jpg)

**Comment by stolksdorf** [comment]
This is an issue with CSS web columns and border-images. Try adding a small vertical spacing snippet right above it.
