### ISSUE TITLE
Admin page no longer lists any brews?

### ISSUE THREAD

**Issue by SnappyTom** [stolksdorf/homebrewery#172]
**Browser Type/Version**: Chrome or Firefox 

**Operating System**: Win7

**Issue Description**: In the last few months, I've noticed when running locally the admin page no longer works, i.e. no brews are listed/found, even though they appear in the 'Recent Brews' dropdown and are accessible by ID.

I'm wondering whether it's even supposed to work anymore or if it's just me. It did work a few months back (sorry I can't remember exactly but either v2.0.0 or v2.1.0).

**Related Images** :
![clipboard01](https://cloud.githubusercontent.com/assets/7448291/17725151/af96b85e-649c-11e6-9487-6f96a3ec96e4.jpg)

**Comment by stolksdorf** [comment]
v2.2.0 had some backend changes. What version of everything are you running currently?

**Comment by SnappyTom** [comment]
Thanks for assistance, Scott.

Did you want to see npm list? It's very long output.




```

**Comment by stolksdorf** [comment]
All the versions look good. I'll try and do a fresh clone and install on my machine alter and see if I can replicate the issue.

**Comment by SnappyTom** [comment]
I tried a fresh clone pointing to a new database myself but experience the same issue.

**Comment by stolksdorf** [comment]
Figured out the issue and it's fixed in v2.3.0

There was a bad search route in the admin page

**Comment by SnappyTom** [comment]
Thanks Scott! Love this project an use it a lot :)
