### ISSUE TITLE
Cant print with <descriptive> boxes

### ISSUE THREAD

**Issue by RalMakadonia** [stolksdorf/homebrewery#175]
Hi,

i have some problems using
```
<div class='wide'>
<div class='descriptive'>
...
</div>
\page
<div class='wide'>
<div class='descriptive'>
...
</div>
```
When i want to print my [http://homebrewery.naturalcrit.com/edit/SJeeaw7mc](url) Document, it stops after page 2. Did i do something wrong?
---

**Browser Type/Version**: Chrome - 52.0.2743.116 m

**Operating System**: Windows 10

**Issue Description**: see above

**Brew code to reproduce**:
```
<div class='wide'>
<div class='descriptive'>
...
</div>
\page
<div class='wide'>
<div class='descriptive'>
...
</div>
```
PUT YOUR BREW CODE HERE

SJeeaw7mc
**Related Images** : 
![error](https://cloud.githubusercontent.com/assets/20952888/17774356/86162d40-6553-11e6-921a-0bf6248bb33b.PNG)

**Comment by stolksdorf** [comment]
You are not writing your html properly. You are opening tags, eg. `<div>` without closing them. 

For example
```
<div class='wide'>
<div class='descriptive'>
...
</div>
\page
```
You opened two divs and only closed one of them. This will cause a ton of problems. 

Also you can mixing in capital letters such as `<Br>`.
