### ISSUE TITLE
Problems Saving PDF >7 Pages?

### ISSUE THREAD

**Issue by gowronatemybaby7** [stolksdorf/homebrewery#176]
**Browser Type/Version**: [Chrome - 52.0.2743.116 (64-bit)]

**Operating System**: [OS-X 10.11.6]

**Issue Description**: [When I try to save the monster manual I've been working on as a PDF, it only seems to let me save the first 7 pages.]

**Brew code to reproduce**: I'm not really sure what this means, but here's the link to the doc I've been making. When I click the share button, all 18 pages are there!

http://homebrewery.naturalcrit.com/share/rJg0D0qK

```
PUT YOUR BREW CODE HERE
```

**Related Images** : [IF APPLICABLE]

**Comment by stolksdorf** [comment]
You have malformed HTML at the bottom of the 7th page.

`<img src="http://i.imgur.com/bX0HAoO.png" style='position:absolute;bottom:450px;right:50px;width:350px'style="padding-bottom:0.5em;" />` 

should be

`<img src="http://i.imgur.com/bX0HAoO.png" style='position:absolute;bottom:450px;right:50px;width:350px' style="padding-bottom:0.5em;" />`

re-open this, if it's not the case

**Comment by gowronatemybaby7** [comment]
Hm... That didn't seem to do it. Sorry!

**Comment by gowronatemybaby7** [comment]
Scratch that! I figured it out! There was a random piece of code above all that that was doing it. I think it was left over from some time before when I was mucking about with adding in a caption.
