### ISSUE TITLE
Links on admin page incorrect

### ISSUE THREAD

**Issue by SnappyTom** [stolksdorf/homebrewery#177]
**Issue Description**: Thanks for fixing the admin page. It now displays brews. However, the URL links are slightly wrong.

Clicking on an "Edit ID" link takes you to say:
http://localhost:8000/homebrew/edit/By3gyz7W
where it should be 
http://localhost:8000/edit/By3gyz7W

At the moment, clicking the link takes you to the URL but displays the default instructional brew.

The share link does the same thing but I'm not sure what that should be.

**Comment by stolksdorf** [comment]
Just pushed a fix. When I separated the Homebrewery from my other D&D projects, I didn't update it's admin page to be standalone. I haven't had to use it in so long, so I didn't notice the bugs. 

Everything should be good now if you grab `master`.
