### ISSUE TITLE
Possible expansion

### ISSUE THREAD

**Issue by EndlessSeptember** [stolksdorf/homebrewery#178]
I recently started using Homebrewery for a Cyberpunk campaign. Works great, but if there was a way to change the background parchment style to something else it would fit better with the style of the game.

Possible options:
1. Allow the user to add an image as a background image in place of the parchment.
2. Have a half-dozen or so replacement options for the parchment. For some possible options look at any [Pathfinder ](http://imgur.com/gallery/rm4fj), [GURPS](http://imgur.com/gallery/avw5K), [Cyberpunk 2020](http://imgur.com/gallery/ntLgb) ,  [Stargate](http://imgur.com/gallery/C88N3),  [Shadowrun](http://imgur.com/gallery/XD4z3)

**Comment by stolksdorf** [comment]
This can already be done by modifying what the background image is via `<style>` tags
