### ISSUE TITLE
"Optimized" for Chrome

### ISSUE THREAD

**Issue by haxblade** [stolksdorf/homebrewery#179]
"Optimized for Chrome" seems a strange way of saying "Anything you make is going to look complete crap in any browser other than Chrome, screw those guys anyway."

**Comment by Saucy** [comment]
If you can't be bothered to download Chrome, which takes about 10mins, why bother making this issue? He clearly states that's where he's put his time and effort to, to support Chrome.

The code is MIT, feel free to include support for other browsers yourself.

**Comment by stolksdorf** [comment]
A bit of history in regards to Firefox (and other browsers) with Homebrewery. When I first started the project, it wasn't even possible to make the site on Firefox. Homebrewery relies on using [CSS columns](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts) which Firefox didn't support for quite some time. 

Eventually support came, so I invested so time on mking the rendering a bit better for Firefox. But this is incredibly boring and tedious work. Every change I make I have to double check many edges cases back and forth between Chrome and Firefox, and some things I want to do just end up being too finicky or impossible. The final nail in the coffin for me was just *how bad* Firefox's render to PDF functionality is. Even if you can get a brew looking perfect on web, when you render to PDF on FF all bets are off. This is something I just have no control over. I'd much rather spend my time working features that would benefit the whole user base, or on new tools.

As Saucy pointed out, could do all work work and _still_ deliver a subpar product, or just ask the user to Chrome. I understand your comment was constructive in hopes of better browser support, but I just wanted to give you some context on how tricky of a problem it is.
