### ISSUE TITLE
ReDead Challenge Rating

### ISSUE THREAD

**Issue by Geleron** [stolksdorf/homebrewery#184]
Looking at the ReDead abilities I don't believe they should be 1/4 CR. I will play test it this weekend but just looking at they're damage dice (a total of 3d6 instead of just 1d6) and their abilities (eg. Petrifying gaze, and the ability to latch on to the player), compared to a regular Zombie, should make them a higher CR.

![2016-08-31](https://cloud.githubusercontent.com/assets/21376945/18155360/f44369ea-6fc1-11e6-92ae-9b6796b22465.png)

![zombie_stat](https://cloud.githubusercontent.com/assets/21376945/18155349/d8e20dfa-6fc1-11e6-8bee-6b011dd143c3.jpg)

---

**Browser Type/Version**: FILL OUT

**Issue Description**: FILL OUT

**Brew code to reproduce**: <details><summary>Click to expand code</summary>
```
PUT YOUR BREW CODE HERE
```
</details>

**Related Images** : IF APPLICABLE

**Comment by stolksdorf** [comment]
I believed you are submitting an issue for the Zelda Monster Manual Homebrew. This project is for The Homebrewery itself, and not a specific brew. 

[Here's the original post](https://www.reddit.com/r/DnD/comments/4zkvr7/completed_legend_of_zelda_monster_manual_i/) though, so you can contact the author through that and update them on your issue :)

**Comment by Geleron** [comment]
Awesome, thank you :p sorry for the error

**Comment by stolksdorf** [comment]
No problem man. Glad you are enjoying the tool.
