### ISSUE TITLE
Feature: Offline Mode

### ISSUE THREAD

**Issue by Billeh007** [stolksdorf/homebrewery#192]
Hi, I'm not sure if this is possible, but would you be able to make a version that can be used offline? I will be away from the internet for large periods of time in the upcoming months, and won't be able to use your program while offline, as the offline saved page does not work properly in Firefox or Chrome.

**Comment by stolksdorf** [comment]
A few ways you can already do this. The simplest way is to just leave the tab open and save your brews to a text file after your done editing them. Homebrewery saves your brews as just text and the rendering engine is all in browser, so you can just save the text yourself manually usually notepad or something.

If you want to be a bit fancier, The Homebrewery is open source, so you can download your own version and run it locally. The instructions are on the [main page of this project](https://github.com/stolksdorf/homebrewery).
