### ISSUE TITLE
Loading the racial fonts?

### ISSUE THREAD

**Issue by McToomin** [stolksdorf/homebrewery#193]
Hi, I was just wondering if it would be possible to load the racial fonts into the Homebrewery? They're listed in this thread:

https://www.reddit.com/r/DnD/comments/2jwsx2/dnd_and_other_script_font_collection/

I was wanting to put something in draconic in one of my brews, and thought it would be really cool to be able to put it in there. I installed it myself and copied it into the homebrewery, but it switched it back to the normal font.

Thanks!

**Comment by stolksdorf** [comment]
Yup, you can do this. First the font has to be hosted somewhere (Dropbox might work as well), then [you load them in using CSS](https://css-tricks.com/snippets/css/using-font-face/) and use style tags.

```html
<style>
@font-face {
  font-family: 'Draconic';
  src: url('path-to-font.woff') format('woff');
}
.draconic{
  font-family : 'Draconic';
}
</style>


<div class='draconic'>I am in Draconic now</div>

```

**Comment by McToomin** [comment]
This is awesome, I really appreciate it!

If you don't mind, I've been working on this for a long time and I can't
seem to get it to show up. Here's what I've got:

<style>
@font-face {
  font-family: 'Draconic';
  src: url('http://www.megafileupload.com/oj3Y/Iokharic.otf')
format('opentype');
}
.draconic{
  font-family : 'Draconic';
}
</style>

<div class='Draconic'>I am in Draconic now</div>

I can't get a direct file link from Google Drive or Dropbox This is still
showing the text normally, so I'm not sure what to do from here. I tried
changing the font to a .woff type and leaving the format as 'woff,' but it
was still the same. Would you have any ideas of how to fix it? If you don't
have time that's fine, I'll keep working on it.

**Comment by stolksdorf** [comment]
Easy fixes.

Firstly, capitalization matters. `<div class='Draconic'>I am in Draconic now</div>` should be `<div class='draconic'>I am in Draconic now</div>`

Secondly, the megaupload link doesn't actually link to the font, it goes to a webpage where you can download it. I suggest using dropbox. In your Dropbox there should be a public folder, put the font in there, wait for it to sync and then right click and hit 'Copy public link'. Use that link in your brew.

Check it.

![image](https://cloud.githubusercontent.com/assets/387742/18482980/4fe13da2-79b0-11e6-8453-7368230306dc.png)

**Comment by McToomin** [comment]
Wow awesome! Unfortunately, dropbox accounts created after 2012 don't have
a Public folder unless you pay for it. I'll have to find somewhere to host
it, but I momentarily copied your link there and it worked. I really
appreciate your help!
