### ISSUE TITLE
API for new brew

### ISSUE THREAD

**Issue by ChadKeating** [stolksdorf/homebrewery#194]
Hi I'm the creator of http://rolladvantage.com/
I'm currently developing a monster builder and would like to send some generated markdown of the monster data to homebrewery.
Im looking at the current routes I dont see a way of doing this. Am I wrong or could this be added soon?
Thanks,
Chad

**Comment by vorpalhex** [comment]
No need for an API. The styles and markdown setup are in the repo. You should be able to render locally.

**Comment by ChadKeating** [comment]
Never mind I figured it out.

Example:

Post route:
`http://homebrewery.naturalcrit.com/api`

Data:
```
{
   "title": "Some Title",
   "text": "A test"
}
```

Returns edit id and share id

**Comment by stolksdorf** [comment]
Yup that works. However if you just want to render something on your site and not save and use The Homebrewery database, I would suggest what @vorpalhex said and use the styling and parsing from the project and run it locally. Not only would it provide a better experience for your users, but it would also save work on my servers and database :P

Message me if you need help setting that up.

**Comment by MicahKinsey** [comment]
I know this thread is ancient but does the API described here still exist / work? Thanks!
