### ISSUE TITLE
Printing issue/ converting to PDF

### ISSUE THREAD

**Issue by Wolfskin75** [stolksdorf/homebrewery#195]
**Browser Type/Version**: Chrome Version 53.0.2785.101 m (64-bit)

**Issue Description**: repeating the words "number" and ability to make it look like a solid two blocks. Also, doubling up the Stat labels like "str" and "dex" .. 

**Brew code to reproduce**: <details><summary>

Click to expand code</summary>

```
<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>
<style>
  .phb{ background : white;}
  .phb img{ display : none;}
  .phb hr+blockquote{background : white;}
</style>

___
___
> ## Mia "Wind" Neriynore
>*Daughter of Tres Oli*
> ___
> - **Armor Class** 24
> - **Hit Points** 94(1d4 + 5)
> - **Speed** 30ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|16 (+3)|20 (+5)|13 (+1)|12 (+1)|13 (+1)|16(+3)|
>

<div class='descriptive'>
##### SAVING THROWS:
| Number | Ability |
|:----:|:-------------|
| +7 | Str. |
| +9 | Dex. |
| +1 | Con. |
| +1 | Int. |
| +1 | Wis. |
| +3 | Cha. |
</div>

-
> - **Resistances:** Dark Damage, Damage Reduction: Dark Damage
> - **Senses** passive Perception 11, Darkvision 60ft
> - **Languages** Common, elvish, Draconic, Sylvan, Thieves Cant
> - 
> ### Actions
> - Attacks 2 
> - Initiative +5 
> - Speed 30ft


<div class='pageNumber auto'>
</div>
 ## Languages:
 > * Common 
 > * Elvish 
 > * Draconic
 > * Sylvan
 > * Thieves Cant
```

```

<div class='descriptive'>
### Skills
| Number | Ability |
|:----:|:-------------|
| +9 | **Acrobatics** |
| +5 | **Animal handling** |
| +1 | arcana |
| +7 | **Athletics** |
| +3 | deception |
| +1 | history |
| +1 | insight|
| +3 | intimidation |
| +1 | investigation |
| +1 | medicine |
| +5 | **Nature** |
| +1 | perception |
| +7 | **Performance** |
| +7 | **Persuasion** |
| +1 | religion |
| +9 | **Sleight of Hand** |
| +9 | **Stealth**|
| +5 | **Survival** |


```

</details>

**Related Images** : ![issues](https://cloud.githubusercontent.com/assets/22088408/18501341/b9f9be18-7a1d-11e6-9baf-49eff7fb0489.JPG)

**Comment by SecretShop** [comment]
i am going to expand on this and state that my code is producing this PDF image and the stats are double appearing like the above problem.

[Holy-o-Wisp.pdf](https://github.com/stolksdorf/homebrewery/files/532356/Holy-o-Wisp.pdf)

All i did was copy your monster stat block example and use it multiple times. The problem only appears when pressing "Get PDF". If it helps, here is the markdown for what i was doing:

`___
> ## Holy-o-Wisp
>*small fiend, chaotic neutral*
> ___
> - **Armor Class** 10
> - **Hit Points** 11(3d6 + 2)
> - **Speed** 30ft. (hover)
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|1 (-5)|16 (+3)|10 (+0)|13 (+1)|14 (+2)|10 (+0)|
>___
> - **Damage Resistances** Nonmagical attacks
> - **Condition Immunities** None
> - **Senses** passive Perception 16
> - **Languages** Common, Gibberish
> - **Challenge** 1 (100 XP)
> ___
> ***Holy Light Aura.*** This monster emits a 5ft aura of light that pierces through any darkness. it also emits 5 extra feet of dim light.
> ### Actions
> ***Shock*** *Melee Spell Attack:* +3 to hit, reach 5ft., one target. *Hit* 4 (1d6 + 1) 


___
> ## Heart of People
>*Medium Undead nature, neutral*
> ___
> - **Armor Class** 18
> - **Hit Points** 60(10d10 + 10)
> - **Speed** 0ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|0 (0)|0 (0)|0 (0)|0 (0)|0 (0)|0 (0)|
>___
> - **Damage Resistances** Fire, piercing
> - **Damage Vulnerabilities** Water
> - **Senses** omnipotent
> - **Languages** the wind
> - **Challenge** tree (idk XP)
> ___

> ***Blood Excretion.*** If damage dealt to the Heart of People by a single hit is 10 or higher, any players within a 5 ft radius must make a Dexterty saving throw (12+) to avoid. If they are hit, the player is dealt 1d4+1 acid damage.
>### Actions
> ***Summon Sap Shambler.*** *Just happens:* roll a d12, summon that shambler. if it is summonned already, don't do anything.

___
> ## Sap Shambler
>*Medium Undead, neutral*
> ___
> - **Armor Class** 8
> - **Hit Points** 12(2d8 + 5)
> - **Speed** 20ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|13 (+1)|6 (2)|16 (+3)|3 (+-4)|6 (-2)|5 (-3)|
>___
> - **Damage Immunities** Poison
> - **Condition Immunities** Poisoned
> - **Senses** passive Perception 16
> - **Languages** Common, Gibberish
> - **Challenge** 1/8 (25 XP)
> ___

> ***Sap Explosion.*** If damage reduces the Shambler to 0 hit points, it explodes and oozes its sap. Any players within a 5 ft radius must make a Dexterty saving throw (12+) to avoid. If they are hit, all shamblers gain +10 movement toward the player and spawn one more.
>### Actions
> ***Slam.*** *Melee Weapon Attack:* +3 to hit, reach 5ft., one target. *Hit* 4 (1d4 + 1)

`

**Comment by calculuschild** [comment]
Duplicate of #318
