### ISSUE TITLE
Text on FFXIV classes (I love the inspiration for these classes though. Seriously great)

### ISSUE THREAD

**Issue by Scootieloo** [stolksdorf/homebrewery#199]
**Browser Type/Version**: Firefox

**Issue Description**: Many table issues and text overlaying images of class descriptions. Text scrolls offpage and onto images.

**Brew code to reproduce**: <details><summary>Click to expand code</summary>
```
PUT YOUR BREW CODE HERE
```
</details>

**Related Images** : 
![arcanist](https://cloud.githubusercontent.com/assets/20214526/18574036/38cd2158-7b86-11e6-9b18-626bd5ca3f32.PNG)

![summoner](https://cloud.githubusercontent.com/assets/20214526/18574048/4fa50b34-7b86-11e6-9620-4578b4e70b24.PNG)

![bmage text flow](https://cloud.githubusercontent.com/assets/20214526/18574069/76d0e5ac-7b86-11e6-8fe9-f61f1f9e60e9.PNG)

![dknight](https://cloud.githubusercontent.com/assets/20214526/18574078/8aa302c2-7b86-11e6-843e-2ca01ddff43a.PNG)

**Comment by stolksdorf** [comment]
I can't really help unless you give me the share url.

**Comment by Scootieloo** [comment]
It is the only homebrew online at this moment, right?
Maybe I am using the website incorrectly -- I can only see the FFXIV
classes since a friend shared a link with me. How do I find others?

**Comment by stolksdorf** [comment]
There should be a big warning in the nav bar about using chrome if the rendering isn't working?

**Comment by stolksdorf** [comment]
Re-open this if there's any updates :)

**Comment by Scootieloo** [comment]
Finally finally found the shared file. Was on my laptop. I was on school
PCs, my bad

http://homebrewery.naturalcrit.com/share/B1HBWX5j
