### ISSUE TITLE
Page Jumping onto second column

### ISSUE THREAD

**Issue by Pruney** [stolksdorf/homebrewery#20]
I don't want to link my sheet incase other people can edit it, is there an email I can send it?

Basically the text gets halfway down the page and then it jumps onto the right column rather than going all the way to the bottom

**Comment by stolksdorf** [comment]
You can use [dpaste](http://dpaste.com/) to link to the markdown code on here. It's probably a css column issue. They are pretty tricky. Paste up your code and I'll give it a look.

**Comment by Pruney** [comment]
http://dpaste.com/11R29A2

Date: Thu, 14 Jan 2016 07:59:13 -0800

**Comment by stolksdorf** [comment]
Can't replicate your issue. Which browser are you using, I'm assuming a non-chrome one?

**Comment by Pruney** [comment]
Yeah Firefox, newest version

Date: Thu, 14 Jan 2016 09:48:06 -0800

**Comment by GholtAmble** [comment]
Same issue here. I'm using Firefox 46.0.1
Halfway through text jumps to the right side of the page. 
Aside from that, I'm really enjoing this tool.

**Comment by stolksdorf** [comment]
@GholtAmble can you post the markdown code (wrap it in triple ticks) that's causing the issue?

**Comment by GholtAmble** [comment]
```
### Life-Tapping Darts
*You launch magical darts at an ally and a foe. The dart that
strikes the foe transfers vitality to your comrade in a golden
flash.*
___
- **Daily ● Arcane, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Reflex

**Hit:** 2d10 + Intelligence modifier damage, and one ally
within 10 squares of you gains 10 temporary hit points.

**Miss:** Half damage, and one ally within 10 squares of you
gains 5 temporary hit points.

```
```


### Spike Wire
*You throw a bundle of barbed wire that bites into your enemy's
flesh, digging deeper and deeper.*
___
- **Encounter ● Arcane, Force, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Fortitude

**Hit:** 1d8 + Intelligence modifier force damage. Until the
end of your next turn, any attack deals extra damage to
the target equal to your Wisdom modifier.

```
```
```
```

### Spike Wire
*You throw a bundle of barbed wire that bites into your enemy's
flesh, digging deeper and deeper.*
___
- **Encounter ● Arcane, Force, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Fortitude

**Hit:** 1d8 + Intelligence modifier force damage. Until the
end of your next turn, any attack deals extra damage to
the target equal to your Wisdom modifier.
```

The last entry is fully transfered to the right side.

**Comment by GholtAmble** [comment]
Here you go.
http://dpaste.com/053X260
The last entry is fully transfered to the right side of the page.

**Comment by stolksdorf** [comment]
Maybe I'm not understanding your issue properly, but you need to specify the end of each page with `\page`

```
### Life-Tapping Darts
*You launch magical darts at an ally and a foe. The dart that
strikes the foe transfers vitality to your comrade in a golden
flash.*
___
- **Daily ● Arcane, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Reflex

**Hit:** 2d10 + Intelligence modifier damage, and one ally
within 10 squares of you gains 10 temporary hit points.

**Miss:** Half damage, and one ally within 10 squares of you
gains 5 temporary hit points.

```
```


### Spike Wire
*You throw a bundle of barbed wire that bites into your enemy's
flesh, digging deeper and deeper.*
___
- **Encounter ● Arcane, Force, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Fortitude

**Hit:** 1d8 + Intelligence modifier force damage. Until the
end of your next turn, any attack deals extra damage to
the target equal to your Wisdom modifier.


\page


### Spike Wire
*You throw a bundle of barbed wire that bites into your enemy's
flesh, digging deeper and deeper.*
___
- **Encounter ● Arcane, Force, Implement ● Ranged** 10
- **Standart Action** 
- **Target:** One creature
- **Attack:** Intelligence vs. Fortitude

**Hit:** 1d8 + Intelligence modifier force damage. Until the
end of your next turn, any attack deals extra damage to
the target equal to your Wisdom modifier.
```

**Comment by GholtAmble** [comment]
![78](https://cloud.githubusercontent.com/assets/19651446/15652698/b255bd8c-2690-11e6-9e84-a503f920f19b.jpg)

**Comment by stolksdorf** [comment]
What do you expect the tick block to do? And two of them back-to-back? 

The tick block ends the column, so after the darts, you have it end the column, jumping over to the second to draw the Spike wire. After you you end the column twice, then draw the second Spike wire. At this point it _should_ be drawing on the "4th column" of the page (which doesn't exist) and should be *way* off the page. 

If you want all those things to be in one column, just drop all of the tick blocks.

**Comment by GholtAmble** [comment]
They were an attempt to fix the problem of displaying
![13](https://cloud.githubusercontent.com/assets/19651446/15652941/56dd2cea-2692-11e6-9eba-a7dfb6105cc5.jpg)
Even your example is shown weird in that regard.
![12](https://cloud.githubusercontent.com/assets/19651446/15652954/692bf84a-2692-11e6-867c-a55b9839a1f2.jpg)
I'm sorry if that issue became a bother.

**Comment by stolksdorf** [comment]
Right. I forgot you said you are on firefox. Chrome and Firefox render things slightly differently. As well, Firefox treats CSS columns a bit differently than chrome (You can see even the fonts render a bit weird). If you're looking for perfect rendering, I suggest using Chrome. 

I've tried my best to get Firefox looking okay, but it's an incredibly finicky and difficult problem, and I'd rather spend my time solving more interesting problems.

Try your brew on Chrome, if the problem persists, let me know.

**Comment by GholtAmble** [comment]
Interesting. I guess, i'd rather use chrome then. You did a nice job with that brewery. Thanks for your time, man.

**Comment by stolksdorf** [comment]
I hate giving the answer "Just use Chrome". I'm really hoping someone out there that loves D&D and Firefox will dive in and spend the hours needed to get it looking identical to Firefox and submit a PR. There's also the issue that Firefox's Print to PDF is very bad as well. So even if I do spend the time on the styling, they'll still need to hop over to Chrome to print it properly.
