### ISSUE TITLE
Does not route properly behind a deep URL path

### ISSUE THREAD

**Issue by LukeKennedy** [stolksdorf/homebrewery#210]
I'm attempting to run homebrewery behind a reverse proxy in a specific URL path (think domain.com/homebrewery). When the asset links are generated, they route to the the root instead of the relative directory (domain.com/lib.js instead of domain.com/homebrewery/lib.js), which prevents the app from working.

Offending code in HTML output (taken from homepage):

<script src="/libs.js"></script>

<script src="/homebrew/bundle.js"></script>

Offending code from template.dot:15:
{{=vitreum.libs}}
{{=vitreum.js}}

Unfortunately, Vitreum is foreign to me so I can't figure out how to fix this myself. If the generated script tags dropped the leading /, the problem would go away (as in should be 'src="lib.js"' instead of 'src="/lib.js"').

**Comment by stolksdorf** [comment]
Vitreum is a build system that I've made for my side projects. `template.dot` is not the output HTML, but it's used as a template to build the output HTML. So after you run a build you can modify the resultant `bundle.dot` files in the `/build` with the pathing you want.

**Comment by LukeKennedy** [comment]
That's an okay work around, but it does not solve the issue. A way to generate relative paths instead of absolute ones from the root would be a much better fix. Is this a restriction from the build tools side?
