### ISSUE TITLE
Indention 

### ISSUE THREAD

**Issue by Apevian** [stolksdorf/homebrewery#211]
On the title screen, you should include how to perform indents with inline HTML "&nbsp;" 

This would help a lot with Homebrew creations! I love the website and I'm making a TON of homebrew classes and races between college classes for my groups. Keep it up!

And, of course, Homebrewy is heavily credited on the final page of the binder.  Take care!

**Comment by stolksdorf** [comment]
Not quite sure I'm following what you mean.

**Comment by stolksdorf** [comment]
Re-open if you can clarify your issue.
