### ISSUE TITLE
Question / Suggestion: Fonts

### ISSUE THREAD

**Issue by AlbertMokrejs** [stolksdorf/homebrewery#215]
I wanted to suggest the ability for users to upload a font file for their homebrews, because I think it could be cool for more dark-fantasy / eldritch designs. Alternatively maybe making it possible to link to instead, so as to avoid uploading and clutter.

I also wanted to ask what the fonts that Homebrewery uses are, as I need to figure out if their licenses permit commercial use.

**Comment by stolksdorf** [comment]
You can already use custom fonts by defining them within stlyes tags. Google how to setup custom fonts in CSS.

All assets I use can be found in the [repo here](https://github.com/stolksdorf/homebrewery)
