### ISSUE TITLE
Stored on Server

### ISSUE THREAD

**Issue by darthnos** [stolksdorf/homebrewery#217]
Are there any plans to make the brews stored on the server searchable or browsable in some way?  Like I saved the one I made but I didn't save the url (my mistake, i know) but even past that i'd like to browse things others have done.

**Comment by stolksdorf** [comment]
Check the recent brews in the nav bar on the computer you made the brew on, it should be there. 

I'm looking into making an account system of sorts, but it's a lot of work that's pretty boring.

**Comment by darthnos** [comment]
Would it be easier / possible to just have the brews searchable without an account system?  I've got a saved pdf copy of the brew in question (which I did incognito anyway since I may or may not have been at work), but it'd be cool to see what other brewers are doing.

**Comment by stolksdorf** [comment]
I would love to implement something like that and is on my roadmap, but I'm worried about the costs involved. Search would be pretty resource intensive server-wise, and running this project already costs a fair bit (Patreon is making it close to breaking even though!)

Accounts will come before search though, as it would make the search experience much better. Thanks for the comments and I'll keep you in the loop as I work on more things.

**Comment by darthnos** [comment]
I understand, and please bear in mind that when I ask for things, I have no idea what they involve, so like I don't want to sound pushy or anything!  I think it's super awesome even as it is.  Thanks for all your work, and expense!

**Comment by clineamb** [comment]
If you're already using MonogDB, you can try using Algolia to help index searches. It can do most of the boeirng stuff for you, and you essentially wouldn't need the accounts.  They have a free tier version where you just put the logo on the site.

https://www.algolia.com/

Disclaimer: I'm not a developer or anything on algolia, but I have used it before on some projects for work.

**Comment by stolksdorf** [comment]
@clineamb thanks for the suggestion, but the problem isn't really with an indexing solution but cost and time. The larger problem is that there is not any metadata stored about homebrews (description, edition, author, etc.) which would be needed to create a good searching experience for my users. I'm working to provide solutions to these problems, but it's not close.

**Comment by clineamb** [comment]
@stolksdorf - algolia can help tag and index entries based on content.

However, for some user-determined tags, perhaps simply just adding a tag system.  
I can see how Author you'd need a user system.  Perhaps easiest to simply use reddit / twitter / fb or something else oauth.
