### ISSUE TITLE
Popup to tell user to save work before closing browser

### ISSUE THREAD

**Issue by Crazedseal** [stolksdorf/homebrewery#219]
Hello, first off I would like to thank you for creating such a wonderful tool.

I just have a small suggestion, I'm not sure how it's implemented but could you make that it when I attempt to close the tab/browser that your webpage does a text message that stops it from closing and warns the user to save their work.

I thought this might be useful if someone accidentally closes their browser/tab with work they haven't saved.

Thanks, Crazedseal.

**Comment by stolksdorf** [comment]
Thanks for the suggestion, but this feature is already implemented on any page that has saving.

**Comment by Crazedseal** [comment]
Oh my bad. I realized you actually have to press the New Brew thing. >.<

**Comment by stolksdorf** [comment]
The flow is a bit interesting. I found people tend to make a lot of throwaway brews to test test ideas/formatting and early this devoured my database space. So now someone must actively choose to save before I start auto-saving. Anything on the `/new` is stored into local storage everytime there's a change, so if you close the tab and come back, the new page should be how you left it :)
