### ISSUE TITLE
Thx for your work

### ISSUE THREAD

**Issue by takiskal** [stolksdorf/homebrewery#222]
First of all congratulations on your amazing work, this tool you created will make it a lot easier for people to homebrew stuff, seriously well done. I am currently  unemployed but when i do  get a job i will definetely  contribute. I want to ask a question, how can i just save a created doc as a pdf in my computer? I know this may sound silly but I can't seem to find it.

**Comment by michaeltlombardi** [comment]
On the top right, you should see the `Save` button - after saving, you'll have an option for `Get PDF` - clicking that button should bring you over to the print-to-pdf option inside of chrome in a new tab.

Does that work for you?

**Comment by stolksdorf** [comment]
On the homepage, there's a green block of text describing the exact process for generating a PDF, but it's basically what @michaeltlombardi said.

Thanks for the kind words! I hope journey to employment goes well :)

**Comment by stolksdorf** [comment]
Images will have to be uploaded to a image hosting service, like Imgur. Then you use `img` tags to link it in. Google "html image tags" for more information.
