### ISSUE TITLE
Bug: Can't Place H1 on Right Side Column

### ISSUE THREAD

**Issue by jeffdavidthompson** [stolksdorf/homebrewery#224]
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't, I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: Chrome Version 54.0.2840.71 m

**Issue Description**: H1s drop over to the left, even if the rest of the format is correct. This can be demonstrated on the default screen by changing any H2 or H3 to an H1. It will disrupt text flow on the left.

**Comment by stolksdorf** [comment]
Not a bug, H1s span both columns by default.

**Comment by jeffdavidthompson** [comment]
Understood. There's a little difficulty then if say, you have a stat block in the left column and need an H1 on the right. Anyway it may be helpful to have a comment about it in the app. Such a great tool overall.
