### ISSUE TITLE
Standalone Homebrewery script?

### ISSUE THREAD

**Issue by adangtran87** [stolksdorf/homebrewery#225]
I'm not acquainted with javascript so apologies if this is a dumb question, but is there an easy way to run/package your modified markdown and html generation in a standalone script?

Use case:
* I want to source control Homebrewery Markdown text files
* I would write a script to run the text files through a 'homebrewery script' and generate html/pdf. 

Eventual Goals:
* When creating a 'homebrew handbook' I can modularize into multiple text files. Script can then assemble into one text file to send through script to create a large pdf.
* Create a script to generate a static website from text files ala Jekyll. 

I know this is not a use case that's intended for the site itself, so I understand if this delineation isn't feasible. Ideally I'd like to leverage your business logic and hopefully it only requires a little bit of packaging to make this possible.

**Comment by michaeltlombardi** [comment]
I'd be interested in using/helping with this. I have the same use cases.

**Comment by stolksdorf** [comment]
I would be relatively easy to do this, as this is exactly what happens when the print page is rendered. Look through the code to see how that's done and you can pull out those parts into a headless script.
