### ISSUE TITLE
Issue: exporting several page PDF

### ISSUE THREAD

**Issue by SneakyOrc** [stolksdorf/homebrewery#226]
**Browser Type/Version**: Chrome

**Issue Description**: When exporting a document of 4 pages, separated using \page, the PDF only shows the first page. Seems as if at the bottom of this single page it attempts to fit the contents of the other three which causes it to have a mess of text. 

**Brew code to reproduce**: <details><summary>Click to expand code</summary>
```
4 one page long wide tables, new page after each one. 
```
</details>

**Related Images** : IF APPLICABLE
![image](https://cloud.githubusercontent.com/assets/23322706/20075856/511beef4-a536-11e6-92ae-0eb8420d9478.png)

**Comment by stolksdorf** [comment]
This is caused by having malformed HTML in your brew. Can you provide your share link? I'm working on a new parser that will detect errors like this and I want to test it against your brew.

**Comment by SneakyOrc** [comment]
Of course! Here it is: http://homebrewery.naturalcrit.com/share/HJ3pUD0xx
![image](https://cloud.githubusercontent.com/assets/23322706/20096142/c858bc14-a5a8-11e6-959e-02441a349b84.png)

(sorry about all the irrelevant text)
Curiously enough, now when I opened it up it gave the errors you were talking about (see attached image.)

Side note: It really is an excellent tool! Very functional and for the most part easy to use. I would like to mention though that it might be nice to include some tips and usage guide for some tools in the future. Especially for people like me who have little experience with HTML and CSS (I assume thats what it uses?) certain tools require some mucking about before understanding how they work. For example when creating a table that exceeds one page you need to brake page and create a new table, for this table if you do not want headers at the top of the columns you cant just press space and be done with it. However, if you use the numeric character of space &#160; that works just fine. There might be better ways to do this but it also works for aligning the header. So certain tips and a brief description on the behavior and usage of tools could be quite useful. All in all its a fantastic tool, thanks! Keep it up

**Comment by stolksdorf** [comment]
Thanks for the feedback. The majority of the issues I receive now was because of bugs like this, so I pushed out the update last night. I am planning to include a small guide, but to be honest, The Homebrewery syntax is just Markdown with pages. It is possible to use HTML within markdown, but that's more of a "super user" thing.
