### ISSUE TITLE
Lists not breaking across columns

### ISSUE THREAD

**Issue by tyson-nw** [stolksdorf/homebrewery#229]
Long list are not breaking across columns.  If the list would span between columns it all jumps to the next column,  Manually adding 2 empty lines or a horizontal line `____` between list items it will break there.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/BybhOT3v-g

Removing `-webkit-column-break-inside: avoid;` from `.phb ul` and adding it to `.phb ul li` seems to solve it for me.

**Comment by dmmagic** [comment]
I can confirm this issue is still occurring.

**Comment by stolksdorf** [comment]
Fixed in v2.6.0, let me know if it's still happening. Column-stuff can be tricky.
