### ISSUE TITLE
Problem with list of brews on my profile.

### ISSUE THREAD

**Issue by Dustin-T** [stolksdorf/homebrewery#231]
The brews I saved go off the page in my profile. Probably best if I just show you so I took some screenshots. Reloading the page doesn't help, clicking the links did fix it kinda but was unreliable and doesn't seem to help anymore, and publishing one of them made it worse. 

**Share Link** : 
![homebrew profile 1](https://cloud.githubusercontent.com/assets/24196917/20644949/2821daea-b418-11e6-986a-5c90a96458c1.png)
![homebrew profile 2](https://cloud.githubusercontent.com/assets/24196917/20644950/2823b720-b418-11e6-8138-d22855e2a33f.png)

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
All fixed in v2.5.1. Let me know if there's anymore issues. Thanks for reporting this :)
