### ISSUE TITLE
Minor Bug with new Profile Page

### ISSUE THREAD

**Issue by SpiderMikeH** [stolksdorf/homebrewery#232]
Hello! 
I absolutely love the work you've done with the Homebrewery page. It's saved me so much time organizationally, and visually for homebrewing D&D content. I'm utilizing it heavily for my campaign.  

I just thought I would let you know of an issue I've encountered with your profile page on Homebrewery.naturalcrit. 

If you have a bunch of brews the content goes off the page, and makes accessing the links extremely troublesome. The only solution is to change my zoom on the webpage, but that varies every time I have a new homebrewery link. I'm also using chrome, and have attached some screenshots.  

Here's my browser zoomed at 67%
![screen shot 2016-11-26 at 8 43 51 pm](https://cloud.githubusercontent.com/assets/24197124/20644969/cdcb79ba-b418-11e6-8440-9602dae8c113.png)

Here's 100%:
![screen shot 2016-11-26 at 8 44 00 pm](https://cloud.githubusercontent.com/assets/24197124/20644974/0dc8afd8-b419-11e6-8de3-7256169bd4ca.png)

I know this is a free service, and I figured you might appreciate some bug finding. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Thanks! I'll fix this today :)

**Comment by stolksdorf** [comment]
All fixed in v2.5.1. Let me know if there's anymore issues. Thanks for reporting this :)

**Comment by SpiderMikeH** [comment]
Thank you so much for the quick reply. I appreciate it a lot.
