### ISSUE TITLE
Feature Request: Table of contents

### ISSUE THREAD

**Issue by tullisar** [stolksdorf/homebrewery#234]
It would be really handy if we had a method for generating a table of contents for headers in the document, similar to how [Markdeep](https://casual-effects.com/markdeep/) handles them. I find myself wanting to jump to certain pages frequently, and scrolling through the doc or the source view for headers is a bit tedious.

**Comment by dmmagic** [comment]
This would be a fantastic addition!

**Comment by stolksdorf** [comment]
Kerblam, it's in v2.6.0 under editor snippets. It will auto generate based on `#`, `##`, and `###` level titles, and become hyperlinks to the pages where those titles show up. Let me know if this fits the bill. Enjoy :)
