### ISSUE TITLE
[Suggestion] Attach homebrews to account, brew Title and more

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#236]
Hi, 
This is not a bug report but rather a suggestion that I think will benefit everyone.
Right now, there's no way (that I could find) to track the homebrews that an user did. For example, I have a bunch of them and I have to keep them all bookmarked otherwise I will loose them.

Since now each user can have an account, could you make the homebrews be attached to an user account? This way each user would be able to manage all homebrews he creates, making it a no brainer to find them.

Also, before it was possible to define a name for the homebew and now its not anymore. Don't know if it's a bug or as intended. I noticed however that the name of the brew is set automatically to the text on the first line of the document. This is a bit inconvenient since what I we write on the first line may not be the best title for the brew

Has an optional functionality (which I think would be great) you could also add a section for comments. This way, wen you share the homebrews, people could comment and even leave suggestion on how to improve it. I don' see it necessary (low priority), but it would be cool :)

Many thanks

**Comment by stolksdorf** [comment]
Hey PalaNolho. Few things here:

1) *Linking brews with accounts*. The whole point of adding accounts was the exact feature you are suggesting, linking brews with a person. If you click on the "profile" link the nav it'll take you to _your_ profile page where it will list all of the brews you've edited. You can check out my personal brews [here](http://homebrewery.naturalcrit.com/user/stolksdorf).

Whenever someone who is logged in makes an edit to any brew, they will now be added to the list of authors. So if you have a number of existing brews, open them up and make a small edit to them and save them while logged in and they will now be associated with that account.

2) *Brew title was removed* It wasn't removed, just the UI was moved. I added several more things to add to a brew, a description, what edition it's for, publishing it, etc. There's a new icon on the right of the editor. Click it and it'll open a new UI where you can modify these things.

3) *Adding comments* I would suggest using existing solutiosn for this. Share you brew with the fine people of [r/UnearthedArcana](https://www.reddit.com/r/UnearthedArcana/) and add the url into the description of your brew. There you can have a much better discussion. Comment systems are notoriously tedious to build and to build right. I have no desire to build another one in my lifetime.

Thanks for the feedback, I hope you enjoy the updates in v2.5.0 ;)

**Comment by PalaNolho** [comment]
Hmmm I don't see any if the options you mention :S

When I click on the profile I'm redirected to the "tutorial/example" page

And I can only see the change logs which has a list of recent edited and viewed.

I also can't find the options you mentioned for title description, etc...

I'm using chrome, that shouldn't be a problem right?

**Comment by stolksdorf** [comment]
What's the version in the navbar for the Homebrewery?

**Comment by PalaNolho** [comment]
2.5.2

**Comment by PalaNolho** [comment]
Ler me get you some screenshoots

**Comment by PalaNolho** [comment]
there you go.
http://screencast.com/t/1kYNb9Ga

**Comment by stolksdorf** [comment]
Re: account issue: You made your account name formatted like an email address, which screws up the url address.

And the metaeditor editor looks like this 
![image](https://cloud.githubusercontent.com/assets/387742/20860939/d8b315ca-b951-11e6-9bea-65d39441ef09.png), but it's on every page **but** the homepage.

**Comment by PalaNolho** [comment]
My I suggest that you put that icon on the left side, just before the "editor" option? it will be more user friendly (it was literally hidden in plain sight :S

As per the login = email ... it seems I found a bug after all lol :D

**Comment by stolksdorf** [comment]
I haven't gotten to logout yet. Soon though. I just hate working on account-system stuff. It's not a fun way to spend my weekends.

**Comment by PalaNolho** [comment]
Thanks for all the effort. It's definitely a great tool and keeps getting better and better.

**Comment by stolksdorf** [comment]
Thanks man. I've been spending a lot of my time actually on other tools. I'm hoping to release them soon :)

**Comment by PalaNolho** [comment]
If I can help, let me know :)
