### ISSUE TITLE
Some format issues

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#237]
Hi, I noticed some format issues in some situations

first one is when you have two paragraphs together and there's a bit o text going to the 2nd line (like 1 or 2 characters only)
http://screencast.com/t/bFrG4zwfP

The other one is on the user brews list, where there's no space between the brews
http://screencast.com/t/OsvMyg2WrC

Also, the "report issue" link is not available while signed in
http://screencast.com/t/lgLrgaPbno
http://screencast.com/t/8gDpALnJ4u

However, when I was using my messed up account (with username = email), I saw the link
http://screencast.com/t/ME4PvUv5

**Comment by stolksdorf** [comment]
1) That's just markdown. Double new lines makes a new paragraph
2) Still working on the best styling for that page. Thanks for the heads up
3) Accidentally removed it from the edit page. My bad.

**Comment by stolksdorf** [comment]
Fixed in v2.6.0
