### ISSUE TITLE
[Suggestions] users homebrews order and layout

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#238]
Hi,
The list of homebrews doesn't seem to have any particular order (currently it's probably by ID or create_data, I presume). I would suggest ordering it by crescent alphabetic order of the Title. It would be more clean and easy to find stuff.

Also, if I may give my opinion, I'm not entirely convinced with the layout of the brews of the user. I have plaied a bit with it and I'm sending 2 suggestions. Maybe they will give some inspiration. I dont know, its just a thought.

1. http://screencast.com/t/b4BuIcKvat
2. http://screencast.com/t/NH76iD66

(the highlighted one is when you mouse over it)

Cheers!

**Comment by stolksdorf** [comment]
I like your ideas. Implemented in v2.6.0
