### ISSUE TITLE
Varying Page Widths Within Brew

### ISSUE THREAD

**Issue by dmmagic** [stolksdorf/homebrewery#243]
Would it be possible to have varying page widths within a brew? For example, I'd like my document to be 17 inches wide, but occasionally I'd like to insert a 20-inch-wide page.

**Comment by stolksdorf** [comment]
Each page is given a specific css ID, so you can change the widths of specific pages using CSS.

**Comment by dmmagic** [comment]
Aha! That did it! Thanks so much!
