### ISSUE TITLE
[Bug]Large brew hung on 'saving.'

### ISSUE THREAD

**Issue by OmniscientSpork** [stolksdorf/homebrewery#244]
So basically, I wrote a 46-page campaign setting document up. Opened it, and noticed that something went weird with the formatting - text was spilling off the page. After spending some time fixing it, I tried to save.

It hung on 'saving.' Changes were reverted when I hit 'share.'

The text was completely fine last time I edited the document - I think something's gone wrong with the CSS. 

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/r1ZuwWe4Je

**Comment by OmniscientSpork** [comment]
Copied the code to a new document. Everything was displaying perfectly and properly-formatted, until I saved. At that point, it immediately reverted to how it was before - text spilling over the sides of pages, random bolding, and so on.

**Comment by OmniscientSpork** [comment]
Done a bit of testing - it appears as though the text is being bolded throughout the document for some reason. When I make an edit, the bolding disappears, but when I save, it returns.

**Comment by stolksdorf** [comment]
If you ever think there's been an issue with saving or worried about it at all: Back up your work to a text file on your computer. We don't want you losing your work. I can't replicate your saving issue, maybe more details?

Secondly, looking through the source in your brew, your html you're using is very badly formatted. You have opened strong tags without closing them, excessive use of br's which can cause rendering issues, etc.  Not sure why you decided to basically not use markdown at all, but this tool was built for that, not to be a full html editor. If you are having rendering issues, I would try to use more markdown and less HTML, unless your are proficient in HTML.

**Comment by OmniscientSpork** [comment]
As mentioned, it was definitely related to the strong takes and brs.  I'm not especially proficient in HTML OR CSS, honestly - and I'm pretty sure the saving issue was tied to my bad coding.
