### ISSUE TITLE
Reference links don't share across pages

### ISSUE THREAD

**Issue by tullisar** [stolksdorf/homebrewery#245]
If you create a reference style link in Markdown with the `[name]: link` style, it's only valid for the page on which it's defined. It would be nice to be able to use a few named ones across the entire document without having to copy paste the link definition to each page it needs to be used on.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HkRzO8Xmg

**Brew code to reproduce** : <details><summary>Click to expand</summary>

```
# Page 1

## Link to [Google][google]

\page

# Page 2

## Link to [Google][google]

[google]: http://www.google.com "Google"

```
</details>

**Comment by stolksdorf** [comment]
Each page is render in isolation to another, so there is no way to support this markdown feature.
