### ISSUE TITLE
CSS Box-Shadows Displaying as Solid Black in PDFs

### ISSUE THREAD

**Issue by dmmagic** [stolksdorf/homebrewery#246]
CSS box-shadows that surround monster stats and notes are displaying correctly on-screen, but once printed as a PDF, the shadows turn solid black. Using updated version of Chrome, Windows 7.

![box-shadows](https://cloud.githubusercontent.com/assets/15933118/20910222/1cbb4d04-bb15-11e6-8d00-1387535b1682.jpg)

**Comment by dmmagic** [comment]
I went to another page that uses CSS box shadows and tried to print it -- and that page's shadows also come out as solid black.

https://css-tricks.com/almanac/properties/b/box-shadow/

**Comment by stolksdorf** [comment]
Note to future self: Add a print media query to remove all box shadows?

**Comment by dmmagic** [comment]
This page talks about the box-shadow bug in Chrome: http://stackoverflow.com/questions/13975198/text-shadow-and-box-shadow-while-printing-chrome

**Comment by stolksdorf** [comment]
Fixed in `v2.7.0`

**Comment by dmmagic** [comment]
You fixed it?! Awesome!

**Comment by stolksdorf** [comment]
Please test it/double check it. If you're still having issues I'll try and get to the bottom of it. The current CSS for rendering is getting pretty out of hand. I'm doing a big spring cleaning in v3

**Comment by Carcabob** [comment]
It seems to be broken again in Chrome 69.0.3497.81

This thread has CSS to fix it though: https://github.com/stolksdorf/homebrewery/issues/354
