### ISSUE TITLE
Links are not usable in footnotes.

### ISSUE THREAD

**Issue by Dustfinger1** [stolksdorf/homebrewery#249]
Links aren't functioning in the "class='footnote'" code. Is this intentional?

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='footnote' style='position:absolute;bottom:30px;right:40px'>[yourtexthere](http://www.somelinkyouwant.com/)

</pre></code></details>

**Comment by stolksdorf** [comment]
Example?

**Comment by Dustfinger1** [comment]
http://homebrewery.naturalcrit.com/edit/B1ld4L2vXl 

Not sure if that's what you're looking for, but also

`</style><div class='footnote'>[reddit](https://www.reddit.com/)</div>`

**Comment by Dustfinger1** [comment]
or `<div class='footnote'>[reddit](https://www.reddit.com/)</div>`

**Comment by stolksdorf** [comment]
Note to future self: Add a differing z-index to `div.footnote` and `div.footnote::after`

**Comment by stolksdorf** [comment]
Fixed in `v2.7.0`
