### ISSUE TITLE
Suggestion: Tags for Projects

### ISSUE THREAD

**Issue by Lv99Pangolin** [stolksdorf/homebrewery#252]
Okay, so I don't know if everyone is like me, but having tags for projects would be amazing. Tagging each creation with something like Monster, Class, Subclass, Feat, Race, Item, World, Mechanic, Notes, and et cetera I feel, would be really helpful. Especially to people (like me) whom either have a bunch of stuff they're making all at once, or are just really bad wit hthe alphabet (like me) and occasionally forget that they added a 'The' in the title and are searching for their brew for a whole 5 minutes. (It's happened, and this is one of the reasosn I'm suggesting this). 

I love the Homebrewery, and use it often, so thanks for it!

**Comment by stolksdorf** [comment]
That's what the description field is for. Does that not solve your problem?
