### ISSUE TITLE
Class Table & Half Table don't work in Chrome.

### ISSUE THREAD

**Issue by R3vnant** [stolksdorf/homebrewery#253]
![image](https://cloud.githubusercontent.com/assets/22801701/21187834/9b28ec10-c1d6-11e6-991b-908963857f42.png)

When I click on Class Table or Class Half Table, nothing works, like the button doesn't even press.

Also, homebrewery on Internet Explorer doesn't work at all anymore for the last two weeks.

![image](https://cloud.githubusercontent.com/assets/22801701/21187920/e073c268-c1d6-11e6-807a-2abf0e5ff2d4.png)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Fixed in v2.6.2
