### ISSUE TITLE
class tables not working

### ISSUE THREAD

**Issue by DanSaad** [stolksdorf/homebrewery#255]
attempting to insert a half or full class table from the menu does not insert the table.

### .Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by StringsNeverCry** [comment]
I'm also having the same problem.

**Comment by Case104** [comment]
Same issue

**Comment by Dyabolique** [comment]
Same issue as well

**Comment by stolksdorf** [comment]
Fixed in v2.6.2
