### ISSUE TITLE
Wide Monster Stat Block With Image Not Printing Correctly

### ISSUE THREAD

**Issue by Plasma-Wisp** [stolksdorf/homebrewery#256]
Using Safari 9.1.3 on Macbook with OS X 10.9.5
Wanted Product: 
![fernando error](https://cloud.githubusercontent.com/assets/23702902/21248742/6209f9e4-c2f6-11e6-9757-09100eae12bc.jpg)
Printed Version: 
![fernando error printed](https://cloud.githubusercontent.com/assets/23702902/21248767/889b1ae8-c2f6-11e6-8c51-5fd752434195.jpg)
### Additional Details
**Share Link** :http://homebrewery.naturalcrit.com/edit/Bygp9ijl4l 
or
**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
```
___
___
> ## Fernando:
> ## Poisonous Snake
> *Tiny beast, unaligned*
> <div style='margin-top:0px'></div>
> <img src='https://s-media-cache-ak0.pinimg.com/564x/68/cb/bc/68cbbc0caf98be646a730e955ceae9ef.jpg' style='width:300px' />
> <div style='margin-top:25px'></div>
> ___
> - **Armor Class** 13
> - **Hit Points** 2 (1d4)
> - **Speed** 30 ft, climb 30 ft
> ___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|2 (-4)|16 (+3)|11 (+0)|1 (-5)|10 (+0)|3 (-4)|
>___
> - **Proficiency Bonus** +2
> - **Senses** blindsight 10 ft, passive Perception 10
> - **Languages** －
> - **Challenge** 1/8 (25 XP)
> ___
> ### Actions
> ***Bite.*** *Melee Weapon Attack:* +5 to hit, reach 5 ft, one target. Hit: 1 piercing damage, and the target must make a DC 10 Constitution saving throw, taking 5 (2d4) poison damage on a failed save, or half as much damage on a successful one.
> ___
```
</pre></code></details>

**Comment by stolksdorf** [comment]
The Homebrewery is not built to work in Safari. There should be a big warning in the navbar telling you to use Chrome if you are having rendering issues.

**Comment by Plasma-Wisp** [comment]
I don't think it is a problem with safari, but with the .phb styling. I'm not a pro when it comes to css, but I when through and deleted things, and when I deleted the hight and width, the page looked like the printed product. Sadly, I wanted it to be the other way around (the printed product looks like the page).
With Hight and Width:
![untitled](https://cloud.githubusercontent.com/assets/23702902/21296017/c571d09a-c51e-11e6-87b0-726bc897420e.jpg)
Without Hight and Width:
![untitled](https://cloud.githubusercontent.com/assets/23702902/21296024/ea5d30fc-c51e-11e6-9e86-5b58b1d1636a.jpg)
