### ISSUE TITLE
Are wide footnotes possible?

### ISSUE THREAD

**Issue by phaeren12** [stolksdorf/homebrewery#258]
As stated, would love to be able to add a wide footnote for Acknowledgements and Copyright info. IS this possible/how would I go about this?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Use the wide block snippet with however you are making footnotes?
