### ISSUE TITLE
I'm bad at coding and need help with putting an image in correctly

### ISSUE THREAD

**Issue by thaneofwinter** [stolksdorf/homebrewery#259]
So I'm trying to put an image in and I'm just getting an outline and a broken image icon
This is the line of code I'm using, how do I improve it?
< img src='http://imgur.com/gallery/hnj40.' style='position:absolute;bottom:50px;right:15px;width:400px' />

I apologize if I'm breaking any posting rules or anything but I need help and I have no idea where to go. Any help is appreciated, thank you!

**Comment by stolksdorf** [comment]
This is the place. Remove the space between the `<` and `img`, eg. `< img src='http://imgur.com/gallery/hnj40.' style='position:absolute;bottom:50px;right:15px;width:400px' />`

**Comment by thaneofwinter** [comment]
I put the space so the line of code would show up. I didn't know how to put the code in :I

**Comment by thaneofwinter** [comment]
I finally figured it out. I wasn't using the direct link. My apologies :x

**Comment by stolksdorf** [comment]
I mentioned that in my first reply?
