### ISSUE TITLE
No Longer able to Customize Title of File

### ISSUE THREAD

**Issue by melegaunt** [stolksdorf/homebrewery#260]
I am no longer able to customize the Name of my file to organize how it appears in my brews list. Before I used to have a box up top that I could type in, but now it is not there. Needless to say when you save it just pulls the first line of the file and puts it as the title, formatting included. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Hit the "i" button on the editor bar.

**Comment by melegaunt** [comment]
Brilliant. Thank you!

**Comment by stolksdorf** [comment]
Sorry about the confusion. I had to move things around since I added much more metadata to the brews.
