### ISSUE TITLE
Link to External CSS

### ISSUE THREAD

**Issue by dmmagic** [stolksdorf/homebrewery#262]
I've made a large number of changes to the formatting. It would be great to be able to link to an external CSS. Right now, I only have three brews, so if I make a change that I want to be universal, it's easy to open all three brews and modify the internal CSS. But as my brew collection grows, that would become time consuming.

**Comment by stolksdorf** [comment]
Try using a link tag. If that doesn't work, there's not really another solution, I've never tested nested lazy loading as this is going far beyond what this tool was designed to do. If you are modifying so much of the HTML and CSS you could probably just write your own webpage at this point and host it :P
