### ISSUE TITLE
Layout fucked up (screenshots attached)

### ISSUE THREAD

**Issue by BaronMurph** [stolksdorf/homebrewery#263]
After showing my current brew to a few people, I've encountered a major problem; the layout gets completely fucked up anywhere except for in Google Chrome on my own computer.
It gets fucked up in pdfs, share link, and edit links in Microsoft Edge on my computer, and in Edge, Chrome, and Firefox on other computers.
A bunch of examples:
On my computer in Chrome: http://i.imgur.com/X3usFIs.png
On my computer in Edge: http://i.imgur.com/Dx3Sg6o.png
On someone else's computer in Firefox: http://i.imgur.com/nyDp9CQ.jpg
On someone else's computer in Chrome: http://i.imgur.com/U6uvnPB.jpg
Our screens are both the same size and our browsers at 100% zoom.
Share link: http://homebrewery.naturalcrit.com/share/HkZOfJUGze

I'd have suspected it to be my chrome's fault, but it looks differently fucked up on different browsers, and one person I showed it to had no issues at all using their chrome.

**Comment by dmmagic** [comment]
Homebrewery is optimized for Chrome. It would be a hell of a feat to make it work exactly the same in all browsers.

![dx3sg6o](https://cloud.githubusercontent.com/assets/15933118/21335555/a8d36ae2-c614-11e6-99f6-a9056b918612.png)

**Comment by stolksdorf** [comment]
As @dmmagic said, The Homebrewery is only built for chrome. Checking your screenshots, it looks like things are rendering fine in Chrome. If you need to share it with people who may not have Chrome, I suggest your export it to PDF first.
