### ISSUE TITLE
Column Break breaks Large Monster Stat block.

### ISSUE THREAD

**Issue by Regerem** [stolksdorf/homebrewery#264]
When placing a wide monster stat block past the column break it is automatically displayed at the bottom of the page, completely breaking the formating. It looks fine on the preview but when exporting in pdf it is broken.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HJ9nCpEze

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div style='margin-top: 30px'></div>

### The King of the Wild Hunt

<div style='margin-top: 10px'></div>

No enemy is more terrifying than the King of the Wild Hunt, who leads a horde of ghastly riders across the sky. Doom incarnate, he fears no opponent, for he can always decide that his adversary is doomed, which usually determines the outcome of any clash. Many suggest he is either an Archfey or an Archwraith. Beneath his ragged robes, he wears elements of an ancient suit of armor. The ornaments on his clothing and crown evoke associations with bones and death. The King of the Hunt is the only known *Aen Alle* able to manifest his own spectral form, acting independently from any Hunt and without the help of a navigator.

```
```

<div style='margin-top:30px'></div>

___
___
> ## King of the Wild Hunt
>*Large fey, lawful evil*
> ___
> - **Armor Class** 17
> - **Hit Points** 285 (30d10 + 120)
> - **Speed** 30 ft., fly 50 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|6 (-2)|24 (+7)|18 (+4)|20 (+5)|19 (+4)|22 (+6)|
>___
> - **Saving Throws** Dex +13, Int +11, Wis +10, Cha +12
> - **Damage Vulnerabilities** fire, force
> - **Damage Resistances** lightning; bludgeoning, piercing and slashing from nonmagical weapons
> - **Damage Immunities** cold, poison
> - **Condition Immunities** charmed, frightened, paralyzed, petrified, poisoned, prone, restrained, stunned
> - **Senses** truesight 120 ft., passive Perception 14
> - **Languages** Elvish, Primordial, Sylvan
> - **Challenge** 21 (33,000 XP)
> ___
> ***Force Disruption.*** Whenever the King of the Wild Hunt takes force damage, it has disadvantage on attack rolls and ability checks until the end of its next turn.
>
> ***Incorporeal Movement.*** The King of the Wild Hunt can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.
> 
> ***Legendary Resistance (3/Day).*** If the King of the Wild Hunt fails a saving throw, it can choose to succeed instead.
>
> ### Actions
> ***Multiattack.*** The King of the Wild Hunt makes three melee attacks. When its Soul Tear is available, it can use it in place of one attack.
>
> ***Spectral Claws.*** *Melee Weapon Attack:* +13 to hit, reach 5ft., one creature. *Hit:* 25 (4d8 + 7) psychic damage plus 18 (4d8) cold damage.
>
> ***Soul Tear (Recharge 4-6).*** The King of the Wild Hunt targets one creature it can see within 60 feet of it.The target must make a DC 19 Wisdom saving throw, taking 61 (7d8 + 30) psychic damage on a failed save, or half as much damage on a successful one. On a failure, the creature is cursed with Soul Torment (see Appendix).
>
> ### Legendary Actions
> The King of the Wild Hunt can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The King of the Wild Hunt regains spent legendary actions at the start of its turn.
> 
> * **Rend Mind.** The King of the Wild Hunt targets one creature it can see within 60 feet of it currently afflicted by Soul Torment. The creature must make a DC 19 Wisdom saving throw. On a failure, the creature fall unconscious for 10 minutes. The effect on the creature ends if it takes damage or if the creature is no longer afflicted by Soul Torment.
> * **Phantasmal Killer (Costs 2 Actions).** The King of the Wild Hunt casts *phantasmal killer* (spell save DC 19), no concentration required.
> * **Soul Bound. (Costs 2 Actions).** The King of the Wild Hunt targets one creature it can see within 30 feet of it. A crackling cord of negative energy tethers the King of the Wild Hunt to the target. Whenever the King of the Wild Hunt takes damage, the target must make a DC 19 Constitution saving throw. On a failed save, the King of the Wild Hunt takes half the damage (rounded down), and the target takes the remaining damage. This tether last until the end of the King of the Wild Hunt's next turn.
> * **Doomsayer (Costs 3 Actions).**  The King of the Wild Hunt targets one creature it can see within 30 feet of it. The target must succeed on a DC 19 Wisdom saving throw or be magically cursed. Until the curse ends, the target has disadvantage on attack rolls and saving throws. The target can repeat the saving throw at the end of each of its turns, ending the curse on a success.

<img src='http://i.imgur.com/R7aaIut.png' style='position:absolute;bottom: 510px;right: -80px; width: 540px' />

\page

<div style='margin-top: 30px'></div>

### Naglfar 

<div style='margin-top: 10px'></div>

**Astral Vessels.** During their travels through the planes, the Wild Hunt learned the secret allowing them to build their naglfar astral vessels, ships that protect them from the raging psychic winds of the Astral Plane. The naglfar are built by their many slaves out of the fingers and toe-nails of the dead, its hull is encased in supernatural ice and its sails made of flayed humanoid skin. A naglfar has no helm, for it is only guided by a navigator that “speaks” to the many souls trapped into the ship. These vessels and their crew of warriors often cross steel with other denizens of the Astral Plane, especially the githyanki, who they battle constantly with for supremacy over the Astral Sea.

<div style='margin-top: 5px'></div>

**Diabolical Catalyst.** The naglfars are more than mere astral vessels, it is said that every slave that built it was slowly drained of its soul by the diabolical vessel, granting it a primitive consciousness and a thirst for souls. Simply standing near the ship can tear apart the mind of a creature, driving it into a magical coma. Imbued with the magic of the White Frost, the naglfar can summon supernatural cold, but it reveals its true potential as a magical catalyst for the powers wielded by navigators, allowing them to breach through dimensions or to tap into its almost limitless well of souls to fuel their spells.

```
```

<div style='margin-top:40px'></div>

___
___
> ## Naglfar
>*Gargantuan construct, chaotic evil*
> ___
> - **Armor Class** 16 (natural armor)
> - **Hit Points** 297 (17d20 + 119)
> - **Speed** 0 ft., 60 ft. (hover)
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|22 (+6)|7 (-2)|24 (+7)|3 (-4)|3 (-4)|16 (+3)|
>___
> - **Saving Throws** Con +11, Wis +0
> - **Damage Immunities** cold, poison, psychic
> - **Condition Immunities** blinded, charmed, deafened, exhaustion, frightened, paralyzed, petrified, prone
> - **Senses** blindsight 120 ft. (blind beyond this radius), passive Perception 6
> - **Languages** -
> - **Challenge** 12 (8,400 XP)
> ___
> ***Innate Spellcasting.*** The naglfar's innate spellcasting ability is Charisma (spell save DC 15). The naglfar can innately cast the following spells, requiring no material components:
> 
> * At will: *ice storm*
> * 2/day each: *fear*, *sleet storm*
> * 1/day each: *investiture of ice*, *otiluke's freezing sphere*
>
> ***Antimagic Susceptibility.*** The naglfar is incapacitated while in the area of an *antimagic field*. If targeted by *dispel magic*, the naglfar must succeed on a Constitution saving throw against the caster's spell save DC or fall unconscious for 1 minute.
>
> ***Magic Resistance.*** The naglfar has advantage on saving throws against spells and other magical effects.
>
> ***Soul Choir.*** Any creature within 30 feet of the naglfar that isn’t immune to be frightened hears in its mind the screams of the hundreds of souls trapped in the ship. As a bonus action, the naglfar can force all affected creatures to make a DC 15 Wisdom saving throw. On a failure, the creature falls unconscious. The effect ends on the creature if it is waked up by the *lesser restoration* spells or similar magic. If a creature's saving throw is successful or the effect ends for it, it is immune to the Soul Choir for the next 24 hours.
>
> ### Actions
> ***Ram.*** *Melee Weapon Attack:* +10 to hit, reach 10ft., one target. *Hit:* 33 (5d10 + 6) bludgeoning damage.
>
> ***Trap Soul.*** The naglfar targets one creature it can see within 30 feet of it that has 0 hit points and is still alive. The target must succeed on a DC 15 Constitution saving throw against this magic or die. If the target dies, the naglfar regains 22 (5d8) hit points. A creature killed by this attack cannot be brought back to life until the naglfar is destroyed.

<img src='http://i.imgur.com/sEfcQtb.png' style='position:absolute;bottom: 470px;right: -90px; width: 630px' />

</pre></code></details>

**Comment by stolksdorf** [comment]
I don't see the issue on your link, but if I'm understanding you, you trying to squeeze something that is two columns wide into a 1 column space. If that's the case, then it will render poorly. Reopen this issue if you have some more details.
