### ISSUE TITLE
Bulleted List Bugs

### ISSUE THREAD

**Issue by karagenit** [stolksdorf/homebrewery#265]
Hey,

The tool I was using to turn HTML to Markdown has a tendency to add lots of unnecessary new lines, and that has some weird effects with bulleted lists.

Result: http://imgur.com/a/tqOps

```
## Bulleted List Bugs

* First:
* This bullet doesn't render

  * When I have a new line then a sublist
  
  
* Second:
* Similar weird behavior
  * With sub-sublists and a new line
  
    * It affects all parent bullets
    
    
* Finally:
* 
  * Having an empty list element then a sublist looks odd
```

**Comment by stolksdorf** [comment]
This is standard [Markdown behaviour](https://help.github.com/articles/basic-writing-and-formatting-syntax/). Newlines inbetween lines will cause this behaviour.
