### ISSUE TITLE
Monster stat block rendering oddly

### ISSUE THREAD

**Issue by DM12176** [stolksdorf/homebrewery#266]
When making a stat block that extends into the second column the entire block jumps to the second and 3rd column, and off the side of the page.  Ive included the share link for reference

### Additional Details

**Share Link** :http://homebrewery.naturalcrit.com/share/r1DHOW8Vl

**Comment by stolksdorf** [comment]
Weird bug. This is complex/impossible to fix though, sorry.  My suggestion is to just use a wide monster stat block.
