### ISSUE TITLE
Saved homebrew in editor and then live update disappeared

### ISSUE THREAD

**Issue by lunarnite** [stolksdorf/homebrewery#267]
Clicked save in editor and then the live update disappeared, would not appear in chrome or firefox, when using the share feature it still wasn't view-able. Neither I or friends could see it anymore.

### Additional Details

**Share Link** :
http://homebrewery.naturalcrit.com/edit/Skg4E9dUEx
http://homebrewery.naturalcrit.com/share/BJNN9OUNe
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

http://imgur.com/a/jGGHA
http://i.imgur.com/f3CLrv3.png

</pre></code></details>

**Comment by lunarnite** [comment]
I'm a fucking idiot

**Comment by stolksdorf** [comment]
What was the issue?
