### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#268]
Ok, only recently found The Homebrewery, and love it, but have few questions I seem to can't find answers on.

- How to delete a brew?
- Do I need to "publish" a brew? If so how?
- Other than going to "homepage" how can I create a new brew?
--- Would be nice to have a "Create/New" link on top bar, or on my brew page?

**Comment by stolksdorf** [comment]
First two points, hit the 'i' icon on the editor bar to access a bunch of metadata and functions for your brew. Publishing, deleting, changing description and title. I'll probably be changing the icon, as a lot of people are having issues finding this. 

Publishing a brew means you are telling me you are okay with it being publicly find-able. Right now that means only published brews will show up on your user page for other users to see. Eventually this will also include if it can be found via search.

I'll look into adding some more nav items, but I'm weary of overloading the navbar.
