### ISSUE TITLE
Running Locally - ERROR: Run Mongodb.exe "ya goof!"

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#270]
Ok, loving this project!

I just downloaded nodejs, and cloned/downloaded the project to local disk, but when follow instructions "npm run watch" I get an error ">>> ERROR: Run Mongodb.exe ya goof!"

Do I need to separately download mongodb and install? Or does this have it package? 
Thanks

**Comment by stolksdorf** [comment]
Install and run [MongoDB](https://www.mongodb.com/)

**Comment by vlos** [comment]
thanks - will do. (might want to add to install (or as a side note).
PS: I see you use Patreon for donations, by chance do you use paypal?

**Comment by stolksdorf** [comment]
I'll update the docs to be more clear soon. They need some love. Thanks for the heads up.

If you can't use Patreon, don't worry about it. Just enjoy the site :)
