### ISSUE TITLE
Is there a Landscape setting/style?

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#271]
Just wondering if there is a style to switch a page to landscape mode and then back to portrait mode?

**Comment by stolksdorf** [comment]
```
<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>
```

Set the width and height to whatever dimension you want.
For a specific page
```
<style>
  .phb #p3{
    width : 210mm;
    height : 296.8mm;
  }
</style>
```

**Comment by vlos** [comment]
thanks got the following to work.
.phb#p2 {
    width : 296.8mm;
    height : 210mm;
  }
