### ISSUE TITLE
Additional Table... Things

### ISSUE THREAD

**Issue by Puliping** [stolksdorf/homebrewery#274]
While making a list of all Classes and their subclasses (Archetypes, etc.), I noticed we couldn't take an item in a table and give it a set of "subitems". An example of this is the **Tools** table (Player's Handbook, page 154): notice how _Artisan's Tools_ has various subitems (Alchemist’s supplies, Brewer’s supplies, etc.).

I made do by simply adding a ">" in front of the subitems, but it'd look much prettier if it was more like the example I gave.

**Comment by vlos** [comment]
Actually you can with a little HTML coding.
http://homebrewery.naturalcrit.com/share/By45KHbHg
Use a non-breaking space before the label.
|&nbsp;&nbsp;&nbsp;Sub Item| description |

**Comment by Puliping** [comment]
Ah! That's actually what I was looking for! Guess I'll just have to keep note of that code then. Thanks!
