### ISSUE TITLE
Bullets Will Not Render With <p> Tags

### ISSUE THREAD

**Issue by karagenit** [stolksdorf/homebrewery#275]
This is related to Issue #265 

As stated in the [markdown reference docs](https://daringfireball.net/projects/markdown/syntax#list) adding a newline between elements causes adjacent list items to be surrounded with \<p> tags (which occur within the \<li> tags).

Normally, when the HTML is rendered this causes extra space in between each list element. I think a bug exists that's causing these bullets not to appear. You can see that it's an issue with the HTML rendering by using the inline-HTML feature:

```
## Proper List

<ul>
<li> one </li>
<li> two </li>
</ul>

## List with tags

<ul>
<li><p> one </p></li>
<li><p> two </p></li>
</ul>
```

Result: http://imgur.com/a/Nr2Bk

You can see that the list elements are indented properly *and* the elements have proper spacing between them, yet the bullet itself isn't appearing.

**Comment by stolksdorf** [comment]
This is because of an `overflow:hidden` property set on the `.phb p` selector. Feel free to remove that property on your brew using css.
