### ISSUE TITLE
Lost homebrew

### ISSUE THREAD

**Issue by throwawayaccount9908** [stolksdorf/homebrewery#278]
So I had three homebres I was working on. The names were "Compendium of random homebrew" (there were two of these) and "Money mage".I have th elink to a shared PDF of the last:
http://homebrewery.naturalcrit.com/share/SJHeC7QC

Anyways. I didn't have an account before, and I made it just to report this issue. But when I wanted to edit them today it informed me that the links are faulty. Either that is true and they got deleted for some reason (and no one aside from me had access to them), or access to them was denied. What I mostly want is the links to these so I can edit further and not lose all of my progress. If need be I can provide proof that it is indeed me that had these homebrews and can give some of the content,

If they were deleted, then so be it.

**Comment by stolksdorf** [comment]
To clarify, you had 3 brews you were working on. I'm assuming there edit links stopped working in some way? If so how did they stop working/what errors did they throw? And you still have the share links for them? And those work? But not the edit links?

Worst case scenario is just to open your brews with the share link, click 'Source', copy the brew code over to a new brew and save it.

**Comment by throwawayaccount9908** [comment]
I had 3 of them, yes. And no. I didn't have the shared link for them all, just that one. The other two were still so early on that I didn't share them. And they just stopped workin. Just says "Page does not exist".

I can mostly get them back, and while my primary motivation was to get them back if possible, it was also in case it happens to anyone else.
