### ISSUE TITLE
Edition flags do not save

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#282]
Hi, 
the system edition checkbox do not save correctly (or don't load the correct value on page load)

**how to replicate:**
- open a brew
- set one or more flags
- save (or let the page save automatically
- refresh the page

**Expected result**
- checkbox that were checked, are still checked

**Verified result**
- all checkbox are unchecked

![image](https://cloud.githubusercontent.com/assets/6009914/21936489/3b39e800-d9a9-11e6-9640-c053906b3a70.png)

**Comment by stolksdorf** [comment]
Weird. I'll take a look later.

**Comment by stolksdorf** [comment]
Fixed in `v2.7.0`
