### ISSUE TITLE
offer Help

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#284]
Hi,
I know that you are probably with lot's of work in hands and because of that you have probably not spent the time your wished on this tool.

For that reason, I would like to know if you think it would be helpful for you If I sent you some more layout and organisation mock-ups (like I did before) or if you would prefer not.

Many thanks,
- Miguel

**Comment by stolksdorf** [comment]
Hey Miguel,

Thanks for the offer. I'll reach out if I need any assistance in those areas. Right now I'm swamped trying to triage and figure out all these issues.
