### ISSUE TITLE
Inserting "Class Feature" from menu inserts copies of current document

### ISSUE THREAD

**Issue by MildMastermind** [stolksdorf/homebrewery#285]
To reproduce: 

1. open a new document.
2. insert a table (for example) 
![homebrewery 1](https://cloud.githubusercontent.com/assets/24236041/21943488/aa130fba-d98e-11e6-8e2b-9a6ddccdc2dc.PNG)

3. insert a class feature
4. watch as 3 copies of your table are inserted between the class features heading and the actual class features.
![homebrewery 2](https://cloud.githubusercontent.com/assets/24236041/21943497/b147c80c-d98e-11e6-9dcc-fab279e9cc1f.PNG)

**Comment by MildMastermind** [comment]
![homebrewery fix](https://cloud.githubusercontent.com/assets/24236041/21944214/42a64a78-d992-11e6-92fc-7aed019afa31.PNG)
 I think it is just missing a "var" declaration.

**Comment by stolksdorf** [comment]
I have this fixed in v2.7, but I'm on vacation and haven't been able to finish and deploy that version yet.

**Comment by stolksdorf** [comment]
Fixed in `v2.7.0`

**Comment by pyromanci** [comment]
This is still a problem or the fix was never pushed.
