### ISSUE TITLE
Can no longer rename?

### ISSUE THREAD

**Issue by mlenser** [stolksdorf/homebrewery#286]
Can we no longer rename the titles of brews?

**Comment by stolksdorf** [comment]
Works for me. You'll have to provide more details.

**Comment by mlenser** [comment]
Perhaps I've missed how to rename. I used to be able to click the name and it'd turn into an input. That doesn't seem to be the case anymore.

I searched through the issues and didn't see anything about it.

**Comment by stolksdorf** [comment]
Yeah, sorry. Editing the metadata from a brew has been moved to that little 'i' icon on the bar. Horrible icon, I know, I'm changing it in the next version. I'll probably put back in editing the titlebar as well.

**Comment by mlenser** [comment]
Perfect, thanks Scott.

Sorry for my lack of detail on the OP - I was on mobile.
