### ISSUE TITLE
Background image and/or coloring toggle

### ISSUE THREAD

**Issue by Dhuraal** [stolksdorf/homebrewery#288]
This isn't and issue exactly, just a suggestion. Could you make it so that we can toggle the background on and off? That way you could toggle the background off, save it, and print it onto colored/parchment paper. 

1) less ink used
2) no having to fiddle with borders

**Comment by stolksdorf** [comment]
This already exists. Just hit the 'Ink Friendly' Snippet under the 'Print' option.
