### ISSUE TITLE
Custom Web Fonts (WOFF) Fonts?

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#289]
was trying to add the following custom font and didn't seem to work.
http://miniworld.com/fonts/ - works on my web server, 
but for some reason when I try to add it to Homebrewery it doesn't seem to add it.
Would like to contribute some new fonts for pages.

<code><pre>
<style>
@font-face {
  font-family: 'Espruar';
  font-style: normal;
  font-weight: 400;
  src: local('Espruar'), local('Espruar-Regular'), url("http://miniworld.com/fonts/ESPRUAR.woff") format('woff');
}
.espruar {
    font-family: Espruar;
}
</style>
<p class="espruar">test this font</p>

</pre></code>

**Comment by stolksdorf** [comment]
Your CSS is specifying that you are only changing the font for divs with the class `espruar`, which you have none of in your example.

**Comment by vlos** [comment]
Well it got eaten up by the forum.

I had  `<p class="espruar">test this font</p>`

**Comment by stolksdorf** [comment]
Works for me.

![image](https://cloud.githubusercontent.com/assets/387742/21956656/32116424-da3a-11e6-9da8-79cbf9009aff.png)

**Comment by vlos** [comment]
The font should look like the following:
http://miniworld.com/fonts/espruar.html
![espruar](https://cloud.githubusercontent.com/assets/12104952/21956797/88aa5f9a-da56-11e6-907b-c86c5ae58c39.png)

**Comment by stolksdorf** [comment]
![image](https://cloud.githubusercontent.com/assets/387742/21956818/bfd5cbf8-da3d-11e6-9986-d3fd308e7283.png)

miniworld.com has disallowed other sites from loading their fonts remotely. You'll have to upload your font to a service that you can access it from.

**Comment by vlos** [comment]
Ah, thanks. Do you know of a service?

**Comment by stolksdorf** [comment]
Ummm, not off the top of my head. I would have said just use a Public Dropbox folder, but I think they are shutting down that service, sorry.

If you do find one, do you mind commenting what it is on this thread? I'm putting together some FAQs and this question gets asked a lot. Thanks!

**Comment by vlos** [comment]
stolkdorf,

I have pulled down a local copy of homebrewery and have it running.

I added a new folder under /build call "/fonts" since /build is your static directory. I then added  the font ESPRUAR.woff to the "/fonts" directory and added the "/static" to the path in the font URL reference.

I then started the server and added the code.
![hb-customfont01](https://cloud.githubusercontent.com/assets/12104952/21963116/8e378cc4-db02-11e6-8b21-bbdfaa8c3371.png)

`<pre>
<style>
@font-face {
  font-family: 'Espruar';
  font-style: normal;
  font-weight: 400;
  src: local('Espruar'), local('Espruar-Regular'), url("/static/fonts/ESPRUAR.woff") format('woff');
}
.espruar {
    font-family: Espruar;
}
</style>
</pre>`

But still does not seem to be loading it. Would this be how I put it on my local server,
As you can see by the attached image when I select the paragraph, it shows that it has the properties which points to the local served font.

Not sure what else I need to do, any input would help.

**Comment by vlos** [comment]
Ok, did some more testing.
I added a "test" page to the server under static, I also changed the static include.
`<pre>
app.use('/fonts', express.static(__dirname + '/build/fonts'))
</pre>`
was added to line #9 of server.js
![hb-customfont03](https://cloud.githubusercontent.com/assets/12104952/21963831/06266730-db0f-11e6-81ef-3c662482206c.png)

And added testFont.html page. When I start up the server, it seems to load the font fine. 
![hb-customfont04](https://cloud.githubusercontent.com/assets/12104952/21963852/5d937de6-db0f-11e6-94bc-d881bb05139d.png)

But still same result (not showing font) when I load it up under homebrewery content.

**Comment by vlos** [comment]
If we can get this to work, then what I am thinking is I create a nodejs font server and just upload to one of the nodejs free servers my set of fonts.

**Comment by stolksdorf** [comment]
Okay so a lot going on here. The main issue is that you keep using `/static` in your url pathing. `express.static` does not works like that. The pathing you used for your `testFont.html` page was correct. You can look in the project how pathing works to any other file within `/build/assets`.

However, all of this doesn't help your issue at all. Your goal is to find a to store a file accessable online without being blocked by [CORS](http://enable-cors.org/). 

I suggest trying the following:
1. Setup a AWS S# bucket, [enable CORS](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) on it, upload your font and use that url
2. Create a dead simple server on Heroku, enable CORS, and host your file.

**Comment by vlos** [comment]
Woot got it working!!
http://homebrewery.naturalcrit.com/share/HJ_SX95Ig

I may restrict it to just homebrewery domain for access though. But right now it's open to all.

**Comment by vlos** [comment]
Question, how did you convert the custom fonts you use over to base64?
