### ISSUE TITLE
Class Table Margins Issue

### ISSUE THREAD

**Issue by Villanseacow** [stolksdorf/homebrewery#291]
I'm working on a homebrew class, and I'm having a peculiar issue that I can't figure out how to solve. Basically, the margins on the page with the class table are completely screwed up, pushing the text beneath the table up into the class table. [Image shown here.](http://imgur.com/a/B5DH7)

Anyone else have this problem, or know how to solve it?

**Comment by stolksdorf** [comment]
what's the code to replicate this?

**Comment by Villanseacow** [comment]
Here's the code for that page:

`\page

<div class='classTable wide'>
##### The Psion
| Level | Proficiency Bonus | Features |Psi Points| Psionic Disciplines 
|:---:|:---:|:---|:---:|:---:|
| 1st | +2 | Psionic Gift, Psi Bolt | 2 | &mdash; |
| 2nd | +2 | Psionic Discipline | 4 | 2 |
| 3rd | +2 |Psionic Augmentation | 6 | 2 |
| 4th | +2 | Ability Score Improvement| 8 | 2 |
| 5th | +3 | Psionic Gift Feature | 10 | 2 |
| 6th | +3 | Psionic Discipline | 12 | 3 |
| 7th | +3 |  Psionic Focus | 14 | 3 |
| 8th | +3 | Ability Score Improvement | 16 | 3 |
| 9th | +4 | Psionic Gift Feature| 18 | 3 | 
| 10th | +4 | Psionic Discipline | 20 | 4 | 
| 11th | +4 | Psionic Augmentaion | 22 | 4 | 
| 12th | +4 | Ability Score Improvement | 24 | 4 | 
| 13th | +5 | Psionic Gift Feature | 26 | 4 | 
| 14th | +5 | Psionic Discipline | 28 | 5 |
| 15th | +5 | Timeless Body, Psionic Augmentation | 30 | 5 | 
| 16th | +5 | Ability Score Improvement| 32 | 5 | 
| 17th | +6 | Psionic Discipline | 34 | 6 | 
| 18th | +6 | Psionic Gift Feature | 36 | 6 |
| 19th | +6 | Ability Score Improvement| 38 | 6 |
| 20th | +6 | Psionic Ascendance | 40 | 6 |
</div>


are able to reopen the mental gate to the astral plane and refresh your expended points. You must spend at least 30 minutes of the rest meditating to regian your psi points. 

Some of your psionic features require your target to make a saving throw to resist the feature's effects. the saving throw DC is calculated as follows:

**Psi save DC** = 8 + your proficiency bonus + your Intelligence modifier. 

Likewise, some psionic features require you to make an attack roll against a creature. The attack roll is calculated as follows:

**Psionic Attack Modifier** = your proficiency bonus + your Intelligence modifier

> ##### Psionics and Magic
> Psionics and magic are two separate forces. As a general rule, things that would affect magic, such as *detect magic*, *dispel magic*, and *antimagic field*, do not affect psionic abilities. The exception to this would be psionic features and disciplines that allow you to recreate spells. In this case, psionic energy is being used to manipulate magic and cast the spell. Therefore, these are considered to be magic, and are thus affected by the aforementioned effects. 


### Psionic Discipline
Rigorous mental focus and concentration have enabled you to channel the energy of the astral plane in a way that broadens and enhances the abilities your psionic gift to give you more control and versatility. 

At 2nd level, you learn two psionic disciplines of your choice. Your discipline options are detailed at the end of your class description. You gain additional psionic disciplines at 6th, 10th, 14th, and 17th levels. 
When you learn a new psionic discipline, you can choose one of the psionic disciplines you know and replace it with another discipline, so long as you meet the prerequisite for the new one. 

### Psionic Augmentation
At 3rd level, you gain the ability to use an action to heighten the effect of your psionic powers and disciplines. You gain one of the following augmentation options of your choice, and gain another one at 11th and 15th levels. You can only use one augmentation on a psionic power or discipline, unless otherwise noted. You cannot augment entire features, only psionic disciplines or psionic powers. 

#### Increased Range
You can spend 1 psi point to double the range of any psionic power or discipline. 

\page
`

**Comment by stolksdorf** [comment]
I can't replicate. It renders fine for me.

**Comment by calculuschild** [comment]
I can't replicate it either. Maybe share a link to your brew? (share on the top-right of the page)

**Comment by Villanseacow** [comment]
I think it's just my computer being stupid, everyone else I've talked to
irl doesn't have a problem with it.

**Comment by calculuschild** [comment]
Duplicate of #295
