### ISSUE TITLE
Live updater still not working.

### ISSUE THREAD

**Issue by Ryxian** [stolksdorf/homebrewery#298]
Issue is the same as before. Right side is there until I save, then it disappears. Issue persists in chrome, ie, and firefox. Not getting any error messages and get pdf works just fine.

**Comment by stolksdorf** [comment]
Okay. I don't know what the issue is then. Probably related to having bad HTML in your brew code.

**Comment by Ryxian** [comment]
This is my brew code

# Diclonius
The Diclonii are an odd and new race to Nirn. They originated from another realm but were pulled into this one when an experiment being done by the Psijic order involving plainer gates went awry. They are now the "youngest" race on Nirn, having been here less than a century, but the true age of their race is unknown. 
 
>### Physiology
Members of the Diclonius race are somewhat small in stature and physically weak, possibly the weakest race on Nirn. They are extremely gifted magically and are highly intelligent, though slightly unstable mentally and prone to fits of rage when wronged or provoked.
<div class='descriptive'>
##### Racial Traits
> * **Age**: It is unknown how long a Diclonius can live to be. They seem to simply stop aging physically around 20-25 and there have been no cases of any dying of old age reported. The oldest is thought to be around 100 years old.


> * **Size**: Diclonii normally range from 5' - 5'6".


> * **Culture**: Usually the same as the Psijic order though they can adapt to others if need be.


> * **Classes** : Mostly mages, though some are assassins, theves, tinkerers/inventors, or even scholars. Warriors are nearly unheard of and the few that are always fight in groups of 3-5.




**Tables and lists** both work within a note.
</div>

**Comment by calculuschild** [comment]
It might be easier to help with a link to your homebrew page. Your HTML code sometimes gets changed or hidden if you paste it into the comments here.

**Comment by Ryxian** [comment]
Do I need to publish it first?

**Comment by calculuschild** [comment]
Looks like you had some weird combination of the "descriptive text boxes" and "notes". One uses > on each line, and the other is inside "<div class='descriptive'> .... </div>". I copied your code to my own and as soon as I removed the > from inside the descriptive text box and re-saved it it seems to render fine.

**Comment by Ryxian** [comment]
Thanks.
