### ISSUE TITLE
Render Warnings: Your Browser is Zoomed

### ISSUE THREAD

**Issue by elphrite** [stolksdorf/homebrewery#299]
"This can cause content to jump columns."

I started using a new computer, and even though I'm using chrome, I receive this render warning no matter how my browser is zoomed. The pdf comes out fine, but the live updater suffers. Is it a problem with my chrome settings? It is on 100% zoom with medium text. This computer has a bigger screen than the other one, if that affects it in any way.

GitHub, Markdown, and coding in general are new to me, so if this is a really simple problem, I apologize.

**Comment by eepMoody** [comment]
I am also having this issue. Chrome 55.0.2883.95 on OSX, retina macbook. Could be to do with retina screen and viewport/resolution scaling?

Everything looks fine, no rendering issues or slow scrolling, and I'm 100% sure I don't have the browser zoomed. Ironically, the only thing causing a display issue is that the warning box is covering up part of the page I want to see. (It should probably have a "close" button)

**Comment by elphrite** [comment]
Version 55.0.2883.87 m (64-bit), Windows 10, ASUS (Cannot find model name).

I assumed it was a resolution scaling thing, but settings just had regular zoom options.

It does affect my live updater to be honest. Some brews had columns were jumping off the page, or text was slightly overlapping with tables, but print to pdf was formatted perfectly. I guess I could just use pdf to preview how everything looks, but it would be easier if everything lined up in real time.

**Comment by cryptobird** [comment]
I'm getting this one too, but no other issues besides the error permanently blocking my view of the page

**Comment by Klorophane** [comment]
Can anyone report if running local will fix the issues ?

**Comment by stolksdorf** [comment]
Disabled the zoom warning in v2.7.1. 

Apparently detecting the [Zoom Level](http://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers) for a [browser](http://stackoverflow.com/questions/14870651/how-to-check-zoom-level-is-below-100-ctrl-and-in-each-browser) is [really](http://stackoverflow.com/questions/28676431/detect-zoom-level-on-all-modern-browsers) [hard](https://github.com/tombigel/detect-zoom#read-this-detect-zoom-is-currently-unusable-for-desktop).
