### ISSUE TITLE
Simple dot leader function for Table of Contents?

### ISSUE THREAD

**Issue by DoctorDan1986** [stolksdorf/homebrewery#301]
I've looked up a million different ways to have dot leaders separating my ToC items from the page numbers; none of them work particularly well, and some have almost tanked a project.  I'm pretty much an HTML and CSS neophyte, but it'd be nice if there was an integrated way to simply insert a <leader></leader> tag without having either the dot leaders showing through the text that's supposed to cover it or having simple color blocks around the text being offensively obvious...

**Comment by calculuschild** [comment]
I think I found the same methods you did that involved using color blocks to hide the dots. I modified that approach a bit, and hopefully this is more what you're looking for. Using the CSS style here, you then just put spans around both your section title and page number. For whatever reason it wouldn't work correctly unless the page number was first (even though it is printed at the end of the line).

    <style>
      .toc ul:first-child {
        width: 100%px;
      }
    
      li span:nth-child(2){
        width: auto;
        overflow: hidden;
        white-space: nowrap;
        display: block;
      }
    
      li span:nth-child(2):after{
        color: green;
        overflow: hidden;
        content:
          " . . . . . . . . . . . . . . ."
          " . . . . . . . . . . . . . . ."
          " . . . . . . . . . . . . . . ."
          " . . . . . . . . . . . . . . ."; 
      }

      li span:first-child{
        float: right;
      }
    </style>

    <div class='toc'>
    ##### Table Of Contents
    - [<span>page 1</span><span>**1 Alchemist's Supplies**</span>](#p1)
     - [<span>p1</span><span>1.1 Foraging Ingredients</span>](#p1)
     - [<span>goblety-gook</span><span>1.2 Crafting From Alchemical Recipes</span>](#p1)
     - [<span>p1</span><span>1.3 Custom Alchemical Bombs</span>](#p1)
     - [<span>p2</span><span>1.4 Alchemical Recipes</span>](#p2)
    </div>

**Comment by DoctorDan1986** [comment]
Almost identical to the code I tried to write on my own, except I never cottoned on to your "page number first" trick.  It's actually quite thrilling how close I was to the solution.  I wish I knew why the page number needed to go first.
