### ISSUE TITLE
Went to edit my work and every sentence had been uncapitalized...

### ISSUE THREAD

**Issue by Rainbo-nerd** [stolksdorf/homebrewery#305]
What can I do, other than redoing each sentence?

Help plz?!

**Comment by stolksdorf** [comment]
You're saying that all of your brew suddenly became lowercased?

**Comment by Rainbo-nerd** [comment]
Yes, every sentence is now lowercase, even the first word.

**Comment by stolksdorf** [comment]
more details, like a link?

**Comment by Rainbo-nerd** [comment]
http://homebrewery.naturalcrit.com/share/S1-svdTIPg

**Comment by stolksdorf** [comment]
okay, seriously, I need more details. How long ago did you create this, last edit, on multiple computers, etc etc.

**Comment by Rainbo-nerd** [comment]
Sorry, I'm at work, so I'm at a different computer, although it was working fine 30 or so minutes ago, when I showed a coworker.  I created this yesterday, and started a new edit 15 minutes ago, when I noticed the problem.  The original was created on my home computer, but when I did some minor edits (grammar) 30 minutes ago it was fine, I saved and then went back to it and it was like this...

**Comment by stolksdorf** [comment]
So there's nothing in the entire system that can do that. This is most likely an issue on your end. Double check that you don't have any programs on your computer or extensions on your browser that could do this, or that no one has access to the edit link besides you.

If you can replicate it or if other people report the same issue, I'll re-open this.
