### ISSUE TITLE
Question About HTML in 3.0

### ISSUE THREAD

**Issue by dmmagic** [stolksdorf/homebrewery#308]
The Homebrewery welcome page says the following:

"All brews made previous to the release of v3.0.0 will still render normally."

I know raw HTML will be removed in order to reduce the number of problems cropping up, and that markdown will be used to replace many of the most common tags (such as spans and divs). But does the above statement mean that brews created before 3.0 won't need to be updated? In other words, I won't need to go through them all to replace all the HTML? Like they're being grandfathered in somehow?

Thanks!

:)

**Comment by stolksdorf** [comment]
I am leaving in all the old styling and rendering code for rendering "ver1" brews in the project _as well_ as all the new rendering code. In v2.7, I added a version field to all brews letting me know if a brew should use the new rendering code or the old. Wrangling all the edge cases of being able to render both has been tricky, but there are _so many_ existing brews (the site gets ~300req/min), that trying to force everyone to update their brews would be insane and just hurt the community.

Also, post v3 I won't be actively supporting any issues with rendering the old brews, it simply eats up too much of my time.  I'm hoping to release v3 by the end of feb (maybe).

Hope that answers your questions, please feel free to ask any more :)
