### ISSUE TITLE
Possible solution to PDF printing box-shadows

### ISSUE THREAD

**Issue by calculuschild** [stolksdorf/homebrewery#310]
I know there are some bugs in Chrome preventing box-shadows from printing (they appear as solid black) so you had to remove that from printing.  Well, I thought, why not just include a shadow into the border-image for those items, namely the "Note" and the "Monster Stat Block"? Works great, with one caveat: it seems there is still some slight PDF rendering issue with border-image where the corners show up blurry, as I'm sure you've noticed. These artifacts are also visible in the corner of the shadows in the form of slightly darker lines where the corner connects to the edge.

I added the shadow using www.pixlr.com/editor and adding a "drop shadow" of opacity 42%, distance 5, size 11, angle -90, and color black. That seemed to get pretty close to the one you are generating with box-shadow.

**Share link:** http://homebrewery.naturalcrit.com/edit/SyGUzquqvx :

Before (screenshot of PDF):
![image](https://cloud.githubusercontent.com/assets/5878534/22399700/8c752450-e570-11e6-9f30-bc43ae972a34.png)

After (screenshot of PDF):
![image](https://cloud.githubusercontent.com/assets/5878534/22399685/52755536-e570-11e6-9129-c05bfa50a1ee.png)

By the way, I hope I'm not infringing on your domain with these suggestions and code snippets I keep sharing. I just want to see this website continue developing. :)

**Comment by stolksdorf** [comment]
This is an ingenious idea. I'll add this to my todo list for v3.

**Comment by calculuschild** [comment]
@stolksdorf 
FYI, I've been following [this thread](https://bugs.chromium.org/p/skia/issues/detail?id=237) on Chrome's development.  Looks like the PDF box-shadow might be finally resolved. I'm hoping for an update soon.

**Comment by calculuschild** [comment]
With Chrome's bug finally fixed, this is no longer needed.

**Comment by Carcabob** [comment]
Looks like the bug is back because I'm having the problem again with the latest version of Chrome, so thanks for the info!

**Comment by calculuschild** [comment]
You are getting black borders instead of shadows? Can you provide a share
link to one of the documents that does this?

**Comment by calculuschild** [comment]
The original error was the shadows showing up as solid black instead of transparent, so @stolksdorf removed the shadows from printing at all because no shadow was better than ugly black bars.

So, the chrome bug isn't "back". It still works fine. The real issue is that the change to hide the ugly black bars was never removed even though shadows now work correctly on chrome. #354 is the code we have waiting to make the change work properly, but unfortunately we are stuck until @stolksdorf comes back since he is the only one who can push the code fixes to the live site. I wonder where he's gone...

**Comment by Carcabob** [comment]
Oh, gotcha. I'm still pretty new to github, but I've spent hours tinkering with the CSS in the Homebrewery to get it to look more like the Player's Handbook and I'd love to help with development sometime. Anyway, thanks for the explanation
