### ISSUE TITLE
Accessing older versions of work

### ISSUE THREAD

**Issue by MC936** [stolksdorf/homebrewery#313]
I duplicated a tab that I had an 18 page file on to try a few different layouts on, then made a quick stat block for a D&D game that night which saved over the top of the file. Is there any way of accessing older save files or have I just royally screwed myself over?

**Comment by stolksdorf** [comment]
Sorry to say you royally screwed yourself. Homebrewery does not track revisions. For future tinkering, it's best to just copy and paste your markup into the [new page](homebrewery.naturalcrit.com/new), and fiddle with it there. Copy back any changes you want to keep.
