### ISSUE TITLE
After saving the homebrewery, the page disappears.

### ISSUE THREAD

**Issue by Captainscar** [stolksdorf/homebrewery#316]
I wrote the page, and it was appearing fine in the editor, once I saved however, the page disappeared and I can no longer see what I am writing. Getting the .pdf works fine, and appears how I have created it, but I am unable to see the results of what I am writing until saving it as a pdf.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/S1WXKGSpPe

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div style='margin-top:450px;'></div>

# Ialoth: The Land of the Seven Empires

<div style='margin-top:25px'></div>
<div class='wide'>
##### In a land torn apart by war, a small group of adventurer's will rise from an unsuspecting town to bring unity, or destruction to the realm.
</div>

<div class='wide'>

</div>
<img 
  src='https://i.redd.it/stfx6h3zvcby.png' 
  style='width:670px' />

\page

<div class='pageNumber auto'></div><div class='toc'>
##### Table Of Contents
- **[1 Rise of the Ancients Campaign Background](#p1)**
- **[2 Countries of Ialoth](#p2)**
  - [2.1 Skeina](#p1)
  - [2.2 Aslein Isles](#p1)
  - [2.3 Kingdom of Eladia](#p2)
  - [2.4 Commonwealth of Calcona](#p2)
  - [2.5 Tyrian Federation](#p2)
  - [2.6 Vosheta](#p2)
  - [2.7 Acreshian Empire](#p2)
  - [2.8 The Free City of Vinluire](#p2)
 

 <div class='toc'>
- **[3 Races of Ialoth](#p3)**
  - [3.1 Dwarf](#p1)
  - [3.2 Elf](#p1)
  - [3.3 Halfling](#p2)
  - [3.4 Human](#p2)
  - [3.5 Dragonborn](#p2)
  - [3.6 Gnome](#p2)
  - [3.7 Half-Elf](#p2)
  - [3.8 Half-Orc](#p2)
  - [3.9 Tiefling](#p2)
  - [3.8 Aasimar](#p2)
  - [3.8 Goliath](#p2)
- **[4 Special Rules](#p3)**
  - [4.1 Critical Hits and Misses](#p1)
  - [4.2 Renown](#p1)
  - [4.3 Cleaving through Creatures](#p2)
  - [4.4 Massive Damage](#p2)
  - [4.5 Morale](#p2)
- **[4 Allowed Rescources](#p3)**

 <div class='descriptive'>
##### Keep an Eye out for these!
Throughout this document I will be writing small snippets of information, and throwing them in here. They're not critically imporant pieces of information, but they will give you tiny tibits of interesting information for you to read as you go through this document!

</div>
    
</div>
</div>
\page

### Rise of the Ancients Campaign Background
So, you’ve listened to my ramblings, and have decided to take the plunge and make a character for this campaign? Well, let’s get started then. The world of Ialoth has been defined by conflict for centuries, whether that be the humans fighting each other, dwarves and elves clashing over ideological differences, or Halflings being blamed for the theft of a priceless artefact, the world has always had conflict. This was made even worse with the introduction of magic into the world during something known as “The Alignment”, where malicious creatures from a realm quite unlike Ialoth snuck through the portal. This introduced magic, monsters, and links to other worlds. 
<div class='descriptive'>
##### The Alignment and Places of Power
Not many people know about the true origins of the alignment, some say it was a natural disaster, others say it was the will of the gods. But the truth is far more mundane. Throughout the Land of Ialoth, there are parts of the world where the barrier to other realms is weakened. A well known example of this barrier is the Ninth-Age Maelstrom that is just off the coast of Acreshia, most magical sea creatures emerge from this location, and spread far and wide. The Alignment was essentially a mass-weakening of all these borders, which lead to a large incursion of other-worldly beasts. These weakened barriers are called **Places of Power**
</div>

Before the alignment, most of humanity was disorganised, tribal people. Humans were slaughtered by these monsters, and everyone was afraid of what these creatures could do. The 7 Nations of Ialoth rose from these tribal organisations, and became driving powers in keeping humanity alive during this dark time. The empire of the elves fell, and in its place, humanity rose. The Alignment was nearly 500 years ago, and since then, every creature, human or not, has learnt to adapt to the new world.

In this day and age, it is adventurers who keep the world safe from the terrifying creatures that arose from The Alignment. Typically, the groups that survive the longest are the ones that have a variety of skills in their group, most adventurer’s draw inspiration from the heroes of their past, one such set of Heroes was known as The Broken Griffin’s, a party of four adventurers who stopped an evil Lich from raising an army of the dead.

Your characters are on the island of Skeina, whether you were born there, or came from regions abroad, you are free to pick whatever race you want, and whatever class you believe suits your character best. You are in the City of Drolzach, for many different reasons, however the City is abuzz with gossip about a series of brutal murders, and the notes that have been left behind on every corpse.

</pre></code></details>

**Comment by stolksdorf** [comment]
The live renderer doesn't like the way you've structured your TOC page. Replace with this

```


<div class='pageNumber auto'></div>

<div class='toc'>
##### Table Of Contents
- **[1 Rise of the Ancients Campaign Background](#p1)**
- **[2 Countries of Ialoth](#p2)**
  - [2.1 Skeina](#p1)
  - [2.2 Aslein Isles](#p1)
  - [2.3 Kingdom of Eladia](#p2)
  - [2.4 Commonwealth of Calcona](#p2)
  - [2.5 Tyrian Federation](#p2)
  - [2.6 Vosheta](#p2)
  - [2.7 Acreshian Empire](#p2)
  - [2.8 The Free City of Vinluire](#p2)
 
 </div>

 <div class='toc'>
- **[3 Races of Ialoth](#p3)**
  - [3.1 Dwarf](#p1)
  - [3.2 Elf](#p1)
  - [3.3 Halfling](#p2)
  - [3.4 Human](#p2)
  - [3.5 Dragonborn](#p2)
  - [3.6 Gnome](#p2)
  - [3.7 Half-Elf](#p2)
  - [3.8 Half-Orc](#p2)
  - [3.9 Tiefling](#p2)
  - [3.8 Aasimar](#p2)
  - [3.8 Goliath](#p2)
- **[4 Special Rules](#p3)**
  - [4.1 Critical Hits and Misses](#p1)
  - [4.2 Renown](#p1)
  - [4.3 Cleaving through Creatures](#p2)
  - [4.4 Massive Damage](#p2)
  - [4.5 Morale](#p2)
- **[4 Allowed Rescources](#p3)**

</div>

 <div class='descriptive'>
##### Keep an Eye out for these!
Throughout this document I will be writing small snippets of information, and throwing them in here. They're not critically imporant pieces of information, but they will give you tiny tibits of interesting information for you to read as you go through this document!


</div>


\page
```
