### ISSUE TITLE
Cover Image Issues and small text align.

### ISSUE THREAD

**Issue by fitsou** [stolksdorf/homebrewery#317]
Hi
Im totally new to this so my problem may be a rookie mistake..
Im trying to put the image that you can see as cover, but i cannot make it big without the editor cut her. (look at the link)

Also how can i make the Version text appear aligned in the center?

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/B1ax-T6wl

**Comment by stolksdorf** [comment]
I think I am mmisunderstanding you, but if you want to center text use[`text-align:center`](http://www.w3schools.com/cssref/pr_text_text-align.asp)

**Comment by fitsou** [comment]
That does not work with the image...
I want to make the logo appear bigger! if i go above height:200px it cuts the image.. i want it in 400px
How can i do that?

With the text orientation i made some progress. The issue was that in the start of the page (I choose the default option for cover) there was some code that "locked" the whole page orientation. I removed it and i manage to control each section as i like.
Now i have another question how can i Leave a small space in the beginning of each paragraph??

**Comment by fitsou** [comment]
Also is there a glossary with option for each code?
Example: Class=wide (what other options do i have instead of wide?

**Comment by stolksdorf** [comment]
- You have malformed html, making most of your styling not work
- you don't need to use so many wide divs
- `max-width` and `max-height` do what they say, they set the max dimension, but don't actually change the dimension of your image
- If you're not familiar with HTML, try writing less of it. The tool works fine without all the tweaking.

There is no current glossary.  



```
<div class='wide' style='text-align:center'>

<img src='http://i40.photobucket.com/albums/e228/Fitsou/wow_zpsv1tfx5o1.png ' style='width:600px' />


## 5e RPG Conversion

#### Version: 2.0.5
##### The sands of time have run out.
-Medivh, the last Guardian
##### Sometimes, the hand of Fate must be forced.
-Illidan Stormrage

###### Many have waited for Blizzard to approve another conversion of their world to the tabletop playing realm.
Alas, many waited in vain. However, tabletop players are well-known for their persistence and tenacity in getting what they want to play--or at least, satisfying themselves with an adequate replica.
And thus, the WoW RPG 5e Project begun. This conversion is of the much-loved World of Warcraft Role Playing Game, as for 5th edition of Dungeons and Dragons, made by the fans, for the fans. This not only includes special classes, races, and magical spells, but also includes magical items, and even a few subsystems built in the streamlined format of 5th edition, for the benefit of all role-players.

###### **Project Start:** Aug 27, 2015
**Edition (Content updates only):** Beta released on Oct 11, 2015. 1.7 released on July 2016. 1.9 released on August 2016. 2.0 released on November 28.

###### **Note:** The monster manual can be found [here](https://docs.google.com/document/d/14tdxydPO6l-ogj_pKC77AQ9MNwZ_sV0OEF_xn_m980c/edit).

###### **Note:** Forum Discussion can be found [here](http://www.thepiazza.org.uk/bb/viewtopic.php?f=58&t=13944).

##### Credits
|									||
|:----:|:-------------|
|Project Manager					|Arrius Nideal|
|House Rules Conversion				|Arrius Nideal, Djmove|
|Writing & Edditing					|Arrius Nideal, Djmove, Fitsou|
|Design & Graphics Manager			|Fitsou|
|Illustrators						||
|Warcraft Inspiration and Setting	|**Blizzard Entertainment. Inc**|
|Additional Inspiration				| [WoWWiki.com](wowwiki.wikia.com) & The Internet|
|Contributors						|Mcgeneral, Big Mac, Grimm, Pagnabros, as well as all the Forum commenters|

</div>
```

**Comment by fitsou** [comment]
What you wrote turn the orientation of the whole page to the Center. That is not what i want.
Correctly or not, Now the first page looks exactly the way i want. (I copied only the lines regarding the logo if you take a look). I would appreciate if you saw me a Correct version that looks the way i have it right now.

Yes practically this is the first time that i write HTML... that why i making stupid questions and mistakes. thanks for your patience and your help.

**Comment by stolksdorf** [comment]
No problem.
