### ISSUE TITLE
Can't see the brew I'm working on

### ISSUE THREAD

**Issue by PhilippeBolduc13** [stolksdorf/homebrewery#321]
It seems I can't see the document I'm working on. Here's what I see when I'm selecting the document from my profile.

### Additional Details

**Share Link** : https://scontent-yyz1-1.xx.fbcdn.net/v/t34.0-12/16426459_10154232764673314_2140315761_n.png?oh=5d5d663eb6f01f16cc2c79517ba1a00d&oe=58946275

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

## Elemental Bender
As an Elemental Bender you must choose one of the following elements: Air, Water, Earth and Fire.

#### Spell Casting ability
___
As an Elemental Bender you gain the ability to cast elemental spells using your ki points. You use the same Spell ability modifier and Spell DC as your Ki save DC. The cost in ki points of your spells follow the table below.

<div class='classTable'>
##### Spell Cost
| Spell Slot Level | Ki Cost | Monk Level Minimum
|:---:|:---:|:---|:---:|
| 1st | 2 | 3|
| 2nd | 3 | 7 |
| 3rd | 4 | 12|
| 4th | 5| 16
</div>

Starting at level 3rd, you know two cantrips and two bending spells. You gain two more spells at level 6th and 17th, you also gain one new spell at level 11th. Each time you gain new spells, you can change spells you already knew.
___
**Cantrips:** The two cantrips you know at level 3rd are Basic Bending and Elemental Bolt.

> #### Elemental Bolt
*Cantrip*
___
>- **Casting Time:** 1 action
>- **Range:** 60 feet
>- **Duration:** Instantaneous
>- You hurl a bolt of your element. Make a ranged ki
attack against one creature within range. On a hit, a target takes 1d10
bludgeoning damage (Air and Earth Bending) or cold damage (Water Bending) or fire damage (Fire Bending).
>- This form's damage increases by 1d6 when you
reach 5th level (2d10), 11th level (3d10), and 17th
level (4d10).

#### Elemental Feature:
___
___
At level 6th, you gain a new feature depending of your element:
___

- **Air:** Whenever you are blinded, attack rolls against you don't have advantage and your attack rolls don't have disadvantage.
- **Water:** You gain a swimming speed equal to your normal speed. Ice and snow are no longer difficult terrain for you. in addition, you can perform your elemental spells underwater without penalty.
- **Earth:** When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack's damage against you.
- **Fire:** As a bonus action on your turn, you can choose a target. Until you choose to end the effect as a bonus action, you have advantage on attack rolls against the target, but attack rolls against you have advantage.

#### Sub-Style
___
___
At level 11th, your control over your elements because more precise. You can choose one of the two sub-style for your element.

___
**Air:** 
- Spiritual projection: You gain the ability to cast the Etherealness spell at the cost of 9 ki points. You also gain proficiency in Animal Handling. (You gain double proficiency if you are already proficient in this skill)
- Levitation: You gain the ability to fly. You have a flying speed equal to your walking speed at all time. You also gain proficiency in Acrobatic.(You gain double proficiency if you are already proficient in this skill)

**Water:** 
- Healer: You gain the ability to cast Cure Wounds as a 5th level spell and the Greater Restoration spell for both 6 ki points. You also gain proficiency in Medicine. (You gain double proficiency if you are already proficient in this skill)
- Blood Bender: You gain the ability to cast Dominate Person for 6 ki points, Hold Person for 3 ki points and Crown of Madness for 3 ki points.

**Earth:**
- Lava Bender: When using an earth bending spell, you can add 2 ki points the spell add 3d6 fire damage. Zones spell create lava. Your basic bending cantrip works on lava and you are able to cool down the lava using your bonus action.
- Metal Bender: When using an earth bending spell, you can add 2 ki points the spell add 3d8 slashing damage.  Your basic bending cantrip works on metal.  

**Fire:**
- Lighting Bender: You gain the ability to cast the chain lightning spell for 8 ki point. You also get resistance to lightning.
- Combustion Bender: You gain the ability to cast the Disintegrate spell for 8 ki point but it deals fire damage instead of force damage.  You also gain resistance to fire.

#### Investiture of Element
_________
At level 17th, you gain the ability to cast the Investiture of Fire, Ice, Stone or Air for 8 ki points.

\page

##### *FireBending Spells:*
>##### "Fire is the element of power."
— Iroh
<div class='spellList'>

##### 1st Level 
- BackFire
- Battering Flames
- Blinding Spray

##### 2nd Level 
- Blazing Meteors
- 

##### 3rd Level 
- Barrage of Flames
- Blinding Shot
- 

##### 4th Level 
- Ash Rain
- 

</div>

>#### Basic FireBending
>*Cantrip*
___
>- **Casting Time:** 1 action
>- **Range:** 30 feet
>- 
>- **Duration:** Instantaneous
>- Anyone who is a firebending can initiate the following effects within a 5-foot cube.
>- You cause fire to form into simple shapes and animate at your direction.
>- You can cause a flickering flame to appear from your body (usually in your hand). The flame remains there as long as you concentrate, and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet.
>- You can instantly expand any existing flame in one direction, provided that wood or other fuel is present in the location.
>- You instantly extinguish any flames within a 5-foot cube. 
>- The area you can affect increases by 5 feet and the amount of bright light your fire produces increases by 10 feet when you reach 5th level (10-foot cube, 20 feet of bright light), 11th level (15-foot cube, 30 feet of bright light), and 17th level (20-foot cube, 40 feet of bright light).

</pre></code></details>

**Comment by stolksdorf** [comment]
Duplicate here #247
