### ISSUE TITLE
Lost File - The Husk

### ISSUE THREAD

**Issue by JamesIntrocaso** [stolksdorf/homebrewery#322]
Hey There,

I was working in The Homebrewery this morning and everything was saving. Like an idiot I forgot to copy the code and when I went back it wasn't saved in my recent brews. Should I look somewhere else for it? Is it lost? I know for sure I was saving and it was also saving automatically.

Thanks!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
@JamesIntrocaso Do you still have the links to that document? It's probably long gone by now, but there's a chance it's cached somewhere on the internet.

For now, I'm going to close this with the assumption that there's nothing we can do since this was so long ago.
