### ISSUE TITLE
Can't close render warnings

### ISSUE THREAD

**Issue by TmpAcc257949** [stolksdorf/homebrewery#325]
The render warning, notifying users that the Homebrewery works best on Chrome, can't be closed.

This can block the screen for those of us who don't always have access to a desktop version of Chrome.

### Additional Details

**Share Link** : http://m.imgur.com/gZJBDSY

**Comment by stolksdorf** [comment]
This is expected behaviour. I receive an excessive number of issues from users experiencing rendering issues on non-chrome browsers, which I don't support. Users ignore more discreet warnings and close others without reading them.

**Comment by SuscriptorJusticiero** [comment]
This warning is useful *exactly once*. One would expect to be able to hide it manually once it has outlived its usefulness.
