### ISSUE TITLE
Removing the 'Page Number' bar decoration

### ISSUE THREAD

**Issue by DoctorDan1986** [stolksdorf/homebrewery#326]
I have a few pages that employ full-page pictures, but that have text boxes/stat boxes/etc on top of them.  On these pages, I do not want that decorative bar that the page numbers appear by (and the chapter names above) to show.  I've messed around with z-index, but it'd be much more helpful if there was a simple command we could simply employ to delete the decoration on a per-page basis.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
`#p1::after{display :none}`

**Comment by Sansd20** [comment]
I am unable to get this to work.

**Comment by DoctorDan1986** [comment]
Change the number 1 in the example above to the brewery page that you want to remove the decoration on.  So, if you want to remove the decoration on page 31, you would write:

#p31::after{display : none}
