### ISSUE TITLE
Parser can't parse end-parenthesis in URL

### ISSUE THREAD

**Issue by BrentNewhall** [stolksdorf/homebrewery#327]
End-parentheses in URLs cause the parser to stop parsing the URL at that point. For example:

  [Link to full image](https://example.com/image(1)_sample.jpg)

Renders as:

  Link to full image_sample.jpg

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

  [Link to wikimedia page](https://commons.wikimedia.org/wiki/File:Каменный_век_(1).jpg)

</pre></code></details>

**Comment by stolksdorf** [comment]
I'm assuming you are using the Markdown syntax for your image link. In that case refer to [this thread about using brackets in Markdown links](http://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses).

**Comment by BrentNewhall** [comment]
Yep, I'd found that. :-) I tried several of those alternatives -- including
Bare, encoded and delimited -- and couldn't find one that worked. With HTML
going away in later versions of Homebrewery, which syntax should I use if I
need an end-parenthesis in a hyperlinked URL?

**Comment by stolksdorf** [comment]
Cool. Looks like that is a bug then.

**Comment by stolksdorf** [comment]
Looks like it's [not possible without some deep changes](https://github.com/chjj/marked/issues/690) to the markdown lexer I'm using.

If you replace the closing paren in your url with `%29` it will though.

**Comment by BrentNewhall** [comment]
FYI, I just tried this and it inserted the literal %29 into the URL without
interpreting it as the ")" character. :-/

**Comment by stolksdorf** [comment]
okay.
