### ISSUE TITLE
Not clear how to rename/edit metadata of brews

### ISSUE THREAD

**Issue by hephalumph** [stolksdorf/homebrewery#328]
I am not sure how or why, but one of my brews was initially saved with no title/name. And I cannot name it now. I don't *really* want to clog up the servers by replicating it in whole, simply to add a name. But I can't figure out any other options.

**Comment by calculuschild** [comment]
Follow the bar with the Editor, Tables, PHB snippets over to the right and click on the little hamburger icon button (☰). That will open up a menu where you can change the name.

@stolksdorf , it might be a good idea to change that button from a menu icon to something that says "Edit Project Data" or something. This question has popped up more than once.
