### ISSUE TITLE
I LOST ALL MY BREW! And my game is tomorrow!

### ISSUE THREAD

**Issue by MarquinhoC** [stolksdorf/homebrewery#329]
Hi! I finally finished writing by brew and decided to teak a break and go get dinner.
When I came back EVERYTHING WAS GONE to yesterday's version. I didn't save the code but I did save regularly my code. Is there any way to get it back?

I'm running my game tomorrow. Is there any way to get it back? 
This is my username: http://homebrewery.naturalcrit.com/user/marquinhoC
And the brew is called: Hacia el Episodio Nº 3

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by ChosenSeraph** [comment]
something probably cleared your computer cache, if you had the link to the brew you should be able to get it back. My advice is to bookmark individual brews.

**Comment by calculuschild** [comment]
This looks like it might be related to #654 .

Closing for now since the document in question has since been deleted.  Feel free to reopen this issue if this is still a problem for you and you can provide more information. @MarquinhoC

**Comment by JoeCreates** [comment]
The user's brews list is stored locally in the browser cache!? I've just discovered I've lost my brews also... I don't remember the edit links.
