### ISSUE TITLE
Unable to Edit Brew

### ISSUE THREAD

**Issue by ApolloPhin** [stolksdorf/homebrewery#331]
I was attempting to share the brew with a friend to check on what needs to be edited and usability. However I am now unable to see the brew at all. I did notice at the top of the screen as seen in the attached image. I do not know if this is an added issue. Could use some help.
![issue](https://cloud.githubusercontent.com/assets/25593264/22661700/fb90c45a-ec6b-11e6-99bb-1e7db910a91f.PNG)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE
H1Gg0SEtDe
</pre></code></details>

**Comment by calculuschild** [comment]
You've got a <style> tag on line 40 that should not be there, and is causing the whole thing to crash.

To get your code back, you can click the "share" button on the top right, then when that comes up (it will also be a blank page) you can click the "source" button on the top right, which will load up your code. Copy and paste this into a new brew and delete that <style> tag before you save.

**Comment by ApolloPhin** [comment]
Thank you this worked. Is there a way to have the broken page removed or deleted?

**Comment by calculuschild** [comment]
Haha.... no, I don't think there's a way to do that yet. I've got a couple copies of your thing on my account as well from me trying to figure out your broken page and I can't delete them. Might be good if there were a delete button right there on the profile page, huh?

**Comment by ApolloPhin** [comment]
yes, that would be wonderful

**Comment by stolksdorf** [comment]
Pushed an update in v2.7.2 that adds a button on the user page to delete a brew.
