### ISSUE TITLE
Wrap Source Text - option

### ISSUE THREAD

**Issue by tylerpaul** [stolksdorf/homebrewery#332]
This is to **improve user experience** and is **not an "Issue"**.

It would be nice to be able to wrap source text when viewed.
Some users put time into formatting their source, but, since the editor wraps text, many do not consider it. This leads to painful use of the horizontal scrollbar or Home and End keys to navigate source text.
There are workarounds, including copying the text into a simple text editor, but I thought it might improve your already excellent product (perhaps by only a small margin).

**Comment by calculuschild** [comment]
This is good and will not be hard to implement. Thanks for the feedback!

**Comment by Rae2che5** [comment]
Fixed by #665.
