### ISSUE TITLE
How to force an indent?

### ISSUE THREAD

**Issue by blackwind1kaze** [stolksdorf/homebrewery#334]
So i'm working on an adventure and i'm wanting to have the first line always indent like most of the paragraphs do however some of them don't do this automatically so i was wondering how to force the indent without adding something stupid like a line with a dot or something like that.

Example: (ignore the {Line} stuff)

{!Line1}The adventure starts with the group walking through [Redacted] in order to reach their destination of [Redacted].
{!Line2 - for a paragraph break}
{!Line3}[Redacted] is normally just a trade route so seeing merchant wagons on this road is common. Others travelling this road are uncommon but most of the rocky terrain is stable enough to allow other types of traffic.

Line 3 will automatically indent but Line 1 won't.

**Comment by DoctorDan1986** [comment]
Try adding this to your <style> setup:

tab { padding-left:2em; }

Then just put a <tab> where you want it to indent, and </tab> when you want that to end, like so:

<tab>The adventure starts with the group walking through [Redacted] in order to reach their destination of [Redacted].</tab>

**Comment by DoctorDan1986** [comment]
You can alternately exchange '2em' with 'Zpx', where 'Z' equals the number of pixels you want to indent for very fine control.

**Comment by blackwind1kaze** [comment]
cool, thank you for helping me solve this :)
