### ISSUE TITLE
*New* blank document not working, showing my old page

### ISSUE THREAD

**Issue by Benz74M** [stolksdorf/homebrewery#335]
When I click "Create Your Own", I get a document I was working on, not a new page.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Expected behaviour. The site caches a new document in local storage until you save it. This is to stop users from losing their work if you close the tab before saving. It's also useful for me doing testing in development.
