### ISSUE TITLE
Unable to get back to a default Letter size format? (8 1/2 x 11)

### ISSUE THREAD

**Issue by Benz74M** [stolksdorf/homebrewery#337]
Don't know what happened, but my document seems to be stuck on A4 size. I want Letter size and I don't know how to get back to that format. I don't see any page format code... (When I try to print it, it has a blank page for every page, the reason for which I guess is incorrect format.)

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/Hk7Sxb6Ol

**Comment by DoctorDan1986** [comment]
Don't know how to help, but I read the share link, saw your "mostly dead" Macguffin for characters level 1-2, and the "needs a Miracle Max" bit, and just about lost my shit laughing.  Well done - I love the references.

**Comment by stolksdorf** [comment]
Line 501 you have styling that sets your document to A4

**Comment by Benz74M** [comment]
Hey, thanks for your help guys!

Ben
