### ISSUE TITLE
Pdfs are blank

### ISSUE THREAD

**Issue by NedTurner613** [stolksdorf/homebrewery#339]
This issue only started a few days ago. I'm not certain if the issue is with my system or not, but whenever I print as a pdf, the pdf is completely blank. It looks fine during the actual preview, but the pdf comes out without any images on it at all, which is baffling

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
You might need post the "share" link to your brew so someone can look at what's going on in your project.

**Comment by NedTurner613** [comment]
I'm not sure it's the brew itself. I think it might be the app? Because it
looks fine in the print preview. It isn't until it actually makes the pdf
that you can see the flaw

**Comment by calculuschild** [comment]
There are some cases where the PDF generation and the web page render are actually quite different. If you are on Chrome, for example, they have not actually implemented drop shadows, box shadows, and some text art styling. There are also issues with tables and other things that are handled differently in the PDF renderer versus the web page renderer. In any case, it doesn't hurt to just click the "share" button and paste the link on here so we can eliminate that possibility.

**Comment by NedTurner613** [comment]
Here's an example of one of my Homebrews. There doesn't seem to be any
problem until it finishes exporting, at which point I get a blank document,
which I've attached.

http://homebrewery.naturalcrit.com/share/NJivWjqjg

I'm using Chrome Canary for this, and the most bewildering thing is that
this issue only started occurring less than a week ago

**Comment by calculuschild** [comment]
Well, using your share link I can generate a perfectly fine PDF (attached) using both Chrome and Canary but on Windows.
[The Homebrewery - NaturalCrit.pdf](https://github.com/stolksdorf/homebrewery/files/784174/The.Homebrewery.-.NaturalCrit.pdf)

I think we can safely eliminate your brew and the Homebrewery Site as being the likely source of issues. I wonder if its a bug in the latest version of Canary for mac? Googling this seems like it's popped up in the past where people can see a print preview that looks fine but printing PDF results in a blank document.

It is a problem with printing from any other websites?

**Comment by calculuschild** [comment]
Closing this since the issue seems to have been related to an old version of Chrome.
