### ISSUE TITLE
Chrome pdf export pushing wide headers to bottom of page

### ISSUE THREAD

**Issue by PhantasticJoe** [stolksdorf/homebrewery#340]
### Additional Details

Basically, when I try and save my stuff as pdf, everything in the wide block after the columns with tables gets shunted to the bottom of the page, and offscreen. It looks great in share, just not once it's actually exported. Edit: This on Chrome with Mac btw

Here's an example doc that demonstrates the problem pretty simply.
**Share Link** : http://homebrewery.naturalcrit.com/share/BybF2voNFx

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='wide'>
### Testing
</div>
<div class='classTable'>
##### Test Table
| Level | Proficiency Bonus | Features | Spiritual Biochemistry|
|:---:|:---:|:---|:---:|
| 1st | +2 | Phased Linguist | +1 |
| 2nd | +2 | Police Necromancer | +2 |
| 3rd | +2 | Pharmaceutical Gunslinger | +2 |
| 4th | +2 | Ability Score Improvement, Astrological Botany | +3 |
| 5th | +3 | Plasma Outlaw | +4 |

</div>

```
```

<div class='classTable'>
##### Test two
| Level | Proficiency Bonus | Features | Spiritual Biochemistry|
|:---:|:---:|:---|:---:|
| 1st | +2 | Civil Alchemy | +1 |
| 2nd | +2 | Seismological Divination | +2 |
| 3rd | +2 | Gunslinger Corruptor | +2 |
| 4th | +2 | Ability Score Improvement, Immunological Incantations | +3 |
| 5th | +3 | ─ | +4 |

</div>

<div class='wide'>
### Here's where the problem is

Everything down here goes away
</div>

</pre></code></details>

**Comment by calculuschild** [comment]
Yes... A bug in the code. The column-break done by the ``` generates `<pre><code></code></pre>`. This has the CSS style of
```
//Column Break
pre, code{
	visibility                 : hidden;
	-webkit-column-break-after : always;
	break-after                : always;
	-moz-column-break-after    : always;
}
```

Unfortunately, `-webkit-column-break-after: always;` is causing issues. I'm not sure why it is messing things up that way, but it seems like its always trying to do a full page break rather than just a column break, and it ends up causing weird issues. Most of the values on this page seem to have the same result (http://realworldvalidator.com/css/properties/-webkit-column-break-after)

In your case, if you're using Chrome, there's already the normal "break-after" tag there, so just erase that property by adding to your code:

```
<style>
.phb pre, code { -webkit-column-break-after: initial;}
</style>
```

Edit: It almost seems like the combination of -webkit-column-break-after and -moz-column-break-after is causing the issue. Either one by itself (and changing to ```-webkit-column-break-after: column```) seems to work fine. It's not until you have both that weird things happen. Maybe it's interpreting them twice somehow giving you two column-breaks in a row.

**Comment by PhantasticJoe** [comment]
Yep that fixes the problem. Thanks for the help!

**Comment by calculuschild** [comment]
@stolksdorf Might want to look at this and see if it makes sense to remove -webkit-column-break-after or -moz-column-break-after here, especially where you're only really supporting Chrome.
