### ISSUE TITLE
Professional Lore's section is blank

### ISSUE THREAD

**Issue by fatty8cake** [stolksdorf/homebrewery#342]
I am not sure if the class is unfinished, or if it is a problem that I am experiencing. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Can you clarify what you mean by "professional lore?"

**Comment by fatty8cake** [comment]
The features you start get at level 3 is complete blank

**Comment by calculuschild** [comment]
Can you maybe provide a link to the brew you are working on? I still have no idea what you are talking about.

**Comment by fatty8cake** [comment]
http://homebrewery.naturalcrit.com/share/E1SmjtnRx if you look under the Professional Lores Section,  it's completely blank.

**Comment by calculuschild** [comment]
Is this your brew? Or someone else's? This sounds like a question you should be asking the author of the brew, not the developer of the website he built it on. A quick google search shows you probably found that brew from here? http://www.giantitp.com/forums/archive/index.php/t-483790.html

I would post on that forum and ask the author your question.

**Comment by fatty8cake** [comment]
Oh OK thanks man,  I though this is where I would report to the author.

**Comment by Dustfinger1** [comment]
should probably close this issue, as its not code relevant.
