### ISSUE TITLE
Render Warning won't go away...

### ISSUE THREAD

**Issue by Thethousandfold** [stolksdorf/homebrewery#345]
As soon as I load the page, I get a big "RENDER WARNINGS: Made for Chrome" alert on the right hand side of the page. This never leaves the page and blocks all view of the finished brew...even when I'm using Chrome.

I am using an Ipad Pro.

Thanks!
![img_1608](https://cloud.githubusercontent.com/assets/25954595/23211681/39c37062-f8d1-11e6-80b0-766643ffb1d9.PNG)

**Comment by Konahrik13** [comment]
I also want to know if it's possible to remove the warning. I can't read things that are in the corner where it is because it covers it and there's no option to get rid of it.

I use Firefox and getting the warning every time is irritating.

**Comment by Giorgiosmikelis** [comment]
I have the excact same problem here. I have an iPad 4 mini, I am using chrome app and the warning is still there. Please fix it.

**Comment by Konahrik13** [comment]
Please give us Firefox users a close button for it. It blocks text that can't be read because there's no way to make it go away. I understand that for some reason it takes offense at Firefox but having an option to say "Yes I know. Close." would be great.

**Comment by SuscriptorJusticiero** [comment]
I second Konahrik13's suggestion. I don't have Chrome in all the computers I work at, for example, so it's not because of ignorance that I'm using something else. It should be possible to hide it at least for the session.

**Comment by Thethousandfold** [comment]
Yes, the option to click ignore would be great!

**Comment by stolksdorf** [comment]
Option to close the render warnings window add in `v2.7.4`.
