### ISSUE TITLE
Wide monster stat blocks not displaying properly

### ISSUE THREAD

**Issue by Geodude6** [stolksdorf/homebrewery#347]
When a monster stat block becomes too large for one single column, the entire stat block jumps over to the next column, with the excess stat information spilling over into a barely-visible third column.

### Additional Details

**Brew code to reproduce** : <details><summary>RAW Ancient Black Dragon stat block</summary><code><pre>

___
> ## Ancient Black Dragon
>*Gargantuan dragon, chaotic evil*
> ___
> - **Armor Class** 22 (natural armor)
> - **Hit Points** 367 (21d20+147)
> - **Speed** 50 ft., fly 100 ft., swim 50 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|27 (+8)|14 (+2)|25 (+7)|16 (+3)|15 (+2)|19 (+4)|
>___
> - **Saving Throws** Dex +9, Con +14, Wis +9, Cha +11
> - **Skills** Perception +16, Stealth +9
> - **Damage Immunities** acid
> - **Senses** blindsight 60 ft., darkvision 120 ft., passive Perception 26
> - **Languages** Common, Draconic
> - **Challenge** 21 (27,500 XP)
> ___
> ***Amphibious.*** The dragon can breathe both air and water.
>
> ***Legendary Resistance (3/day).*** If the dragon fails a saving throw, it can choose to succeed instead.
> ### Actions
> ***Multiattack.*** The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.
>
> ***Bite.*** *Melee Weapon Attack:* +15 to hit, reach 15 ft., one target. *Hit*: 19 (2d10+8) piercing damage plus 9 (2d8) acid damage.
>
> ***Claw.*** *Melee Weapon Attack:* +15 to hit, reach 10 ft., one target. *Hit*: 15 (2d6+8) slashing damage. 
>
> ***Tail.*** *Melee Weapon Attack:* +15 to hit, reach 20 ft., one target. *Hit*  17 (2d8+8) bludgeoning damage.
>
> ***Frightful Presence.*** Each creature of the dragon's choice that is within 120 feet of the dragon and aware of it must succeed on a DC 19 Wisdom saving throw or become frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on a success. If a creature's initial saving throw is successful or the effect ends for it, the creature is immune to the dragon's Frightful Presence for the next 24 hours.
>
> ***Acid Breath (Recharge 5-6).*** The dragon exhales acid in a 90-foot long, 10-foot wide line. Each creature in that line must make a DC 22 Dexterity saving throw, taking 67 (15d8) acid damage on a failed save, or half as much on a successful one.
> ### Legendary Actions
> The dragon can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The dragon regains spent legendary actions at the start of its turn.
>
> ***Detect.*** The dragon makes a Wisdom (Perception) check.
> ***Tail Attack.*** The dragon makes a tail attack.
> ***Wing Attack (Costs 2 Actions).*** The dragon beats its wings. Each creature within 15 feet of the dragon must succeed on a DC 23 Dexterity saving throw or take 15 (2d6+8) bludgeoning damage and fall prone. The dragon can then fly up to half its fly speed.

</pre></code></details>

**Comment by stolksdorf** [comment]
Use a wide monster stat block?

**Comment by Geodude6** [comment]
I did use a wide monster stat block.

**Comment by calculuschild** [comment]
Can you provide the "share" link to your brew to see what's going on?
