### ISSUE TITLE
Issue with a suggested fix

### ISSUE THREAD

**Issue by sorakite5** [stolksdorf/homebrewery#350]
At some point or another I lost the URL to a brew I made. Now that I want to go back and edit it, I cannot for the life of me find the thing to do so! That being said, I have a copy of the brew printed to PDF, and that made me wonder if at some point it may be possible to implement a way to upload a PDF and place the information into a brew.

I'd simply copy-paste it and reorganize it to the look it had, however that does not work well as copy pasting adds an extra character between every single letter. Would be faster to simply retype the whole thing!

**Comment by stolksdorf** [comment]
In regards to your lost brew, there are many ways to recover it.

- If you made any edits with an account, you can go to that account's page
- Homebrewery stores the last handful of brews you've viewed or edited under the recent brews tab
- Check your browser history for the edit link
- If all of that fails, find the share link, open the source and copy it into a new brew.

Adding a feature of parsing a PDF would be incredibly difficult, rarely used, and often misused by users trying to upload a PDF not created by the site expecting it to work.
