### ISSUE TITLE
HTML & CSS Considerations

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#351]
From reading other posts it sounds like you are having problems with styling because of the "nested" css styles you currently use.

One thought is to build less of a hierarchy and make your css more "local" to elements/tags.

For example. In your monster stat block, if you replace BLOCKQUOTE tag with a div and assign that div a class something like .statBlock (or .quickStatBlock) you can remove all your prefixing of .phb + hr + blockquote to simply .statBlock (this has side benefit of removing need of HR above the block quote).

This should help cleanup your css issues, because things are more "local" to the specific div/element.

Sample markup is here:
http://miniworld.com/adnd/generators/characterBlock.html

Another idea would be to add classes to "localized" elements. So again your STAT table in the monster block you could create a new class called ".stats" (or ".characterStats") which is applied to the table and then have styling specific to that.

It just seems you are styling too much at a "global" level rather than localizing it to elements(or adding extra DIV tags to make it more local).

Another recommendation is try to avoid using HTML Markup tags(STRONG/EM) and use style classes instead in a SPAN or DIV tag. In my example (linked above) you can see "Armor Class" and those attributes are in DIV rather than UL/LI (though I am using INPUT fields for the values as I'm working on a NPC creation form. (just replace input with wrapping DIV around value). 

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

.statBlock {
  position: relative;
  padding-top: 15px;
  background-color: #FDF1DC;
  border-style: solid;
  border-width: 10px;
  border-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA8CAMAAADG+c2+AAAACVBMVEX///8AAADmmihtJc8lAAAAAXRSTlMAQObYZgAAACxJREFUeAHt2EEBACAAwkCwf2hL8NK7AAuwdCw9U5Og4FgeAAAAAK7IBxPjAl3qBs+hfAnLAAAAAElFTkSuQmCC) 10;
  width: 300px;
}

.statBlock  h2 + p {
  padding-bottom: 0px;
}
.statBlock  h3 {
  font-family: ScalySans;
  font-weight: 400;
  border-bottom: 1px solid #58180D;
}
.statBlock  hr + ul {
  color: #58180D;
}
.statBlock  ul {
  font-family: ScalySans;
  padding-left: 1em;
  font-size: 0.352cm;
}
.statBlock  ul em {
  font-family: ScalySans;
  font-style: italic;
}
.statBlock  ul strong {
  font-family: ScalySans;
  font-weight: 800;
  letter-spacing: -0.02em;
}
.statBlock  hr + table {
  margin: 0;
  column-span: 1;
  background-color: transparent;
  border-style: none;
  border-image: none;
  -webkit-column-span: 1;
}
.statBlock  hr + table tbody tr:nth-child(odd),
.statBlock  hr + table tbody tr:nth-child(even) {
  background-color: transparent;
}
.statBlock  table {
  color: #58180D;
}
.statBlock  p + p {
  margin-top: 0em;
  padding-bottom: 0.5em;
  text-indent: 0em;
}
.statBlock  hr {
  visibility: visible;
  height: 6px;
  margin: 4px 0px;
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAeCAYAAACR82geAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAAt5JREFUaEPtWTtoVEEUHf8iaEjMZt/ME6Jx3X1zlwgavyAICoL4aRWFIFYWAUURLZQo+GkUTGHc92Y2q2AKI0oKLbQIKRS0UPxCilgEFIKCTYIfyBrPi4NImGKJyWZ3Xw4cpth9b84c7ty59w3TaXdAS3FXEz8VkLtNp5YuZjNgoTGj/1KRGNEkXoEqkM4RmLamlbG55u/RwXhj7BRDMKw3kPyKkmKflk69ebxyYTeiAJL4CLO6AynOaI/v8Buqq8wrKwPWRU+Ef7bgOy3dm4p4i0456/wmNs9MU36wLnKySO4wzHqCyLoGsw4EyfiKUcZmmalLG9YFTSVJDMKkB0ryc1np7OxsrKo2UkoLVvHFJLl5GNWHpH5bS35UUXxDWyKxwMibPljFTjdJfMP2ewbDrgee06xWxhIoGWYbycWBVViJMQvCqM/go4D4Be25u/wkr4X8qctXNiFlwjwiqx9RdQfj8ZznbvI5X2SW9f+wTFi+JPEdfIHaysd4SKdEqnXrBKt26wQVQrMFv+IE7MlKcakjLfbkKOYUVDLYXljhzOMEHEBU3UMfeDJLfIu1cbY8GDmqtPiJyHoDaph1OJOqa5wxBgyNCUi8DY3pgDEqWbc6csaotPsLUTEAE+7rdES30t/kS7wHJlzGSbU349Xy6CVfEj9gwksk1yDKxzV6LPEBlXAXxhPaE5v9pogVeOGWQAR8AR/DhIuBJ3ZnE04M8iPWEqCJRIJ8jmhohynNimKJLsbmGMnFgVVYMTn22cHtgxGdgcePZWR8Y66+fqGRN32wip1KkhgEHwaSnw8/VClaVmOklBas4ieL5A7jlHiK4qlNEz/YvqquIXqfNkmMoIJ8j+R4C2a0+ElnfSux+Waa8oN1kQUwS+ITzOhWnjir05G9PhFDMKEX7ftV1Av7b6Tiy83jlYvxJmArhPdDrzHq8Io24/G1Ub2iHbvURzN1GuP2tkTNEvNThMHYbySiA8IawOrpAAAAAElFTkSuQmCC);
  background-size: 100% 100%;
  border: none;
}

</pre></code></details>

**Comment by stolksdorf** [comment]
Thanks for the suggestion. This is approach that I am taking for the next version of the site I am currently working on. 

I am actually disabling HTML parsing for v3 and modified the Markdown parser to include a new syntax for creating classed `divs`.
