### ISSUE TITLE
Column spacing in tables?

### ISSUE THREAD

**Issue by Dustfinger1** [stolksdorf/homebrewery#352]
### Additional Details
I find myself unable to dictate the spacing of my columns in tables. As I'm going to eventually turn my docs into PDFs and JPGs, this is a formatting nightmare. My specific issue is that a dash, as in "14-15" will put a line break after the dash if the adjacent cell has to use a line break. Maybe that sounds weird. I don't know how to explain it properly I suppose, so here's an example link.

**Share Link** :  http://homebrewery.naturalcrit.com/edit/BJl9at-Bqe

**Comment by calculuschild** [comment]
You could try adding some &nbsp; spaces to the header to make the column
wider.

**Comment by stolksdorf** [comment]
@calculuschild suggestion is correct. This is by design to keep the Markdown syntax simpler. You could also modify the spacing with some advanced css selectors.

**Comment by Dustfinger1** [comment]
Neat, thanks all!
