### ISSUE TITLE
Page Rendering Issue

### ISSUE THREAD

**Issue by IrdunWindseeker** [stolksdorf/homebrewery#353]
Hello. I have created a Player's Handbook for a Star Wars Homebrew rpg that is different from swd20. However, some of the pages will not render in edit and share mode. When I convert them to a pdf to print they seem fine, but otherwise they do not render when you scroll down. In particular, it seems to have  extreme difficulty with the spell descriptions (or force power descriptions, in this case) and the feat list. 

I will post the share link below, if it helps.

### Additional Details

**Share Link** :  http://homebrewery.naturalcrit.com/share/BJavghB_x

**Comment by stolksdorf** [comment]
Seems like an issue with the partial page rendering again. If you notice as you scroll farther and farther, the page numbering slowly gets out of sync.

**Comment by IrdunWindseeker** [comment]
Okay. What can I do to fix this problem?

**Comment by stolksdorf** [comment]
That's on me. Pushed out a quick-fix on `v2.7.3` that will increase the rendering range for Partial Page Rendering. It's a hacky fix, but you should now see your pages.
