### ISSUE TITLE
Everything goes nuts when I convert to a PDF

### ISSUE THREAD

**Issue by jddavis1** [stolksdorf/homebrewery#359]
Its possible that this is related to my code, but everything looks beautiful when im working on my brew, and then its positioned wrong when I click "get PDF"

I would be glad to supply the code it requested

### Additional Details

**Share Link** :
http://homebrewery.naturalcrit.com/edit/SklhIQA4cl

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Yeah, your HTML is a mess. Tons of opened tags without closing tags, `br`s all over the place, nested `font` tags. If you aren't comfortable with HTML, I suggest not using it.

**Comment by jddavis1** [comment]
Hi scott,

Thank you for taking a look. Admittedly this is my first time using HTML. I
will do some more research.

James
