### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Rhopper85** [stolksdorf/homebrewery#360]
Any way of combining this with the power of 5etools with the ability to look up all the existing creatures, races, spells etc which they have so we don't have to manually type out any stat blocks for creatures that already exist?

**Comment by vlos** [comment]
He's going to add Monster (SRD) lookup, READY TO ADD.
Not sure about the others as I only provided him with the monster list.

**Comment by stolksdorf** [comment]
There's a lot of interesting stuff going on right now with [Arcana.io](https://arcana.io/) and [D&D Beyond](http://dnd.wizards.com/articles/dndbeyond). I'm going to wait a bit before adding in features that rely on external sites, just to see where everything lands.

In the meantime I'm working on tightening up the reliability of rendering and the overall experience.
