### ISSUE TITLE
Formatting option?

### ISSUE THREAD

**Issue by fantom87** [stolksdorf/homebrewery#361]
Would it be possible to add some additional formatting options like font, font size, and column width and such?

**Comment by DoctorDan1986** [comment]
You already can do things like this.  By exploring just what CSS can do, I learned that practically everything is possible.  I've added things like small caps by doing:

` smallcaps { font-variant: small-caps; }`

and other fonts and font sizes by things like:

't.arial {font-family: "Arial"; }'

and 

' t.tiny { font-size: 70%; }'

or

' t.bold { font-weight: bold; }'

There's a lot you can do - keep experimenting!
