### ISSUE TITLE
Saving PDF with more than 2 pages

### ISSUE THREAD

**Issue by jarossjr** [stolksdorf/homebrewery#363]
I have a brew that ended up being 3 pages long, but whenever I try and save it, it only gives me the first two pages, plus whenever I try and access it, it wont show me the brew on the right; just the editor on the left. And whenever I click the share, it gives me a blank screen.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HJm0Ubuqjx
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# Raptornoids
No one is sure where these came from, but only a fool would look at a Raptornoid and see nothing more than a big, scaly, feathered humanoid. Their physical shape not withstanding, Raptornoids do not have much in common with Humans, Elves or Dwarves, rather having more in common with birds or prey. Raptornoids possess an alien and inscrutable mindset, their desires and thoughts driven by a different set of basic principles than those of warm blooded creatures. Their homes may lie hundreds upon hundreds of miles from the nearest human settlement, but their way of thiking bridges an even larger gap. 

Despite their alien look, some Raptornoids make an effort to understand and, in their own manner, even befriend people of other races. Such Raptornoids make faithful and skilled allies.
### Alien Minds
The Raptornoids birdlike, yet somehow reptilian nature comes through not only in their appearance, but also in how they think and act. Raptornoids experience a more limited emotional life than other humanoids.

Raptornoids experience most feelings as detached descriptions of creatures and situations. For example, humans confronted by an angry troll experience fear on a basic level. Their limbs shake, their thinking becomes panicked and jumbled, and they react by instinct. The emotion of fear takes hold and controls their actions. In contrast, Raptornoids see emotions as traits assigned to other creatures, objects and situations. A Raptornoid doesnt think, "I'm scared." Instead, aggressive, stronger creatures register to them as fearsome beings to be avoided if possible. If such creatures attack, Raptornoids flee, fighting only if cornered. Raptornoids aren't scared of a troll; instead, they understand and react accordingly.

Raptornoids never become angry in the way others do, but they act with aggression toward creatures thet they could defeat in a fight and can't be dealt with in some other manner. They are aggressive toward prey they want to eat, creatures that want to harm them, and so on.

Pleasurable people and things make life easier for Raptornoids. Pleasurable things should be preserved and protected, sometimes at the cost of their own safety. The most pleasurable creatures and things are ones that allow Raptornoids to assess more situations as benign rather than fearsome.

### Cold and Calculating
Most humanoids describe cold-blooded peopl as lacking emotion and empathy. The same label serves as an apt depiction of Raptornoids.

Lacking any internal emotional reactions, they behave in a distant manner. They don't mourn fallen comrades or rage against their enemies. They simply observe and react as a situation warrents.

Raptornoids lack meaningful emotional ties to the past. They assess situations based on their current and future utility and importance. Nowhere does this come through as strognly as when Raptornoids deal with the dead. To a Raptornoid, a comrade who dies becomes a potential source of food. That companion might have once been a warrior or hunter, but now the body is just frshly killed meat.

A Raptornoid who lives among other humanoids can, and over time, learn to respect other creatures' emotions. The Raptornoid doesn't share those feelings, but instead assesses them in the same clinical manner. Yes, the fallen dwarf might be most useful as a meal, but hacking the body into steaks provokes aggression in the other humanoids and makes them less helpful in battle.

### Utility and Survival
The Raptornoids mindset might seem unnecessarily crueld, but it helps them survuve in a hostile environment. The shrub steppes they inhabit are filled with a staggering variety of threats. Raptornoids focus on survival above all, without sentiment.

Raptornoids assess everyone and everything in terms of utility. Art and beauty have little meaning to them. A sharp sword serves a useful and good purpose, while a dull sword is a dead weight without a whetstone.

Raptornoids see little need to plan for a season or so into the future. This approach allows them to maintain their current level of influence in the world, but it limits their growth. Raptornoids have no interest in developing writing, making long term plans, or cultivating other methods to progress beyond their simple existence as hunters and gatherers.

### Hapless Soft Ones
At their core, Raptornoids view other humanoids with an indifference verging on pity. Born into the world lacking without stout scales, warming feathers and sharp teeth, it's a wonder they have managed to survive for so long.

Still, if other creatures prove useful to Raptornoids, those creatures can trigger a protective response made all the stronger by their apparent weakness. The Raptornoids assess such beings as hatchlings, young ones incapable of protecting themselves but who might prove useful in the future if they receive care.

```
```

<img src='https://68.media.tumblr.com/b2f0c5a31b6b16d31e5b559a578cd2dc/tumblr_mx7qnq1zqo1qj0hg3o1_r1_500.jpg' style='position:absolute;bottom:50px;right:30px;width:280px' />

<div class='pageNumber'>1</div>
<div class='footnote'>Raptornoids</div>

\page

### Raptornoid personality
You can use the Raptornoid Quirks table to determine a personality quirk for a Raptornoid or to inspire a unique mannerism.

##### Raptornoid Quirks
| d8 | Quirk |
|:----:|:-------------|
| 1 | You hate waste and see no reason not to scavenge fallen enemies as food. |
| 2 | You think their are only two species of humanoids, Ratornoid and meat. |
| 3 | You have learned to laugh and use this talen in all emotional situations. |
| 4 | You enjoy eating your food while its still alive. |
| 5 | You appreciate the soft humanoids who realize they need armor an weapons to match the gifts you were born with. |
| 6 | You still don't know how metaphors work. That doesn't stop you from using them at every opportunity. |
| 7 | Money is meaningless to you. |
| 8 | You have a bad habit of pointing out just how powerful an opponant might be, and of the impending doom you all face. |

___
### Raptornoid Names
Raptornoids take their names from a form of the Draconic language known as Scruf. They use simple descriptives granted by the tribe based on an individual's notable deeds or actions. For example, Ner translates as "spear", a name given to a Raptornoid who deafeated a warrior and claimed their foe's weapon. A Raptornoid who like to hide in a stand of reeds before ambushin an animal might be called Achuak, which means "green" to describe how she blends into the foliage.

Raptornoid names make no distinction between male and female in their naming conventions. Each example name given includes its translation in parenthesis.

**Raptornoid Names:** Achuak (green), Aryte (war), Baeshra (animal), Caesin (forest), Garurt (axe), Graproc (bitter), Irhtos (secret), Jhank (hammer), Kepesk (storm), Korth (danger), Kosj (small), Mirik (song), Ner (spear), Niarhaanin (river), Othokent (smart), Sauriv (eye), Sjach (shadow), Thurkear (night), Usk (iron), Valignat (burn), Vargach (battle), Verthica (mountain), Wutha (black), Vyth (steel) 

### Raptornoid Appearance
Raptornoids come in all different appearances, roll twice on the features table (ignoring doubles) and roll three times on the feathered table (ignoring doubles) to determine how your Raptornoid appears.

| d6 | Feature |
|:----:|:-------------|
| 1 | You have a beaklike mouth |
| 2 | You have two rows of teeth (bite becomes 1d8+str mod) |
| 3 | You have a retractable toe claw(1d6+ STR Mod slashing damage) |
| 4 | You have five fingers and a thumb |
| 5 | You have two fingers and a thumb |
| 6 | You have three fingers and a thumb |

<div style='column-count:2'>
| d6+d8 | Feathering |
|:---:|:------------|
|  1  | Your body is covered in protofeathers        |
|  2  | Your body is covered in down feathers       |
|  3  | Your body is covered in true feathers        |
|  4  | You have true feathers on your arms, legs and tail      |
|  5  | You have protofeathers on your arms, legs and tail  |
| 6 | You have down feathers on your arms, legs and tail |
| 7 | You have true feathers on your arms, appearing like small wings |

```
```

| d6+d8 | Feathering |
|:---:|:------------|
|  8  | You have protofeathers on your arms, appearing like small wings    |
| 9  | You have protofeathers across your face      |
|  10  | You have true feathers across you face     |
| 11  | You have down feathers across your face     |
|  12 | You have a crest of true feathers     |
| 13 | You have a crest of protofeathers |
| 14 | You have a crest of down feathers |
</div>

### Raptornoid Traits
Your Raptornoid has the following racial traits.

**Ability Score Increase** Your Constitution score increases by 2, and your Wisdom Score increases by 1.

**Age** Raptornoids reach maturity around age 12 and rarely lived longer than 70 years.

**Alignment** Most Raptornoids are nuetral. They see the world as a place of preadators and prey, where life and death are natural processes. They wish only to survive, and prefer to leave other creatures to their own devices.

**Size** Raptornoids are bulkier and taller than humans, ranging from 6'2"-7"5", weiging around 300-400lbs

**Speed** Your base walking speed is 35.

**Bite** Your fanged maw is a natural weapon, which you can use to make unarmed strikes. If you hit with it, you deal 1d6+ your STR mod, piercing damage.

**Sprint** You can move an extra 10 feet on a turn, only being able to do so again after you take a turn where you move 0 feet.

**Hunter's Lore** You gain proficiency with two of the following skills of your choice: Animal Handling, Nature, Perception, Stealth and Survival.

<div class='pageNumber'2</div>
<div class='footnote'>Raptornoids</div>

\page

**Natural Armor** You have tough skin. When you are not wearing armor, your AC is 13+your Dexterity Modifier. A shields benefits apply as normal while you use your natural armor.

**Hungry Jaws** In battle, you can throw yourself into a feeding frenzy. As a bonus action, you can make a special attack with your bite. If the attack hits, it deals its normal damage, and you gain temporary hitpoints (minimum of 1) equal to your constitution modifiers, and you can't use this trait  again until you finish a short or long rest.

**Languages** You can speak, read and write Common and Scurf.

**Fearless** Due to their emotional mindset, Raptornoids are immune to the fear condition.

>### Raptornoid Speech
Raptornoids can master Common, but their mindset results in a speech pattern distinct from other Humanoids. Raptornoids rarely use metaphors. Their speech is allmost always literal. They might pick up idioms, but only with some difficulty. Names confuse them, unless they are descriptive. They tend to apply their own naming conventions to other creatures using Common words. Raptornoids use active verbs to describe the world. A Raptornoid might say, "This wind brings cold." rather than "I feel cold." Raptornoids tend to define things in terms of actions, rather than effects.

<div class='pageNumber'>3</div>
<div class='footnote'>Raptornoids</div>

</pre></code></details>

**Comment by stolksdorf** [comment]
Looks like you deleted your brew?

**Comment by michaellasalle** [comment]
I think I may be having a similar issue. Mine is 2 pages, but if I save, the second page disappears. I am able to paste the source code into a new one and print a copy of both pages, but as soon as I save, the second page disappears again. 

http://homebrewery.naturalcrit.com/share/HJ-zNszGeW

**Comment by stolksdorf** [comment]
@michaellasalle you have bad HTML. Lines 121 - 124. You open a tag, then end the page. This will cause rendering issues.

**Comment by michaellasalle** [comment]
That fixed it. Thanks! :smiley:
