### ISSUE TITLE
Formatting issue on different computers

### ISSUE THREAD

**Issue by theclasywaggon** [stolksdorf/homebrewery#366]
### Additional Details
My friend had an issue with vertical spacing. The right column was unaffected with the inserted code, and any attempts to fix it caused the text to bunch together. I copied the code to my comp, and it worked fine. This is what he sees:

![image](https://cloud.githubusercontent.com/assets/26558687/24127654/6f7cc018-0da4-11e7-9836-654af71ce357.png)

The code is exactly the same for both separate projects.
Here is my personal file:

![captdvdsxure](https://cloud.githubusercontent.com/assets/26558687/24127776/3e0394fc-0da5-11e7-9389-28fe3d89c32d.PNG)

**Share Link** :
http://homebrewery.naturalcrit.com/share/rkW6skAje

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img src='http://i.imgur.com/TG53Bfr.png' 
  style='position:absolute; top:0px; right:0px; width:850px' />
  <div style='margin-top:489px'></div>
  
<img 
 src='http://i.imgur.com/tSQviwP.png' 
  style='position:absolute; top:20px; right:380px; width:430px' />

## Aarakocra
Sequestered in distant islands atop tall trees, the aarakocra, sometimes called birdfolk, evoke fear and wonder. Many aarakocra aren’t even native to the Material Plane. They hail from a world beyond—from the boundless vistas of the Elemental Plane of Air. They are immigrants, refugees, scouts, and explorers, their outposts functioning as footholds in a world both strange and alien.

### Beak and Feather
From below, aarakocra look much like large birds. Only when they descend to roost on a branch or walk across the ground does their humanoid appearance reveal itself. Standing upright, aarakocra might reach 5 feet tall, and they have long, narrow legs that taper to sharp talons. 
	
    
Feathers cover their bodies. Their plumage typically denotes membership in a tribe. Males are brightly colored, with feathers of red, orange, or yellow. Females have more subdued colors, usually brown or gray. Their heads complete the avian appearance, being something like a parrot or eagle with distinct tribal variations.

### Avian Mannerisms
TheThe resemblance of aarakocra to birds isn’t limited to physical features. Aarakocra display many of the same mannerisms as ordinary birds.
```
```
<div style='margin-top:315px'></div>

They are fastidious about their plumage, frequently tending their feathers, cleaning and scratching away any tiny passengers they might have picked up. When they deign to descend from the sky, they often do so near pools where they can catch fish and bathe themselves. 

Many aarakocra punctuate their speech with chirps, sounds they use to convey emphasis and to shade meaning, much as a human might through facial expressions and gestures. An aarakocra might become frustrated with people who fail to pick up on the nuances; an aarakocra’s threat might be taken as a jest and vice versa. 

The idea of ownership baffles most aarakocra. After all, who owns the sky? Even when explained to them, they initially find the notion of ownership mystifying. As a result, aarakocra who have little interaction with other people might be a nuisance as they drop from the sky to snatch livestock or plunder harvests for fruits and grains. Shiny, glittering objects catch their eyes. They find it hard not to pluck the treasure and bring it back to their settlement to beautify it. An aarakocra who spends years among other races can learn to inhibit these impulses. 

Nowhere are the aarakocra more comfortable than in the sky. They can spend hours in the air, and some go as long as days, locking their wings in place and letting the thermals hold them aloft. In battle, they prove dynamic and acrobatic fliers, moving with remarkable speed and grace, diving to lash opponents with weapons or talons before turning and flying away. 

Once airborne, an aarakocra leaves the sky with reluctance. On their native plane, they can fly for days or months, landing only to lay their eggs and feed their young before launching themselves back into the air. Those that make it to a world in the Material Plane find it a strange place. They sometimes forget or ignore vertical distances, and they have nothing but pity for those earthbound people forced to live and toil on the ground.

Confinement terrifies the aarakocra. To be grounded, trapped underground, or imprisoned by the cold, unyielding earth is a torment few aarakocra can withstand. Even when perched on a high branch or at rest in their treetop homes, they appear alert, with eyes moving and bodies ready to take flight.

\page

### Homelands
Most aarakocra live on the Elemental Plane of Air. Aarakocra can be drawn into the Material Plane, sometimes to pursue enemies or thwart their foes’ designs there. Accident might also send a nest of aarakocra tumbling into a world on that plane. A few find their way to such a world through portals on their own plane and establish nests in high tree or in the canopies of old forests. 

Once tribes of aarakocra settle in an area, they share a hunting territory that extends across an area up to 100 miles on a side, with each tribe hunting in the lands nearest to their colony, ranging farther should game become scarce. 

A typical colony consists of one large, open-roofed nest made of woven vines. The eldest acts as leader with the support of a shaman.

### Sky Wardens
Aarakocra enjoy peace and solitude. Most of them have little interest in dealing with other peoples and less interest in spending time on the ground. For this reason, it takes an exceptional circumstance for an aarakocra to leave his or her tribe and undertake the adventurer’s life. Neither treasure nor glory is enough to lure them from their tribes; a dire threat to their people, a mission of vengeance, or a catastrophe typically lies at the heart of the aarakocra adventurer’s chosen path. 

The Aarakocra Adventurers table can serve as inspiration for determining why a aarakocra character leaves the nest.

##### Aarakocra Adventurers
| d?| Reason for Adventuring |
|:--|:-----------------------|
| 1 | I have sworn my service to the Wind Dukes of Aaqa |
| 2 | Chocolate Chip |
| 3 | 2 or lower |
| 4 | 3 or lower |
| 5 | 4 or lower |
| 6 | 4 or lower |

### Aarackocra Traits

</pre></code></details>

**Comment by calculuschild** [comment]
Might be related to #295
