### ISSUE TITLE
"Recent Brews" Tab not updating properly on PC

### ISSUE THREAD

**Issue by sIllverback** [stolksdorf/homebrewery#368]
Whenever I view any homewbrewery link, nothing appears in my recent brews tab - my own brew or others. I deleted my browsing history and my cookies to see if some faulty data was saved, but all it did was erase everything from the tab itself. Now whenever I view brews, my recent view tab never updates.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by sIllverback** [comment]
EDIT: I'm on phone right now, and everything updates properly on my phone. It's just my PC.

**Comment by sIllverback** [comment]
Edit 2: I just double checked, nothing updating on phone now either.

**Comment by calculuschild** [comment]
This happens for me too. I can still log in and look at my own brews from the profile but all Recent Brews are always empty.

**Comment by calculuschild** [comment]
Duplicate of #577
