### ISSUE TITLE
column break and vertical spacing aren't working correctly

### ISSUE THREAD

**Issue by 3v3rl0st** [stolksdorf/homebrewery#372]
after putting in a column break and then vertical spacing, the text to be adjusted remains at the top of the next column.  took all the pages i built and has the spacing all wrong.

### Additional Details

**Share Link** :  http://homebrewery.naturalcrit.com/edit/HyfEgJ_lTl

or

test page left column

```
```

<div style='margin-top:240px'></div>

test page right column with vertical spacing

**Comment by bakgaard** [comment]
@3v3rl0st - What is it you want it to do?

You can insert a spacer with something like this line:
```<img src='' style='position:relative; height:430px;'/>```

**Comment by 3v3rl0st** [comment]
originally i had a picture as the top banner crossing both columns.  then
for proper spacing i'd add a column break, then need to lower the 2nd
column.  When i did that the menu option for vertical spacing was not
working properly it would just stay where it was  at the top of the column.

i ended up adding <br>  above the vertical spacing command in order to
force the vertical spacing to work properly....so i think i'm ok now?

**Comment by bakgaard** [comment]
I think you left out the img in the link. 

If you found a workaround, perhaps we can close the ticket?

**Comment by 3v3rl0st** [comment]
yeah, can close this one out. i put a comment on the open ticket. thank you
very much for your quick response on this!

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
