### ISSUE TITLE
Single-pound-sign text gets stuck halfway down page

### ISSUE THREAD

**Issue by BaronMurph** [stolksdorf/homebrewery#373]
(Solved:) When trying to dump a wide block on the bottom of a page - or anywhere further than around 950 px down, really - it refuses to move further down. Doesn't matter if you put stuff in front or behind or try to make it move like 3000 px off the page, it just stops at around 950 px from the top of the page.
(Not solved:) Also happens with
`# this stuff`
and wide monster stat blocks.
The issue:
http://homebrewery.naturalcrit.com/edit/SJgLbb4-px

**Comment by calculuschild** [comment]
Your spacing div is still in the two-column area. Once it reaches about halfway down the page, the 3000px "margin" you are using kind of becomes invalid for whatever reason, but I think that's normal CSS behavior, not anything wrong with the Homebrewery.

Here's the solution: if you move your spacing div inside the "wide" block, it will function as expected, since your spacer is no longer split between two columns.

**Comment by BaronMurph** [comment]
Thanks! Works like a charm with the wide block.
`# This stuff` still fucks up, though.

**Comment by JamesIntrocaso** [comment]
Hey I am having the same problem. How do I move my spacing div inside the "wide" block? Sorry for being new at this.

**Comment by BaronMurph** [comment]
You quite literally just move it inside, haha
<div class='wide'> (your wide block)
<div style='margin-top:140px'></div> (your spacing)
Everything in here will be extra wide. Tables, text, everything! Beware though, CSS columns can behave a bit weird sometimes. (your text)
</div> (the closing tag of your wide block)

**Comment by calculuschild** [comment]
@BaronMurph I assume this is still an issue? We should try taking another whack at this now that we have been granted the ability to fix the site.

**Comment by BaronMurph** [comment]
Ah, I actually completely forgot about this issue, but—and I literally just started screwing around with this 5 minutes ago, re-acquainting myself with the issue—there's a very easy solution by just going:
`<div class='wide'>
<div style='margin-top:140px'></div>
# Single-Pound-Sign-Text-Stuff
</div>`
Literally just what you said in your first reply, except in regards to single-pound-sign-text-stuff rather than vanilla text. To be perfectly honest, I don't know what I was doing when you originally answered that question that I didn't even try that lmao. Thank you for your diligence, though.
