### ISSUE TITLE
How to close an open issue?

### ISSUE THREAD

**Issue by BaronMurph** [stolksdorf/homebrewery#376]
Question's been answered, but I don't have a clue how to close the ticket. Help?

Original question:
How do you place images over text?
Along the lines of: https://s-media-cache-ak0.pinimg.com/736x/62/c0/90/62c0909d42f23341655d5dd3a2f34eac.jpg

**Comment by calculuschild** [comment]
Are you talking about the monster art? This is very easy. You can add CSS styling to your image to place it in front:

`<img src='http://i.imgur.com/q5Hxu7r.png'  style='z-index: 20;'/>`

You just need to change the z-index of your image to be greater than the z-index of the stat blocks (which appears to be about 14 just by trial-and-error). Larger z-indices will place the item closer to the top.

**Comment by BaronMurph** [comment]
lol dammit man, now you're just making me feel stupid.
Works perfectly, thanks!
Ticket can be closed now.
