### ISSUE TITLE
Can't remove footer image

### ISSUE THREAD

**Issue by Rhopper85** [stolksdorf/homebrewery#379]
I don't have the `<div class='pageNumber auto'></div>` added to this page, but it still has the footer image there, and I am trying to insert a full-page image here, but that footer appears on top. How do I remove it?

**Comment by BaronMurph** [comment]
I'm assuming you mean the beige lines?
You can get rid of 'em by inserting the following somewhere on the page;
`<style>
  .phb#p[NUMBER]:after{ display:none; }
</style>`
with [NUMBER] being the page number.

**Comment by Rhopper85** [comment]
hmm doesn't seem to be working.

**Comment by BaronMurph** [comment]
So you can see it happening: http://homebrewery.naturalcrit.com/edit/H1gfFuMRpx
Also, make sure you count your pages right. Other than that, I'm not sure what else I can do to help you.

**Comment by Rhopper85** [comment]
ah that worked, I was typing my page number in wrong. thanks!
