### ISSUE TITLE
Saved Brew leads to Blue Background

### ISSUE THREAD

**Issue by MajorWolf2** [stolksdorf/homebrewery#384]
I'm trying to help my GM with organizing their Homebrew content for a Naruto DnD game, but the act of saving the brew cause it to not load the brew. I've tried accessing it from my profile, both the share button and the edit button, and all I receive is a blue background with the page count in the upper left hand corner.

### Additional Details

**Share Link** :
http://homebrewery.naturalcrit.com/share/HJDMsfX0l

**Comment by BlackbeardIII** [comment]
I had a similar issue, #385 is mine.

**Comment by calculuschild** [comment]
Take a look at #385. You might be having a similar issue. The Homebrewery doesn't like `<div>` tags sitting right after other text with formatting. Try putting spaces between your divs and other sections of text.
