### ISSUE TITLE
Shared copy is all blue, not showing my brew.

### ISSUE THREAD

**Issue by BlackbeardIII** [stolksdorf/homebrewery#385]
My friend reformatted my class, and when he tried to share it, the shared pages were all blue. When copied and pasted his reformatted version onto the homebrew, and shared it, the same thing happened. It all goes blue when I share it.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/By4zXAF2x

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
There is an issue with having divs starting the line right after another tag, in your case the bullet points make a `<li>` tag. The Homebrewery or Markdown or something is deciding to start your `<div>` tag before closing the current `<ul>` sequence.

The solution for you right now is simply to move the `<div>` down one line. Leave a blank line between the bullet points and the div and it should work fine.

I don't know if this will be solved with v3, but this might be something @stolksdorf should be wary of.

```
<ul>
<li>Keen Smell.</li>
<li>Darkvision.</li>
<li>Base speed of 30 feet.</li>
<li>Proficiencies in: Medium Armor, Heavy Armor, Martial Weapons, Heavy Weapons.</li>
<li>Resistance to one melee damage type of your choice.
<div style='margin-top:140px'>f</li>
</ul>
 </div>
```

**Comment by BlackbeardIII** [comment]
Your suggestion worked. Thanks a lot for the help, I wouldn't have been able to figure that out myself. I'll also be wary of this in the future. Again, thanks!

**Comment by stolksdorf** [comment]
Thanks @calculuschild for the detailed response. This is an issue with mixing HTML and Markdown together. It's little weird things like this is why I want to move away from having raw HTML.
