### ISSUE TITLE
Page dont render ?

### ISSUE THREAD

**Issue by melon87** [stolksdorf/homebrewery#386]
As im making extended weapons lists i cant seem to get everything renderd, i can see 2 pages, but everything else is gone in viewport

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

##### Weapons

<div class='classTable wide'>
##### Simple Melee Weapons
| Name| Cost |  Damage | Weight |Properties| 
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Axe, throwing| 8 gp |1d6 |2 lb.| Slashing (range 10/30)
|Battle aspergillum	| 5 gp|	 1d4	| 4 lb.	 |Bludgeoning|
|Brass knuckles	| 1 gp|	1d4	| 1 lb.|see text|
|Cestus	 |5 gp|	 1d4 	|	 1 lb|see text|
| Club | 1sp |1D4 Bludgeoning  | 2lb |light |
| Dagger | 2gp |1D4 piercing  | 1lb |Finesse, light, thrown (range 20/60) |
|Gauntlet|	 2 gp|	 1d4	| 1 lb.|		 -|
| Greatclub | 2sp |1D8 Bludgeoning  | 10lb |Two-handed |
|Hammer| 1 gp | 1d4|   2 lb. |Bludgeoning (range 20/40)|
| Handaxe | 5gp |1D6 Slashing  | 2lb |Light, thrown (range 20/60)
| javelin | 5sp |1D6 Piercing  | 2lb |Thrown (range 30/120)
|Kukri| 8 gp| 1d4 |2 lb.| Slashing
| Light hammer |2 gp| 1d4 bludgeoning| 2 lb.| Light, thrown (range 20/60)
|Light mace|	 3 gp|	 1d4	 | 	 4 lbs.	|-|
|Mace |5 gp |1d6 bludgeoning| 4 lb.| -|
|Mere Club |1 sp |1d4 bludgeoning| 1 lb.| -|
|Pick| 4 gp| 1d4| 3 lb.| Piercing
|Punching dagger|	 2 gp|	 1d4 Piercing	|	 1 lb.	 |-|
|Quarterstaff |2 sp| 1d6 bludgeoning| 4 lb. |Versatile (1d8)|
|Sap |1 gp| 1d4   | 2 lb. |Bludgeoning
|Sickle| 1 gp| 1d4 slashing |2 lb.| Light
|Spear |1 gp| 1d6 piercing| 3 lb.| Thrown (range 20/60), versatile (1d8)
|Spiked gauntlet|	 5 gp|	 1d4	|	 1 lb.	 |-|
|Unarmed strike| -|1Bludgeoning|-|-
|Wooden stake|		-| 1d4	 	| 1 lb.	 |Thrown (range 10/40)|
|Whip| 2 gp| 1d4 slashing| 3 lb.|-|

</div>
<div class='classTable wide'>
##### Simple Ranged Weapons
| Name| Cost |  Damage | Weight |Properties| 
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:||
|Crossbow, light |25 gp| 1d8 piercing| 5 lb.| Ammunition (range 80/320), loading, two-handed
|Dart |5 cp |1d4 piercing| 1/4 lb.| Finesse, thrown (range 20/60)
|Shortbow |25 gp| 1d6 piercing| 2 lb.| Ammunition (range 80/320), two-handed
|Sling| 1 sp| 1d4 bludgeoning |-| Ammunition (range 30/120)|
|Underwater Crossbow, light |50 gp| 1d8 piercing| 5 lb.| Ammunition (range 80ft), loading, two-handed
</div>

\page

<div class='classTable wide'>
##### Martial Melee Weapons
| Name| Cost |  Damage | Weight |Properties| 
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Battleaxe| 10 gp| 1d8 slashing |4 lb. |Versatile (1d6)|
|Boarspear| 6 gp| 1d8 slashing |8 lb. |Thrown (range 20/60), versatile (1d10))|
|Falchion |75 gp| 2d4 | 8 lb.| Slashing,two handed 
|Flail |10 gp| 1d8 bludgeoning |2 lb.| -|
|Glaive| 20 gp| 1d10 slashing |6 lb. |Heavy, reach, two-handed|
|Greataxe| 30 gp| 1d12 slashing |7 lb.| Heavy, two-handed
|Greatclub| 5 gp| 1d10 | 8 lb. |Bludgeoning , two handed
|Greatsword |50 gp| 2d6 slashing |6 lb.| Heavy, two-handed|
|Guisarme|9 gp | 2d4 | 12 lb.| Slashing, two handed
|Halberd |20 gp| 1d10 slashing| 6 lb. |Heavy, reach, two-handed|
|Lance| 10 gp| 1d12 piercing |6 lb.| Reach, special|
|Longsword |15 gp| 1d8 slashing| 3 lb.| Versatile (1d10)|
|Heavy Mace |10 gp |1d12 bludgeoning| 8 lb.| Heavy,|
|Maul |10 gp| 2d6 bludgeoning| 10 lb.| Heavy, two-handed|
|Morningstar |15 gp| 1d8 piercing| 4 lb.| -|
|Pick| 8 gp| 1d6 | 6 lb.| Piercing, heavy
|Pike| 5 gp |1d10 piercing| 18 lb.| Heavy, reach, two-handed|
|Ranseur| 10 gp | 2d4 | 12 lb. |Piercing, two handed
|Rapier |25 gp| 1d8 piercing| 2 lb.| Finesse|
|Scimitar |25 gp| 1d6 slashing| 3 lb. |Finesse, light|
|Scythe| 18 gp| 1d6 |4 lb.|two handed
|Shortsword| 10 gp| 1d6 piercing |2 lb.| Finesse, light|
|longspear| 5 gp| 1d8 piercing |5 lb.| Thrown (range 20/60)Versatile (1d10)|
|Trident |5 gp |1d6 piercing |4 lb.| Thrown (range 20/60), versatile (1d8)|
|War pick |5 gp| 1d8 piercing |2 lb.|-|
|Warhammer| 15 gp| 1d8 bludgeoning| 2 lb.| Versatile (1d10)|

</div> <div class='classTable wide'>
##### Martial Ranged Weapons
| Name| Cost |  Damage | Weight |Properties| 
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Blowgun| 10 gp |1 piercing| 1 lb.| Ammunition (range 25/100), loading|
|Crossbow, hand| 75 gp| 1d6 piercing |3 lb.| Ammunition (range 30/120), light, loading|
|Crossbow, heavy |50 gp| 1d10 piercing| 18 lb.| Ammunition (range 100/400), heavy, loading, two-handed|
|Longbow| 50 gp| 1d8 piercing| 2 lb. |Ammunition (range 150/600), heavy, two-handed|
|Net| 1 gp| -| 3 lb. |Special, thrown (range 5/15)|
|Underwater Crossbow, heavy |10 gp| 1d10 piercing| 8 lb.| Ammunition (range 120ft), heavy, loading, two-handed|

</div>

\page

##### Armor

<div class='classTable wide'>
##### Light armor
|Armor | Cost |  Armor class | Strenght |Stealth| Weight|
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Padded| 5 gp| 11 + Dex modifier| — |Disadvantage| 8 lb.|
|Leather |10 gp| 11 + Dex modifier| —| —| 10 lb.|
|Studded leather| 45 gp| 12 + Dex modifier| —| — |13 lb.|
|Haramaki|	 3 gp|	 11 + Dex modifier|	 -	| -	|1 lb.|
|Padded	 |5 gp	| +1	|||	 10 lbs.
|Quilted cloth	| 100 gp|	 11 + Dex modifier	|||12 lbs.
|Silken ceremonial|	 30 gp|	 11 + Dex modifier	||| 3 lbs.
|Lamellar cuirass|	 15 gp|	 11 + Dex modifier	|||	 8 lbs.
|Parade	| 35 gp	| 12 + Dex modifier	 ||| 18 lbs.
|Wooden	| 20 gp|	 11 + Dex modifier	 |||25 lbs.
|Chain shirt|	 100 gp	| 13 + Dex modifier	||| 30 lbs.
|Lamellar (leather)	| 60 gp	| 13 + Dex modifier	 |||25 lbs.

</div><div class='classTable wide'>

##### Medium armor
|Armor | Cost |  Armor class | Strenght |Stealth| Weight|
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Hide |10 gp|12 + Dex modifier (max 2)| —| —| 12 lb.|
|Chain shirt| 50 gp |13 + Dex modifier (max 2)| —| —| 20 lb.|
|Scale mail |50 gp| 14 + Dex modifier (max 2)| — |Disadvantage |45 lb.|
|Breastplate| 400 gp| 14 + Dex modifier (max 2)| —| —| 20 lb.|
|Half plate| 750 gp |15 + Dex modifier (max 2)| — |Disadvantage|40 lb.|
|Armored coat |25 gp| 12 + Dex modifier (max 2)| -||15lbs|
|Do-maru |	100 gp |  13 + Dex modifier (max 2||| 20 lbs.
|Kikko |30 gp |13 + Dex modifier (max 2||| 20 lbs.
|Lamellar (horn)| 100 gp| 13 + Dex modifier (max 2) ||| 25 lbs.
|Agile breastplate |400 gp| 14 + Dex modifier (max 2)| ||18 lbs.
|Four-mirror| 45 gp| 14 + Dex modifier (max 2)| || 30 lbs.
|Lamellar (steel) |75 gp| 14 + Dex modifier (max 2) ||| 25 lbs.
|Mountain pattern |150 gp| 14 + Dex modifier (max 2)| ||30 lbs.

</div><div class='classTable wide'>
##### Heavy armor
|Armor | Cost |  Armor class | Strenght |Stealth| Weight|
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Ring mail| 30 gp| 14| —| Disadvantage| 40 lb.|
|Chain mail |75 gp| 16| Str 13| Disadvantage |55 lb.|
|Splint| 200 gp |17 |Str 15| Disadvantage| 60 lb.|
|Plate| 1,500 gp |18 |Str 15 |Disadvantage| 65 lb|

\page

</div><div class='classTable wide'>
##### Shields
|Armor | Cost |  Armor class | Strenght |Stealth| Weight|
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Shield| 10 gp| +2| -| -| 6 lb.|

</div>

</pre></code></details>

**Comment by calculuschild** [comment]
Is this still an issue for you? If you can provide the *share* link to your document that will make it a little easier to see what's going on. I'm not noticing anything wrong with the code you provided.

Closing for now because this was so long ago and we don't have enough information to solve the problem. Feel free to reopen this issue if this is still a problem for you and you can provide more information. @melon87
