### ISSUE TITLE
Issue with image being pushed to right side of page

### ISSUE THREAD

**Issue by Stormhammer-87** [stolksdorf/homebrewery#391]
Hello everyone.  I started making a new adventure a few days ago and have been playing around with this site ever since.  I'm having an issue right now however.  I have some text at the top of my first page, then I have an image underneath it (inserted using the command in the available menus).  I linked my own image and it shows up fine.  The problem I'm having is this: whenever I go to the line underneath the image, I use the "#" to get the big red text that is used for introductions and the like, but when I do so it pushed the entire picture off to the right column on the page.  Despite numerous attempts with different code I found, I can't seem to find a fix.  Can anyone help with this?

Here are a few pictures for reference on what's happening (with my code included):

Before: http://imgur.com/8VcZEjm
After: http://imgur.com/oLmyW2S

Any help at all is greatly appreciated!

**Comment by calculuschild** [comment]
The thing is, the `#` creates an html `<h1>` header, which is by default a full-page-width item. So when you stick another one halfway down the page, its assuming your columns are ended and pushes your image over to fill the empty space in the other column.

What you probably should be doing is using the `<h2>` headers for everything else, using two `##`. The font is slightly smaller, but fits itself into a single column.

If you REALLY need the large font size, what you can do, is add some CSS
<pre><style>
h1 {display: inline-block;}
</style></pre>
to the top of your brew, which will change `<h1>` headers to not act as a full-width item. This means they will not span across columns anymore, so your first header "Act 1: Creeping Death" will probably flow down to a second row.

In that case, you can manually replace the titles you want to fit into a single column with `<h1 class="myHeader">Introduction</h1>` and then change the CSS to say
<pre><style>
.myHeader {display: inline-block;}
</style></pre>
or something.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Stormhammer-87
