### ISSUE TITLE
Backslash not removing italics feature from asterisk in tables

### ISSUE THREAD

**Issue by dekelpilli** [stolksdorf/homebrewery#397]
Outside of a table, "this\* is a test\*" looks like "this* is a test*".
Inside a table, "this\* is a test\*" looks like "this _is a test_"

In the code below, level 8 is the problematic level
<details><summary>Click to expand</summary><code><pre>

<div class='classTable'>
##### The Ilhiid
| Level | Proficiency Bonus | Features | Max CR of non-humanoid host|
|:---:|:---:|:---|:---:|
| 1st | +2 | Body thief, Sense illithids\* | ─ |
| 2nd | +2 | Devour intellect\* | ─ |
| 3rd | +2 | Improved body thief | 2 |
| 4th | +2 | Ability score improvement | 2 |
| 5th | +3 | Magic resistance, Detect sentience, Mind blast, Extract brain\* | 2 |
| 6th | +3 | Improved devour intellect\* | 3 |
| 7th | +3 | Ability score improvement, telepathy range increase\* | 3 |
| 8th | +3 | Improved devour intellect\*, Mind blast\*| 3 |
</div>
</pre></code></details>

**Comment by calculuschild** [comment]
Looks fine to me. Copied and pasted your code directly and all asterisks show up.

![image](https://cloud.githubusercontent.com/assets/5878534/25904721/0e4451f2-356e-11e7-885a-f5e60886c78c.png)

**Comment by dekelpilli** [comment]
Very strange. 
![bug](https://cloud.githubusercontent.com/assets/11293359/25906803/fdc9eed8-35e8-11e7-8a01-7f3a142cad0a.png)

[Here is a link to the full code](https://archive.is/PXvrx)

**Comment by calculuschild** [comment]
Yep, that's weird. Somehow the other divs in the document are affecting that, as you can see if you remove everything except the next div with 90px margin. As soon as you delete that 90px div it works again.

I recommend then just putting in the ASCII code for your asterisk. `&#42;`

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @dekelpilli

**Comment by dekelintelematics** [comment]
It's all good, from memory I just ended up using `&#42;`. It's still a bug, but there's an easy workaround, so this would be a very low priority edge case.

**Comment by dekelpilli** [comment]
@calculuschild Using `&#42;` was a viable workaround. You can close the ticket as an easy solution was found, but the bug still exists (although it would be very low priority as it's an edge case with an easy solution).
