### ISSUE TITLE
Exo Traits - Strength misspelling

### ISSUE THREAD

**Issue by SaviorXTanren** [stolksdorf/homebrewery#404]
"Ability Score Increase. Increase your Constitution and **Strenght** Modifier by 1."

**Comment by SaviorXTanren** [comment]
Found another one:

"Quick Build
You can make a Guardian quickly by following these suggestions. First, Dexterity should be your highest ability score, followed by Charisma (Hunter), **Strenght** (Titan) or Intelligence (Warlock). Second, chose the Blank background."

**Comment by calculuschild** [comment]
Hey there. Looks like you were trying to give feedback to somebody's brew and accidentally submitted a bug report to the maker of the website instead. If you found that brew on Reddit or something I would recommend sending your feedback there instead.
