### ISSUE TITLE
Stuck on full screen, can't get page visual back

### ISSUE THREAD

**Issue by jamesholbert** [stolksdorf/homebrewery#408]
I can't find any option to restore the actual visual of the doc I'm working on.

**Comment by calculuschild** [comment]
Do you have a screenshot showing what you mean?

**Comment by jamesholbert** [comment]
I was able to scroll way over and find the window stretch bar. Wouldn’t have seen it had I not scrolled so far over for the screenshot. Thanks

--
James Holbert
Account Manager– Economic Development
Cell: 360-870-6931
Office: 208-883-3500
