### ISSUE TITLE
Request: Dynamic element support

### ISSUE THREAD

**Issue by Qazzquimby** [stolksdorf/homebrewery#409]
I've attempted to make buttons to hide and show content, but keep running into problems.
 * Getting divs by id doesn't seem to work.
 * Calling previously defined functions doesn't seem to work
 * When I set things up using inline onclick="*complex function call", the page rendered incorrectly and wouldn't let me edit the document anymore. https://i.gyazo.com/63930cc1dc614ec2ec8372b624cc64ad.png

I know that html is being phased out, so this may be moot, but is there any way to support these js altering page elements?
Applications include:
 * Filtering a book (only include content with a tier 3 power level, exclude sillier content)
 * Modifying content based on content already chosen (only show legal feat choices, legal character options)
 * Embedded tools (Random result from table, treasure calculator, cr calculator)

**Comment by stolksdorf** [comment]
Homebrewery will only support HTML and CSS. Any Javascript functionality will not be supported. If you wish to have javascript features I suggest you take the HTML and CSS output from the Homebrewery and create your own webpage using it.
