### ISSUE TITLE
How to make new columns when using the Spell List template

### ISSUE THREAD

**Issue by Faolyn** [stolksdorf/homebrewery#410]
When I type in the two lines of three tildes each, all I get is a line, not the new column that I get on regular pages. When I try using [/div][div class='spellList'] (but, you know, with carets), which I saw in the sample, it both doesn't work and turns the dashes at the start of each line into bullets. What should I use instead?

**Comment by calculuschild** [comment]
CSS doesn't handle columns very nicely. This is kind of a janky way to do it, but if you know which block of text you want to all fit in the same column, you can surround it with `<div style="display: inline-block;">` and `</div>`, and it should put everything inside that div on the same column. You should be able to control every item on each column using that, but it's not the prettiest code.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Faolyn
