### ISSUE TITLE
Blank space between pages after rendering to PDF

### ISSUE THREAD

**Issue by TormDeltest** [stolksdorf/homebrewery#416]
Hi, I just rendered a project I'm working on and there are some weird blank spaces between each page. I have no idea where they are coming from and how to get rid of them. Do you have any tips? 

Screenshot: http://i.imgur.com/VMrKSIn.png

Share link: http://homebrewery.naturalcrit.com/share/BkaJMpwJb

Thanks for help and ideas.

**Comment by calculuschild** [comment]
What page size are you printing on? You might need to change the page size
on the print view between A4 and 8.5x11. Or you can change the whole
project to the other size (there's a button in the editor somewhere), but
that's a pretty big document and it might mess up your image positions and
line breaks.

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
