### ISSUE TITLE
Would you like help knocking out these issues?

### ISSUE THREAD

**Issue by calculuschild** [stolksdorf/homebrewery#417]
I noticed you'll pop in every other week or so and respond to a couple people here, but I can imagine it's hard to find the time to deal with everyone's questions and pump out v3 at the same time. I've got a fair bit of experience with front-end web development, and I've gone through several items here and commented with solutions to the problems, but I wonder if you are accepting pull requests for some of the issues at this point?

**Comment by stolksdorf** [comment]
I would definitely accept some PRs. It just might take me a bit of time to get around too. I appreciate it man.
