### ISSUE TITLE
Issues with Starting up

### ISSUE THREAD

**Issue by kiddragon826** [stolksdorf/homebrewery#418]
Hey, I'm trying to work on a new class idea with a friend of mine. On his computer the full class table comes out the correct shape. For me every time I try to use it, the table appears in the shape of the half character table, but all of the info such as spells are coming out of the side. I have completely closed and retried several new pages to see if it is just a fluke. The picture is a screen shot of the issue happening with a fresh made table right after I hit the button.

![homebrew issue](https://cloud.githubusercontent.com/assets/29154877/26749329/e3c1cb86-47cd-11e7-8815-2753406f5e4b.jpg)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Use chrome.
