### ISSUE TITLE
Problems building from the Repository

### ISSUE THREAD

**Issue by ranaur** [stolksdorf/homebrewery#424]
Hi! I'm trying to install homebrewery locally (I found it great!), and I stepped in trouble. :-)

When I run npm install I get this error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebrewery@2.7.4 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebrewery@2.7.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I noticed that vitreum library removed the ".partial" support. So I removed it from the script/build.js.

Then it worked.

> const label = 'build';
> console.time(label);
> 
> const clean = require('vitreum/steps/clean.js');
> const jsx   = require('vitreum/steps/jsx.js');
> const lib   = require('vitreum/steps/libs.js');
> const less  = require('vitreum/steps/less.js');
> const asset = require('vitreum/steps/assets.js');
> 
> const Proj = require('./project.json');
> 

Then, when I compile I get a warning message:

(node:51440) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
(node:51440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:51440) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje

but it builds. 

However, when I try the site (on localhost) it come very grabbled. The message on chrome browser says:

> libs.js:2700 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) .com/login?redirect=http://localhost:800
>  (server) .com/login?redirect=" color="teal" icon=
> printWarning @ libs.js:2700
> 

I'm not sure if it was due my change, I appreciate any help.

I'm running it on a macosX, with node 8.1.2.

Thanks!

**Comment by HeruAsatru** [comment]
You may wanna check the comments in this issue: https://github.com/stolksdorf/homebrewery/issues/442
A solution was presented and worked for me.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@ranaur If you are still experiencing this issue, feel free to reopen and provide information.
