### ISSUE TITLE
Noticed an issue with bullet point formatting

### ISSUE THREAD

**Issue by SpiderMikeH** [stolksdorf/homebrewery#431]
![screen shot 2017-07-01 at 11 19 17 pm](https://user-images.githubusercontent.com/24197124/27767029-b9ab22b8-5eb4-11e7-9127-99ae6d86f226.png)
Hello. I noticed a small issue with how the website is generating bullets sometimes. I've attached a screenshot of the issue in particular. Here's my use case: 

1. Google chrome, browser view is at 100% zoom. 
2. Macbook pro, 2011 version. OS Sierra. 

I tried to reformat the bullets, but it hasn't seemed to correct it. I've noticed this occur in other descriptive text boxes within some of my other brews too. 

Personally, Its not a huge issue (i can just remove the bullets); but I thought you would like to know! 

Thanks again for all your effort and time put into this homebrew solution. It's phenominal, and I use it weekly in my homebrew campaign -- and personal reference binder for my games. 
 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by dosjos** [comment]
Remove the > without any content behind it, between the bulletpoints. It will become right.

**Comment by SpiderMikeH** [comment]
Okay! Thank you.

**Comment by treisdorf** [comment]
I am experiencing the exact same issue, except that it is not in a table and so the solution above is not possible. 

I am attaching a screenshot. **I have tried using both * and - for the bullet points, and both resulted in this issue.** 

![homebrewery - bullet point issue](https://user-images.githubusercontent.com/30560520/28749478-3d788858-748e-11e7-85dc-e31dc1446498.jpg)

**Comment by treisdorf** [comment]
I have managed to rig a temporary fix (see attached image), but this is not how it is supposed to work and I am extremely OCD about my code and so this is **not** a viable long-term solution. I want it to look **and function** exactly as it would before. Please advise. Thank you.

![homebrewery - bullet point issue - temp solve](https://user-images.githubusercontent.com/30560520/28749495-02277772-748f-11e7-8cc5-4a373273736e.jpg)

**Comment by danielricks** [comment]
![hbbulletspic](https://user-images.githubusercontent.com/2449536/30006989-146b6516-90c2-11e7-8560-c950c0ac7a35.png)

I got bullets to format correctly by removing the space between each bulleted item. Maybe try that. Cheers.

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
