### ISSUE TITLE
Class Table and Half Class Table Produce the Same Background Table Image

### ISSUE THREAD

**Issue by AceWindu** [stolksdorf/homebrewery#441]
The background graphic for < div class='classTable' > and < div class='classTable wide' > remains the same size no matter how much I manipulate it. the text looks fine but that graphic is really bugging me. Is there a quick fix? Or just a bug that will be resolved in due time?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
can you show a picture of what you're talking about?

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information. @AceWindu
