### ISSUE TITLE
Saving PDF

### ISSUE THREAD

**Issue by heardhiscall** [stolksdorf/homebrewery#443]
Hey I may just be stupid or something like that but is it possible to save a PDF straight to computer and not printing the file?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
You can "print" the pdf as a pdf file. In your printer choices you should
have at least one option that says "print as pdf" or something, and it will
just open up a normal document save window.

**Comment by heardhiscall** [comment]
Thanks, I knew i was being stupid.

**Comment by jimcullenaus** [comment]
Someone should mark this issue as closed.

**Comment by calculuschild** [comment]
Duplicate of #656
