### ISSUE TITLE
How do you make introductory quotes?

### ISSUE THREAD

**Issue by esda01** [stolksdorf/homebrewery#445]
In the official D&D Books, they use quotes in the beginning of each race to give a feel for what they are like. A special font and formatting is used to set it apart from the actual race description.

Does anyone know how to formal the text to look like this? if possible at all?

**Comment by granack** [comment]
Those just look like italicized regular font to me, but...

You can give paragraphs custom fonts and styles. I made a brew describing how to use Google Fonts. I think I describe it well, but you can view the source of the brew to see working examples.

http://homebrewery.naturalcrit.com/share/HJNNFqYI-

As far as which font to use, that's for you to decide. There are many hundreds to choose from at https://fonts.google.com and you can use them from elsewhere (but maybe not as easily).

It's not clear if these methods will work when v3 eventually comes out.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@esda01 If you are still experiencing this issue, feel free to reopen and provide information.
