### ISSUE TITLE
All Gone

### ISSUE THREAD

**Issue by emilyfroese** [stolksdorf/homebrewery#446]
I don't even know what happened. I was just typing away and it all disappeared. Share link leads to blank page, just like edit link. I have an account on the site that had it regularly saving, but its just all gone. I've dedicated _hours_ to this project, meant to be launching tomorrow, and i am devastated. Undo doesn't work.

Please tell me there's an archive somewhere, because I'm about to cry.

My brew was called God Punchers

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
When you say blank page do you mean the blank blue screen, or just an empty
document?

What are the links to your share and edit files? I'm not the owner of the
site, but one time I accidentally deleted my work and google had cached a
version that I found just by searching the block of letters on my link.

**Comment by emilyfroese** [comment]
I mean the blank document. I didn't bother posting the links because I saw your comment on an earlier thread suggesting those techniques and pursuing them did nothing for me. There is no cached file, even when i search only the block of letters, which is why I am wondering about an archive because I have looked in to every other option to no avail

**Comment by calculuschild** [comment]
See #654
