### ISSUE TITLE
"Can't get that" error when trying to open my edit or share link

### ISSUE THREAD

**Issue by NinjaZach54** [stolksdorf/homebrewery#449]
Hello,
I coded a homebrew class called "The Gambit" and have been editing it over the past few days. Today both of the edit and share links give me the error message in the title "Can't get that".

Is there a new link that I can get so I can continue editing and keep my work?

Thanks,
Zach

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/ByvacwBr-

**Edit Link**  http://homebrewery.naturalcrit.com/edit/SylDa5vBS-

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
I google searched the character string at the end of your edit link and luckily they had a cached page from the 14th of July.  That was a few days ago, but its the most recent source code I could find.

Searching your share link gets me a page from the 16th, so two days later, but it just has the shared view; can't get the source code. [Here it is.](http://webcache.googleusercontent.com/search?q=cache:K6b1accjJH8J:homebrewery.naturalcrit.com/edit/SylDa5vBS-+&cd=1&hl=en&ct=clnk&gl=us) anything changed between those two days I'd grab the source code from the 14th to start and try making any of the updates from the 16th by hand before google's cache gets updated to your blank page. Go ahead and start a new document and paste the code in there.

I had something similar happen to me, and it was when I accidentally shared my edit link with a random stranger on reddit. As soon as somebody clicks your edit link, they also become editors to your document and can delete the file if they wish. Could be what happened.  Just in case, always keep a backup of your code somewhere.

Here's the recovered source code from google's cache:

<pre># **The Gambit**
<div class='classTable'>
##### The Gambit
| Level | Proficiency Bonus | Features | Cards Per Attack | Deck Stacks | Stack Damage Dice |
|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Magic-Stacked Deck | 1 | 0 | - |
| 2nd | +2 | Deck Stack | 1 | 2 | 1d4 |
| 3rd | +2 | Deck Suit | 1 | 3 | 1d4 |
| 4th | +2 | Ability Score Improvement | 1 | 4 | 1d4 |
| 5th | +3 | Deck: Rapid Withdrawl | 1 | 5 | 1d4 |
| 6th | +3 | Suit Feature | 2 | 6 | 1d6 |
| 7th | +3 | - | 2 | 7 | 1d6 |
| 8th | +3 | Ability Score Improvement | 2 | 8 | 1d6 |
| 9th | +4 | Feelin' It | 2 | 9 | 1d6 |
| 10th | +4 | Deck: Lifesteal | 2 | 10 | 1d6 |
| 11th | +4 | Suit Feature | 3 | 11 | 1d8 |
| 12th | +4 | Ability Score Improvement | 3 | 12 | 1d8 |
| 13th | +5 | - | 3 | 13 | 1d8 |
| 14th | +5 | - | 3 | 13 | 1d8 |
| 15th | +5 | Deck: Deep Cuts | 3 | 13 | 1d8 |
| 16th | +5 | Ability Score Improvement | 4 | 14 | 1d10 |
| 17th | +6 | Suit Feature | 4 | 14 | 1d10 |
| 18th | +6 | - | 4 | 15 | 1d10 |
| 19th | +6 | - | 4 | 15 | 1d10 | 
| 20th | +6 | Hold 'Em | 4 | 15 | 1d10 |
</div>



<div style='margin-top:140px'></div><div style='margin-top:140px'></div>






## Creating a Gambit
When creating a Gambit try to remeber where he/she was given their Magic-Stacked Deck. Did you happen upon it in a dark alleyway? Were you approached by a mysterious stranger? Did you win it in a game of chance? 






## Hit Points
**Hit Dice:** 1d8

**Hit Points at 1st Level:** 8 + CON Modifier

**Hit Points at Higher Levels:** 1d8 (or 5) + CON Modifier per Gambit level after 1st.


## Proficiencies
**Armor:** Light Armor

**Weapons:** Simple, Deck of Cards

**Tools:** None

**Saving Throws:** Dexterity, Charisma

**Skills:** Choose 2 skills from Acrobatics, Arcana, Deception, Perception, Slight of Hand, Stealth


## Equpiment
You start with the following equpiment, in addition to any equipment granted by your background.
- **(A)** Quarterstaff -or- **(B)** Any Simple Weapons
- **(A)** 5 Javelins -or- **(B)** Light Crossbow and 20 bolts
- Magic-Stacked Deck
- Dungeoneer's Pack




<div class='pageNumber'>1</div>
<div class='footnote'>Page 1 | Gambit</div>




\page

## Magic-Stacked Deck
Starting at 1st level you gain this magic weapon. It is your primary means of damage. The deck will gain features at 5th, 10th, and 15th level. Also as you level up, you will gain the ability to throw more than a single card at a time.

Range: 60ft

Damage: 1d4 + DEX Mod


### Deck Feature: Rapid Withdrawl
At 5th level, whenever you use your action to make a ranged attack and it hits a target, as a reaction, you may then use your magic to immediately bring the thrown card back to your hand dealing an extra 1d4 damage to the hit target. You can use this ability up to (DEX Mod) times per long rest.

** If more than 1 card was thrown, each card withdrawn will deal 1d4 damage to the creature it initally hit. **

### Deck Feature: Lifesteal
At 10th level, any time you hit a creature with a ranged card attack, you heal for 1 hitpoint.

** If more than 1 card was thrown, each card that hit a creature will regenerate 1 hit point. **

### Deck Feature: Deep Cuts
At 15th level, any time you hit a creature with a ranged card attack, the creature will take 2 damage at the start of its next turn.


## Deck Stacking
Starting at 2nd level you gain the ability to add an effect to your ranged card attacks. You may expend a STACK to grant a ranged attack one of the following effects as well as add the STACK Damage Dice (Shown in table)
- This attack deals an extra 2 fire damage
- This attack reduces the enemy's speed by 10 for a single round
- This attack deals no damage, but instead blinds the creature for a single round.
- This attack gets a +2 to hit, but doesn't deal the STACK Damage Dice bonus
- This attack poses disadvantage on target's next saving throw unless they pass a WIS saving throw.

** Your suit will also grant STACK options. **


- **If you are throwing more than 1 card, the STACK only applies to half of the cards thrown rounded down. **

Table shows how many STACKS you can use per long rest.


## Suit
At 3rd level, you will choose one of the following suits : Hearts, Clubs, Diamonds, or Spades. Each suit has different effects detailed later.
<div style='margin-top:50px'></div>

## Ability Score Increase
At 4th level, you take an ability score upgrade. You will upgrade again at 8th, 12th, and 16th level.






## Feelin' It
At 9th level, all of your ranged card attacks get an extra +2 to hit.



## Hold Em'
At 20th level, you may use as many STACKS as you'd like in a single ranged card attack. Also, at the end of each day, you regain half of your used STACKS.



<div class='pageNumber'>2</div>
<div class='footnote'>Page 2 | Gambit</div>

\page

# Suits

### Hearts
When you take this suit, you get +1 AC. Also, as you level up in the Hearts suit, you gain access to the following STACK effects. ** These STACK effects can only be used once per long rest! **
<div style='margin-top:20px'></div>



L3: Jack of Hearts: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: You heal yourself for 1/2 of the damage dealt by this attack. If the attack misses, you gain no life and the STACK is still expended.

L6: Queen of Hearts: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table. 
Effect: This attack auto-matically hits. Reduce the damage done by the attack by 5. Up to 3 friendly creatures within 10 feet of you may heal 5 hitpoints.

L11: King of Hearts: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target takes an extra 4d8 necrotic damage and becomes immune to healing effects for the next hour. If the attack misses, nothing happens and the STACK is 
still expended.

L17: Ace of Hearts: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: This attack auto-matically hits. Target takes an additional 10d8 acid damage and the target's AC is reduced by 3 for the next hour.

### Clubs
When you take this suit, you get +1 AC. Also, as you level up in the Clubs suit, you gain access to the following STACK effects. ** These STACK effects can only be used once per long rest! **
<div style='margin-top:20px'></div>

L3: Jack of Clubs: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target must make a CON saving throw. On a fail, the target has disadvantage on the next 2 attacks it makes. If the attack misses, nothing happens and the 
STACK is still expended

L6: Queen of Clubs: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, creates a circle (15ft radius) of dark tar centered on target. Creatures inside the area take 1d4 poison damage and cannot take a reaction until your next 
turn. The tar dissipates at the beginning of your next turn.

L11: King of Clubs: Expend a STACK to add this effect to your next attack.
Effect: This attack auto-matically hits. Target takes an extra 1d12 piercing damage and becomes stunned until the end of your next turn.

L17: Ace of Clubs: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: Target either self and another friendly creature. Target gains advantage on all skill checks and saving throws for the next 10 minutes.

<div style='margin-top:40px'></div>

### Diamonds
When you take this suit, you get +1 AC. Also, as you level up in the Clubs suit, you gain access to the following STACK effects. ** These STACK effects can only be used once per long rest! **
<div style='margin-top:20px'></div>

L3: Jack of Diamonds : Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, sharp magic diamonds erupt and hit any hostile creature within 10 ft that is not the initial target for 2d4+1 damage. If this attack misses, nothing happens
and the STACK is still expended.

L6: Queen of Diamonds: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target is marked. If the marked target dies before the end of your next turn, it explodes dealing 4d4 piercing damage to all creatures in a 15ft radius. If 
this attack misses, nothing happens and the STACK is still expended.

L11: King of Diamonds: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: Oh hit, target must make a CON saving throw or become unconsious. Target takes an extra 4d4 piercing damage. If this attack misses, nothing happens and the STACK
is still expended.

L17: Ace of Diamonds: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, this attack deals an extra 9d4 and explodes in a 15ft radius. All enemy creatures must make a DEX saving throw or take 9d4 damage. Half on a pass.

### Spades
When you take this suit, you get +1 AC. Also, as you level up in the Clubs suit, you gain access to the following STACK effects. ** These STACK effects can only be used once per long rest! **
<div style='margin-top:20px'></div>

L3: Jack of Spades: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target takes an additional 1d10 piercing damage. If this attack misses, nothing happens and the STACK
is still expended.

L6: Queen of Spades: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target must make a STR saving throw or drop it's weapon. If this attack misses, nothing happens and the STACK
is still expended.

L11: King of Spades: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: Target becomes marked. Until it passes a WIS saving throw it takes an aditional 1d4 damage from all sources.

L17: Ace of Spades: Expend a STACK to add this effect to your next attack, adding also the Stack Damage Dice shown in table.
Effect: On hit, target takes an extra 8d4 piercing damage. Then roll from the Wild Magic Table. The effect happens to the target, on it's location.
</pre>

**Comment by PaleMage** [comment]
I saved and edited a little your code, NinjaZach54, to better satisfy page layout. Feel free to reorder anything as You see fit... 

[Gambit_Homewery_Code.txt](https://github.com/stolksdorf/homebrewery/files/1163246/Gambit_Homewery_Code.txt)

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@esda01 If you are still experiencing this issue, feel free to reopen and provide information.
