### ISSUE TITLE
Right Column Monster Stat Blocks leaving shadows in left side and won't move.

### ISSUE THREAD

**Issue by JamesIntrocaso** [stolksdorf/homebrewery#451]
So I'm having a problem in that when I create two single-column monster stat blocks on a page and the second one moves to the right column, I have it's shadow still in the left column and I can't move that second stat block at all. I've tried vertical spacing and column breaks, but the shadow remains and the second stat block won't move. I'm new to this so any help is huge. 

### Additional Details

**Share Link** :
<img width="411" alt="screen shot 2017-07-20 at 12 32 40 pm" src="https://user-images.githubusercontent.com/25487735/28428501-8f45ede0-6d47-11e7-948e-678b6f357620.png">

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
After the second stat block moved to the right, did you manually add the column brake? If you do, i think the <div style="margin-top: 123px"></div> should work to lower the right stat block.

**Comment by JamesIntrocaso** [comment]
This is with the column break added manually.

**Comment by HeruAsatru** [comment]
I just tested it, and you're right, most of the stuff doesn't work to move it. But, ` <br/> ` does still works. Try it and tell me, if that does anything for you.

**Comment by JamesIntrocaso** [comment]
Ah I see. That is a new one by me. Thank you! It works.
