### ISSUE TITLE
Brew Preview is No Longer Updating in Real Time, and ToC Page is Missing

### ISSUE THREAD

**Issue by jldixon1** [stolksdorf/homebrewery#456]
### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/edit/SJlr51v6I-

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Duplicate of #655
