### ISSUE TITLE
When creating PDF, blank sheets are added

### ISSUE THREAD

**Issue by Sansd20** [stolksdorf/homebrewery#458]
Trying to create a PDF, there is a blank page added after every page in the brew.

http://homebrewery.naturalcrit.com/share/rkuzC8LL-

[prayerbook 012.pdf](https://github.com/stolksdorf/homebrewery/files/1201289/prayerbook.012.pdf)

Page is setup for half sheet. This worked last week.

**Comment by HeruAsatru** [comment]
Works fine for me, used your brew.

There is a setting in printer options where there is a blank page added between each page. Check your printer/pdf settings. This doesn't seem like a homebrewery issue.

**Comment by jimcullenaus** [comment]
Possibly related to #468.

**Comment by calculuschild** [comment]
This is likely due to selecting the incorrect page size when printing the PDF. Closing for now because the document in question has been deleted.

Feel free to reopen this issue if this is still a problem for you and you can provide more information. @Sansd20 .
