### ISSUE TITLE
Add Class Feat change many things

### ISSUE THREAD

**Issue by htorres09** [stolksdorf/homebrewery#462]
When I add a Class Feat it adds me another Cover Page, another Content Page, another page with the same content as other one, and change all things written in tables to undercase

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Duplicate of #413 . A fix is on the way.
