### ISSUE TITLE
Issue with npm install and build. Which version of node.js is needed?

### ISSUE THREAD

**Issue by Zephilinox** [stolksdorf/homebrewery#467]
This is using the master branch, last commit around april. I assume that's correct?

I've tried a few different versions of node.js but can't seem to get through this part without some kind of error. At the moment I'm using node.js v6 LTS x64 on Windows 7 x64, which gives me these deprecation warnings if they're at all relevant:

![image](https://user-images.githubusercontent.com/2060863/29337056-df7704f0-8207-11e7-81a6-1ebd50de9d5d.png)

After it's done, I see this:

![image](https://user-images.githubusercontent.com/2060863/29337694-2fd7cc52-820a-11e7-9215-bd6e5016e8c3.png)
![image](https://user-images.githubusercontent.com/2060863/29337700-34b40e84-820a-11e7-831b-3f683a97177c.png)
![image](https://user-images.githubusercontent.com/2060863/29337711-3c69c088-820a-11e7-9672-78026611e7fe.png)
![image](https://user-images.githubusercontent.com/2060863/29337716-470ae314-820a-11e7-9ec9-5c3a431921f5.png)

Here's the npm log: https://drive.google.com/file/d/0B8_z2CL9xOpIV1BwM1E2cnBxZXc/view?usp=sharing

**Comment by HeruAsatru** [comment]
There seems to be a problem with the current homebrewery build and the newer versions of npm/node, specifically the vitreum library. You might wanna check out these two issues: https://github.com/stolksdorf/homebrewery/issues/424 & https://github.com/stolksdorf/homebrewery/issues/442

**Comment by HeruAsatru** [comment]
You may wanna check the comments in this issue: https://github.com/stolksdorf/homebrewery/issues/442
A solution was presented and worked for me.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Zephilinox
