### ISSUE TITLE
words hidden by the edge

### ISSUE THREAD

**Issue by wspr119** [stolksdorf/homebrewery#470]
parts of the text are being hidden by the edge nd there is no way to read them besides the parts that are visible

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
It's hard to help without seeing what's going on. Mind posting the "share" link to your brew as the above form asked you to?

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information. @wspr119
