### ISSUE TITLE
Can we please get a truncated version of tables?

### ISSUE THREAD

**Issue by PariahSilver** [stolksdorf/homebrewery#472]
Tables are implemented really well, but is it possible to shrink them a bit vertically? Something simple, like reduce the padding on the top and bottom of each line. Just a little bit would do, so I can fit more on each page, would be great.

**Comment by Rae2che5** [comment]
What table are you referring to in particular? You can do this with inline style blocks. For example, to reduce the top and bottom padding of class tables, add this to the beginning of your brew:

```
<style>
  .classTable table tbody tr td { padding-top:1px; padding-bottom:1px; }
</style>
```

See [here](http://homebrewery.naturalcrit.com/share/S16vVCROZ) for an example. Alternatively, you can do it for all tables by adding a style of `td { padding-top: 1px !important; padding-bottom: 1px !important; }`.

**Comment by PariahSilver** [comment]
Rae2che5 that's perfect, I didn't realize it would register CSS. Thanks!
