### ISSUE TITLE
Creating a tab space in the next line in a monster stat block

### ISSUE THREAD

**Issue by undeadjebus** [stolksdorf/homebrewery#474]
Example 1 (Where my problem lies at the last line):
___
___
> ## Mask, god of thieves
>*Black mask, Chaotic Neutral*
>___
> ##### Trickery Domain Spells
>| Cleric Level | Spells |
>|:----:|:-------------|
>| 1st  | *charm person, disguise self* |
>| 3rd  | *mirror image, pass without trace* |
>| 5th | *blink, dispel magic* |
>| 7th | *dimension door, polymorph* |
>| 9th | *dominate person, modify memory* |
> ___
>#### Bonus Proficiences
>At 1st level, you gain proficiencey with martial weapons and heavy armor.

>#### Wrath of the Storm
>Also at 1st level, you can thunderously rebuke attackers. When a creature within 5 feet of you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d8 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one.
>	You can use this

**** Example 2 (What I'm trying to get it to look like)

Also at 1st level, you can thunderously rebuke attackers. When a creature within 5 feet of you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d8 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one.
    You can use this feature....

****Example 3 (What I keep getting)

Also at 1st level, you can thunderously rebuke attackers. When a creature within 5 feet of you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d8 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one. You can use this feature....

****or

Also at 1st level, you can thunderously rebuke attackers. When a creature within 5 feet of you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d8 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one.

• You can use this feature.....

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by undeadjebus** [comment]
Okay. So what is missing is a gap of space at the beginning of "You can use this feature..."

**Comment by calculuschild** [comment]
You could try typing in "&nbsp" a few times. That will put a blank space.

**Comment by Gadget2020** [comment]
I use this to eliminate the blank space (it works for lists too):

... and half as much damage on a successful one.
___
<div style='margin-top:-16pt'></div>
You can use this...
