### ISSUE TITLE
Changing Title/ Deleting an item that I cannot see the delete icon for

### ISSUE THREAD

**Issue by Mwhite0788** [stolksdorf/homebrewery#476]
I saved an item before i added any text to it and now the item does not have a title on my user screen and i also cannot delete it becuase the only icons i can see are the share and edit icon. Any help would be appreciated. 

Thanks,

**Comment by calculuschild** [comment]
Can you click the edit button and just delete it from the edit screen?

**Comment by Mwhite0788** [comment]
/facepalm.. Never noticed those 3lines that opened the menu for options, Was able to add a title there and it worked perfectly. 

Thanks
