### ISSUE TITLE
Ordered list inside stat block not displaying correctly.

### ISSUE THREAD

**Issue by Sansd20** [stolksdorf/homebrewery#485]
The first line in an ordered list inside stat block not displaying correctly. I am seeing the number, with the line starting on the next line below. The line below the ordered list is indented when it shouldn't be, Also, when changing this to a standard state block, the page layout get all weird. 

### Additional Details

http://homebrewery.naturalcrit.com/share/rJXFUU9aYW

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

___
___
>## Spectator
>*Medium aberration, lawful neutral*
>___
>* **Armor Class** 14 (natural armor)
>* **Hit Points** 39 (6d8 + 12)
>* **Speed** 0 ft., fly 30 ft.
>___
>|STR | DEX | CON | WIS |INT|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|8 (-1) | 14 (+2) |14 (+2)|14 (+2)|13 (+1)|11 (+0)|
>___
> - **Skills Perception** +6
> - **Condition Immunities** prone
> - **Senses** darkvision 120 ft., passive Perception 16
> - **Languages** Deep Speech, Undercommon
> - **Challenge** 3 (700 XP)
>___
> ***Hover.*** The spectator hovers as long as it is alive.
>
> ***Telepathy.*** The spectator can communicate telepathically with any creature within 100 feet of it that can understand a language.
>___
> ### Actions
> ***Bite.*** *Melee Weapon Attack:* +1 to hit, reach 5 ft., one target. *Hit:* 2 (1d4 - 1) piercing damage.
>
> ***Eye Rays.*** The spectator uses two of the following eye rays. It can use each ray only once per turn. Each ray targets a creature the spectator can see within 90 feet of it.
>
> 1. *Confusion Ray.* The target must succeed on a DC 13 Wisdom saving throw, or it can't take reactions until the end of its next turn. On its turn, the target can't move, and it uses its action to make a melee or ranged attack against a randomly determined creature within range. If the target can't attack, it does nothing on its turn.
>
> 2. *Paralyzing Ray.* The target must succeed on a DC 13 Constitution saving throw or be paralyzed for 1 m>nute. The target can repeat the saving throw at the end of each of its turns, ending the effect early on a success.
>
> 3. *Fear Ray.* The target must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, with disadvantage if the spectator is visible to the target, ending the effect early on a success.
>
> 4. *Wounding Ray.* The target must make a DC 13 Constitution saving throw, taking 16 (3d10) necrotic damage on a failed save, or half as much damage on a successful one.
>
> ***Create Food and Water.*** The spectator creates enough food and water to sustain itself for 24 hours.
>
> ### Reactions
>***Spell Reflection.*** If the spectator makes a successful saving throw against a spell, or a spell misses it, the spectator can choose another creature within 30 feet of it that it can see. The spell affects the chosen creature instead of the spectator.

</pre></code></details>

**Comment by Rae2che5** [comment]
You can work around the problem by removing the blank lines after every list item: http://homebrewery.naturalcrit.com/share/SyW_Id3AKZ. (I'm not sure what exactly goes wrong in the style sheet with those lines there, but given the workaround is easy it seems best to just use it.)

**Comment by Sansd20** [comment]
huh. I could have sworn that I had tried that. Thanks.

So any idea how to get rid of the indent on **_Create Food and Water_**?

**Comment by Rae2che5** [comment]
There's a style rule that adds a `1em` indent to `.phb ol+p`. I assume that's necessary in certain cases, but you can customise your existing `<style>` block by adding `
  .phb hr+blockquote ol+p { text-indent: 0px; }` -- hopefully that won't break anything else.

**Comment by Sansd20** [comment]
Sorry, I am just now getting back to this. That worked thanks.
