### ISSUE TITLE
Table Issues

### ISSUE THREAD

**Issue by festivefetusss** [stolksdorf/homebrewery#493]
Hi, 

I'm working on my brew and am having some troubles with a few tables that I'm creating. 
It's probably something really simple that I'm missing...I'm *really* new to "coding" and still have a ton to learn. 

I want the bottom table (Racing Dinosaurs) to be more spread out...It looks really bad right now, and all crammed together. I've tried using the "wide table" formatting, but when I close off the </div> it displays as plain text. If I remove the ">" from the closing div tag, the table looks how I want it too, but of course there's an HTML error. 

Can you please help me out? I'm ready to get my ToA game off the ground, and really want to get this doc over to my players so we can start up. 

Like, i said...I'm really new to HTML, and CSS, and all that stuff so my code probably looks really bad. I apologize in advance. 

Let me know if you need more information. 

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/ryZT0_OocZ

![ugly table](https://user-images.githubusercontent.com/22503381/30518022-b4184c0a-9b26-11e7-9aab-1dccbebf58c0.jpg)
![dafuq](https://user-images.githubusercontent.com/22503381/30518021-b41846f6-9b26-11e7-940d-a74bb6bb55e5.jpg)
![dafuq x2](https://user-images.githubusercontent.com/22503381/30518020-b417f778-9b26-11e7-9ae4-654fa30485d2.jpg)

**Comment by calculuschild** [comment]
I think you left some blank spaces at the end of the line with your table headers (mount, speed, etc...) My guess is the system responsible for converting your table into HTML is getting confused by those.

**Comment by festivefetusss** [comment]
**Thank you so much!**
You called it, man. The extra spaces at the end of line 32 (screenshot) totally caused the issue. 
Once I removed them, the table formatted properly. 

Thanks again. 
Gonna close this one out now. 

*finger guns* u da man
![fixed-code](https://user-images.githubusercontent.com/22503381/30523584-ae31df0a-9b98-11e7-971b-7fd78569699d.jpg)
![fixed-table](https://user-images.githubusercontent.com/22503381/30523585-ae32bc36-9b98-11e7-9558-761e4f2e30eb.jpg)
