### ISSUE TITLE
Brew not loading, showing blue and version 0.0

### ISSUE THREAD

**Issue by KelpTheShark** [stolksdorf/homebrewery#494]
One of my brews is no longer loading. Both the typing space and the preview are solid blue, and the version number says 0.0 If I export as PDF it still shows my brew, minus one of the most recent parts I worked on. 

Right before this happened I was testing the Ink friendly option out, and then i closed and tried to reopen the brew and it wouldn't load.

Any idea how to fix this, I wasn't done with it yet.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by KelpTheShark** [comment]
Just tried clearing my browsers cache. No effect.

**Comment by calculuschild** [comment]
This is the same as about 90% of other issues listed here. You have entered
some invalid HTML code and saved it while it was invalid. This causes the
rendering system to crash.

If you can't get to your code, you can at least go to the "share" button on
the top right, then "view source", copy your code, make a new brew, fix
your code, then save. You can then delete your old brew through your
account page.
