### ISSUE TITLE
Sharing and Downloading

### ISSUE THREAD

**Issue by wuzzy41123** [stolksdorf/homebrewery#495]
How do I go about sharing and downloading my Homebrew PDF?

I couldn't find it anywhere on the site. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
If you go to print it you can "print" it as a pdf.

**Comment by Sansd20** [comment]
Wuzzy, if you click on "Get PDF" on the top right, that, at least for me, brings up the print dialog. From here, you can print to PDF.

To share, to the left of that, is "Share" where you can send or post the link as you see fit.

The closest to downloading and then reuploading would to copy the source to a txt document, and when you want to "reload" would be to paste the content of that text file into a new brew.

**Comment by wuzzy41123** [comment]
@calculuschild  I don't want to print it as a PDF, at least not yet. I want to have it saved as a PDF, so I can share it with other players/DM's via email and forums.

**Comment by calculuschild** [comment]
Right. So when I say "print as PDF" it will literally create a digital PDF
file you can save on your computer, as opposed to "print on paper".

So when you click the "Get PDF" button, and it tries to print, you just
select one of the "Print to PDF" printers:

[image: image.png]

**Comment by calculuschild** [comment]
Right. So when I say "print as PDF" it will literally create a digital PDF
file you can save on your computer, as opposed to "print on paper".

So when you click the "Get PDF" button, and it tries to print, you just
select one of the "Print to PDF" printers:

![image](https://user-images.githubusercontent.com/5878534/30703195-fc0903da-9ebc-11e7-9258-76ba5c9a0b8a.png)

**Comment by Sansd20** [comment]
@wuzzy41123 Think of "Print to PDF" as "Save as PDF"

If you use the "Share" button, you can send out a link that will show your friends an non-editable version of the brew.
