### ISSUE TITLE
Suggestion : white background option

### ISSUE THREAD

**Issue by Benz74M** [stolksdorf/homebrewery#498]
Could it be possible to have a white background option (printer-friendly)?

Or maybe there's a way to do it already and I haven't seen it...

Thanks!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
I'm pretty sure there is a literally a "printer-friendly" snippet somewhere
in there. It will add a small bit of code to your brew that disables the
background.

**Comment by Sansd20** [comment]
It also disables any images you may have on the sheet.

**Comment by HeruAsatru** [comment]
You can always add 

`<style>  
    @media print {  
        .phb{  
            background: #FFF;  
        }  
    }  
</style>`



to your brew to have it print with a white background.
