### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kelhendros** [stolksdorf/homebrewery#500]
Hi there man, 
First of all, great tool! It makes me want to be more creative just to use it more.
I have one question... Do you know by any chance something alike but with Vampire The Masquerade style?
I am asking you after hours of searching without any luck. Maybe you, being in this project, know of something.

Thanks a lot!! 
Best regards and good luck with the 3.0!!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
I don't think anything like that exists. However, if you know CSS, you can change the style of your documents to be just about whatever you want. People have made templates to change the style to suit the D&D 5e Monster Manual, Dungeon Master's Guide, etc. by swapping out backgrounds and fonts and colors.

That's about as close as you can get for now.
