### ISSUE TITLE
Homebrewery DNS Address Not Found?

### ISSUE THREAD

**Issue by TheRealNeal** [stolksdorf/homebrewery#502]
I love the Homebrewery a lot and use it for a ton of stuff, but I got on to do some editing and I couldn't even get on the page. The message that came up was DNS Address Not Found. Don't know what it means exactly XD 
Is it an issue on my end or is it some kind of maintenance? Thanks very much!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
http://downforeveryoneorjustme.com/homebrewery.naturalcrit.com

Seems like it's an error on your side. There are sooo many possible reasons for that to happen, there's not much we can do here to help you. If you are at work, ask your IT guy. If you are at home, check if it happens with every device or just one, to locate the error.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@TheRealNeal  If you are still experiencing this issue, feel free to reopen and provide information.
