### ISSUE TITLE
get pdf -> print, ignores right paragraphs in the text 

### ISSUE THREAD

**Issue by loopmeagain** [stolksdorf/homebrewery#503]
hi, so i tried to print the abhorsen handbook, and when i get to the printing part, it ignores the second colmuns (right oriented, for example spellcasting habilities, and fightingstyle )

**Share Link** : http://homebrewery.naturalcrit.com/share/B1vibnUiW

**Comment by HeruAsatru** [comment]
does work for me just fine. maybe you have selected a wrong papersize in your print settings?

**Comment by loopmeagain** [comment]
I tried using firefox instead vivaldi and that solved the things for me
