### ISSUE TITLE
List Text Overrun When Saving to PDF

### ISSUE THREAD

**Issue by DoctorDan1986** [stolksdorf/homebrewery#504]
So, I've encountered a strange error in my campaign workbook.  Using lists, I always encounter a strange error using this particular code when saving to PDF format - the list heading (in this case the | English | Qaadi | part of the list multiplies itself and covers the rest of the items within that list.  I have other lists in this brew which do not cause such errors, so I'm at a complete loss to explain what is going on with this.

The HTML render does not show this - only the output when you click "Get PDF" does, as well as the actual saved PDF file.  I've attached the whole of the page code below.  Any help would be appreciated.

### Additional Details

**http://homebrewery.naturalcrit.com/share/rJ0zTGao-** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='pageNumber auto'></div>
<div class='footnote'>APPENDIX D: SPEAKING QAADI</div>

<div id="Speaking Qaadi"></div>

# Speaking Qaadi

As  far as the *March of the Worm-King* campaign setting is concerned, Qaadi is the Arabesque language of the southern regions of Tebryn, encompassing the whole of the Qaad Sultanate and the Shayd'm Desert tribes.  However, to the DM, Qaadi is not a true constructed language, in that it does not have a lexicon or grammatical structure.  It is instead a kind of **cipher**, a method of encrypting or altering information beyond simple comprehension.

While several example phrases are provided for your use throughout this book, the enterprising DM (or clever players) can use this cipher to create their own questions, answers, statements, or anything else they wish in Qaadi. 

Qaadi employs **unvoiced consonants**, where consonants immediately followed by an apostrophe (') are pronounced without using the vocal cords.  The apostrophe also  acts as an indicator for a brief pause in speech, or as an unvoiced 'eh' sound if at the end of a word.

When dealing with words that have a silent end letter (such as **there**), it is up to the DM or player to determine where to transliterate each letter into Qaadi, or simply the sound of the word.  It might even be better to do both when and where it pleases you - some words simply sound better one way or the other!

##### Qaadi Cipher
| English | Qaadi |
|:----:|:---|
| A | al/ab'd|
| B | bah/behd|
| C | *not used* Use 'S' or 'K' sound|
| D | desh|
| E | el/eb'd|
| F | fahd/foht|
| G | gan/geb'd|
| H | h/CH' *like German hard ch*|
| I | il/ib'd|
| J | j'ad/j'od *like German j or English y*|
| K | kahn/kop|
| L | l' |
| M | mahd/mod't|
| N | nahd/nod't|
| O | ol/ob't|
| P | p'/pahd|
| Q | qulit'|
| R | rahn/rod't|
| S | s'/saCH'd|
| T | t'/teh|
| U | ul|

| English | Qaadi  |
|:----:|:-------|
| V | vahn/vag't|
| W | W'/weCH'd|
| X | k'sh'|
| Y | y-/yob't|
| Z | zedt|

##### Example Phrases
| English|Qaadi|
|:---|---:|
|Halt!|W'alilt'!|
|Who are you?|W'hol yol-ul?|
|Why are you here?|W'h'yob't yol-ul hel rahn-el?|
|I don't understand you.|Ib'dnol kahnod't olweCH'd.|
<br/>
Take the first phrase, **"W'alilt'!"** *(W! ah-LEEL-teh)*.  Meaning 'halt!', it is derived from the English "Wait!".  By encoding each letter with the Qaadi cipher, we come up with the sounds *W', al, il,* and *t'*, representing the letters (or sounds, depending on your perception and choice) of **W**, **A**, **I**, and **T**.  We can string these together in an exotic-sounding word, **W'alilt'**.

Obviously, however, it would be impractical and ponderous to take full English sentences and encipher them.  The solution is twofold: first, break a sentence down to its most important components, such as in the next example phrase, **"W'hol yol-ul?"** *(W! hole yo-LOO-uhl)*, meaning, "Who are you?".  It is derived from the simplistic phrase, "Who you?".  Keep in mind that some word choices may need to be altered to fit the needs of pronunciation or timeliness.

The second half of the solution is simply to encipher 

</pre></code></details>

**Comment by Sansd20** [comment]
Move the “<div class='pageNumber auto'></div>
<div class='footnote'>APPENDIX D: SPEAKING QAADI</div>“ to the bottom of the page.

**Comment by DoctorDan1986** [comment]
FFFFFFFFFF...seriously?  That was IT?!

That's so dumb.  And so stupid.  And SO dumb.  And SO stupid.

IT'S SO GODDAMNED DUMB!

*sigh* 

Thanks.

**Comment by Sansd20** [comment]
That is not showing up on mobile. Move the two doc tags on page numbers and footnotes to the bottom of the page.

**Comment by Sansd20** [comment]
When your looking at code for a long time, it all starts to blur.
