### ISSUE TITLE
Is there a way to receover the password?

### ISSUE THREAD

**Issue by DBio616** [stolksdorf/homebrewery#505]
I did some work on Homebrewery and I can't manage to login.
Is there a way to reset/retrieve the password?

Thank you!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Nope, but if you have your edit links bookmarked, you can create a new account and edit them while logged in and they'll be added to the new account.
