### ISSUE TITLE
Automatic Pagination

### ISSUE THREAD

**Issue by taylorhadden** [stolksdorf/homebrewery#506]
Hi there!

I noticed that you support automatic column flow but not automatic pagination. What mechanism are you using for column flow? Could you detect when a page has flowed to three columns and automatically page break? I'm sure you've thought of it, I was just interested in what roadblock you hit.

Cheers!
-Taylor

**Comment by stolksdorf** [comment]
Thanks for the suggestion. I've always wanted to do this, but as far as I can tell this is exceedingly difficult and would probably be wrong more often than right, which would be very frustrating for the user. If anyone has any suggestions on doing this effectively, let me know.
