### ISSUE TITLE
Text Justify

### ISSUE THREAD

**Issue by Sansd20** [stolksdorf/homebrewery#507]
I am trying to figure out how to justify just the body text. when I place `  .phb{ text-align:justify }`  into the style, ***ALL*** text becomes justified. Headers, things in description boxes, ect. Anyone have any insight?

**Comment by HeruAsatru** [comment]
All body text is enclosed by `<p> </p>`, so you may give `.phb p{ text-align:justify }` a try.

**Comment by Sansd20** [comment]
That worked. Thanks.
