### ISSUE TITLE
Half class table breaks when trying to print/save as pdf

### ISSUE THREAD

**Issue by OptionalDamage** [stolksdorf/homebrewery#512]
When trying to save as a pdf, an issue occurs where the title in the half class table is repeated down the table itself, but only in the print dialog. In the editior and the page that prompts the print dialog it appears fine. I think it might be just a user issue, but I'm very confused.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/H1XzGhNhW

**Screenshot**: https://puu.sh/xS7ts/17bbb2f506.png

**Comment by DoctorDan1986** [comment]
Try pressing the 'enter' key after your </style> and get back to us.  It should look like:

`<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>

# Arcane Demolitionist`

**Comment by DoctorDan1986** [comment]
Also, you might not want to alter the page dimensions - it looks like your custom size isn't applied to every page, and that's screwing with your PDF creation, too.

**Comment by OptionalDamage** [comment]
Huh, that fixed it. Thank you so much!
As for the custom size, that was just the "A4 Pagesize" option from the print menu on the top of the editor. I'll remove it anyway since I added that initially to fix another issue.

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
