### ISSUE TITLE
It's down: Version 0.0.0 is live

### ISSUE THREAD

**Issue by bakgaard** [stolksdorf/homebrewery#515]
Version 0.0.0 is the one online. So nothing is working :(

**Comment by calculuschild** [comment]
The website is up, don't worry.

What likely happened is you have bad HTML in your brew, which will crash
the renderer, and the version number will also be broken on your screen.

**Comment by bakgaard** [comment]
That blows. What do I do? I can most likely narrow it down to one of two brews, but how to correct it?

**Comment by bakgaard** [comment]
I cleared my browser history - It's back on now.
