### ISSUE TITLE
Homebrewery Page won't save/print properly

### ISSUE THREAD

**Issue by jgiles1977** [stolksdorf/homebrewery#521]
So I'm new to Homebrewery, such a fantastic tool though. I do have an issue, when I print to PDF the first page is blank and the second page doesn't have any of the background color and only has one column that ends up getting cut off at the end of the second page rather than continue on the second column, its the same if I try printing it. I'm using Firefox and I don't know if that makes any difference or not.

Jon

### Additional Details

http://homebrewery.naturalcrit.com/share/rytX9z5b2Z :

or

 : <details><summary>Click to expand</summary><code><pre>

http://homebrewery.naturalcrit.com/share/rytX9z5b2Z

</pre></code></details>

**Comment by DoctorDan1986** [comment]
You have two column breaks (``` ```) on the same page.  Use only one per page, and create a new page with the \page code.  Welcome aboard!

**Comment by DoctorDan1986** [comment]
Ugh. Mobile version of github sucks.  Six hash marks like the following
```
```

**Comment by DoctorDan1986** [comment]
*facepalm*

This symbol: `

**Comment by DoctorDan1986** [comment]
Also, homebrewery will only work correctly on Google Chrome.  Use that instead

**Comment by jgiles1977** [comment]
Thank you! I'll try this out after work today! Thanks!

On Oct 12, 2017 11:10 PM, DoctorDan1986 <notifications@github.com> wrote:

Also, homebrewery will only work correctly on Google Chrome. Use that instead

**Comment by jgiles1977** [comment]
It worked for me! Thanks!

On Oct 12, 2017 11:09 PM, DoctorDan1986 <notifications@github.com> wrote:

Ugh. Mobile version of github sucks. Six hash marks like the following
