### ISSUE TITLE
No Render

### ISSUE THREAD

**Issue by birkeybrke** [stolksdorf/homebrewery#522]
Currently, instead of showing a preview of the document either in edit or share view I get a blue page with a black page count and nothing else. If I print, I get a good document, but the second page is white with no formatting. If I transfer the code to a new brew it works for a little bit then doesn't work again.

### Additional Details

http://homebrewery.naturalcrit.com/share/BybVO8mw5W

**Comment by Sansd20** [comment]
That is odd. I viewed the source, copy-and-pasted it to a new brew, and I see it just fine. Saved it, and it still works.

**Comment by birkeybrke** [comment]
Thanks for the suggestions, I will take a look at those.

I wonder if yours still works. I tried doing the same thing, copy the code, create a new document, and then paste the code in. The new one worked for an hour or so, then had the same problem. I have tried multiple computers with multiple browsers, and with private tabs without luck.

**Comment by Sansd20** [comment]
Hmm, I deleted shortly after sending my last message. I will copy it over and check it out.

I will say that when I open that link, I only get the black title bar.

**Comment by ReggaeShark1** [comment]
This same problem has just happened to me. I have tried all those things you have to, with no luck. No obvious cause either

**Comment by Sansd20** [comment]
I saved it. Ill look at it either tonight or tomorrow.

**Comment by Sansd20** [comment]
@ReggaeShark1 what is the link to your brew?

**Comment by ReggaeShark1** [comment]
http://homebrewery.naturalcrit.com/share/Sk3fEtFqb

**Comment by Sansd20** [comment]
@birkeybrke Also, when you want to break a column, use three back ticks (`)on a new line, and three more right below that. so you would have

**Comment by ReggaeShark1** [comment]
I have fixed the problem, which was purely my fault. It was as simple as accidentally deleting a '</div>' out of the end section of source code for a descriptive text block.

**Comment by birkeybrke** [comment]
@Sansd20, thanks for the formatting tips. So far my third attempt at this file seems to be holding, so I guess I will just go with it for now and resubmit if it breaks again.

Thanks again!
