### ISSUE TITLE
selkie art credit

### ISSUE THREAD

**Issue by jessicashirleyart** [stolksdorf/homebrewery#528]
On your post about selkies you have credited my painting "the selkie" to another person (jane morrissey?) While I don't mind my art being used in blog posts I would appreciate it if you would either change the credit to Jessica shirley or remove the art if you prefer.

Thank you,
Jessica

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
It looks like you are trying to contact somebody who has recently used this website to create a document. Unfortunately this page is only for reporting bugs and glitches in the website code. You will probably need to find a different way to contact the author with your concerns.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@jessicashirleyart  If you are still experiencing this issue, feel free to reopen and provide information.
