### ISSUE TITLE
Saving screws up the formatting

### ISSUE THREAD

**Issue by AngusMurray** [stolksdorf/homebrewery#529]
### The title says it all

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div style='margin-top:50px'></div>
# The Vex
###### "Living metal. Incomprehensible intelligence."
<div style='margin-top:10px'></div>

The Vex are architects of ancient and complex structures 
thought to be buried beneath many parts of the world. They 
are living metal, clockwork for sure...but they're alive, they 
have a consignee. They are exceedingly rare to find, often found guarding ancient ruins that litter depths of our world. 
Their patience is timeless and their purpose unknown, they are not to be underestimated; they aren't normal, mindless constructs.

<div style='margin-top:px'></div>
### Mysterious Mechanics
<div style='margin-top:0px'></div>

Over recent years people have reported more and more sitings of strange constructs hanging around old ruins at night; looking for something and building things. They act in silence, but with calculated purpose, these constructs are never alone and always travel together in large groups.

How these machines, people have taken to calling Vex, came into existance is all but a mystery. Very little is known about them at all, other than they are made a strong compound metal, with white liquid flowing around their body and that the source of their power comes from magical crystals housed in the centre of the bodies. 

<div style='margin-top:0px'></div>
### Knowledge is Power
<div style='margin-top:0px'></div>

The Vex are ancient even by the most long lived species; they are thousands of years old at least. There are many ruins buried beneath the surface of our world, these ruins hold power and the key to Vex's purpose, they can often be seen at ruins from long dead races; examining, researching and then rebuilding them into places they can live in, this proccess is short and often only takes a few months for a single ruin depending on its size. Who knows maybe their goals is to do the same to the entire world; make it somewhere only they can survive and kill us all?

The Vex, from limited study, have never spoken to each other or anyone else; the communicate perfectly without actually talking. This is because their minds are linked to each other constantly relaying information and research to further their unknown purpose.

<div style='margin-top:0px'></div>
### The Black Garden
<div style='margin-top:0px'></div>

One Vex ruin of note is called the Black Garden; said to be a place of un-told beauty as far as the eye can see. Tt has only ever been visited a few non-vex, it's said to be almost impossible to gain access if you aren't Vex. Very few even know where it is, they are either dead or lost. 

Finding this place has claimed the lives of many scholars and adventures alike, the Vex aren't to be trifled with and they don't like to be disturbed.
<div style='margin-top:10px'></div>
<img 
  src='http://planetdestiny.com/wp-content/uploads/2014/10/504150_a5dae487985a62ae8a1b2f180abcbba9.jpg'
  style='width:325px' />
Credit: Bungie

<div style='margin-top:0px'></div>
### The Vex Network
<div style='margin-top:0px'></div>

The Vex are split into several major groups, each one acting with unique objectives and purpose. These groups are;Hezen Corrective, Hezen Protective, Virgo Prohibition and Sol Divise. The Vex work in unison and aim to be as efficient as possible in everything they do...everything! Nothing is done without meaning and each group, although seperate from eachother, work together in constant relay. 

All of the groups have a hierarchy; leading 'mind', hydra units, minotaur units to goblin, hob-goblin and harpy units. This hieracrhy is crucial to their survival, their goal and without it they would be scattered and without purpose, lost souls waiting to die.

<div style='margin-top:70px'></div>

\page 

<div style='margin-top:50px'></div>
### Vex Names
<div style='margin-top:0px'></div>

The Vex don't have genders as far as we know, although some 
of their names are more masculine than others. We don't even know how or why they name themselves.<div style='margin-top:10px'></div>
** Names: ** Atheon, Qodron, Theosyion, Zydron, Sekrion
<div style='margin-top:10px'></div>
### Vex Traits
<div style='margin-top:0px'></div>

Your Vex character has certain traits and features common among all Vex.<div style='margin-top:3px'></div>

**Ability Score Increase: ** Your Inteligence Score increases by 2. 

**Age: ** Ageless. In theory they can live forever due to their mechancial body, but like anything mechancial without proper maintenance and care they will still wither and die. 

**Alignment: ** The Vex seldom meld with societies outside of their own, they rarely interact with people and have even been known to show kindness to those bold enough to stand their ground. They will, defend themselves and their homes with no mercy and will do unspeakable things to those they capture.

**Size: ** You tower over most normal people as you stand a staggering 10ft tall(min).

**Speed: **Your base walking speed is 30.

**Armour Plating:** As a living, metal construct you have no need for armour as you have your own. Your armour comes in the form of plate metal and provides +1 to you AC. 

**Darkvision: ** As a machine who guards ancient ruins you can see almost perfectly in the dark. You can see dim light as if it were bright 60feet in front of you. You cannot disern colour only shades of grey.

** Headless Frenzy: ** Although you have been design to look humaniod you don't need certain parts of your body. When your head is severily damaged or knocked off **(if enemy targets head or hits +5 above your AC)**, you charge that foe, you can double move and attack an extra time.

** Timeless: ** As a construct you have no need for food, water or sleep. You never fatigue and disease doesn't affect you. However you do need to maintain yourself and thus must perform maintanence 4 hours per day; this is equivilant to a long rest. You have a disadvantage on all checks whilst doing this.

** Seemless transition:**You have the cantrip  **Temploral Blur**

**Language: **You can speak(although not well), read and write Vex, Common and can interact with constructs of anykind.
<div style='margin-top:10px'></div>

### Vex Collectives
<div style='margin-top:0px'></div>

All Vex made for a particular sect of the Vex network, each sect performs specific objectives that seldom overlap. Vex are act differently depending on the group they are made for.<div style='margin-top:0px'></div>
Choose a group to be a part of:
#### Hezen Corrective<div style='margin-top:0px'></div>

The Hezen corrective are aggressive in their work, they probe ancient ruins, perform research operations; they're often seen altering ruins so they can inhabit them.
<div style='margin-top:0px'></div>** Problem Solver: ** You gain proficency in Investigation. 

<div style='margin-top:0px'></div>** Aggressor: ** Add +1 to initiative. 

#### Hezen Protective<div style='margin-top:0px'></div>

The Hezen protective work in conjuction the Corrective, they act as sentinels standing ever vigilant, protecting their own.
<div style='margin-top:0px'></div>** Sentinel: ** You gain proficency in Perception. 
<div style='margin-top:0px'></div>** Overseers Gaze: ** Add +3 to passive perception.

#### Virgo Prohibition<div style='margin-top:0px'></div>

The Virgo Prohibition are designed to test, probe for weakness of anykind. They are unrelenting and don't care about their losses, only yours.
<div style='margin-top:0px'></div>** Developed  Mind: ** You gain proficency in Insight. 
<div style='margin-top:0px'></div>** Onslaught: ** Your movement speed is now 45. 
#### Sol Divisive <div style='margin-top:0px'></div>

The Sol Divisive are highly religous, they worship some form of higher power, one that transends their own. 
<div style='margin-top:0px'></div>** Fanatical: ** You gain proficency in Religion. 
<div style='margin-top:0px'></div>** transcendental Power: ** +1 to all Saving throws. 

<div style='margin-top:10px'></div>
### Vex Creation
<div style='margin-top:0px'></div>

Vex do everything with a purpose. When Vex are 'born' they are designed into differnent units for specifc purposes and help to achieve their goal. Some Vex are designed unique units to fullfil a much larger role, what that role is, is unknown. You may choose four aspects of your creation.

##### Enchanced Optics & Sensors
You have much improved vision and have sensors in your metal horns that make it much easier to attack from long range. This is often given to Assassin or ranged units.

You have proficiency with all ranged weapons and can add 1d4 to your attack rolls when using ranged weapons.

##### Stasis Repair
Some Vex, mainly the weaker ones, are outfitted with self repair modules that allow them to repair any major wounds inflicted upon them in combat. 

When you first become unconcious in combat you instead enter a stasis mode, in which you're invulnerable to all damage for one turn and you heal for 15% of your total health.(can only happen once per fight)

##### Pneumatic Legs
Many, much larger vex have this to help them control their movement.

Your legs fill with compressed air that allow you fall 10ft without suffering damage.

You can jump 10ft higher and futher

\page 
##### Gyro Stabalisers
This is used in fast moving Vex to keep them from falling over so easily.

You have been outfitted with stabilisers and are therefore much harder to knockdown. It takes twice as much effort to knock you down.

##### Sentinel Chasis
Some Vex are made as guards, their sole purpose is to keep a watchful eye...or two over everthing.

Your passive perception is the same as your perception at all times. Your passive perception can never be under 14

##### Intergrating tinkers tools
Some Vex are needed as workers, rather than war machines.

You have a set of tinkers tools built into your wrists, they cannot be removed. If you're searched they require DC18 perception check to find. 

They can be used to perform very specific tasks; they can perform medicine checks on constructs, and repair small amounts of damage too 1d4's worth.

##### Heavy Chasis
Larger Vex, such as Minotaurs, are often fitted with heavy chasis for moving heavy objects. There are improved hydraulics in your limbs that aid with this.

You can carry weight is increased by 100lbs and you have advantage on strength checks.

##### Defensive Matrix 
Vex guards are given improved defensive capabilities so they can stand ground for longer and imposing foes. However using it costs a lot of power and is therefore limited in its use.

You can use the **Shield** spell twice per short rest.

</pre></code></details>

**Comment by calculuschild** [comment]
I see no issues using the code you posted. Could you maybe provide the share link to your document and a more detailed explanation of what you mean by "screws up the formatting?"

**Comment by AngusMurray** [comment]
http://homebrewery.naturalcrit.com/share/r1MJD5cTZ  Is that it?  A more detailed explanation: So the document is fine, everything looks as it should do but as soon as i save it half of the document isn't shown and only the last page is actually visible.

**Comment by Sansd20** [comment]
May I ask what’s up with all the div containers?

**Comment by calculuschild** [comment]
I know at one point we found that placing divs in the same line with
headers (#) caused the markdown to not properly generate the html. Try
shifting your divs to be on their own lines and see if that makes any
difference.

**Comment by AngusMurray** [comment]
> placing divs in the same line with
headers (#) caused the markdown to not properly generate the html.

That was total it. Thanks!

**Comment by calculuschild** [comment]
See #657.

**Comment by ericscheid** [comment]
Everything on the line following a `#` heading marker is consumed and used as a header. The markdown renderer doesn't treat the appearance of an opening `<div ...>` element as ending the heading. This is apparent when you inspect the code and see the text of the html elements included into the heading id, like `<h2 id="heading-text-div-class-wide">...</h2>`. The opening `div` gets wrapped by the heading, but the closing `</div>` appears where specified later.

The rendered html is thus something like this:
```
<h2 id="heading-text-div-class-wide">Heading Text<div class='wide'></h2>
Some text that was meant to be inside the wide-div but now isn't.
</div>
```
But the browser, seeing a case of broken html i.e. `<h2>text<div></h2>text</div>` .. attempts to rectify it by (a) closing the  unclosed element, and (b) ignoring the unmatched closing tag, and so you get this:
```
<h2 id="heading-text-div-class-wide">Heading Text<div class='wide'></div></h2>
Some text that was meant to be inside the wide-div but now isn't.
```
Don't put anything on the heading line that isn't meant to be part of that heading.

----

This brewcode now works and isn't getting mangled.
```
## heading here
<div class='foo'>
Everyone be foo fighting
</div>
```
