### ISSUE TITLE
Not saving on Homebrewery

### ISSUE THREAD

**Issue by Martin-conDoin** [stolksdorf/homebrewery#531]
My Homebrewery file won't save.

### Additional Details

**Share Link** : [http://homebrewery.naturalcrit.com/share/By7CiG70pW](url)

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
For now, you can at least copy the text and save it onto your computer.

Whenever there is some issue with saving, it is almost always invalid HTML. The code you typed might not even be bad, but the way the website interprets the code might get confused. For instance, I see you have a header (##) literally on the same line as a (\page). This seems like something that would cause issues.

**Comment by Martin-conDoin** [comment]
@calculuschild it still won't save after i finished after i fixed the error

**Comment by Sansd20** [comment]
I am unable to see the brew. i go to http://homebrewery.naturalcrit.com/share/SyWNjV8pZ and get "Can't get that"

**Comment by Martin-conDoin** [comment]
I fixed the issues, thanks for the help everyone.
