### ISSUE TITLE
I came back to my file and a page of info can't be seen.

### ISSUE THREAD

**Issue by Snow566** [stolksdorf/homebrewery#533]
I see the beginning of the rest of the words way off to the right but when I try to fix any of the formatting it completely disappears and I can't get it to reappear. I made a new file and plugged the exact same code in and it showed up correctly, then the second I hit save it got rid of everything but the first page.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HkYGN-0a-

**Comment by DoctorDan1986** [comment]
You have an erroneous Table of Contents class on line 8, and a corresponding bad </div> on line 133.  Remove both of these lines, and your problem should resolve quite nicely.

**Comment by Snow566** [comment]
Thank you!
