### ISSUE TITLE
Can askii or html number codes be used to insert special symbols?

### ISSUE THREAD

**Issue by Gadget2020** [stolksdorf/homebrewery#537]
Specifically I'm looking for 1/4  ( `&#188;` or `&frac14;` )

**Comment by Sansd20** [comment]
I don’t know how it works on Mac, but if you go to Character Map in Windows, select it there, then copy and paste.

**Comment by HeruAsatru** [comment]
You can use html number codes to add special symbols. You could have found that out just by trying it.

But be warned, there might be symbols that are not included in the homebrewery fonts and will not look right.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for many months and it is assumed the problem was solved.

@Gadget2020  If you are still experiencing this issue, feel free to reopen and provide information.
