### ISSUE TITLE
Half Tables breaking?

### ISSUE THREAD

**Issue by LordShinryu** [stolksdorf/homebrewery#540]
Not sure why this is happening. The half tables break upon saving as a pdf. Perhaps the tables are formatted incorrectly, but I have no idea. This is the first time I'm using tables in this homebrew.

http://homebrewery.naturalcrit.com/share/S1SFOfZGiZ

**Comment by Moi-Brisingr** [comment]
Ok I went through this and fixed your formating. There were a lot of <br> to remove. I only kept them where they would keep the design closer to the original.  I would advise you to use them less.
Replaced "<li></li>" with "- ".
Put blank lines between divs and text, it helps a lot.

You can just copy the source code from this:
http://homebrewery.naturalcrit.com/share/BkBQJjKvAZ

**Comment by LordShinryu** [comment]
Thanks for the help!...  But the half tables keep on breaking when I'm trying to print/save as PDF. The headers overlap with the actual table, and I have no idea why. I even copy/pasted your fixed source code.

Screenshot: https://imgur.com/aqzyGxS

**Comment by LordShinryu** [comment]
I'm using the same source code you provided.

**Comment by Moi-Brisingr** [comment]
Well I found a closing style tag in front of the table of content and removed it from the version I gave you but that didn't solve the problem yet.

**Comment by Moi-Brisingr** [comment]
Alright I have found the problem and fixed it. Just use the link from the first post. 
... The problem was the lack of blank lines between the pagenumber and footnote divs on every page.
