### ISSUE TITLE
Previous Saves

### ISSUE THREAD

**Issue by HawaiianCoconut** [stolksdorf/homebrewery#545]
Is there any way I can return to previous saves because I accidentally deleted everything and when I tried to reset I lost the past 5 hours of work I just did. Please if anyone can help me as soon as possible it would be much appreciated

**Comment by Rhaenon** [comment]
If you close the tab and reopen it using ctrl+shift+T it loads up an older version, perhaps you can try that?

**Comment by calculuschild** [comment]
Duplicate of #654
