### ISSUE TITLE
Can't view my brews.

### ISSUE THREAD

**Issue by SorcusMasterOfDungeons** [stolksdorf/homebrewery#547]
So, I cannot view my created brews, when I click my name it just brings me back to the home screen. The link it brings me to is
http://homebrewery.naturalcrit.com/user/Sorcus,%20The%20Dungeon%20Master

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Moi-Brisingr** [comment]
Do you actually have a comma in your name? If you do this might work:
http://homebrewery.naturalcrit.com/user/Sorcus%2C%20The%20Dungeon%20Master
if it doesn't you may need to make a new account.

**Comment by SorcusMasterOfDungeons** [comment]
That worked, thank you, there is actually a comma in my name.

There's a considerable difference between courage and reckless stupidity. -
The Third Doctor.
