### ISSUE TITLE
Lost my save

### ISSUE THREAD

**Issue by Applesauce92** [stolksdorf/homebrewery#553]
Hello! I recently started a new Brew called 'A Child's World'. I made sure to save it, but apparently I wasn't logged in at the time, and now I can't find it anymore. Is there a way to get it back? I'm sure I did hit the save button. 

Love,

Applesauce92

**Comment by Moi-Brisingr** [comment]
Well you can check your browser history and try to find the edit link to your brew.

**Comment by Applesauce92** [comment]
Smart! Thanks, it worked!
