### ISSUE TITLE
Brew not rendering

### ISSUE THREAD

**Issue by arwelbrown** [stolksdorf/homebrewery#559]
Hi all,

I tried to put a spell table into my brew, and bang all of a sudden it vanished on the render side. Code is all still fine, and the spell list has now been put in, but the brew still won't render.

Thanks.

Link is here: http://homebrewery.naturalcrit.com/edit/B1fzu3qllf

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by mbergfors** [comment]
Yeah, I'm consistently having this same problem. If I cut and paste carefully into a new brew, it'll work for a while, but eventually breaks again and stops rendering. Prints to PDF just fine; seems to be only the render.

**Comment by calculuschild** [comment]
For both of you, this means you have some HTML error in your brew, which causes the renderer to crash. If you could provide your *share* links (not the edit link, this adds any viewer as an editor who is then free to delete your brews @arwelbrown) somebody can help you find the invalid code.

**Comment by Sansd20** [comment]
@arwelbrown, if you could post the markdown code, for when I go to that link, i get "Can't get that" message. I will try to take a look at it and see what I can come up with.

@mbergfors, if you could post either the code, or the the share link, I can do the same for you.
