### ISSUE TITLE
Save Issues

### ISSUE THREAD

**Issue by Oddish-Flumph** [stolksdorf/homebrewery#563]
I have a brew, of which I have imputed new content multiple times, but it rarely saves the changes made, reverting to the old version. I don't know why it does this, but i'd like it to be addressed.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Sansd20** [comment]
By chance, do you have the brew open in  another browser window/tab when this happens?

**Comment by Oddish-Flumph** [comment]
I have my profile with all my brews open, but no duplicates

**Comment by calculuschild** [comment]
Duplicate of #654
