### ISSUE TITLE
Add a space in the middle of a line of text?

### ISSUE THREAD

**Issue by gowronatemybaby7** [stolksdorf/homebrewery#565]
Hello! Pardon my ignorance, but is there a way to add a space in the middle of a line of text? I'm trying to format some text around an image and the image cuts through the line of text, so I'd just like to move some of the words over slightly to the right.

I want it to look like this:

words words (Picture of a sword) words words.

Obviously, just hitting space a bunch of times doesn't do it.

**Comment by calculuschild** [comment]
You  can type in "&nbsp" and it will give you a space. or "&emsp" for a
larger space.

**Comment by Sansd20** [comment]
@calculuschild I knew of `&nbsp` but not `&emsp`. Thank you.
