### ISSUE TITLE
Spell List Missing

### ISSUE THREAD

**Issue by AZDfox** [stolksdorf/homebrewery#567]
### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/B1vibnUiW

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

</pre></code></details>

**Comment by DoctorDan1986** [comment]
I went through your code and everything you've written appears.  What 'spell list' are you supposed to be missing?

**Comment by AZDfox** [comment]
Previously, when I had looked at it, there was a list of spells the Abhorsen class knew (as mentioned under the Spellcasting header).

**Comment by DoctorDan1986** [comment]
Looking at your code, I can see where it SHOULD be, but there's no code for the actual table.

**Comment by AZDfox** [comment]
Exactly! Something appears to have happened to it. Which is a problem because I need the spells for my character.

**Comment by DoctorDan1986** [comment]
Well, unless you have a backup of it somewhere, I'm afraid that you're going to have to re-create it.

**Comment by AZDfox** [comment]
Yeah, that's what I was afraid of. :(
