### ISSUE TITLE
Can't sign up for natural crit

### ISSUE THREAD

**Issue by Lokilyc2099** [stolksdorf/homebrewery#578]
it wont let me sign up for natural crit so i can save my homebrew
it just stays there with the idle waiting circle beside the username block and will not recognize any username so that i may sign up. i am very interested in using this for my custom dnd campaign but i cannot due to this issue please help me with this i would be most appreciative

**Comment by stolksdorf** [comment]
Sorry your having some issues. My login server had some problems over the last few days and it looks like the issue has passed. You also don't need an account to create or share brews.
