### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by Reuwriting** [stolksdorf/homebrewery#580]
I have attempted to log in to the site with a new computer, as my old one has died. Google Chrome saved the passwords so i know it's correct, but it will not let me in.

I'm no coder, so any help would be... helpful.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Sorry, I have not implemented any password recovery options. If you have any of your brew's edit links, you can create a new account and edit them to link those brews with your new account.

**Comment by Reuwriting** [comment]
Wow... that was a lot of work... and it's gone. if you can find the file "the Planet of Thear" i'd appreciate the help otherwise 20+ pages no longer exist.

**Comment by Reuwriting** [comment]
Disregard, i found the login info on the hard drive of my dead machine. Thank God. I have backed up the information.

**Comment by stolksdorf** [comment]
Don't worry, it's not lost. If you have the share link I can look it up for you. Otherwise I'll have to do a query on the DB later.

**Comment by stolksdorf** [comment]
Okay good to hear. It's good to back things up, but also simply bookmarking the edit links is enough as well.

**Comment by DataAndDeadlifts** [comment]
Having problems logging in as well. Can't get into my brews. Login appears to work but nothing changes on the page and heading to the naturalcrit site on homebrewery doesn't register that I've logged in.

**Comment by calculuschild** [comment]
This is a known issue. The Homebrewery relies on the Naturalcrit website for its login, and the issue resides on that repository which most of us do not have access to. We have contacted the developer (@stolksdorf ) so he can fix it.
