### ISSUE TITLE
Class table brakes when exporting to pdf

### ISSUE THREAD

**Issue by Danishnerd** [stolksdorf/homebrewery#582]
As titles says, when i export my brew to pdf, some of the text moves in over the other.

![image](https://user-images.githubusercontent.com/34663628/34130266-7cca38ac-e447-11e7-91a2-98794e837024.png)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Sansd20** [comment]
This, I believe, is a known issue. I have seen it reported before.

**Comment by calculuschild** [comment]
Try looking at the issue [here](
https://github.com/stolksdorf/homebrewery/issues/318). There is a solution
at the bottom.

**Comment by Danishnerd** [comment]
Thanks, solved my problem :)

**Comment by calculuschild** [comment]
Duplicate of #318
