### ISSUE TITLE
Class Features Glitch

### ISSUE THREAD

**Issue by StringsNeverCry** [stolksdorf/homebrewery#584]
Hey, So whenever I click on the class features option in the editor, if it is not the very first thing that I click it basically infinitely repeats everything else that I did before I tried to set up the class features. I've tried to just type it all in manually in the past, but in the end it just doesn't line up right. So I posted the link to the brew. Hopefully this is something that can be fixed in the future. 

http://homebrewery.naturalcrit.com/share/B1qXlZPGM

**Comment by gsheppard** [comment]
Also experiencing this.

**Comment by calculuschild** [comment]
Duplicate of #413 . A fix is on the way.
