### ISSUE TITLE
PDF export issue

### ISSUE THREAD

**Issue by Falquano** [stolksdorf/homebrewery#589]
Hi.
When I try to export to pdf, the said pdf has problems. 
here is the original homebrew : http://homebrewery.naturalcrit.com/share/rybaTbpkQG

For now I have only tried with Firefox.

The PDFs I got only show one column...

What can I do?
I'll try using chrome tomorrow.

**Comment by Falquano** [comment]
Oh, while I'm here, how can I modify the name of the brew?

**Comment by Moi-Brisingr** [comment]
The homebrewery is made to work with chrome, so you should use that for the best results.

You can edit the title by clicking the "Edit Brew Metadata" button on the right of the gray bar above the souce code.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for several months and it is assumed the problem was solved.

@Falquano  If you are still experiencing this issue, feel free to reopen and provide information.
