### ISSUE TITLE
My Homebrewery project is gone

### ISSUE THREAD

**Issue by tinchopunkeado** [stolksdorf/homebrewery#590]
I Have been working since last month on a project, which suddenly dissapeared from my list of projects!
there's another project which i have since last year which works perfectly fine

**Comment by Moi-Brisingr** [comment]
You should be able to find the edit link for your missing brew in your browser history.

**Comment by tinchopunkeado** [comment]
Thank you!

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
