### ISSUE TITLE
No such property: column-break-inside

### ISSUE THREAD

**Issue by ericscheid** [stolksdorf/homebrewery#595]
In bundle.css, there is a rule of 

    column-break-inside: avoid;

That should be simply `break-inside: avoid`. 

The `-webkit-column-break-inside` is still valid though, and chrome's support for that has probably hidden this bug.

**Comment by ericscheid** [comment]
So .. four lines inside `phb.style.less` ... can someone walk me thru my first pull request? 

Where do I even start?

**Comment by calculuschild** [comment]
Gonna close this since the PR has been merged.
