### ISSUE TITLE
Problem pdf rendering when mixing column breaks with wide tables

### ISSUE THREAD

**Issue by ripread** [stolksdorf/homebrewery#597]
### Additional Details

For some reason Homebrew won't display the table when it tries to render as a pdf. If I remove the backticks it renders correctly but then my columns aren't aligned like I want them to be. 

http://homebrewery.naturalcrit.com/share/Sk4HEqtXf

**Comment by Sansd20** [comment]
Is that what you are looking for?

*note: don't paste the edit link, use the share link*

**Comment by ripread** [comment]
I don't want the indent because the second column doesn't start a new paragraph. I guess it works though

**Comment by Sansd20** [comment]
Now take a look.

**Comment by ripread** [comment]
Perfect! You're amazing

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
