### ISSUE TITLE
Glitched printing tables

### ISSUE THREAD

**Issue by vid12348** [stolksdorf/homebrewery#602]
When u attempt to save my brew as a pdf, all of the top layers of some of the tables are glitched out, causing them to repeat over the whole table.

**Share Link** : http://homebrewery.naturalcrit.com/share/BJ-9_XFixG

**Comment by esto713** [comment]
table rendering glitch seems to be related to usage of <div class='wide'> tags

[Share Link](http://homebrewery.naturalcrit.com/share/r1bqRAjTVz)

**Comment by vid12348** [comment]
Can you tell me how to fix this issue, im kinda new to this.

**Comment by esto713** [comment]
I wish I knew. I just joined github two days ago.

**Comment by calculuschild** [comment]
This is a known issue. Unfortunately development on this site has stalled for a while now, so a permanent fix has not been added yet, even though the solution has been reported several times.

You can solve this yourself by adding a bit of CSS code to your brew:

<pre><code>
.phb table thead { display: table-row-group;}
</code></pre>

**Comment by vid12348** [comment]
How do I use this code??? (Im a complete nub)

**Comment by esto713** [comment]
nest the code between 

> <style> </style>
tags

**Comment by vid12348** [comment]
<style>

display: table-row-group;

</style>

(Like that??
