### ISSUE TITLE
Brew will not save new changes unless the page is reloaded

### ISSUE THREAD

**Issue by Singador** [stolksdorf/homebrewery#603]
Hi everyone.

After testing a saving issue I had for a while now I realised that my brews would not save new changes unless I reloaded the page after it had save. If I closed the browser and reopened the page without have refreshed the homebrewery page prior, all the changes would have disappeared.

This issue started manifesting itself a couple months ago and I still have not been able to find out why I have this issue. I run on Win10, edit my brews on Chrome and have not downloaded any sort of new extensions around the period when the issues started happening.

Does anyone have any idea on how to fix this?

Here's the source link if it's of any help: http://homebrewery.naturalcrit.com/source/H1-5DO_-- Apologies for the messy formatting, I may have fudged something with the code but if so I have no idea where.

**MAYBE SOLVED:** The reason I had the problem was because when I opened chrome it restored my previous session and just loaded the page it had stored in the cache, therefore overriding whatever I had saved in the homebrewery prior to closing the browser. I solved the issue by having chrome start a new session whenever I open the browser instead of restoring my previous session. Let me know if it works!

**Comment by 182736459** [comment]
I too am experiencing this issue and would really like a solution

**Comment by Singador** [comment]
Hello! I have managed to solve the issue, which I don't think is actually related to the homebrewery, but to chrome and firefox as I've been able to replicate the issue and dispel it on both browsers.

I realised with the help of a friend that the brew had saved correctly, but that by opening when previous session with all its tabs active when I turned on my browser, it loaded the version that was saved in the cache. The homebrewery had saved my document just fine, but the browser had loaded what it last saved in the cache, and therefore loaded that version over the homebrewery version.

So the solution is to make your browser open on your home page with no trace of your previous session. On chrome that parameter is at the very bottom of the settings page prior to opening the advanced settings, let me know if it helps

**Comment by calculuschild** [comment]
This seems like something that maybe the Homebrewery could try to handle better, because I've noticed it too. When refreshing, it might make more sense to have it load from the saved data on the server and skip over any cached versions.

**Comment by calculuschild** [comment]
This might be another clue to #654 .
