### ISSUE TITLE
Saving to PDF causes columns to overlap

### ISSUE THREAD

**Issue by cjdudley1** [stolksdorf/homebrewery#604]
Hi,

I'm having issues saving a brew to PDF, and it's not the first time I've come across this. Namely, I have a page (first page linked) with two columns. when I try to save the file as a PDF, they both overlap. This can be seen [here](https://imgur.com/a/hmjF5).

I'd appreciate a solution or workaround, or some clarification on how to avoid this issue. Many thanks!

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/ByTgdAVRZ

**Comment by Christian-Eichhorn** [comment]
It works fine for me. Did you try to pin point the problem? Like removing the lines:
`<img src='https://i.pinimg.com/564x/22/0f/1b/220f1ba30ae7dc96e152ce74fc7896d9.jpg'
  style='width:350px; position:absolute; top:550px; right:40px;mix-blend-mode:darken' />`
and/or
`<span style="opacity:0">ewf</span>`
`<div style='margin-top:1px'></div>`

Whats the point of the last two anyways?

**Comment by cjdudley1** [comment]
Hi,

I made some changes, and moved the image to the bottom of the right hand column which seemed to fix it. In general I've found moving text to the right hand column and moving it down to be buggy; a column break followed by vertical spacing doesn't always play ball.

Thanks for the input
