### ISSUE TITLE
Get PDF results in some weird issues

### ISSUE THREAD

**Issue by Rajarotert1** [stolksdorf/homebrewery#609]
I've been trying to get the pdf of a homebrew I made, but when i go to print to pdf the headline of each table prints on every line of said table (see link). Now ive tried getting the pdf on Firefox and edge as well, these platforms have their own issues, firefox makes it so that tables dont fit lengthwise and edge only prints the first top left corner of a page. Of course i know homebrewery was made for chrome, but it was worth a shot!

[https://imgur.com/sI2GHPc](url)

**Comment by calculuschild** [comment]
See #602

**Comment by Rajarotert1** [comment]
Works for me! Thank you
