### ISSUE TITLE
Two column table and spell list style are breaking

### ISSUE THREAD

**Issue by Khaio** [stolksdorf/homebrewery#616]
I'm trying to create a wide table and a wide spelllist and both are only expanding to a single column, and therefore, breaking the style as can be seem at the bottom of this page 

http://homebrewery.naturalcrit.com/share/HkW-2Eo_LM

Code preview:
<pre>
<div class='spellList'>
##### Cantrips (0 Level) 
- Magical Enchantment of Arrogance
- Dominate Ramen Giant
- Cursed Ritual of Bad Hair
- Sorcerous Dandruff Globe
- Irritate Peanut Butter Fairy
- Dark Chant of the Dentists
- Heavenly Transfiguration of the Cream Devil
- Cure Baldness
- Invoke Complaining
- Illusionary Transfiguration of the Babysitter 

##### 1st Level 
- Animal Friendship
- Beast Bond
- Create or Destroy Water
- Cure Wounds
- Detect Magic
- Detect Poison and Disease
- Faerie Fire
- Goodberry
- Healing Word
- Jump
- Purify Food and Drink
- Speak with Animals 

##### 2nd Level 
- Alter Self
- Animal Messenger
- Barkskin
- Beast sense
- Darkvision
- Enhance Ability
- Find Traps
- Lesser Restoration
- Locate Animals or Plants
- Pass without a Trace
- Protection from Poison

##### 3rd Level 
- Dispel Magic
- Feign Death
- Meld into Stone
- Plant Growth
- Protection from Spells
- Water Breathing
- Water Walk

##### 4th Level 
- Confusion
- Dominate Beast
- Freedom of Movement
- Locate Creature
- Polymorph
- Conjure Woodland Beings

##### 5th Level 
- Antilife Shell
- Awaken
- Commune with nature
- Greater Restoration
- Insect Plague
- Mass Cure Wounds
- Raise Dead
- Tree Stride
</div>
</pre>
<pre>
<div class='classTable wide'>
##### The Beastmaster
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | Spell Slots | Slot Level | Evolution Points | Familiar Intelligence |
|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 1st | +2 | Wild Empathy, Animal Companion, Bonded Souls, Animal Familiar | 2 | 2 | 2 | 1 | - | 6 |
| 2nd | +2 | Evolution Points, Spellcasting, Guard Dog | 2 | 3 | 2 | 1 | 3 | 6 |
| 3rd | +2 | Path Archetype Feature | 2 | 4 | 2 | 2 | 6 | 7 |
| 4th | +2 | Ability Score Improvement, Hermetic Geography | 3 | 5 | 4 | 2 | 9 | 7 |
| 5th | +3 | - | 3 | 6 | 4 | 3 | 12 | 8 |
| 6th | +3 | Path Archetype Feature, Disaster Sense | 3 | 7 | 4 | 3 | 15 | 8 |
| 7th | +3 | - | 3 | 8 | 4 | 4 | 17 | 9 |
| 8th | +3 | Ability Score Improvement | 3 | 9 | 4 | 4 | 20 | 9 |
| 9th | +4 | Undying Devotion | 3 | 10 | 4 | 5 | 22 | 10 |
| 10th | +4 | Path Archetype Feature | 4 | 10 | 4 | 5 | 25 | 10 |
| 11th | +4 | Clever Creatures | 4 | 11 | 4 | 5 | 27 | 11 |
| 12th | +4 | Ability Score Improvement | 4 | 11 | 4 | 5 | 30 | 11 |
| 13th | +5 | Guard Dog (2) | 4 | 12 | 4 | 5 | 32 | 12 |
| 14th | +5 | Master's Presence | 4 | 12 | 4 | 5 | 35 | 12 |
| 15th | +5 | Path Archetype Feature | 4 | 13 | 4 | 5 | 37 | 13 |
| 16th | +5 | Ability Score Improvement | 4 | 13 | 4 | 5 | 40 | 13 |
| 17th | +6 | Retaliatory Strike | 4 | 14 | 4 | 5 | 42 | 14 |
| 18th | +6 | Call of the Wild | 4 | 14 | 4 | 5 | 45 | 14 |
| 19th | +6 | Ability Score Improvement | 4 | 15 | 4 | 5 | 47 | 15 |
| 20th | +6 | Path Archetype Feature | 4 | 15 | 4 | 5 | 50 | 15 |
</div>
</pre>

**Comment by fmkuhn** [comment]
I'm encountering the same issue in Firefox, everything 'wide' I'm adding is just one column wide. It's working in Chrome for me

**Comment by DracoDruid** [comment]
I can confirm. Homebrewery has several problems with Firefox. Wide content is not displayed correctly and print to pdf is not working correctly

**Comment by calculuschild** [comment]
Unfortunately the homeberewery is only supported on Chrome. There are some formatting functions that don't work as cleanly in the other browsers and for now that is not a priority.

**Comment by calculuschild** [comment]
if this issue still occurs on Chrome, however, we can look into it and see what's wrong.

**Comment by fmkuhn** [comment]
Ah, I wasn't aware, that it's only supported on Chrome. Thanks for the information, Chrome is working great for me :-)

**Comment by calculuschild** [comment]
Great! Glad it is working for you. I will close this issue then
