### ISSUE TITLE
Add "Descriptive text Box"

### ISSUE THREAD

**Issue by TheRedMandrake** [stolksdorf/homebrewery#63]
First of all, thank you for your amazing work !

Would it be possible to add a template for the "descriptive text box" found in the DnD 5e published adventures ? That would be really useful for homebrew adventures.
![example](https://cloud.githubusercontent.com/assets/759971/13715683/bacb183e-e7d6-11e5-936a-5b7580f27b80.PNG)

Thanks again !

**Comment by stolksdorf** [comment]
What syntax do you suggest should be used to represent this?

**Comment by kevetoile** [comment]
I suggest begin the paragraph with "<<"

**Comment by Tsurumah** [comment]
I would dearly love this, too!

**Comment by stolksdorf** [comment]
Since markdown prases into raw HTML, I'm kinda limited to what elements I can use. Most of the base ones (tables, blockquotes, etc.) have been used by other features. This is why it's not easy to add things like full-width tables yet.

One solution I wanted to avoid is to just use HTML directly, like `<blockquote class='description'> </blockquote>`. Since this is more of niche block, I wouldn't be against doing that. What do you guys think?

**Comment by Tsurumah** [comment]
As a placeholder, I would think it'd be fine, but I'm speaking as a person with a passing familiarity with HTML and CSS (haven't done a website in over a decade, though). The documentation on Markdown syntax is fairly sparse, though, so I haven't found a full list yet to teach it to myself and am not sure what is used and what isn't used already.

It might be worthwhile to have a dropdown menu that just has a list of what syntax is used and a brief blurb about what it does, as well.

**Comment by stolksdorf** [comment]
[Markdown Syntax I use](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for future reference.

My goal with the snippets was a very simple UX for encourage exploration of how to add new things to your brew without the need for explanations or what not. I think it might be prudent to add a link to the Markdown spec though.

**Comment by calculuschild** [comment]
Is this something we might be seeing soon then?  Even if you have to resort to an HTML tag to start with?

**Comment by nadcraker** [comment]
I actually was just looking for the "read aloud" text button this morning. I'm writing a homebrew adventure and it would be really cool to have this feature. It would make the tool produce even more "authentic" looking modules than it already does.

**Comment by sirbrillig** [comment]
+1 for this! I think using `<blockquote>` would be a fine solution, although my personal vote would be for something less verbose.

Perhaps a modified markdown quote, in the same way you've used horizontal rules to modify info blocks for monster stat blocks. I'm not sure if your parser can detect the difference between horizontal rules generated by `---`, `***`, and `___` ([all legal](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#horizontal-rule)), but if so you could use one of those.

If not, what about a markdown blockquote (`>`) beginning with a double quote (`"`)? Or maybe a block following a line containing nothing but a double quote? Just brainstorming as I haven't looked at the code yet. 😄

**Comment by stolksdorf** [comment]
Added in v2.2.7
