### ISSUE TITLE
The class table only covers half the screen

### ISSUE THREAD

**Issue by Splintr1322** [stolksdorf/homebrewery#630]
so, i love this so far, it is my first time using it, and its amazing, but the class table is only covering half the screen, not the whole thing like its supposed to. is there a way i can fix this?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Looks like you might have forgotten to paste your share link so we can see what you mean. Could you go back and edit your post to include that? Thanks!

**Comment by grinningwolf** [comment]
I'm having the same issue.

http://homebrewery.naturalcrit.com/share/Hk-Y5XqFkX

I believe this is an issue with Firefox. Seems like it might not support "-moz-column-span :all" used in  ".phb .wide". Looks like we'll need to grab a different browser for full functionality unfortunately.

**Comment by ericscheid** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=616436

Firefox does not support column-span or -prefix variants.

**Comment by grinningwolf** [comment]
Yep grabbed Opera and it's working perfectly.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Splintr1322
