### ISSUE TITLE
Homebrew formatting completely broke upon save. No idea why. :/

### ISSUE THREAD

**Issue by Boomboxcrab** [stolksdorf/homebrewery#632]
Hi everyone, Everything was fine with this homebrew earlier, I was making a more balanced arcane puppeteer for a player in one of my sessions, however, for some reason this evening the formatting has gone absolutely crazy! I have never had this issue before, all the code was working fine earlier, I haven't changed anything since my last save... In a new file when I paste the code it looks fine, but as soon as I save the brew it breaks completely.

### Additional Details

**Share Link** : https://homebrewery.naturalcrit.com/share/ByiGI0Jtz

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div style='margin-top:75px'></div>
<div style="text-align: center"/span>
# <span style="color:white"><font size="+6">**THE ARCANE PUPPETEER**</font></span></div>

<img 
  src='https://cdna.artstation.com/p/assets/images/images/001/144/544/large/yu-han-chen-30avdl.jpg?1443927238' 
  style='position:absolute; top:-15px; right:-15px; width:985px;filter:hue-rotate(10deg);filter:brightness(90%)' />

<img
src='http://i.imgur.com/YRAeIcj.png' style='position:absolute;left:320px;top:10px;width:20%'/>

<img
src='http://i.imgur.com/SGYtcP2.png' style='position:absolute;top:150px;left:85px;width:80%'/>

<img
src='http://i.imgur.com/UNR8ilF.png' style='position:absolute;bottom:180px;left:0px;width:50%'/>

\page

<div style='margin-top:1000px'></div>

<img 
  src='https://i.imgur.com/vxIkVnur.png' 
  style='position:absolute;top:0px;right:0px;width:820px;mix-blend-mode:darken' />

<div style='margin-top:30px'></div>

# Arcane Puppeteer<br>
Arcane puppeteers are gifted arcane users who can choose to channel their magical energy through their creations, another being, or  by channeling the magic themselves. Some Arcane practitioners are afraid of direct confrontation, leading to the creation and use of puppets that can be manipulated with ease on the battlefield, all the while leaving the controller relatively safe. These puppets can be used in a multitude of different ways, each benefiting from their own set of skills depending on the crafters needs and preferences.<div style='margin-top:5px'></div>

The marionette gracefully weaves through corpses litterd across the battlefield. The sound of turning gears emnates from its wooden carapace, its large white eyes flick and flitter between the boddies, a childlike smile seems to cackle as it moves, its strings attached to the fingers of its human master. Swords cut through flesh and poisoned darts find target. All his enemies laying on the ground, the human ends his performance with a satisfactory smirk.<div style='margin-top:5px'></div>

The legs of the multi-coloured puppet tap rhithmicly in front of an audience while he juggles four brightly coloured balls in the air. As he catches the balls one by one in his mouth, confetti shoots out of its hand. As a cheerful Halfling appears behind the curtain, the onlookers applaud the magnificent performance.<div style='margin-top:5px'></div>

Whatever their goals and affairs, all puppeteers share their devotion to their puppet. Wether they perform tricks before a king, fight in battle alongside others, or play their puppet just to entertain theirselfs, their puppet is an extension of their body. With a flick of their fingers, power and play surge through the strings and puppet to make steady steps to their goal.<div style='margin-top:5px'></div>

Enchanters, Artificers & Tinkerers, the makers of magic-infused obects, are defined by their meticulous nature. Like wizards, they see magic as a complex system waiting to be decoded and controlled through a combination of thorough study and investigation. Arcane Puppeteers on the other hand, although meticulous and thorough in their craft, they are far more experimental when it comes to magical practice, viewing it as more of a performance and showcase, focusing on the bizare, the spectacular and the beautiful, whether that be on stage, or on the battlefield.

<div class='pageNumber'>1</div>
<div class='footnote'>ARCANE PUPPETEER</div>

\page

### Master Craftsmen
The Puppet is everything to the Puppeteer. They spend hours crafting one to their liking and can be crafted as one sees fit. Arcane Puppeteers spend countless hours tinkering and altering their creations, whether these are war-machines used for slaughter or dancing jesters for the purpose of entertainment, a master craftsman is always looking to perfect their art.

### Swift Strings
There is a special bond between a crafter and their creation, and even more sore between a puppeteer and the their puppet. A puppeteers strings symbolize a strict union, they are the veins and life blood of the relationship between the Arcane Puppeteer and their puppet. By forming this union through magical strings, the puppeteer can transger magical essence used to manipulate and sustain the puppet.

### Rivals
The puppeteers’ drive to create, craft and expand their arcane knowledge stems from an intense desire to uncover new magical discoveries. A puppeteer who does not understand a mechanism, trap or arcane anomaly will seek to investigate, understand and take advantage of it. Just like Performers, almost every Puppeteer has at least one rival, someone whom they seek to outdo them at every turn. By the same token, puppeteers are often quite closed off and secretive with their discoveries, just as no magician would reveal the secret behind their tricks, no sane minded puppeteer would reveal the mechanisms or arcane encoding that make their<br> puppets special.

<img 
  src='https://i.imgur.com/IsYLkLJ.png' 
  style='position:absolute;top:405px;right:0px;width:500px;mix-blend-mode:darken' />
  
<img 
  src='https://i.imgur.com/h5HdqeC.png' 
  style='position:absolute; top:500px; right:340px; width:500px;filter:brightness(100%);transform:scaleX(-1);transform:rotate(210deg)' />  

## Creating an Arcane Puppeteer
<div style='margin-top:10px'></div>

#### Quick Build<div style='margin-top:10px'></div>
You can make an Arcane Puppeteer quickly by<br> following these suggestions. First, Dexterity<br> should be your highest ability score, followed<br> by Charisma. Secondly, choose the artisan<br> background. You can also pick quirks, personality<br> traits, ideals, bonds and flaws from the premade<br> rollable tables.
<div style='margin-top:0px'></div>

## 5e Class Features<div style='margin-top:10px'></div>
As a Arcane Puppeteer you gain the following<br> class features. Your puppets features depend on<br> the type of puppet and craft school you choose.

#### Hit Points
<br>
**Hit Dice:** 1d8 per Arcane Puppeteer level.<br>
**Hit Points at 1st Level:** 8 + Constitution modifier.<br>
**Hit Points at Higher Levels:** 1d8 (or 5) +<br> Constitution modifier per Arcane Puppeteer<br> level after 1st.<br>
<div style='margin-top:50px'></div>

#### Proficiencies<div style='margin-top:10px'></div>
**Armor:** light armor.<br>
**Weapons:** simple weapons, martial weapons.<br>
**Tools:** tinker's tools and one artisans tool of your choice.<br>
**Saving Throws:** Dexterity, Charisma<br>
**Skills:** Performance, and your choice of two from: Sleight of Hand, Acrobatics, Arcana, Deception, Stealth, or Intimidation.

#### Equipment<div style='margin-top:10px'></div>
You start with the following equipment, in addition to the equipment granted by your background:
<br>
<br>padded armor: 11AC + DEX Modifier<br>
*(a)* 2 light hammers or *(b)* a spear<br>
*(a)* a hand puppet or *(b)* a shadow puppet<br>
*(a)* Scholar's pack or *(b)* Entertainer's pack<br>
*(a)* Tinker's tools or *(b)* Thieves tools<br>
<br>
If you are using starting wealth, you have [[5d4×10gp]] in funds.<br>

<div class='pageNumber'>2</div>
<div class='footnote'>CREATING AN ARCANE PUPPETEER</div>

\page

<img 
  src='https://i.pinimg.com/originals/e6/75/39/e675390caad916885ccd7eec4eeba869.jpg' 
  style='position:absolute;top:0px;right:0px;width:820px;mix-blend-mode:darken' />

<img 
  src='https://i.imgur.com/tQjcZ5n.png' 
  style='position:absolute; top:110px; right:-200px; width:1300px' />

<div style='margin-top:800px'></div>

<div class='classTable wide'>
##### The Arcane Puppeteer
| Level | Proficiency Bonus |Spells Known| Features | 1st | 2nd | 3rd | 4th | 5th |
|:---:|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 |---| Arcane Puppet, Willing Puppet, Puppet School | — | — | — | — | — |
| 2nd | +2 |2|Spellcasting | 2 | — | — | — | — |
| 3rd | +2 |3| Puppetry Expertise | 3 | — | — | — | — |
| 4th | +2 |3| Ability Score Improvement | 3 | — | — | — | — |
| 5th | +3 |4| --- | 4 | 2 | — | — | — |
| 6th | +3 |4| Improved Control | 4 | 2 | — | — | — |
| 7th | +3 |5| Puppet School Feature | 4 | 3 | — | — | — |
| 8th | +3 |5| Ability Score Improvement | 4 | 3 | — | — | — |
| 9th | +4 |6| --- | 4 | 3 | 2 | — | — |
| 10th | +4 |6| Marionette Maestro | 4 | 3 | 2 | — | — |
| 11th | +4 |7|	Puppet School Feature | 4 | 3 | 3 | — | — |
| 12th | +4 |7| Ability Score Improvement | 4 | 3 | 3 | — | — |
| 13th | +5 |8| --- | 4 | 3 | 3 | 1 | — |
| 14th | +5 |8| Travel Trunk | 4 | 3 | 3 | 1 | — |
| 15th | +5 |9| Marionette Fusion | 4 | 3 | 3 | 2 | — |
| 16th | +5 |9| Ability Score Improvement | 4 | 3 | 3 | 2 | — |
| 17th | +6 |10| --- | 4 | 3 | 3 | 3 | 1 |
| 18th | +6 |10| Puppet School Feature | 4 | 3 | 3 | 3 | 1 |
| 19th | +6 |11| Ability Score Improvement | 4 | 3 | 3 | 3 | 2 |
| 20th | +6 |11| Powerful Performance | 4 | 3 | 3 | 3 | 2 |
</div>

<div class='pageNumber'>3</div>
<div class='footnote'>CLASS TABLE</div>

\page

## Strings<div style='margin-top:10px'></div>

At 1st level you gain access to arcane strings. These strings are threads of magical energy that tether yourself to your puppets and other creatures, but more than this, they are used to control the actions of your puppets and other creatures. Your puppet is considered an object you are holding when affected by spells.

A set of strings comprises of five arcane threads, not actual threads of rope or wire. These arcane tethers attach to each of your fingers on one hand to the limbs and head of a target puppet or creature. You must have an empty hand to use one set of strings: thus if you have two empty hands you can control two sets of strings connecting to two puppets. Strings are intangible and invisible and cannot be severed. If your puppeteer ever loses a hand or arm, they find a magical replacement that can channel and control the strings; they cannot control five strings from a stump.

At 1st level the length of your strings is 60 feet. You lose control of the subject of the strings if you are separated from it by a distance longer than the length of the strings. You can connect to, dismiss one or both sets of strings on your turn: this does not require an action. The strings also disappear if you fall unconscious.<br>

## Puppet Saving Throw<div style='margin-top:10px'></div>

Some features of your puppets require a target to make a saving throw against your puppet DC.
<div style='margin-top:-5px'></div>
**This is equal to:**
<div style="text-align: center">
8 + your Dexterity modifier + your proficiency bonus.
</div>

## Arcane Puppet<div style='margin-top:10px'></div>

You can craft an arcane marionette  using the "crafting a magic item" downtime activity (DMG p. 128). At 1st level you can craft a common marionette. If you begin play as an arcane puppeteer (but not when you multiclass into arcane puppeteer) you start with one common marionette.<br>
<br>
An arcane marionette is a small animated object with the following statistics:

* 25 HP, AC 16, Str 6, Dex 14, Con 10, Int 3, Wis 3, Cha 1, speed 30 ft.<br><br>
* Gains as much HP as you do when you level up.<br><br>
* Unlike other animated objects, it does not have blindsight, instead sharing your senses.<br><br>
* It can make a slam (melee weapon) attack that deals 1d8 + 2 bludgeoning damage, with an attack modifier equal to your Dexterity modifier + your proficiency bonus. It does not roll for initiative, take its own turn, and cannot move or take actions or reactions on its own.<br><br>
* The marionette uses your proficiency bonus, but does not share your proficiencies.<br><br>
* If the marionette falls to 0 hit points, it is destroyed.<br><br>
* It weighs 40 lbs. You can use an action to fold it up into Tiny size to be transported in a backpack, sack or basket; it takes another action to unfold it for use.<br><br>
* The Marionette is able to use items and weapons instead of its slam attack.<br><br>

#### Marionette Manipulation<div style='margin-top:10px'></div>

You control a marionette using a set of strings. While you are controlling a marionette, you can sense what it senses.

If you are in control of a marionette, you can use your action to have the the marionette take an Attack or Disengage action on your turn, or your reaction to have the marionette take a reaction. You can use your bonus action to allow the marionette to move on your turn.

#### Repairing Marionettes<div style='margin-top:10px'></div>

Marionettes that have less than their maximum hit points but greater than 0 hit points can be repaired. This can be done during a long or short rest, and requires your tinker's tools. It also requires materials worth 1 cp per hit point recovered for a common marionette, 5 cp per hit point for an uncommon marionette, 5 sp per hit point for a rare marionette, 5 gp per hit point for a very rare marionette, and 50 gp per hit point for a legendary marionette.

During a short rest, you can repair 2 hit points × your arcane puppeteer level. During a long rest you can repair all your marionettes back to their maximum hit points.

A destroyed marionette cannot be repaired, but can be salvaged for parts for building a new marionette. It provides materials equal to half its original value.

## Willing Puppet<div style='margin-top:10px'></div>

You can attach a set of strings to a willing creature within 30 feet. On that creature's turn you can use your reaction to allow the target to move and make an action, even if they are incapacitated, paralyzed or stunned. In addition, you can use your reaction to immediately stand the target up if they are knocked prone.

## Puppet School<div style='margin-top:10px'></div>

Choose a puppet school: the School of Aegis, the School of Adroitness, the School of Simulacra, or the School of Furtiveness.

Your choice of school grants you a benefit at 1st level, and again at 7th, 11th and 18th level.

## Spellcasting<div style='margin-top:10px'></div>

By the time you reach 2nd level, you have learned to cast arcane spells.

<div class='pageNumber'>4</div>
<div class='footnote'>MASTERING PUPPETRY</div>

\page

#### Spell Slots<div style='margin-top:10px'></div>

The Arcane Puppeteer table shows how many spell slots you have to cast your spells of 1st level or higher. To cast one of these arcane puppeteer spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.

#### Spells Known of 1st Level and Higher<div style='margin-top:10px'></div>

You know two 1st-level spells of your choice from the arcane puppeteer spell list. The Spells Known column of the Arcane Puppeteer table shows when you learn more arcane puppeteer spells of your choice. Each of these spells must be of a level for which you have spells slots.

Additionally, when you gain a level in this class, you can choose one of the arcane puppeteer spells you know and replace it with another spell from the arcane puppeteer spell list, which also must be of a level for which you have spell slots.

* Cantrips: blade ward, dancing lights, mage hand, Prestidigitation, Minor Illusion, resistance, true strike, eldritch blast.<br><br>
* 1st level: alarm, expeditious retreat, feather fall, grease, jump, mage armor, sanctuary, shield, unseen servant.<br><br>
* 2nd level: barkskin, blur, cloud of daggers, cordon of arrows, enlarge/reduce, hold person, knock, levitate, magic weapon, rope trick, warding bond.<br><br>
* 3rd level: conjure barrage, counterspell, dispel magic, fly, glyph of warding, haste, phantom steed, slow
* 4th level: arcane eye, fabricate, freedom of movement, mage's faithful hound, stoneskin.<br><br>
* 5th level: animate objects, arcane hand/bigby's hand, awaken, creation, hold monster, telekinesis.<br><br>

#### Spellcasting Ability<div style='margin-top:10px'></div>

Charisma is your spellcasting ability for your arcane puppeteer spells. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for an arcane puppeteer spell you cast and when making an attack roll with one.<div style='margin-top:0px'></div>
**Spell save DC =** 8 + your proficiency bonus + your Charisma modifier<br><br>
**Spell attack modifier =** your proficiency bonus + your Charisma modifier<br>

#### Marionette Somatics<div style='margin-top:10px'></div>

If you are in control of a marionette, you can have your marionette perform the somatic component of a spell you cast. Thus you do not need an empty hand to cast such a spell, so long as you are using a set of strings to control a marionette.
<div style='margin-top:10px'></div>
## Puppetry Expertise<div style='margin-top:10px'></div>

From 3rd level onwards, you can project your voice through a marionette you control. You can convince another creature that your marionette is talking by making an Charisma (Deception) contested by their Intelligence (Investigation) check.

In addition, when you can make an Charisma (Performance) check to entertain others with a nonmagical puppet (such as a hand puppet or shadow puppet). When you do so, you are considered proficient in the Performance skill and add double your proficiency bonus (instead of your normal proficiency bonus).

## Improved Control<div style='margin-top:10px'></div>

At 6th level, the length of your strings increases by 30 feet. In addition, the AC of all your marionettes increases by 1.

## Marionette Maestro<div style='margin-top:10px'></div>

Starting at 10th level, you can use an action or a bonus action to allow a marionette you control to take an Attack or Disengage action. One marionette you control may move on your turn without you having to use a bonus action.

<img 
  src='https://img00.deviantart.net/0194/i/2014/222/3/b/the_muse_by_chris_karbach-d76vilm.jpg' 
  style='position:absolute; top:450px; right:-0px; width:500px;' />

<img 
  src='https://i.imgur.com/pEJl0m5.png' 
  style='position:absolute; top:20px; right:-250px; width:1000px;' />

<div class='pageNumber'>5</div>
<div class='footnote'>MASTERING PUPPETRY (cont)</div>

\page

<div style='margin-top:820px'></div>

<div class='wide'>

## Travel Trunk<div style='margin-top:10px'></div>

From 14th level onward, you can spend 1 hour preparing a nonmagical chest as an arcane travel trunk. You can only have one such trunk at a time: when you prepare a new trunk, the old trunk reverts to a nonmagical chest. Marionettes treat the interior of the trunk as nondimensional: you can place folded-up marionettes into the trunk, up to its carry capacity of 300 lbs, regardless of the size of the marionettes. If the trunk only contains marionettes, it has a fixed weight of 25 lbs.

If the trunk is destroyed, its contents spill out unharmed.<br><br>

Once per turn, if you are within 60 feet of the trunk, you can call the name of one of your marionettes. It will immediately spring out of the trunk and unfold.

## Marionette Fusion<div style='margin-top:10px'></div>

At 15th level, if you are in control of two marionettes and they are within 5 feet of each other, you can use your bonus action to have them combine into a single marionette. Two Small marionettes become a Medium object; two Medium marionettes become a Large object.

Combined marionettes are treated as a single marionette, although you still require two sets of strings to control it. Its statistics are as follows:

* It has hit points equal to the total of the component marionette's hit points.<br><br>
* Each ability score is the better of the component marionette's scores.<br><br>
* Its AC is the better of the two component marionette's ACs.<br><br>
* When it takes the Attack action, it may attack twice instead of once.<br><br>
* It has all the special features of the two component marionettes.<br><br>
* They remain combined until you separate them with a bonus action or fold them up. When you do so, divide its remaining hit points between the two component marionettes (up to that marionette's maximum hit points).<br><br>

## Powerful Performance<div style='margin-top:10px'></div>

At 20th level, the length of your strings increases to 120 feet. In addition, your marionettes have resistance against bludgeoning, piercing and slashing damage from nonmagical weapons.
</div>

<img 
  src='http://lore.heroesofnewerth.com/wp-content/uploads/2015/08/DalangPuppetMaster_Wallpaper.jpg' 
  style='position:absolute;top:0px;right:0px;width:820px;mix-blend-mode:darken' />

<img 
  src='https://i.imgur.com/tQjcZ5n.png' 
  style='position:absolute; top:160px; right:-200px; width:1300px' />
  
<img 
  src='https://i.imgur.com/tQjcZ5n.png' 
  style='position:absolute; top:255px; right:-200px; width:1300px; filter:opacity(80%);transform:rotate(180deg)' />

<div class='pageNumber'>6</div>
<div class='footnote'>MASTERING PUPPETRY (cont)</div>

\page

# SCHOOLS OF PUPPETRY

<div class='pageNumber'>7</div>
<div class='footnote'>SCHOOLS of PUPPETRY</div>

\page

#### Quirks<div style='margin-top:10px'></div>

<div>
| d10 | Quirks      |
|:---:|:------------|
|  1  | Wooden or missing apendage.|
|  2  | Glass eye.|
|  3  | Fiddles and fidgets nervously.|
|  4  | Talks to inanimate things.|
|  5  | Has a nervous tick.|
|  6  | Cowardly butvery good at it.|
|  7  | Dirty and unkempt.|
|  8  | Takes everything literally.|
|  9  | Day-dreams alot.|
|  10 | Has been struck by lightning.|
</div>

#### Personality Traits<div style='margin-top:10px'></div>

<div>
| d10 | Personality Traits |
|:---:|:------------|
|  1  | When faced with a problem, I talk out the solution to myself.|
|  2  | I have a hard time focusing on conversations when I see an object I don't understand.|
|  3  | I give unsolicited advice to anyone who will listen.|
|  4  | I never do anything technology could do for me.|
|  5  | Lightning   |
|  6  | Acid        |
|  7  | Cold        |
|  8  | Fire        |
|  9  | Force       |
|  10 | Lightning   |
</div>

#### Ideals<div style='margin-top:10px'></div>

<div>
| d10 | Personality Traits |
|:---:|:------------|
|  1  | When faced with a problem, I talk out the solution to myself.|
|  2  | I have a hard time focusing on conversations when I see an object I don't understand.|
|  3  | I give unsolicited advice to anyone who will listen.|
|  4  | I never do anything technology could do for me.|
|  5  | I believe that anything worth doing is worth doing right. I can’t help it — I’m a perfectionist.|
|  6  | I always want to know how things work and what makes people tick.|
|  7  | Cold        |
|  8  | Fire        |
|  9  | Force       |
|  10 | Lightning   |
</div>

#### Bonds<div style='margin-top:10px'></div>

<div>
| d10 | Personality Traits |
|:---:|:------------|
|  1  | When faced with a problem, I talk out the solution to myself.|
|  2  | I have a hard time focusing on conversations when I see an object I don't understand.|
|  3  | I give unsolicited advice to anyone who will listen.|
|  4  | I never do anything technology could do for me.|
|  5  | Lightning   |
|  6  | Acid        |
|  7  | Cold        |
|  8  | Fire        |
|  9  | Force       |
|  10 | Lightning   |
</div>

#### Flaws<div style='margin-top:10px'></div>

<div>
| d10 | Personality Traits |
|:---:|:------------|
|  1  | When faced with a problem, I talk out the solution to myself.|
|  2  | I have a hard time focusing on conversations when I see an object I don't understand.|
|  3  | I give unsolicited advice to anyone who will listen.|
|  4  | I never do anything technology could do for me.|
|  5  | Lightning   |
|  6  | Acid        |
|  7  | Cold        |
|  8  | Fire        |
|  9  | Force       |
|  10 | Lightning   |
</div>

<div class='pageNumber'>6</div>
<div class='footnote'>QUIRKS, PERSONALITY TRAITS, BONDS, IDEALS & FLAWS</div>

\page

<div style='margin-top:75px'></div>
<div style="text-align: center"/span>
# <span style="color:white"><font size="+7">**THE ARCANE PUPPETEER**</font></span>
</div>

<img 
  src='https://cdn1.artstation.com/p/assets/images/images/001/144/545/large/yu-han-chen-30regl.jpg?1443927243' 
  style='position:absolute; top:-15px; right:-15px; width:985px;filter:hue-rotate(10deg);filter:brightness(90%)' />

<img
src='http://i.imgur.com/YRAeIcj.png' style='position:absolute;left:320px;top:10px;width:20%'/>

<img
src='http://i.imgur.com/SGYtcP2.png' style='position:absolute;top:150px;left:85px;width:80%'/>

<img
src='http://i.imgur.com/UNR8ilF.png' style='position:absolute;bottom:180px;left:0px;width:50%'/>

</pre></code></details>

**Comment by calculuschild** [comment]
It looks fine to me. Do you want to paste a screenshot of what happens?

Also, please replace your edit link above with a "share" link. Anyone who clicks on that edit link will be added as an author and they will be free to edit/replace/delete your brew. In fact it might be a good idea to copy your code into a brand new brew and don't share the Edit link with anyone.

**Comment by Boomboxcrab** [comment]
So my friend who uses the homebrewery a lot says that laptops and computers with different resolution sizes /zooms in chrome window alters the format of the document, I was working off of a different computer when I had this issue, I don't really understand why this is the way it is, and I am a bit worried the pdf will look terrible on different peoples computers when it is finished (I don't truly understand how it will affect the finished product) but at least I can edit on this computer again. I also changed the edit link to a share link...

**Comment by Moi-Brisingr** [comment]
Because you seem unclear about this. I remember looking at this brew when it was messed up and a day later when the problem was gone. The second time the source code looked a lot cleaner. the divs after headlines were gone and replaced by padding added through style tags, page numbering was switched from manual to automatic, and the really convoluted formating of the title on the first and last page was simplified.
Someone used the edit link and apparently spent quite some time fixing your brew. Yes it might look a little different depending on the zoom level but the main issue was fixed.

If you want to provide the finished brew to someone else you can always export it as a pdf. As long as it looks right in the exported pdf you don't have to worry about it looking different on another computer.

**Comment by Boomboxcrab** [comment]
I read through all the changes to the source code, the titles look so much better and the auto page numbering does help a lot, I am still learning but I have written about 80 pages so far now and I am just starting to get to grips with it. Thank you for all your help everyone :)

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
