### ISSUE TITLE
Can't Resize Editor

### ISSUE THREAD

**Issue by MalRiverdale** [stolksdorf/homebrewery#634]
Hello,

All of a sudden whenever I try to resize the editor, my cursor won't let it go. It defaults to completely closed, so I can't edit anything. I've tried closing and reopening the tab and window, as well as restarting Edge completely. It didn't do this when I first started today, but now it's completely unusable. Please help!!

Thanks,
Maltir

**Comment by calculuschild** [comment]
For what its worth, the Homebrewery is only supported on Chrome. Have you
tried using Chrome?

**Comment by MalRiverdale** [comment]
All my stuff is on Edge. I just tried it on Firefox (happened to have it installed), but it would be preferable if I could centralize everything to a web browser which I'm accustomed.

**Comment by calculuschild** [comment]
Unfortunately that's the way it is. There are simply some things Google Chrome does differently than Edge or even Firefox, and the Homebrewery is focused on working properly on the most popular browser. In the future there may be an effort to get it to rum better on the other browsers, but probably not anytime soon.

**Comment by MalRiverdale** [comment]
Fair enough. Thank you for the responses =]
