### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by Joebing69** [stolksdorf/homebrewery#635]
First off, I LOVE your project. It makes it so easy to build my projects. Thanks so much. I do have a question though. Is there a way to change the background? We are working on a print book, but don't want the Wizards background.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
Add this to the head of your document:

```
<style>
    .phb {
        background: #FFF; <!-- makes the background white -->
    }
</style>
```

or 

```
<style>
    .phb {
        background: url(http://some.thi.ng/bg.png); <!-- adds an image as the background -->
    }
</style>
```


To learn more about the _background_ property, check this site: https://developer.mozilla.org/en-US/docs/Web/CSS/background

**Comment by Joebing69** [comment]
Sweet. I'm assuming there is no way to alter the fonts though. Your stop is
so much easier to run than Publisher, but for a print book to sell, I can't
look exactly like WotC. That's great for DMGuild, but not hard print.

**Comment by HeruAsatru** [comment]
You can of course change the fonts, but that would require more work on your part.

**Comment by HeruAsatru** [comment]
You can of course change the fonts, but that would require more work on your part. 

First, you would need to define the new fonts, for example:
```
<style>
@font-face {
	font-family: Barazhad;
	src: url("http://som.ewhe.re/Barazhad.otf") format("opentype");
    
	font-family: Davek;
	src: url("http://som.ewhe.re/Davek.otf") format("opentype");
}
</style>
```

To learn more about *font-face* and its properties, check this site: https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-face

Then you need to put these fonts in:
```
<style>
.phb {
	font-family: Barazhad;
}

.blockquote {
	font-family: Davek;
}
</style>
```

Of course, these are only a few of the places that would have to change. I don't know all of them by heart, but you can inspect the site and check the *Styles* tab in the Developer Tools to find more places where the *font-family* property is used.

To learn more about the *font-family* property, check this site: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by Joebing69** [comment]
Thanks. Still learning CSS (yeah, late to the party). This will get me
running. If how quickly I learned HTML is anything to go by, this will only
take me a few hours to get the typeset I'm looking for.
