### ISSUE TITLE
Blank The Homebrewery Edit Page

### ISSUE THREAD

**Issue by wolfesamk** [stolksdorf/homebrewery#637]
When I try to open my doc with the copy Brew Code provided, it opens the edit page, but its completely blank on both panes, and the v# is 0.0.0. Not sure what is causing this?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# The Lady Cailin
### Colossal space transport

**Init** -5; **Senses** Perception +5
___
**Defenses** Ref 12 (flat-footed 12), Fort 24; +12 armor
___
**hp** 100; **DR** 15; **Threshold** 76; **SR** 45
___
**Speed** fly 12 squares (max. velocity 800km/h), fly 3 squares (starship scale)
___
**Ranged** laser cannon +1 (see below)
___
**Fighting Space** 12x12 or 1 square (starship scale); Cover total (crew)
___
**Base Atk** +0; **Grp** +34

### Abilities
**Str** 39, **Dex** 10, **Con** --, **Int** 14
___
**Skills** Initiative -5, Mechanics +5, Perception +5, Pilot -5, Use Computer +5
___

**Crew** 2 (normal); **Passengers** 5
___
**Cargo** 20 tons; **Smuggle's Compartments** 200kg
___
**Consumables** 4 months; **Luxury Upgrade** Basic
___

**Carried Craft** none; **Slave circuits** Recall
___
**Sensor Array Computer** +2 Int
___
**Hyperdrive** x3, navicomputer
___
**Availability** Licensed; **Cost** 75,000 (28,000 used)

### Attacks
___
#### **Quad Laser cannon, medium** (gunner)
___
* **Atk** +1 (-4 autofire), **Dmg** 6d10x2
___
#### **Ion cannon, Light** (gunner)
___
* **Atk** +1 (-4 autofire), **Dmg** 3d10x2 ion<style>

</pre></code></details>

**Comment by calculuschild** [comment]
This means you have some invalid html in your brew, which causes the Homebrewery to crash. Try copying your code to a new brew and then fix your code.
