### ISSUE TITLE
Minus signs too short

### ISSUE THREAD

**Issue by mirmalis** [stolksdorf/homebrewery#643]
Negative stat block's modifiers has too short of a minus sign (not only stat block I guess). 
Every minus should be replaced with en-dash or minus sign rendered as en-dash since there is no en-dash key on keyboard.

<code>>|4 (-3)|23 (+6)|16 (+3)|10 (+0)|12 (+1)|7 (-2)| // incorect</code> 
<code>>|4 (–3)|23 (+6)|16 (+3)|10 (+0)|12 (+1)|7 (–2)| // corect</code>

**Comment by jimcullenaus** [comment]
> since there is no en-dash key on keyboard

If users want an en-dash, they should enter an en-dash. Homebrewery shouldn't be interfering with what users typed. En-dashes are not hard to type. Alt-0150 on Windows, Option - on Mac, and just long press on the hyphen on a mobile device. Or copy and paste it from Google.

**Comment by ericscheid** [comment]
Or &mdash; and &ndash; ... and then copy/paste from the rendered page ;-)

**Comment by calculuschild** [comment]
This might actually be a valid issue if we are attempting to mimic the actual WOTC style, although I'm not sure on the best solution.

Reviewing some of the 5e PDF documents available for free from WOTC, such as [Tyranny in Phlan](http://media.wizards.com/2014/downloads/dnd/DDEX110_TyrannyinPhlan.pdf), I was able to actually extract the Unicode character values for the minus signs. Apparently they use two different characters, (maybe depending on who wrote the document):

* (–) U+2013 : EN DASH
* (−) U+2212 : MINUS SIGN

However, the default character when pressing the - key on the keyboard is different and noticeably shorter:

* (-) U+002D : HYPHEN-MINUS {hyphen or minus sign}

So I think there are a few options that would be better than interfering with what users type:

1. Replace the HYPHEN-MINUS in the sample snippet code with the more appropriate MINUS SIGN or EN DASH, and hope that users notice the difference when they type out - on the keyboard.
2. Replace the HYPHEN-MINUS in the sample snippet code with `&minus;` which is the HTML notation for MINUS SIGN. This would make it more obvious that there is something different going on.
3. Go in and literally change the font character to be a duplicate of MINUS SIGN.

**Comment by mirmalis** [comment]
Latex has this thing where `-` is minus, `--` is en-dash and `---` em-dash

**Comment by jimcullenaus** [comment]
@calculuschild I like option 2

**Comment by ericscheid** [comment]
ditto on no.2, but then I'm that guy that types `&times;` and `&prime;` and `&Prime;` instead of `x` and `'` and `"` =)
