### ISSUE TITLE
Picture doubling

### ISSUE THREAD

**Issue by JedRobertson** [stolksdorf/homebrewery#645]
When I click 'Get PDF' the picture I have linked doubles and a second copy appears behind the text. This only appears on the print preview and resultant PDF, not in the editing preview or preview shown behind printing options.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Can you provide the **share link** to your document so we can see what's going on?

**Comment by JedRobertson** [comment]
Thanks for the reply, I updated Chrome and that solved the issue!

**Comment by calculuschild** [comment]
Great! I will go ahead and close this then.
