### ISSUE TITLE
Homebrewery not loading right

### ISSUE THREAD

**Issue by fantascey** [stolksdorf/homebrewery#648]
Was working on my brew and it suddenly stopped saving anything at all and now when i try and load it, all the pages are completely missing, or black. The brew code is below. also none of the last stuff got saved proper and the share page doesnt load either. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

<style>
  .phb#p1{ text-align:center; }
  .phb#p1:after{ display:none; }
</style>

<div style='margin-top:450px;'></div>

# Autumn's Guide to D&D 5e

# Personal Player's Handbook

<div style='margin-top:25px'></div>
<div class='wide'>
##### In a land of dreams and fantasy, danger, and distrust, we must all learn to work together, or we shall all perish.
</div>
<img 
  src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1HD3So_htpFRymWPUIOhNe-L0-sHBwI33dvokCeXKPifrU18N_A' 
  style='width:690px' />
Credit:TylerEdlinArt - DeviantArt
\page# Guide to Autumn's
# Homebrewed World
## Welcome
Welcome to my own continent of the world of our DnD 5e Homebrew game. Here you will find accessible information on each of our locations in-game. You can also view the map here, that has been created for easy-viewing and understanding. Included is a short clarification for character creation, and further races for character building.
Understand, that in this world our characters are working with Prejudices and Biases that have been breeding ill for generations. Most races distrust outsiders, and most villages, cities, or towns, do not welcome Race mixing. It is your parties job to get to the bottom of the reason why, and fix it. For the good of all.  *For all further questions not listed in this Guide, please see your DM.*

##### Frequently asked Questions

**How Does Combat Work?** We are by the book. Refer to the DMG and the PHB for these rules unless in specific circumstances, when the DM says otherwise.

**What if I get three 9's on my Stats?** You would have three 9's on that column. Remember, you are choosing the best of three columns total. Ultimately, it will be up to you if you choose the column that has three 9's. If you have three columns, and they all seem terrible. Refer to the DM for their ultimate opinion.

**If we are on a different continent, how do I choose where my character is from?** You can feel free to choose any of the locations that would apply to your character. The Dungeon Master, can help to explain how you got where you are, or you can think of some other creative story. Example, Kidnapped by pirates and sold into slavery where you eventually escaped or bought your freedom. You no longer are on the same continent, but you are pretty stuck all the same. 

**If I want to pick up a mace, but don't have that proficiency, am I at a disadvantage to attack?** No. You would not be at a disadvantage to pick up this weapon and hit something. It is assumed that all characters know how to pick something up, and accordingly, can hit someone with it. If however, whatever weapon or weapons you attempt to pick up, require some sort of affinity, or two handed weilding, you are at a disadvantage because it has become unwieldy. Or because you may hurt yourself. Examples: You pick up a large battleaxe, it is heavier than you expected so you may drop it on your toe. If you find a blowdart gun, it would be simple to blow through it, but this is an example of a weapon where you need to roll first to see if your character remembers not to breathe in over the tube and suck the dart into their mouth accidentally. Since that is a weapon that requires a knowledge of dartguns.

**Why doesn't anyone Trust Dragons?** This is what you have to figure out. Dragons and other species have been causing discord for several generations. Why? This is the overall Quest of the Game.
## Character Creations
All character general column stats, are rolled with a 3d6 unless otherwise specified.  If a character roll is made with more than one '1', or if the total is less than 9. Then reroll that die group. example. ***3d6 = 1, 1, 5. *** This would be rerolled. If *** 3d6 = 6, 3, 4.*** Then this is an 13 total. *Do not Reroll.*  Roll your stats: Strength, Intelligence, Wisdom, Dexterity, Constitution, and Charisma, once each for one column.  Make three columns, and choose the one that is the best for your needs.  You can put the resulting numbers in whatever statistic you prefer. Your results cannot be higher than an 18, or lower than a 9, in any category when rolled in this way. Any other bonuses or feats may still be added. Characters do not cap at 20 points for level 1 in stat categories. The cap at level 1 is 30.  
> ##### A Note about proficiency bonuses
> Any character has the ability to try and gain a bonus to a proficiency. 
> 
> **Choosing Skills** 
Be aware, Skills and proficiencies are able to be learned, if you want to take the time out of the game to do so. Certain rolls must be met for use of tools, or use of stat increases. Tables listed with the XP charts will give more detailed information on these requirements.

#### All Races in the PHB
Races in the PHB are welcome, with changes to Dragonborn. Dwarf, Elf, Gnome, Half-Elf, Half-Orc, Halfling, Human, and Tiefling have no notable changes. Below, are listed the Dragonborn changes, and other included Races for the game. Note that in one party of adventurers, we try to make sure everyone gets along. If a race states that they do not get along with persons outside their species, everyone in the party should be the same species. Example of this is a Minotaur. Minotaurs can be found in the Unearthed Arcana book. All other races please refer to your DM for clarifcation and approval for use. 
<div class='descriptive'>
##### Races found in other tomes.
Understand that races in other books have not yet been completely approved for use in this game. Unearthed Arcana for example, is not  approved at this time for Race variants. Any authorized Races not in the PHB will be listed here.

**Dungeon Master Rules** Use this guide, and any other specific questions you may have can be referred to the DM. 

**Have Fun** Obviously. That is the point.
</div>
<div class='pageNumber auto'></div>

<div class='footnote'>PART 1 | Welcome</div>
\page

### Dragonborn

Dragonborn in this world is not the same as with the PHB. Dragonborn characters are in fact much the same builds as humans but with marks of the dragon on their skin, and in their hands and feet. Some are born much more heavily marked than others, in some cases it may not become apparent that they are dragonborn until they have reached the ages of 5-8, in other cases, even as a newborn they have claws or scales already. Over time, scales grow out to replace their human skin in places, and claws grow from their tips beneath fingernails. This is a permanent change. With claws they will get bonuses to climbing and dexterity, but will not stand any taller than the average human. Some Dragonborn produce tails, and some do not have this. Some dragonborn also can grow wings in their maturity. Dragonborns are born from humans as live young, and not hatched from eggs. The characteristics of many children Dragonborn are similar to the Humans. As a child grows older though, the marks are more and more apparent. This is common in places like Rain City, but the humans there are distrustful, and if a child begins to show the marks of being Dragonborn, they are usually outcasted from society, abandoned, or culled. Dragons are distrusted and being associated with Dragons will cause you to be an outcast. Some Dragonborn have managed to live with the dragons in harmony in the Spine of the Dragon mountain range. Others have created their own tribes or societies, and are living separately. If a Dragonborn is not living with other dragons, they have a much shorter lifespan. Dragons help them to cope with their growing scales and dragonlike appearances throughout their lifetime. Dragonborns within the presence of dragons reach maurity at age 18 and can live to be 150 years old. Dragonborns not in the general company of dragons age much faster, so they only live to a maximum age of 40. See below the notes for building a DragonBorn.
<img 
  src='https://i.pinimg.com/originals/b4/dc/6e/b4dc6e23197fb9ed90814328555cea1d.jpg' 
  style='width:325px' />
Credit: Google Images

<img 
  src='https://cdn.trendhunterstatic.com/thumbs/prosthetic-dragon-spikes.jpeg' 
  style='width:335px' />
Credit: Google Images

<div class='pageNumber auto'></div>
<div class='footnote'>PART 2 | Races </div>

\page

## Additional Monsters
___
___
> ## Phoenix
>*Tiny Magical Beast, Celestial, Lawful Good*
<img 
  src='http://99-host.com/users/tbalze/bird/Png/phoenix-red-flw-branch.png' 
  style='width:240px' />
>Credit:Google Images
> ___
The Phoenix is a magical creature of celestial bloodlines that is extremely protective of whomever it has become bonded with. These creatures are given by a God or Goddess as a sign of Favor  to their devoted followers. Phoenixes, once bonded, will never bond to another being. If the one they have bonded with, should perish, they will then return to the God or Goddess that granted them to their bond.  A friend of their bond, is a friend of theirs. Enemies of the one they have bonded to, beware the powers of the Phoenix. If you have targeted the one they are bonded with, they go to great lengths to make your life miserable until you have stopped harassing their allies. These creatures are extremely rare.
> ___
> - **Armor Class** 13
> - **Hit Points** 8(1d4 + 5)
> - **Speed** 45ft in air 5ft walking
> - **Senses** Passive Perception 15
> - **Challenge** 2 (60 XP)
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|5 (+1)|17 (+3)|8 (+1)|12 (+1)|12 (+5)|10 (+2)|
>___
> - **Immunities** Fire Damage
> - **Resistances** Poison
> - **Vulnerabilities** Cold, Ice, Being Reborn (see Rebirth).
> - **Languages** Understands Celestial, Common, Elven, Gnomish, Infernal, can speak telepathically in images. 

> ___
> ***Keen Hearing and Sight*** Phoenix has an advantage on Wisdom (perception) checks that rely on hearing or sight.
>
> ***Flyby*** Doesn't provoke opportunity attacks when it flies out of an Enemy's Reach.
>
> ***Rebirth*** Phoenixes can be reborn of their own ashes. This takes a number of 1d4 days before they are back to their normal appearance and health. Until that time, health and stats are all reduced by half. Abilities unavailable, exceptions: Death Burst, Rebirth, False Appearance (looks like a baby bird that just hatched). 
>
> ***False Appearance*** While this is a magical bird, it still looks like an ordinary red bird.
>
> ***Healing Tears*** Producing 1d4 healing for every 60 seconds. Cannot cry during Combat, Must be in contact with the target of the healing or the wound. Tears are collectible for healing potions.
>
>***Birdsong of Strength*** Gives bonus to all allies within hearing distance for up to one hour. +1 to all saving throws.
>
> ### Actions
> ***Talons*** *Melee Weapon Attack:* +3 to hit, reach 5ft., one target. *Hit* 1 slashing damage.

> ***Beak*** *Melee Weapon Attack* +4 to hit, reach 5ft., one target. *Hit* 4 (1d4+2) piercing damage.
>
> ***Birdsong of Attack*** *Attack* deals 1d4 psychic damage and 1d4 radiant damage to one targeted enemy within hearing and 30ft. One action. Unlimited. 

>***Death Burst*** When the Phoenix dies, it explodes in a burst of Flames. Each creature within 5 ft. of it must make a DC 11 Dexterity saving throw, taking 7(2d6) fire damage on a failed save, or half as much damage on a successful one. Death activates Rebirth.
> 
> 

<div class='pageNumber auto'></div>
<div class='footnote'>PART 3 | Monsters</div>

<div </div>\page

### Enchanted Forest of Mysts
This location is home to a very important path. The path in and out of this Forest, leads North and South. It is also home to much more magic than in other places. The path traveling to the North, will lead you straight to the Bridge of Siensnan, and the South Entrance to the city of Siensnan. The path, traveling South, leads you through the Forest and out to the Grassy Plains. This is home to select few Humans, several Faerie species, including but not limited to Nixies, Dryads, Nyads (or Naiads), Tree Changers, Nymphs, and Pixies. This is also the home of several Elementals, Giants, enchanted creatures, and some Dragonborn and human folk in selected locations. Some say the forest itself is enchanted. To stray from the path is dangerous if you do not know where you are going, and even if you do in some cases. This Forest is the hub of faerie and magically mysterious activity, and is known to turn out adventurers and unwary travelers into places unexpected. Stay with your group if you can. It is very easy to get lost or separated from your party. 
Enchanted forest of Myst (fae, faerie, celestial, human, most mythlike creatures, regular creatures. Path is widely used by all.) 
### Eriand
(Gnome City NorthEast of the Spine of the Dragon.) Fae, faeries, humans, dwarves, halflings, celestial,) *dragonborn, infernals, dragons, evil alignment people not welcome here.* The City floats above a glittery lake and is surrounded by misty valleys, safe haven for good creatures and beings. 
 ### Faar
The Lost City of Faar is Lost. The legend says it was a wealth of treasure and knowledge and then, the people of the city angered the Gods by not offering proper tribute. The city was cast from the world into the Sea, by their anger, It has never been found. If it even exists, we have no idea what race of people lived there or if there really was a treasure. People laugh at others who mention trying to find it. A childrens tale. 

### Faerie Crystal Caves 
(hidden faerie city, only faeries and accepted friends know how to find this place) It's existence is Common Knowledge.
### Five Village Circle 
These five villages all are set together in one large circle and have one large gathering location for all of their inhabitants. They are located in the southern section of the Grassy Plains on the Edge of the Woods. It is strictly a set of human villages that all work harmoniously together to provide each others' needs. They are each individually governed by a council of their Elders, which has a 'Head' that is voted on each season. 
(Penn, Stix, Tak, Crow, Din) 
#### Penn
This village is responsible for hunting and trapping food, and growing food in the fields, feeds all five villages. Also trains the children and tests them for fighting, hunting, and other skills of this nature.
#### Stix
This village is responsible for the gathering of Wood, chopping, and also the preservation of the forest. They are careful to use trees that are infested with termites, diseased, or otherwise unhealthy so that they can preserve the overall health of the woods and life of the forest creatures. 
### Tak
This village is responsible for cloth, they tend sheep and use the wool to create the clothes, they also have tanners, and create cloth dyes. Some items are traded outside of the village. 
### Crow 
This village is responsible for messages and scribing. They raise birds which are trained to fly back and forth to various locations. They keep the records for the village circle and make their own ink and paper from the local plants. 
(Penn, Stix, Tak, Crow, Din)  (human villages, outsiders not trusted)	
### Grassy Plains 
(home to many creatures, faeries, tree changers, humans expected, halflings live here too.) several villages.
### Rain City 
(hidden city, home to humans and dragonborn) Rain City exists, but unless you live there, have been there, or were born there you have no idea how to get to it. 

### Sands of Lost Souls 
(hidden desert city is here, yuan ti, dragonborn, elven, human, infernal)	
Savage Seas (just like what it sounds like.) 
### Siensnan  
Siensnan is the Elven City. It is heavily guarded and is the biggest marketplace hub on the North or South Side of the River. All races shop and trade here, but Dragons. Dragonborn are welcome here but distrusted. To get to siensnan, there is one way in or out, from the south legally. They must cross a rope bridge between two cliffs. The city is surrounded by a heavy stone wall against the cliff, and the other side of this cliff, ravine, gorge type area, has a treacherous path that has to be traversed down to the rope bridge. The path can only be accessed from the edge of the Enchanted Forest of Myst. Most merchants do not have wagons, and only can bring what they can carry, or magic, across. It is fortified by several guardhouses and watchmen. The back of the city opens out onto the hot sandy plains. There is heavy protection from the back wall entrance. 

### Spine of the Dragon 
(dwarven city, arctic, home of the dragons, and many dragonborn, faeries welcome, only select few outsiders accepted, (half faerie half human tribes ( also live here, but not inside the mountain with dragons, only on top of it.) ) 
### Valartha 
(valartha is the goblin city, all outsiders unwelcome, ) (northwest of spine of the dragon) 

### Woeful woods 
(home of the satyrcorns, spirits, zombies, and other evil and malevolent beings.) (northeast of the spine of the dragon) 

<div class='footnote'>PART 4 | Locations </div>

<div </div>\page

### Crediting The Homebrewery
Thank you to the anonymous persons, for spending the time to create such a wonderful layout tool. I will be using this in future for all of my own game books creations. Much joy. Have a great life.

<div class='footnote'>PART 5 | Credits </div>
<div </div>\page

</pre></code></details>

**Comment by calculuschild** [comment]
Take a look at #655. It sounds like you have some broken code in your document which is causing the website to crash.

**Comment by fantascey** [comment]
i had already found and fixed my errors, you can remove any tickets with my
username on them please. I thought i noted that on the other one, but it
all opens fine and no longer crashes for me.

**Comment by calculuschild** [comment]
Great to hear you got it working then. I'll close this issue.
