### ISSUE TITLE
Page 2 Overlapping Page 1.

### ISSUE THREAD

**Issue by SexySolidSnake** [stolksdorf/homebrewery#660]
For some reason while I'm creating my page it's perfectly fine, but when I go to print or just simply look at it later without the editing window it overlaps my 2nd page onto my first. I've looked through the informational one to see if I was missing something or did something wrong, and I didn't see anything. I could have missed something and that's what I'm hoping for, but if anyone know anything on how to fix that I'd love to hear it.

**Comment by calculuschild** [comment]
Can you provide a screenshot and the share link to your document so we can see what might be happening?

**Comment by SexySolidSnake** [comment]
![homebrew](https://user-images.githubusercontent.com/38390370/38774433-eca91ce2-4036-11e8-8b84-e1ca092aaa81.png)
![homebrew edit](https://user-images.githubusercontent.com/38390370/38774434-ecb5b394-4036-11e8-870d-2ea750960204.png)

**Comment by SexySolidSnake** [comment]
I hope these help. And, after I save it for the first time anytime I come back to edit it it's locked in the state of overlapping. I've provided one without the editing window, and one with it. In the editing window you should be able to see where I've tried to insert another page, but even though it is there it still overlaps. However, like I said previously it only overlaps when I save it then open it again afterwards.

**Comment by calculuschild** [comment]
In the middle of your "command undead" sectiom it looks like you have half a footnote with the last `<div>`. There footnote on page 1 is also missing the ending `div` tag.

**Comment by calculuschild** [comment]
Basically you have your `\page` plus half of the "command undead" section *inside* your footer on page 1.

**Comment by SexySolidSnake** [comment]
I don't even know how I overlooked that. A very dumb moment on my part, but thank you so much for helping me out with that! It is much appreciated.
