### ISSUE TITLE
Page Display Problem

### ISSUE THREAD

**Issue by VoteforSampedro** [stolksdorf/homebrewery#666]
Whenever my text gets to the point that it would extend into another page, it instead just moves to the next column, only slightly visible on the very right side when converted to a PDF. Has anyone had any similar problems and if so did you get it fixed and how?
![screenshot 104](https://user-images.githubusercontent.com/38485393/38912116-872eace8-42a1-11e8-9019-aba3740043ee.png)

**Comment by GorchD20** [comment]
You have to create a page break, like so:

\page

If you want to auto-number pages (for longer documents, you may instead want to do it like this:


\page
<div class='pageNumber auto'></div>

**Comment by calculuschild** [comment]
Closing this because the solution has been provided.

@VoteforSampedro If you still have the issue, you can reopen here and provide further information.
