### ISSUE TITLE
Nothing showing on right side, when trying to print words are on a different page

### ISSUE THREAD

**Issue by wsorrentini** [stolksdorf/homebrewery#667]
## Before you submit

- Support questions are better asked on the subreddit [r/homebrewery](https://www.reddit.com/r/homebrewery/)
- Read the [contributing guidelines](https://github.com/stolksdorf/homebrewery/blob/master/contributing.md).
- If it's an issue, please make sure it's reproducible
- Ensure the issue isn't already reported.

*Delete the above section and the instructions in the sections below before submitting*

## Description

If this is a *feature request*, explain why it should be added. Specific use-cases are best.

For *bug reports*, please provide as much *relevant* info as possible.

**Share Link** :http://homebrewery.naturalcrit.com/user/wsorrentini

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by wsorrentini** [comment]
was working on homebrewary making some rules. when i last work about a week ago everything was find. now only the code shows on the left, there is Nothing showing on right side(no preview), I tried to make new ones and it does not work. also when trying to print my current work the words are on a different page instead of the background page. 
[The Homebrewery - NaturalCrit.pdf](https://github.com/stolksdorf/homebrewery/files/1929899/The.Homebrewery.-.NaturalCrit.pdf)

**Comment by calculuschild** [comment]
If you have nothing showing on the right side, it means you have some broken code in your brew. See #655 . If you post your share link somebody might be able to look at your code and help you figure out what is broken.

**Comment by Theodoxus** [comment]
Something broke on the lines... they're not wrapping anymore, but going all the way across. Anyway, if you scroll to the far right, you should see three little vertical dots -you can click and drag the dots to the left, pulling the preview pane back into view.

**Comment by calculuschild** [comment]
Unfortunately you still have not provided the *share link* to your document, so I can't see what you are talking about. Can you do that so we can help you figure out the problem?

**Comment by wsorrentini** [comment]
http://homebrewery.naturalcrit.com/edit/rkliidMc3f

**Comment by calculuschild** [comment]
As I suspected, you have some invalid HTML code in your document. You have a `<d` around line 19 that is causing everything to crash. Try removing that and see if the problem goes away.

**Comment by wsorrentini** [comment]
im idiot sorry
