### ISSUE TITLE
No background when exporting to PDF

### ISSUE THREAD

**Issue by carlosrebato** [stolksdorf/homebrewery#670]
The papyrus-like background every document has shows right up to the end, when the print pop-up dialogue appears and I try to save to PDF. The resulting local PDF, however, has formatting right and everything, but no background, just a regular black page.

**Comment by calculuschild** [comment]
Can you provide the **share link** to your document so we can see what's going on?

Are you making sure to print using Chrome? Did you add the "Printer-friendly" option to your document which removes images and backgrounds?

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @carlosrebato
