### ISSUE TITLE
Homebrew not showing up, only showing page numbers

### ISSUE THREAD

**Issue by WesPotato** [stolksdorf/homebrewery#673]
First time posting here, but that's besides the point. I don't know what happened, but while making a homebrew, after saving it and clicking Share, the page showed up blanks, only saying 1/17. Does someone who actually knows what they're doing (i.e. not me) tell me what I did wrong?

**Share Link** :
http://homebrewery.naturalcrit.com/share/BJlVFLNaG

**Comment by calculuschild** [comment]
See #655 . You have some HTML that is not working, or you need to add some blank lines between `<div>`s and other style marks `#`, etc. so the renderer doesn't get confused.  Try cutting your document in halfs then fourths and so on and see if you can pinpoint what part of your code is causing the issue when you share.

**Comment by calculuschild** [comment]
Were you able to solve the problem by fixing any errors in your HTML code? The document you shared looks like it is working now, so I am going to close this issue. Feel free to reopen and add more info if you are still having the issue.
