### ISSUE TITLE
Version 3.0.0

### ISSUE THREAD

**Issue by thecrazygamer25** [stolksdorf/homebrewery#675]
This isn't really an issue but I didn't find anywhere else to put it. I was wondering when Version 3.0.0 of The Homebrewery was coming out. I was looking at the change logs and the last time there was an update was a little over a year ago. I know it takes awhile for these things but I just wanted to know if there is an approximation on ETA

**Comment by calculuschild** [comment]
Redirected to subreddit and closing.
