### ISSUE TITLE
Share page is broken on master

### ISSUE THREAD

**Issue by calculuschild** [stolksdorf/homebrewery#695]
## Description

The */share* page is broken on master. It seems to be generating a `<div class="homePage page">` rather than `<div class="sharePage page">` with components of an editor pane and everything. The result is a garbled display of the document scrunched over to one side of the screen and the snippet bar along the top where there should be nothing. I'm guessing this is some confusion with the routing in [Homebrew.jsx](https://github.com/stolksdorf/homebrewery/blob/a634b76117592158e348ee7843045222093c96c3/client/homebrew/homebrew.jsx) but I can't pinpoint why this is happening.

The issues also occurs with the */changelog* page.

**Edit:** After further searching, it looks like this is actually occurring on *every* page. The expected div is being replaced by `homePage` in each instance; it just isn't readily apparent in the `/edit/` page for example, because both `homePage` and `edit` are similar enough in structure that they both contain the `splitpane`, `editor` and `brewRenderer`.  It looks like somehow the [default URL](https://github.com/stolksdorf/homebrewery/blob/a634b76117592158e348ee7843045222093c96c3/client/homebrew/homebrew.jsx#L77) is overriding everything else.  Is this an issue with the latest Pico-Router maybe?

I'd like to figure out what happened here so we can work on pushing out a new version to live at some point.

@stolksdorf @Rae2che5 Are either of you aware of a particular commit that caused this regression?

**Share Link**:
[http://staging.homebrewery.naturalcrit.com/share/S1U_UU5Af](http://staging.homebrewery.naturalcrit.com/share/S1U_UU5Af)

and

[http://staging.homebrewery.naturalcrit.com/changelog](http://staging.homebrewery.naturalcrit.com/changelog)

**Comment by LeviRosol** [comment]
Do you also see the weird `;` at the bottom of the document and the `Warning: Expected server HTML to contain a matching <div> in <div>.` thrown by libs.js when running locally? I'm not sure if these are related, but it seems like a place to start - as if there's an unclosed div or something somewhere.

FWIW, if I revert back to using `React.` as shown in this commit ( https://github.com/stolksdorf/homebrewery/commit/f18a181e2ec5e372121149b3fe9bafbccbe5884d )

along with reverting back to the old version of React, I can get the page to render the splitter correctly. There isn't any brew data showing, but I assume there are related changes to get it to render correctly.

Additionally, the version of modules will continue to be an issue if they are not specifically set in the package.json. It might be a good idea to remove the `^` in each one

Hope this helps!

**Comment by calculuschild** [comment]
Found the issue. The Pico-Router module was updated and changed some variable names along the way. It was just 7 characters to change  and now it works. See Pull Request #701 .

**Comment by Rae2che5** [comment]
Great sleuthing, and confirmed as fixed.
