### ISSUE TITLE
Text window ate the preview window, can't reverse it

### ISSUE THREAD

**Issue by JoeMiller89** [stolksdorf/homebrewery#699]
This is the second time this has happened. I've somehow expanded the text window and now I cannot see the preview window. They should be side by side but all I see is text code. Does anyone know how to set it back to the text left - preview right setup?

**Comment by calculuschild** [comment]
You should have a scrollbar on the bottom of the screen. Try dragging that all the way to the right; you might have just a little sliver on the edge being covered up where the divider should be, and you can drag it back.

**Comment by JoeMiller89** [comment]
I see that bar, it's on the right side of my screen, however it doesn't respond to any of my efforts to drag it over

**Comment by calculuschild** [comment]
Just to be sure, you see *this bar* (circled in red)? And you can't drag it back to the left?

![image](https://user-images.githubusercontent.com/5878534/40513401-a0c52634-5f73-11e8-8637-6f865103cc98.png)

**Comment by JoeMiller89** [comment]
The update would certainly help in the future but that cache advice seemed to work to reset it, thank you very much for the help.

**Comment by calculuschild** [comment]
Glad it worked for you!
