### ISSUE TITLE
Non-Wide Tables don't format correctly in pdf export

### ISSUE THREAD

**Issue by huulkinat** [stolksdorf/homebrewery#702]
## Description

When creating non-wide tables the exported pdf has a formatting issue.

Here is the table in the editor:
![table_expected](https://user-images.githubusercontent.com/27901726/40462465-bc7f49ca-5ed5-11e8-8878-ec4e498b9594.JPG)

Here is the table in the pdf preview:
![table_pdf](https://user-images.githubusercontent.com/27901726/40462480-c906801e-5ed5-11e8-8874-d13a2365dc30.JPG)

This only occurs when the table is placed after a column break (ie. it is on the right side of the page).

</pre></code></details>

**Comment by calculuschild** [comment]
This is a known issue and a fix is on the way. See #318 for a temporary workaround.

Duplicate of #318
