### ISSUE TITLE
Homebrewery is not printing  or saving to pdf properly.

### ISSUE THREAD

**Issue by Bsketchw** [stolksdorf/homebrewery#706]
I tried to test print a project I am working on and found that it will not properly print the page as it is displayed.  Upon playing with it, I  discovered that I was working at a 90% page size and when I changed the page size it distorted the page layout.  Despite the page layout getting distorted, table borders, descriptive text block borders, and areas of text are printing wrong and displaying wrong when saved to pdf.  However, when viewed at the homebrewery, the page looks just how I want.   I have included the html text from my project to see if it is something wrong with the code or if the website is experiencing bugs itself.  but looking at the display version of this report, I am not sure if that will help.

</style><div class='wide'>
# Gengolor
| Druid 5 | Guild Artisan | Firbolg | Neutral Good |
|:-------:|:-------------:|:-------:|:------------:|
| Class / Level | Background | Race | Alignment |
  
</div>

><div style='column-count:4'>
>
>### &nbsp; &nbsp; 17
>&nbsp; &nbsp;**Armor &nbsp; &nbsp; &nbsp; &nbsp; Class**
>
>### &nbsp; &nbsp; &nbsp; 3
>&nbsp; &nbsp;**Initiative**
>
>### &nbsp; &nbsp;   30
>&nbsp; &nbsp; **Speed**
>### &nbsp; &nbsp; &nbsp; 3
**Proviciency &nbsp; &nbsp; Bonus**

></div>

### STRENGTH
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **14** | 2 | +2 | 

### DEXTERITY
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **16** | 3 | +3 |

### CONSTITUTION
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **15** | 2 | +2 |

### INTELLIGENCE
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **14** | 5 | +5 |

### WIZDOM
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **20** | 8 | +8 |

### CHARISMA
| Score | Modifier | Save |
|:-----:|:--------:|:----:|
| **11** | 0 | +0 |

<div style='margin-top:140px'></div>
<div style='margin-top:140px'></div>

<p>&nbsp;</p>

>### Armor
><div style='column-count:2'>
>|Armor| AC |
>|:---:|:------------|
>| Studded Leather | 12+Dex Mod |
>
>
>
>| Shield | AC |
>|:------:|:-----:|
>| Basic | +2 |
>
></div>

<p>&nbsp;</p>  

<div class='descriptive'>
<div style='column-count:3'>
## &nbsp; &nbsp; &nbsp;35
| Max HP |
|:---:|
|    |
 
<p>&nbsp;</p>  

```
```

<div>
<p>&nbsp;</p>
#### Death Saves
| Pass | Fail |
|:-------:|:------------|
| <empty> | <empty> |
| O | O |
| <empty> | <empty> |
| O | O |
| <empty> | <empty> |
| O | O |
| <empty> | <empty> | 

</div>

<p>&nbsp;</p>
## &nbsp; &nbsp; 5 d8

</div>

</div>

<div class='classTable'>
## Skills
| Proficiency | Stat Bonus | Skill | Stat |
|:-----------:|:----------:|:------|:----:|
|  | +3 | **Acrobatics** | DEX |
|  | +5 | **Animal Handling** | WIS |
|  | +2 | **Arcansa** | INT |
|  | +2 | **Athletics** | STR |
|  | +0 | **Deception** | CHA |
|  | +2 | **History** | INT |
| **O** | +8 | **Insight** | WIS |
|  | +0 | **Intimidation** | CHA |
|  | +2 | **Investigation** | INT |
|  | +5 | **Medicine** | WIS |
|  | +2 | **Nature** | INT |
| **O** | +8 | **Perception** | WIS |
|  | +0 | **Performance** | CHA |
| **O** | +3 | **Persuasion** | CHA |
|  | +2 | **Religion** | INT |
|  | +3 | **Sleight of Hand** | DEX |
|  | +3 | **Stealth** | DEX |
| **O** | +8 | **Survival** | WIS |

</div>
<div class='pageNumber auto'></div>

\page

>### Weapon Proficiencies
><div style='column-count:3'>
>| <space> |
>|:-------:|
>| Club |
>| Javelin |
>| Scimitar | 
>
>
>
>
>
>| <space> |
>|:-------:|
>| Dagger|
>|  Mace |
>| Sling |  
>
>
>| <space> |
>|:-------:|
>| Dart |
>| Quarter Staff |
>| Spear |  
>
></div>

<div class='descriptive'>

### Weapons
| Weapon | Atk Bonus | Damage | Type |
|:------:|:---------:|:------:|:----:| 
| Magic Scimitar | +6 | 1d6+2 | Slashing |
| Sling | +6 | 1d4+3 | Bludgeoning |
| Cross Bow | +3 | 1d8+3 | Piercing |

</div>

**Comment by redhill93** [comment]
Same here pdf files have a white margin at the bottom of each page
![capture](https://user-images.githubusercontent.com/40872790/42350206-5f991698-80a7-11e8-93e0-3af593779c4d.PNG)

**Comment by ericscheid** [comment]
By default, the background image is scaled to fit (IIRC) a US Letter page.

If you are instead printing to an A4 page, the dimensions are different and a white gap appears.

There is however a style snippet you can insert, it's on the "Print" menu (the one above the editor, next to Editor, PHB, and Tables)

**Comment by Forecaster** [comment]
This still happens with the "print" snippet

![image](https://user-images.githubusercontent.com/942137/47321474-32f0b480-d655-11e8-9e26-fb9bc7a2abf8.png)
![image](https://user-images.githubusercontent.com/942137/47321488-3edc7680-d655-11e8-980b-04603e2dcc3c.png)

I unfortunately do not have "US letter page" as an option.

![image](https://user-images.githubusercontent.com/942137/47321520-56b3fa80-d655-11e8-86e7-f98ded45b592.png)

**Comment by Forecaster** [comment]
It seems in my particular case the height needs to be 297mm to remove the margin

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Bsketchw
