### ISSUE TITLE
Wide Table not working properly

### ISSUE THREAD

**Issue by StargazeMelody** [stolksdorf/homebrewery#707]
Here is a screenshot of the issue, the wide table isn't working

![brokentable](https://user-images.githubusercontent.com/39885412/40890149-5393e944-673f-11e8-9312-b09857daeda8.png)

**Comment by ericscheid** [comment]
Firefox does not support the CSS property `column-span` (or `-moz-column-span` or `-webkit-column-span`).

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @StargazeMelody
