### ISSUE TITLE
Homebrewery.naturalcrit is messing up

### ISSUE THREAD

**Issue by PSDNDFUN** [stolksdorf/homebrewery#709]
Hello I write a little bit of homebrew on the side for DND for fun.  When using the site homebrewery.naturalcrit.com I noticed that when I made the documents that I worked on into pdfs the tables get all wonky.

![example of homebrew messup](https://user-images.githubusercontent.com/40307451/41492356-dcd0ef9c-70bb-11e8-841a-8ef866217a20.jpg)

I noticed this happened with other homebrew on different files so I wanted to bring it to your intention because I think it might be the site.  I don't know how someone can get in contact with whomever owns it to fix it but there you go.

**Comment by PSDNDFUN** [comment]
It seems to not be there when viewing it online.  It is only when I try to turn it into a pdf.  That and only that particular table seems to mess up.

**Comment by calculuschild** [comment]
This is a known issue with Chrome. See #683 for a workaround in the meantime. We have a fix ready, but unfortunately the site owner has been M.I.A for a while and we are stuck waiting to upload the changes to the site.

**Comment by calculuschild** [comment]
This issue should be fixed now. Finally got the site creator to give us access to the deployment branch.
