### ISSUE TITLE
Wide tables?

### ISSUE THREAD

**Issue by PariahSilver** [stolksdorf/homebrewery#71]
Heya, I'm not reporting an issue but I do have a question. You have wide monster blocks, which are fantastic, but do you have plans for adding wide tables?

**Comment by stolksdorf** [comment]
Pretty easy to add, I'm just running out of syntax to use. Any suggestions?

**Comment by tonymccallie** [comment]
Just add another line? Like they just add more hashes for headers.. 
```
##### The Linguist
___
___
___
| Level |
```

or maybe longer dashes?
```
##### The Linguist
______
| Level |
```

**Comment by stolksdorf** [comment]
#62

**Comment by kkragenbrink** [comment]
As a suggestion, stolksdorf, I think you should actually reuse the syntax you've got.

```
___
___
> Wide Monster Statblock

___
___
| Wide Table |

**Comment by stolksdorf** [comment]
This has been added in v2.1.0 using the "Wide Block" snippet. Enjoy!
