### ISSUE TITLE
Trouble saving and long times saving

### ISSUE THREAD

**Issue by PSDNDFUN** [stolksdorf/homebrewery#711]
This isn't as much of a problem because sometimes it behaves but I was getting a saving error.  I decided not to post it because it showed my url when I clicked to post that it happened.  Is anyone else getting this?  There have been a lot of issues with this website recently and I'm worried.  I have a lot of homebrew on this website.  Is it because it is too large?  My homebrew in question that I found it on was 73 pages long.  I noticed that it takes a long time to load.  This was about 3 hours after I had just messed with it before and it was fine then.  It is like something bad happened to the website in the meantime.  Does anyone know anything about the creator of the website?  Someone in the last post I did mentioned that they were MIA so hopefully they can fix it or pass it onto someone else that can fix it.

**Comment by PSDNDFUN** [comment]
It got better recently.  I don't know if anyone know what happened or not.

**Comment by RKuerten** [comment]
The site is not that stable, I agree. Your brew is not that large, but past 50+ it gets slower a bit when saving, that's normal.

Is not a bad idea to keep a backup of your brews. Ctrl + A, copy in any text editor and save it somewhere in your PC. Precaution is never bad.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @PSDNDFUN
