### ISSUE TITLE
Images broken on homebrewery

### ISSUE THREAD

**Issue by ZargoGames** [stolksdorf/homebrewery#713]
Images are not loading on any of my documents, and I've attempted to view them on multiple browsers.

**Comment by DanLyght** [comment]
![image](https://user-images.githubusercontent.com/40528512/41813930-888b6b02-7740-11e8-80f0-4e86e59f0e01.png)

**Comment by Boomboxcrab** [comment]
I am having the same issue, I am using Imgur to host my images, I have tried chrome and firefox. Some images seem to be working yet others do not. I am so scared I might have to re-do so much as I have around 800 pages worth of files I have been working on for an upcoming campaign.

Some images work when linked straight from the web so perhaps the homebrewery is suddenly not okay with imgur links? I have no idea...

Share link: https://homebrewery.naturalcrit.com/share/rybF7btq3G

any help would be greatly appreciated.

**Comment by ericscheid** [comment]
I'm seeing 403 DENIED responses for those images when loaded from the page. Copy/pasting the image src urls (i.e. direct) is working find.

imgur.com is blocking the hot-linking.

**Comment by calculuschild** [comment]
Just sent an inquiry to Imgur. We'll have to see if they can unblock us.

**Comment by ericscheid** [comment]
As a workaround, load the brew with `https`, but write all the image links as `http` .. your browser should then *not* send the `Referer` header, and imgur will honour the request.

**Comment by Boomboxcrab** [comment]
the workaround posted by ericscheid works, however I don't really want to have to change thousands of lines of html code in 10 or so homebrews. As I said before, I have a lot of published / unpublished brews, totalling around 800 pages or so I would guess, and every single one of them has this issue...

It would take me so long to fix this when I already have so little time to write and prepare for d&d sessions. :(

**Comment by RKuerten** [comment]
The "https to http" does nothing for me, but if it does for you Boomboxcrab, try copy and pasting your works in a editor like Visual Studio Code, where you can select all instances of "https" easily, and turn them into "http".

**Comment by calculuschild** [comment]
Hey guys, I got a response from Imgur saying they've lifted the ban. How are your brews looking now? You might need to clear your browser cache.

**Comment by DoctorDan1986** [comment]
I’ve been using cubeupload for my brews; imgur always seems to have issues every wet Wednesday.  And the less said about photobucket, the better...

**Comment by WormSlayer** [comment]
Yeah I opened a support ticket with them earlier too, and just got the same reply. They say it could take 24 hours to go through though and is still not working as I write this.

**Comment by calculuschild** [comment]
Looks like its working now, so I'm going to go ahead and close this. Anyone else still having problems?
