### ISSUE TITLE
Saving Brew Ruins it

### ISSUE THREAD

**Issue by BaxterTheTeddy** [stolksdorf/homebrewery#717]
Created a new brew. Everything is fine in the preview area as I'm working. Complete my work, and hit save. Immediately after saving I only have access to a portion of a single page. The code hasn't changed at all but my preview is bugged completely and even changing the code does nothing. 

Print preview is different again, showing incorrectly formatted pages including the last page which simply looks as though it was typed on word. 

I've been able to replicate this error by copy and pasteing my code into a new brew, it works fine. As soon as I save it appears as below. 

**Share Link** : http://homebrewery.naturalcrit.com/share/SJkLZmfzQ

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# Part 2: Personal 

#### The Nomad Camp 

<div class='descriptive'>
##### Nomad Camp
You crest a sand dune and the camp comes into view. Similiar to the last nomad outpost you visited; wooden palisades surrounded a series of tents. This one is in far worse shape, however. Even from here you can see cracks in the palisades, scorch marks along the walls, and even arrows jutting out of the wood. You can see shapes moving along the walls, crouched low and dashing from place to place. Very different from the guards walking back and forth along the walls. 

You get closer and are immediately aware of eyes from the camp upon you. A head pokes out over the palisade and waves to you. Upon reaching the gate, the doors are opened and you are motioned inside. "Quickly!" someone hisses. As you enter, you can hear the creaking of the wooden door as it closes behind you. A halfling man stands before you. Dressed in desert garb and armed with a short bow, he looks up at you. His face is uncovered, and you can see his skin is tan and leathery, years of sun and sand damage. His hands are callaced and scarred. But he still smiles at you. "So, what brings a lot of fools to our humble camp?" 
</div>

- Glint tries to warn the PCs off of visiting the ruins, but puts in very little effort. He knows that they won't listen. He does offer to have his rangers keep an eye out for them well patrolling. 
- He warns them about Ossiran, the collosal guardian of Ahn'Qiraj. 
- If asked he doesn't know where the library is. He, nor any of his rangers, go into the city as there is no reason. 
- He does offer to give the PCs some extra supplies, and that they can leave any excess gear at the camp. No one will take it if they do. 
- When the PCs leave, Glint tells them of a small rocky outcropping, a few hours from the city. It's defensible and he recomends it as a way stop. He also tells them there's usually a small cache they can take from, just make sure to leave some of it for his rangers. 
- It'll take more than a days travel to reach the city. 

<div class='descriptive'>
##### Approaching Ahn'Qiraj
Your campsite gives you a good view of the city. It's massive. At the center is the temple itself, sealed off behind a ring of walls. You can see a magical barrier flicker as sand is blown into it giving off distant flashes of colour. Around it the cities extends out in all directions. Hundreds of ruined buildings: everything from small houses to small palaces. A few buidlings you can see from here could be the library. 
</div>

- After a rest, the PCs should approach the town. 
<div style='margin-top:140px'></div>

#### First Street Fight

<div class='descriptive'>
##### Street Fight
You apporach the city, walking alonge one of the side streets. Most of the buildings are little more than frames covered in rubble. Still, you can see the grandeur that the city must have once been. Most of the buildings look to have been minimum four stories, and the odd surviving mural, or bit of stonework reveal just how grand the city must have once been. CRASH! A body crashes through part of a collapsed wall. A muscular, armoured humanoid wrestles with a Silfid. His tough leathery skin holds each of the front two bladed claws at bay. You get a glimpse of the creatures face: a gnarled expression, with lupine eyes and lower tusks. More silfid and orcs poor into the street, fighting one another.   
</div>

- 3 Orcs (MM 346) and 5 Hunters 
- The Silfid will attack whatever is closest, Orc or PC, well the Orcs are more concerned with the Silfids. However, should the PCs engage them they will turn their attention. 
- After a few rounds, or if the PCs decide to run, read the below. 

<div class='descriptive'>
##### Ossiran's Arrival 
There's a boom, and the earth shakes a little. The banging grows louder, and you can see the Orcs, still fighting, start to panic. From down the street comes a towering behemoth. Twenty five feet tall the contructs reaches the top of many buildings, its eagle head shimmers with an unnatural power. It's eyes stare down the street at the entire group. It's blue torso is detailed with gold, and faux golden wings extend from its arms. Its fame shivers, continueing it's rythmic, but rapid, advance. A beam of energy shoots from it's eyes, a shimmering turqoiuse, and the beam cuts through the street. One of the Orcs, and a pair of Silfid are caught in the beam and vaporised before your eyes without so much as a scream. 
</div>
\page

#### Tavern
<div class='descriptive'>
##### Tavern
Before you is a mostly intact structure. Based on the sign, barely dangling outside the door, it was a tavern of some sort. You can see the flicker of fire light within, and can make out the sounds of talking, and shouting, in some guttural tongue. 
</div>

- 4x Orcs (MM 246) and 2x Bugbears (MM 63) 
- Several of the orcs are gambling, well one of the Bugbears is by the fire "cooking." The remainder are scattered around the room relaxing. They are in good spirits after having scored a good amount of loot. They are distracted, and a little drunk, so we'll have disadvantage on their perception rolls. 
- If fighting starts, the Orcs will flip the table, and attempt to find cover. They remain inside, using windows and doors to engage the PCs at range, where ever possible. The Bugbears head to the doorways to stand guard, and will attempt to grapple the first PC that comes through. The beasts are greedy, and are happy to fight and die for their loot. 
<div style='margin-top:px'></div> 
Loot: 2x Casks of Ale, 1x Barrel of Water (8 liters inside), 80gp, 1 minor Healing, A set of Charlatan's Dice 

#### Bank
<div class='descriptive'>
##### Time to Drop Knowledge
This building could be the library. Four large pillars hold up the front of a marvelous, marble structure. Collapsed statues would have flanked either side of the rather large, impressive doors. One of the two doors is badly cracked, leaving an opening to the interior of the building. Inside, is a round, bare room; it looks as though there must have been statues and decorations on the wall but much of it has been picked clean. A block of rubble, perhaps a counter of some sort, sits near a set of descending stairs totally smashed. You can hear cackling voices, and metal on metal clinking from below. 
</div>
- Two goblins hide in the rubble. If they are spotted, they'll immediately fire their bows and jump down the stairs to give wanring. If the PCs don't spot them, they'll sneak behind them and ambush them when the PCs reach the rest of the goblins. 

<div class='descriptive'>
##### Vault Way
The stairs descend a fair ways, enteringa curving hallway. Several heavy metal doors extend of this part of the hall, with one still closed and sealed. A pack of short, pointed eared, green skinned humanoids stand before the closed door. A pair of larger furry and more muscular looking goblins stand in front of the door, smashing at it with pickaxes. Based on the damage to the door, and several destroyed hammers at their feet, the goblins have been attempting to enter this vault for some time with no luck. 
</div>
- 1x Gobling Boss and 8x Goblins (MM 166) and 2x Bugbears (
- The goblins will use their speed to their advantage, engaging at range to draw the players down the hallway, and try and spread them out. Once a PC over extends, they'll rush them and attempt to bring them down rapidly. They'll duck into the open vaults, or around the next hallway for cover. The goblins know there is no where to go, and will surrender if they are losing the fight badly. 
- The door is magically sealed. DC 10 Arcana to recognize it's magical. DC 20 to unlock the vault. DC 30 to force it open. DC 17 to find the magical mechanism nearby, advantage if someone has recognized it as magical. Once the mechanism is activated, the door becomes a DC 15 to pick. 
<div style='margin-top:px'></div>
Loot: Moon Touched Long Sword (On Goblin Boss) VAULT: 400gp, Ring of Water Walking, Staff of the Python

#### Nobles Manor
<div class='descriptive'>
##### Nobles Manor
You've come across the ruins of what must have been a minor nobles manor. The second floor has completely collapsed, the remains of which are visible in the street adjacent to the building. Once it would have been vaguely keep shaped, clearly intended to provide some protection in a siege or riot. The sides have collapsed, leaving several openings inside along with the front door. Lights flicker within, suggesting others may be using the place. That said, it would be a good place to hold up for the night. 
</div>

<div class='descriptive'>
##### Entrance Way
A pair of statues, in good condition, flank the entrance; men in desert armour stand guard. A rug extends out, ravaged by time and the elements but still intact. The wall before you has collapsed, revaling a dilapidated throne room, complete with throne. On the left is a wall and door that looks to be an isolated room. Several corpses litter the floor their organs and blood still freshly splattered. The stink of death is pervasive. 
</div>

- 4x Zombies (MM 316), 2x Specter (MM 275) 
- The zombies remain motionless until a PC attempts to check them or walks within 5ft. THey will then grapple the PCs, and if successful, drag them to the ground before diving on top of them. A PC grappled like this can't get up till they break the grapple. Once the PCs are engaged by the zombies, the specters will rush from the statues behind them and attack with surprise, trying to bring down any weak PCs. 
\page
<div class='descriptive'>
##### Ossiran Passes By
A booming sound shakes you awake. You glance around, and can feel the massive feet of Ossiran just outside. Every step brings the monster closer, and closer. He's right outside now, every step causing you to jump off the ground just a bit. Suddenly, he stops. There's a moment of peace, before a giant fist strikes the ground right outside. A beak suddenly appears as Ossiran leans down to glance inside. You catch a glimpse of a single, glowing eye turned slightly away from you. He isn't looking at you. Suddenly, the beaked face disappears and Ossiran kicks over a small building across from you. Something screams loudly, before the wooshing of Ossiran's beam. There screaming stops and the behemoth stops away.  
</div>

#### Alchemist's Shop
<div class='descriptive'>
##### Alchemist's Shop
Another mostly intact building. Juding by the sign hanging from the window this would have been an alchemy shop. The door hangs off it's hinges. You can see inside and it looks like there are still vials and flasks with stuff inside of them.
</div>
- A shelf collapses, dumping a noxious smelling ooze onto a PC. 1d4 damage from the vial, and a lingering odour that gives disadvantage to stealth checks when within 50 ft. 
- The floor above collapses, and a spray of acide follows the wood. 1d6 Bludgeoning, 1d4 Acid, and knocked prone. 
- If the PCs attempt to use the stairs, they will collapse and the PCs will fall into the collapsed basement. 1d6 fall damage. There's no way out of the basement, except the hole the PC used to enter. 

#### 2nd Ossiran Encounter
<div class='descriptive'>
##### Ossiran Ambush
As you exit the building, you are immediately aware of rumbling. Suddenly, a shadow descends upon you as Ossiran rounds the corner and charges you. Before you can move much he's outside your building. He smashes a fist through the top floor, sending debris raining from above. 
</div>
- The PCs need to escape Ossiran, and the soon to be demolished building. The PCs have to contend with avoiding Ossiran's fists (vs. AC with disadvantage, no bonus) and falling debris. They may also fall into other incompletely collapsed parts of the basement and need to be rescued.
- Once the PCs escape, let them get away and then have the shop collapse, and Ossiran stomp off. 
<div style='margin-top:140px'></div>

#### Market
<div class='descriptive'>
##### Market
You seem to have entered a large square, where a market would have once been. Carts and stalls dot the landscape, along with long dry fountaisn. Once, this would have been a bustling local market. Now, it is little more than a sad reminder of the lives that once lived here. There's a sudden crash and part of a cart is hurled towards you. 
</div>
- DC 8 Dex to avoid the cart completely. 1d6 damage as part of the cart hits anyone who fails. 
- Minotaur (MM ?) 
- The minotaur will attempt to throw objects at the PCs: carts, stalls, chunks of debris or even the PCs (if he succesfully grapples them, he will throw them at another player Str v. AC with disadvantage. The PC thrown takes 1d6 + str damage, well the one hit will take 1d6 + str + size (+1 small, +2 med, etc.) 
<div style='margin-top:140px'></div>

\page

#### Bridge Fight
<div class='descriptive'>
##### Bridge Fight
You've come across a 20 ft wide canal that looks like it extends down this portion of the city. A surprisingly sturdy looking stone bridge extends before you. The water rests about 15 feet from the lip of the canal. You can hear from where you stand that the canal ends in a waterfall. There's a sudden buzzing sound, a painful sounds that grows louder. From one of the buildings windows rush three giant wasps. They have a pattern to their movements that reveals an intelligence, the kind you've seen in other Silfid. The creatures fan out and buzz toward you. 
</div>
- 3x Wasps 
- The wasps will hit and run as much as possible, avoiding being in melee whenever possible. They attempt to harrass the players, picking off anyone who lets themselves be alone. If the oppurtunity is present, they'll attempt to knock a player into the water; causing them to move 1d6 squares per round as the current takes them. If they reach the waterfall, they'll take 1d10 falling damage and continue to wash away. 
- The bridge isn't as sturdy as it looks. If more than two PCs are on the middle of it at a time it starts to shudder under the weight. If the PCs stay there for more than a round, or a third PC joins, it'll collapse. 

<div class='descriptive'>
##### Ossiran's Arrival

</pre></code></details>

**Comment by calculuschild** [comment]
See #655. Looks like you have some bad code causing issues.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @BaxterTheTeddy
