### ISSUE TITLE
Table Rendering Glitches with PDF conversion

### ISSUE THREAD

**Issue by BradenGodley** [stolksdorf/homebrewery#719]
## Description

When this brew is converted to a PDF file, there is a really odd glitch with how the table is rendered. It looks like its just repeating the 9-slice (at least i think that you are using a 9-slice to render that) rather than actually putting each piece in the correct spot. It might be because I have made some edits so that it would look correct in the editor, making the CSS slightly different. Any help is appreciated, and thank for you providing me with this tool. It makes DMing prep and creating new rules a lot easier to create and format!

Here's what it looks like in the Print page. I'm doing this on Chrome, by the way. It renders incorrectly in the editor when I open it in Firefox, so I don't think there's a way around the problem.
https://prnt.sc/k2o54b

**Share Link** : http://homebrewery.naturalcrit.com/share/HyeEZXCbQ

**Comment by calculuschild** [comment]
Duplicate of #683. There is a solution in there that should fix the issue.

**Comment by BradenGodley** [comment]
Thanks! It worked perfectly.
