### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Crawlspace42** [stolksdorf/homebrewery#721]
When on the homepage of Homebrewery and I select the login button in the top right corner, it will take approx. 5 seconds to load and redirects me to [http://naturalcrit.com/login?redirect=http://homebrewery.naturalcrit.com/](url)

It shows a white screen with the error code: ERR_CONNECTION_TIMED_OUT

Google Chrome is whitelisted in my firewall and I disabled my firewall to see if that would solve the problem but it failed to work. I have reloaded the page several times and tried accessing it through multiple other devices but am unable to do so. I have also switched to several different connections but that failed as well.

Here are links to where I am redirected when attempting to login from homebrewery.naturalcrit.com

Image Link:
[https://imgur.com/wVmVuxC](url)

Direct Link:
[https://i.imgur.com/wVmVuxC.png](url)

**Comment by Lithdoran** [comment]
I'm having the same issue. Seems like something might be wrong with naturalcrit itself?

**Comment by HeruAsatru** [comment]
https://downforeveryoneorjustme.com/homebrewery.naturalcrit.com

Login works for me. Does the problem still persist?

**Comment by Crawlspace42** [comment]
The issue still persists for me on my desktop. I was still logged into my account on my laptop and am able to access my account from my laptop. However, it still shows me the same errors on desktop.

**Comment by HeruAsatru** [comment]
The url where it takes you is correct. Please try it in incognito mode and see what happens then. 

This seems to be a problem on your end and not with the homebrewery. I will try to help, but please be aware that remote troubleshooting is always hard, so I can't guarantee that we will find a solution...

**Comment by Lithdoran** [comment]
The problem seems to have resolved itself for me, thanks.

**Comment by Tallysbta** [comment]
Hello, i keep logged the entire day from my job machine, then i tried to log on in my home pc and the following problem occurred:

`libs.js:1 POST http://www.naturalcrit.com/login 500 (Internal Server Error)
p.end @ libs.js:1
(anonymous) @ bundle.js:1
login @ bundle.js:1
login @ bundle.js:1
handleClick @ bundle.js:1
r @ libs.js:1
r @ libs.js:1
executeDispatchesInOrder @ libs.js:1
d @ libs.js:1
v @ libs.js:1
t.exports @ libs.js:1
processEventQueue @ libs.js:1
r @ libs.js:1
handleTopLevel @ libs.js:1
a @ libs.js:1
perform @ libs.js:1
batchedUpdates @ libs.js:1
batchedUpdates @ libs.js:1
dispatchEvent @ libs.js:1
bundle.js:1 {name: "MongoError", message: "Topology was destroyed"}message: "Topology was destroyed"name: "MongoError"__proto__: Object
`

**Comment by dwugofski** [comment]
I'm trying to sign up for NaturalCrit, and whenever I type in the username I want, the icon to the right (a rotating wheel which I believe is meant to signify it's searching to see if the username is taken) stays spinning. 

When I open the debug console (on either Chrome, Firefox, or Edge) I get a Server Error 500 response for the GET XHR for http://www.naturalcrit.com/user_exists/myusername.

**Comment by Crawlspace42** [comment]
So without going into Incognito, the issue has resolved itself. Now a new dilemma has occurred in which when entering my credentials it will fail and the message: "Something went wrong" appears underneath the password field.

Going into Incognito did not remedy this unfortunately.

**Comment by artsbyjapao** [comment]
I'm having the same issue. What can I do?

**Comment by dwugofski** [comment]
My issue has been resolved.
