### ISSUE TITLE
Broken <div class>

### ISSUE THREAD

**Issue by AlwaysLearning55** [stolksdorf/homebrewery#726]
## Before you submit

- Support questions are better asked on the subreddit [r/homebrewery](https://www.reddit.com/r/homebrewery/)
- Read the [contributing guidelines](https://github.com/stolksdorf/homebrewery/blob/master/contributing.md).
- If it's an issue, please make sure it's reproducible
- Ensure the issue isn't already reported.

*Delete the above section and the instructions in the sections below before submitting*

## Description

When writing the code, the "preview" on the side of the screen looks fine. When pressing "get the pdf", the pdf appears to have "broken code" on the line 169 (the box isnt "clear")

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>

<div class='pageNumber auto'></div>

## Cartilha do Jogador

<div>
Este manual servirá para que os jogadores conheçam um pouco das mecânicas do projeto Crítical Bastard.
</div>

### 1. Participando de Aventuras

<div >
É bem simples participar de uma aventura. Como pode ter percebido, ao entrar no projeto você consegue um RG e automaticamente um rank, iniciando como **filhote de kobold**, e progredindo à medida que sobe de nível. Para se inscrever numa aventura, primeiro você tem
que ter o rank que ela exige, verificar a quantidade de jogadores inscritos e lançar apenas seu nome, não precisa de nenhum outra informação para não poluir o canal. Caso verifique que o número máximo de jogadores foi alcançado, mas ainda está interessado, lance seu nome **_mais o emotion “R” de reserva_**, podendo ter a chance de ser convocado em caso de desistência.

**Lembrando**: Não precisa de mais nada que não seja seu nome na sala de aventura.</div>
 
#### Sistema de Ranks (Níveis)

<div>
O sistema de Ranks utilizado no Projeto Critical Bastards funciona parecido com o sistema de "milestones". Cada Aventura, conta como um passo para o próximo nível.
_Aventura é um nome dado ao "XP"_.
##### Sistema de Level por Aventuras
| Level | Aventuras (Acumulado)|           Rank         | 
|:-----:|:--------------------:|:---------------------: |
|   1   |          0           | Filhote de Kobold      |
|   2   |          1           | Filhote de Kobold      |
|   3   |          3           | Filhote de Kobold      |
|   4   |          5           | Prisioneiro de Bugbear |
|   5   |          8           | Prisioneiro de Bugbear |
|   6   |         11           | Prisioneiro de Bugbear |
|   7   |         14           | Ração de Dragão        |
|   8   |         17           | Ração de Dragão        |
|   9   |         20           | Ração de Dragão        |
|  10   |         23           | Orgulho de Beholder    |
|  11   |         26           | Orgulho de Beholder    |
|  12   |         30           | Orgulho de Beholder    |
|  13   |         34           | Coveiro de Lich        |
|  14   |         38           | Coveiro de Lich        |
|  15   |         42           | Coveiro de Lich        |
|  16   |         46           | Caçador de Tarrasque   |
|  17   |         50           | Caçador de Tarrasque   |
|  18   |         55           | Caçador de Tarrasque   |
|  19   |         60           | Lenda Viva             |
|  20   |         65           | Lenda Viva             |
</div>

### 2. Gerenciamento de ficha

Toda vez que terminar sua quest, anote com calma seus ganhos e mencione o gerente de fichas para que o mesmo possa atualizar seu histórico.

```
```
Para fazer isso, basta seguir modelo abaixo:

> ##### Invocando o Gerente de Fichas
> 
@Gerente de Fichas
<div>Aventuras ganhas: +1 aventura(total 5)</div><div>Vida ganha: (20) + 6+3 (total 29)</div><div>Ouro ganho: 14PO 8PC </div><div>Itens ganhos: 1 espada vorpal</div><div>Nivel ganho: +1 nível de Paladino(total Paladino 3/Ladino 1)</div><div>Recursos de classe ganhos: 2 pontos de ki/1 ponto de feiticeiro</div>
Demais observações: qualquer coisa que você obtenha a mais com a classe, talentos, melhoria de pontos de atributo, magia e outras coisas.

### 3. Profissões
<div>
O projeto conta com um material extra chamado _"Guia de Profissões"_. Todo conteúdo relacionado a profissões se encontra neste guia, e deve ser utilizado em conjunto com a cartilha do jogador.

A profissão pode ser escolhida **somente** enquanto o personagem for _Filhote de Kobold_.
</div>

### 4. Crafting

<div>
Para criar itens você deve consultar a tabela da respectiva profissão. O tempo e valor de criação, além das regras gerais e específicas de cada profissão estão listados no _Guia de Profissões_.

Utilize o seguinte modelo ao utilizar a área de craft:
</div>

> ##### Pedido de Craft
>@Seu nome, fabrica: Nome do item + valor de fabricação + categoria que pertence + tempo de duração. @Trsytam

<div>
O responsável pelo craft irá ver seu chamado, anotar seu pedido no calendário e descontar seu
gold no momento que o chamar. Após iniciar, se o trabalho for cancelado, ele reiniciará do
zero.
Ao concluir, o item será adicionado à sua ficha.
</div>

#### Comércio

<div>
Os preços são tabelados, e não negociáveis, exceto para menos. Deve-se atentar as peculiaridades de cada profissão.

Os produtos fabricados, conseguidos em missões assim como comprados de outros jogadores, ou do livro do jogador (exceto itens Muito Raros e Lendários), podem ser adquiridos pelos jogadores, e vendidos através da área de comércio.

Pra vender algo, você oferta a 80% do valor total do item e então o _Trystam_ automaticamente adiciona o ouro na sua conta e o item é vendido. Salvo seja comprado por outro player, ou pela guilda, considera-se que foi vendido para o mercado de Neverwinter.
</div>

\page
<div class='pageNumber auto'></div>

>##### Venda de item
@Seu nome - vende (nome do item + tipo de item + 80% do valor do item ou menos)
@Trsytam

>##### Compra de item
@Seu nome - compra item (nome do item + tipo de item + valor) @trystam.

<div></div>
### 5. Biblioteca

<div>

A biblioteca usada pelos jogadores depende da liberação de assuntos pelo mestre. Sendo assim, o jogador somente poderá pesquisar o que o mestre demandar/apresentar (não haverão pesquisas aleatórias).
As pesquisas poderão ser feitas de segunda a sábado e as respostas virão de domingo até segunda.

Existem dois tipos de pesquisas, condicionadas ao bônus de inteligência do jogador, conforme abaixo.

</div>

> ##### Pesquisa única: 
> Poderá pesquisar um único assunto, por semana. Fazendo isso, conseguirá um bônus maior.
> <div></div>
> ##### Pesquisa Dupla:
> Poderá pesquisar dois assuntos por semana, Fazendo isso, embora aumente a quantidade de itens pesquisados, a atenção é dividida, resultando em bônus menores na hora de lançar o dado.
> <div></div>
> <div></div>
> _O jogador que escolher um tipo de pesquisa, não poderá utilizar o outro durante a semana._

##### Pesquisa Unica
| Mod Int | Bonus |
|:-------:|:------|
| -1 |  +4  |
|  0 |  +10 |
| +1 |  +12 |
| +2 |  +14 |
| +3 |  +16 |
| +4 |  +18 |
| +5 |  +20 |

##### Pesquisa Dupla
| Mod Int | Bonus |
|:-------:|:------|
| -1 |  +2  |
|  0 |  +5 |
| +1 |  +6 |
| +2 |  +7 |
| +3 |  +8 |
| +4 |  +9 |
| +5 |  +10 |
<br>

<div class='descriptive'>
##### Rolando um Crítico ou Falha Crítica:

No (20), o pesquisador pode fazer uma pergunta ao mestre ao terminar a pesquisa.
Porém, no (1), o mestre irá informar que aquele assunto não existe, e caso seja uma pesquisa única, o livro contendo o assunto se torna indisponível na biblioteca. Caso seja dupla, o livro ainda está disponível para futuras pesquisas.
</div>

#### Pesquisando na prática

<div>

O jogador escolhe o assunto lançado pelo mestre e o marcará na pesquisa. Após escolher o(s) assunto(s), determinará se a pesquisa é única ou dupla (para determinar seus bônus de lançamento dos dados), e lançará o D20 somado ao respectivo
bônus (vide tabela).
</div>

>#####  Realizando uma pesquisa
>(Seu nome), pesquisa: @(mestre), assunto, pesquisa única,
Bônus +14. (e rola o dado).

<div class='descriptive'>

##### Resultado das pesquisas

| Rolagem (c/ bônus) | Rank | O que sabe |
|:--:|:-------------| :--- |
| 10 | Amador | O básico |
| 15 | Veterano | Algo a mais|
| 20 | Especialista | Muito |
| 25 | Excepcional | Quase tudo |
| 30 | Mestre | Tudo | 
</div>

<div>
</div>
### 6. Itens Mágicos	

Na medida que evoluem, os personagens vão ganhando itens. Basta atender ao quesito de nível, de acordo com a tabela segunte e as devidas ressalvas.

Itens Muito Raros e Lendários serão obtidos (comprados ou não) através de uma quest, que servirá de Background do item. O jogador deverá comprar um pergaminho de item (vendido pelos escribas, ou pelo dobro do preço no mercado), e comunicar a um mestre, que então fará uma aventura que será voltada a obtenção do item.

| Rank | Categoria do Item |
|:----|:-------------|
| Prisioneiro de Bugbear  | Incomum |
| Ração de Dragão  | Incomum |
| Orgulho de Beholder | Raro |
| Coveiro de Lich | Muito Raro |
| Caçador de Tarrasque | Lendário |
| Lenda Viva | Surpresa | 

\page
<div>
# Lista de preços de itens Mágicos
</div>
<div> </div>
<div class='classTable wide'>

##### Comuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 50 | Consumível | 40 |
| Menor| 150 | Menor | 120 |
| Maior | 150 | Maior | 120 |
| Arma | 300 | Arma | 240  |
| Armadura | 300 + Armadura | Armadura | 240 + Armadura||
</div>

<div class='classTable wide'>
##### Incomuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 150 | Consumível | 120 |
| Menor| 800 | Menor | 640 |
| Maior | 1300 | Maior | 1040 |
| Arma | 1500 | Arma | 1200  |
| Armadura | 1500 + Armadura | Armadura | 1200 + Armadura||
</div>

<div class='classTable wide'>
##### Raros
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 300 | Consumível | 240 |
| Menor| 4000 | Menor | 3200 |
| Maior | 6000 | Maior | 4800 |
| Arma | 8000 | Arma | 6400  |
| Armadura | 8000 + Armadura | Armadura | 6400 + Armadura||
</div>

</pre></code></details>

**Comment by DMZeff** [comment]
I'm having the same problem. It leads to the descriptive boxes having dots all around the perimeter instead of just the four corners.

**Comment by calculuschild** [comment]
Looks like a duplicate of #683.

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400).
