### ISSUE TITLE
Make red lines in the text

### ISSUE THREAD

**Issue by marcuswallace1991** [stolksdorf/homebrewery#729]
I'd like to know how can i make red lines in the text without using monster tables.
I want add red lines in the normal text to make an appendix, as the final part of monster or player handbook, in which monsters are writtens normally without tables and I need the code to do that.
Ty

**Comment by marcuswallace1991** [comment]
I'd like to know how can i make red lines in the text without using monster tables. 
I want add red lines in the normal text to make an appendix, as the final part of monster or player handbook, in which monsters are writtens normally without tables and I need the code to do that.
Ty

**Comment by AlexeySachkov** [comment]
I'm not sure that it is a best option, but you could use raw html/css:

```html
<span style='color: red'>RED Text</span>
<font color=red>RED text2</font>
```

**WARNING**: always backup your brew locally and check syntax before saving. There is a known-issue which leads to losing your brew, see #655

**Comment by marcuswallace1991** [comment]
ok, but how can i backup locally and save file? I find "Source" type on the menù, is this the right option to do that?

**Comment by marcuswallace1991** [comment]
I try the code, i need not code to write in red, but to make red line on the text 
for example, that line bewteen title and subtitle 
https://www.google.com/search?client=firefox-b-ab&biw=1824&bih=845&tbm=isch&sa=1&ei=5ZRxW7mqLYfWarXukoAD&q=dms+guilde&oq=dms+guilde&gs_l=img.3..35i39k1j0i19k1l2.17905.19013.0.19074.10.9.0.0.0.0.174.955.2j6.8.0....0...1c.1.64.img..2.8.950...0j0i67k1j0i8i30i19k1.0.VeFcjuLBIv0#imgrc=-RIh4FWO4nBuDM:

**Comment by AlexeySachkov** [comment]
If I understand correctly, you saved source code of the editor webpage to your desktop, yes? Please check it: I guess it doesn't contain your brew text.

Sorry, I misread you original question.  I guess the easiest way to add such red line is to insert an image into your brew.
You can read about `img` html tag here: https://www.w3schools.com/tags/tag_img.asp

Basic usage:
```
<img src="put link to an image here" > 
```

If you want to use the same red line as in monster stats block, let me know. I can show you how to re-use it. I mean this one:
![image](https://user-images.githubusercontent.com/6417047/44038289-2675f61a-9f1f-11e8-860e-c31cf8313764.png)

**Comment by marcuswallace1991** [comment]
Ok. No problem, I used your code on 1 copy of document, not in the original =) 
Yes, can you help me? I mean exactly that! I don't wanna use tables (It's an appendix) and I have problems to do that, ty.

**Comment by marcuswallace1991** [comment]
up

**Comment by AlexeySachkov** [comment]
As I can see, red lines in monster stats block (see example in my previous message) are done using styled `<hr>` (horizonal line) html-tag.

You could reuse it if you want. You need to put the following code (it defines style) into your brew only once, somewhere above all usages of red lines:
```html
<style>
hr.my-red-line {
    visibility: visible;
    height: 6px;
    margin: 4px 0;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAeCAYAAACR82geAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAAt5JREFUaEPtWTtoVEEUHf8iaEjMZt/ME6Jx3X1zlwgavyAICoL4aRWFIFYWAUURLZQo+GkUTGHc92Y2q2AKI0oKLbQIKRS0UPxCilgEFIKCTYIfyBrPi4NImGKJyWZ3Xw4cpth9b84c7ty59w3TaXdAS3FXEz8VkLtNp5YuZjNgoTGj/1KRGNEkXoEqkM4RmLamlbG55u/RwXhj7BRDMKw3kPyKkmKflk69ebxyYTeiAJL4CLO6AynOaI/v8Buqq8wrKwPWRU+Ef7bgOy3dm4p4i0456/wmNs9MU36wLnKySO4wzHqCyLoGsw4EyfiKUcZmmalLG9YFTSVJDMKkB0ryc1np7OxsrKo2UkoLVvHFJLl5GNWHpH5bS35UUXxDWyKxwMibPljFTjdJfMP2ewbDrgee06xWxhIoGWYbycWBVViJMQvCqM/go4D4Be25u/wkr4X8qctXNiFlwjwiqx9RdQfj8ZznbvI5X2SW9f+wTFi+JPEdfIHaysd4SKdEqnXrBKt26wQVQrMFv+IE7MlKcakjLfbkKOYUVDLYXljhzOMEHEBU3UMfeDJLfIu1cbY8GDmqtPiJyHoDaph1OJOqa5wxBgyNCUi8DY3pgDEqWbc6csaotPsLUTEAE+7rdES30t/kS7wHJlzGSbU349Xy6CVfEj9gwksk1yDKxzV6LPEBlXAXxhPaE5v9pogVeOGWQAR8AR/DhIuBJ3ZnE04M8iPWEqCJRIJ8jmhohynNimKJLsbmGMnFgVVYMTn22cHtgxGdgcePZWR8Y66+fqGRN32wip1KkhgEHwaSnw8/VClaVmOklBas4ieL5A7jlHiK4qlNEz/YvqquIXqfNkmMoIJ8j+R4C2a0+ElnfSux+Waa8oN1kQUwS+ITzOhWnjir05G9PhFDMKEX7ftV1Av7b6Tiy83jlYvxJmArhPdDrzHq8Io24/G1Ub2iHbvURzN1GuP2tkTNEvNThMHYbySiA8IawOrpAAAAAElFTkSuQmCC);
    background-size: 100% 100%;
    border: none;
}
</style>
```

To insert the red line:
```html
<hr class='my-red-line'>
```

Here is an example of result: 
![image](https://user-images.githubusercontent.com/6417047/44038859-645480a4-9f20-11e8-9783-be63a3cd2e58.png)

**Comment by marcuswallace1991** [comment]
perfect, ty very much.

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
