### ISSUE TITLE
Brew wont work completely (\page)

### ISSUE THREAD

**Issue by AlwaysLearning55** [stolksdorf/homebrewery#731]
## Description
I cant use \page, as it wont create a new page (or at least it doesnt appear in the preview nor "get pdf"). I cant edit the pages past the 2, since it just doesnt update in the preview. And there also seems to be a bug with the viewers, where it says "one", when i never shared any links.
And it wont work in a new brew aswell.

Also, i cant log in my account in my firefox. I tried and it created another account with the same username (but with uppercase letters).

**Share Link** : https://homebrewery.naturalcrit.com/share/ryXoCNmbr7

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<style>
  .phb#p1{ text-align:center; }
  .phb#p1:after{ display:none; }
</style>

<img src='https://i.imgur.com/ApgJhp3.jpg'
style='position:absolute;top:0px;left:0px;width:100%'/>

<img src='https://i.imgur.com/3rDt1rV.png'
style='position:absolute;top:0px;left:0px;width:100%'/>

<img 
  src='http://i.imgur.com/Sa6Nmjx.png'
  style='position:absolute;left:0px;bottom:180px;width:50%' /></p>
<div style='position:absolute;
font-family:"nodesto", nodesto, sans-serif;
font-weight:bold;
font-size:20px;
color:white;
bottom:30px;
right:55px;
width:700px;
text-shadow: 1px 1px 2px #000000,-1px 1px 2px #000000,1px -1px 2px #000000,-1px -1px 2px #000000;
filter:opacity(100%)'></div>

\page
 

<style>
  .phb{
    width : 210mm;
    height : 297mm;
  }

<style>
    .phb .classTable {
        border-image-repeat: stretch;
    }
    .phb .descriptive {
        border-image-repeat: stretch;
    }
</style>

<div class='pageNumber auto'></div>

# Manual do mestre

<div>
Este manual servirá para que os mestres possam localizar todos os elementos e ferramentas que precisar para desenvolvimento de suas aventuras.
</div>

### 1. Sessões e recompensas

<div >
Toda campanha tem uma duração esperada. Porém, esse número pode aumentar ou diminuir de acordo com as ações dos jogadores. Para padronizar a recompensa por cada quest, a seguinte tabela é utilizada.
</div>

| Duração | Quantidade de Aventuras |
|:-----------|:-------------|
| Até 5h59m  | 1 aventura |
| De 6h a 8h59m  | 2 aventuras |
| De 9h em diante | 3 aventuras |

<div style='margin-top:30px'></div>

> ##### Interpretação e Dificuldade
> Caso a sessão tenha um elevado nível de dificuldade, o mestre poderá conceder mais 1 aventura ao grupo, por tal feito.
>
>O mesmo se aplica no caso de uma destaque pelo roleplay. O jogador em questão, caso tenha interpretado muito bem seu personagem, poderá ser recompensado com mais 1 aventura no fim da sessão. Lembrando que essa recompensa pode ser individual ou para o grupo.
>
>Essa recompensa **não** é aplicada na soma do loot, e pode ser dada somente uma vez.

<div style='margin-top:30px'></div>

<div>

##### Atenção!
<p>Mesmo que tenha duração superior a 9 horas, não será concedido mais de 3 aventuras por sessão. Caso a mesa divida a quest em duas ou mais sessões, os horários serão contados separadamente, respeitando o limite de aventura/hora de cada sessão. 
</div>

#### Desconto de aventura

<div>
Como nem tudo no mundo são flores, haverão casos onde deverão ser descontados algumas recompensas dos jogadores.

| Motivo | Quantidade de Aventuras |
|:-----------|:-------------|
| Uso excessivo de metagame  | -1 aventura |
| Desrespeito com Colegas/Mestre  | -1 aventura<br>-25% do loot |
| Saida antecipada do jogo | A critério do mestre |
| Rage quit | Perde toda recompensa e XP, e deve-se comunicar a moderação|

```
```

#### Gold e Loot 

A recompensa de Gold é proporcional ao número de aventuras da mesa, e cada rank tem sua própria quantia. Caso a sessão tenha jogadores de ranks diferentes, para calcular o loot, deve ser somado os valores individuais.

| Rank | Recompensa em PO (Min - Max)|  Loot (individual) | 
|:-----:|:--------------------:|:---------------------: |
| Filhote de Kobold | 30 - 50 | 25  |
| Prisioneiro de Bugbear | 60 - 100  | 50 |
| Ração de Dragão | 120 - 200 | 100  |
| Orgulho de Beholder |  220 - 300 | 150 |
| Coveiro de Lich | 310 - 400 | 200 |
| Caçador de Tarrasque | 410 - 500  | 250 |
| Lenda Viva | Livre para o mestre definir  | Livre para o mestre definir |

> ##### Exemplo de loot
> O mestre fez uma quest para 5 filhotes de kobold, Filhote I , Filhote II, Filhote III, Neto I e Neto II. A quest durou 8h e 30m.
>
> Cada um ganhou 2 aventuras, pelo tempo de sessão. Filhote II se destacou no roleplay, e ganhou mais uma. Durante a sessão, Filhote III teve de se ausentar por 30 minutos para atender o papagaio que tinha caido do telhado, Neto II se irritou com uma rolagem baixa, e saiu da mesa, e Filhote I acabou fazendo muito metagame.
> 
> O grupo achou 125 PO em item/moedas, e o contratante pagou 35 PO's pelo contrato.
>
> Partindo disso, a recompensa para seus jogadres foram as seguintes:

> Filhote I ganhou 32 PO e 1 aventuras.

> Filhote II ganhou 32 PO e 3 aventuras.

> Filhote III ganhou 32 PO e 2 aventuras, pois o mestre não achou que a ausência dele era motivo de penalidade.

> Neto I ganhou 32 PO e 2 aventuras.

> Neto II não ganhou nada. Como o loot é de (125 + 35) PO, o grupo pode redistribuir o gold que Neto II ganharia, caso o mestre permita, aumentando o gold ganho em 6.4 peças.

##### Itens no loot

Caso queira, pode-se adicionar itens ao loot. Apenas retire de peças de ouro, o valor do item, adicionando-o ao loot final.

Ex: Uma espada mágica custa 300 PO. O loot final do grupo **originalmente** era 900 PO. Com a espada mágica, o loot final fica "600PO + Uma espada mágica".

\page

##### Sistema de Level por Aventuras
| Level | Aventuras (Acumulado)|           Rank         | 
|:-----:|:--------------------:|:---------------------: |
|   1   |          0           | Filhote de Kobold      |
|   2   |          1           | Filhote de Kobold      |
|   3   |          3           | Filhote de Kobold      |
|   4   |          5           | Prisioneiro de Bugbear |
|   5   |          8           | Prisioneiro de Bugbear |
|   6   |         11           | Prisioneiro de Bugbear |
|   7   |         14           | Ração de Dragão        |
|   8   |         17           | Ração de Dragão        |
|   9   |         20           | Ração de Dragão        |
|  10   |         23           | Orgulho de Beholder    |
|  11   |         26           | Orgulho de Beholder    |
|  12   |         30           | Orgulho de Beholder    |
|  13   |         34           | Coveiro de Lich        |
|  14   |         38           | Coveiro de Lich        |
|  15   |         42           | Coveiro de Lich        |
|  16   |         46           | Caçador de Tarrasque   |
|  17   |         50           | Caçador de Tarrasque   |
|  18   |         55           | Caçador de Tarrasque   |
|  19   |         60           | Lenda Viva             |
|  20   |         65           | Lenda Viva             |
</div>

\page
\page 

### 2. Gerenciamento de ficha

Toda vez que terminar sua quest, anote com calma seus ganhos e mencione o gerente de Log para que o mesmo possa atualizar seu histórico.

Para fazer isso, basta seguir modelo abaixo:

> ##### Invocando o Gerente de Log
> 
@Gerente das Log Sheet
<div>Aventuras ganhas: +1 aventura(total 5)</div><div>Vida ganha: (20) + 6+3 (total 29)</div><div>Ouro ganho: 14PO 8PC </div><div>Itens ganhos: 1 espada vorpal</div><div>Nivel ganho: +1 nível de Paladino(total Paladino 3 / Ladino 1)</div><div>Recursos de classe ganhos: 2 pontos de ki/1 ponto de feiticeiro</div>
Demais observações: qualquer coisa que você obtenha a mais com a classe, talentos, melhoria de pontos de atributo, magia e outras coisas.

### 3. Profissões
<div>
O projeto conta com um material extra chamado _"Guia de Profissões"_. Todo conteúdo relacionado a profissões se encontra neste guia, e deve ser utilizado em conjunto com a cartilha do jogador.

A profissão pode ser escolhida **somente** enquanto o personagem for _Filhote de Kobold_.
</div>

### 4. Crafting

<div>
Para criar itens você deve consultar a tabela da respectiva profissão. O tempo e valor de criação, além das regras gerais e específicas de cada profissão estão listados no _Guia de Profissões_.

Utilize o seguinte modelo ao utilizar a área de craft:
<br>

</div>

> ##### Pedido de Craft
>@Seu nome, fabrica: Nome do item + valor de fabricação + categoria que pertence + tempo de duração. @Trsytam

<div>

O responsável pelo craft irá ver seu chamado, anotar seu pedido no calendário e descontar seu
gold no momento que o chamar. Após iniciar, se o trabalho for cancelado, ele reiniciará do
zero.
Ao concluir, o item será adicionado à sua ficha.
</div>

#### Comércio

<div>
Os preços são tabelados, e não negociáveis, exceto para menos. Deve-se atentar as peculiaridades de cada profissão.

Os produtos fabricados, conseguidos em missões assim como comprados de outros jogadores, ou do livro do jogador (exceto itens Muito Raros e Lendários), podem ser adquiridos pelos jogadores, e vendidos através da área de comércio.

Pra vender algo, você oferta a 80% do valor total do item e então o _Trystam_ automaticamente adiciona o ouro na sua conta e o item é vendido. Salvo seja comprado por outro player, ou pela guilda, considera-se que foi vendido para o mercado de Neverwinter.
</div>

\page
<div class='pageNumber auto'></div>

>##### Venda de item
@Seu nome - vende (nome do item + tipo de item + 80% do valor do item ou menos)
@Trsytam

>##### Compra de item
@Seu nome - compra item (nome do item + tipo de item + valor) @trystam.

<div></div>
### 5. Biblioteca

<div>

A biblioteca usada pelos jogadores depende da liberação de assuntos pelo mestre. Sendo assim, o jogador somente poderá pesquisar o que o mestre demandar/apresentar (não haverão pesquisas aleatórias).
As pesquisas poderão ser feitas de segunda a sábado e as respostas virão de domingo até segunda.

Existem dois tipos de pesquisas, condicionadas ao bônus de inteligência do jogador, conforme abaixo.

</div>

> ##### Pesquisa única: 
> Poderá pesquisar um único assunto, por semana. Fazendo isso, conseguirá um bônus maior.
> <div></div>
> ##### Pesquisa Dupla:
> Poderá pesquisar dois assuntos por semana, Fazendo isso, embora aumente a quantidade de itens pesquisados, a atenção é dividida, resultando em bônus menores na hora de lançar o dado.
> <div></div>
> <div></div>
> _O jogador que escolher um tipo de pesquisa, não poderá utilizar o outro durante a semana._

<br>
#### Tabelas de Bônus para pesquisa

| Mod Int | Dupla | Unica |  
|:-------:|:------:| :---: |
| -1 |  +2  | +4 | 
|  0 |  +5 | +10 |
| +1 |  +6 | +12 |
| +2 |  +7 |+14 |
| +3 |  +8 |+16|
| +4 |  +9 |+18|
| +5 |  +10 |+20|

<br>
<div class='descriptive'>##### Rolando um Crítico ou Falha Crítica:

<p>No (20), o pesquisador pode fazer uma pergunta ao mestre ao terminar a pesquisa.
Porém, no (1), o mestre irá informar que aquele assunto não existe, e caso seja uma pesquisa única, o livro contendo o assunto se torna indisponível na biblioteca. Caso seja dupla, o livro ainda está disponível para futuras pesquisas.

</div><div style='margin-top:140px'></div>

#### Pesquisando na prática
O jogador escolhe o assunto lançado pelo mestre e o marcará na pesquisa. Após escolher o(s) assunto(s), determinará se a pesquisa é única ou dupla (para determinar seus bônus de lançamento dos dados), e lançará o D20 somado ao respectivo
bônus (vide tabela).

<div> 
</div>
<br>

>#####  Realizando uma pesquisa
(Seu nome), pesquisa: @(mestre), assunto, pesquisa única,
Bônus +14. (e rola o dado).

<br>

<div class='descriptive'>
##### Resultado das pesquisas

| Rolagem (c/ bônus) | Rank | O que sabe |
|:--:|:-------------| :--- |
| 10 | Amador | O básico |
| 15 | Veterano | Algo a mais|
| 20 | Especialista | Muito |
| 25 | Excepcional | Quase tudo |
| 30 | Mestre | Tudo |

</div>
### 6. Itens Mágicos	

Na medida que evoluem, os personagens vão ganhando itens. Basta atender ao quesito de nível, de acordo com a tabela segunte e as devidas ressalvas.

Itens Muito Raros e Lendários serão obtidos (comprados ou não) através de uma quest, que servirá de Background do item. O jogador deverá comprar um pergaminho de item (vendido pelos escribas, ou pelo dobro do preço no mercado), e comunicar a um mestre, que então fará uma aventura que será voltada a obtenção do item.

| Rank | Categoria do Item |
|:----|:-------------|
| Prisioneiro de Bugbear  | Incomum |
| Ração de Dragão  | Incomum |
| Orgulho de Beholder | Raro |
| Coveiro de Lich | Muito Raro |
| Caçador de Tarrasque | Lendário |
| Lenda Viva | Surpresa | 

\page
<style>
    .phb .classTable {
        border-image-repeat: stretch;
    }
    .phb .descriptive {
        border-image-repeat: stretch;
    }
</style>
<div>
# Lista de preços de itens Mágicos
</div>
<br>

<div class='classTable wide'>

##### Comuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 50 | Consumível | 40 |
| Menor| 150 | Menor | 120 |
| Maior | 150 | Maior | 120 |
| Arma | 300 | Arma | 240  |
| Armadura | 300 + Armadura | Armadura | 240 + Armadura|
</div>

<br>

<div class='classTable wide'>
##### Incomuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 150 | Consumível | 120 |
| Menor| 800 | Menor | 640 |
| Maior | 1300 | Maior | 1040 |
| Arma | 1500 | Arma | 1200  |
| Armadura | 1500 + Armadura | Armadura | 1200 + Armadura||
</div>

<br>

<div class='classTable wide'>
##### Raros
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 300 | Consumível | 240 |
| Menor| 4000 | Menor | 3200 |
| Maior | 6000 | Maior | 4800 |
| Arma | 8000 | Arma | 6400  |
| Armadura | 8000 + Armadura | Armadura | 6400 + Armadura||
</div>

\page
<div>

<h2 id="credits">Credits</h2>
<p><strong>Designer/Produtor:</strong> <a>AlwaysLearning</a></p>
<div>  </div><p><strong>Cover Illustrator:</strong> <a>
Chris Dien</a></p>

<div>  </div><p><strong>Context:</strong> Dungeons and Dragons 5th Edition by Wizards of the Coast, LLC</p>
<div>  </div><p><strong>The Homebrewery:</strong> An amazing tool by <a href="https://www.patreon.com/stolksdorf">Scott Tolksdorf</a></p>
<p><img 
src='http://dfwroleplayers.com/wp-content/uploads/2012/01/dice-polyhedral-stipple.png'
style='position:absolute;mix-blend-mode:multiply;left:0px;bottom:57px;width:53%;'
/></p>
</div><div class="phb" id="p3" data-reactid="39"><style>
  .phb#p3{ display:none; }
</style>
</div>

</pre></code></details>

**Comment by calculuschild** [comment]
It appears to be working fine to me on my end. All of your \page tags create a new page. Could you provide a screenshot maybe that shows the problem on your computer?

**Comment by AlwaysLearning55** [comment]
[https://i.imgur.com/aKj7Nrg.png](url)

As you can see, there is a "missing" piece of info, and also, the \page doesnt work, creating a random, (later requested) page of brew, BUT, if i try to edit it, it just doesnt edit..
[https://i.imgur.com/vPV8nRv.png](url)

(full line of "asdasdsdasdasdasd")

**Comment by Heesp** [comment]
I have a similar issue, \page doesnt create a new page.

**Comment by misthero** [comment]
@AlwaysLearning55  your code is a mess of unopened/unclosed/wrongly opened and closed, unuseful html tags between p, div, a, style

here is a cleaned version but you are going to broke it up again you you aren't a bit more careful

`<style>
  .phb#p1{ text-align:center; }
  .phb#p1:after{ display:none; }
    .phb .classTable {
        border-image-repeat: stretch;
    }
    .phb .descriptive {
        border-image-repeat: stretch;
    }
  .phb{
    width : 210mm;
    height : 297mm;
  }
</style>


<img src='https://i.imgur.com/ApgJhp3.jpg'
style='position:absolute;top:0px;left:0px;width:100%'/>

<img src='https://i.imgur.com/3rDt1rV.png'
style='position:absolute;top:0px;left:0px;width:100%'/>

<img 
  src='http://i.imgur.com/Sa6Nmjx.png'
  style='position:absolute;left:0px;bottom:180px;width:50%' /></p>
<div style='position:absolute;
font-family:\"nodesto\", nodesto, sans-serif;
font-weight:bold;
font-size:20px;
color:white;
bottom:30px;
right:55px;
width:700px;
text-shadow: 1px 1px 2px #000000,-1px 1px 2px #000000,1px -1px 2px #000000,-1px -1px 2px #000000;
filter:opacity(100%)'>
</div>

<div class='pageNumber auto'></div>
\page
 




# Manual do mestre

<div>
Este manual servirá para que os mestres possam localizar todos os elementos e ferramentas que precisar para desenvolvimento de suas aventuras.
</div>

### 1. Sessões e recompensas

Toda campanha tem uma duração esperada. Porém, esse número pode aumentar ou diminuir de acordo com as ações dos jogadores. Para padronizar a recompensa por cada quest, a seguinte tabela é utilizada.



| Duração | Quantidade de Aventuras |
|:-----------|:-------------|
| Até 5h59m  | 1 aventura |
| De 6h a 8h59m  | 2 aventuras |
| De 9h em diante | 3 aventuras |

<div style='margin-top:30px'></div>


> ##### Interpretação e Dificuldade
> Caso a sessão tenha um elevado nível de dificuldade, o mestre poderá conceder mais 1 aventura ao grupo, por tal feito.
>
>O mesmo se aplica no caso de uma destaque pelo roleplay. O jogador em questão, caso tenha interpretado muito bem seu personagem, poderá ser recompensado com mais 1 aventura no fim da sessão. Lembrando que essa recompensa pode ser individual ou para o grupo.
>
>Essa recompensa **não** é aplicada na soma do loot, e pode ser dada somente uma vez.

<div style='margin-top:30px'></div>

##### Atenção!
Mesmo que tenha duração superior a 9 horas, não será concedido mais de 3 aventuras por sessão. Caso a mesa divida a quest em duas ou mais sessões, os horários serão contados separadamente, respeitando o limite de aventura/hora de cada sessão. 



#### Desconto de aventura

Como nem tudo no mundo são flores, haverão casos onde deverão ser descontados algumas recompensas dos jogadores.

| Motivo | Quantidade de Aventuras |
|:-----------|:-------------|
| Uso excessivo de metagame  | -1 aventura |
| Desrespeito com Colegas/Mestre  | -1 aventura<br>-25% do loot |
| Saida antecipada do jogo | A critério do mestre |
| Rage quit | Perde toda recompensa e XP, e deve-se comunicar a moderação|

```
```

#### Gold e Loot 

A recompensa de Gold é proporcional ao número de aventuras da mesa, e cada rank tem sua própria quantia. Caso a sessão tenha jogadores de ranks diferentes, para calcular o loot, deve ser somado os valores individuais.

| Rank | Recompensa em PO (Min - Max)|  Loot (individual) | 
|:-----:|:--------------------:|:---------------------: |
| Filhote de Kobold | 30 - 50 | 25  |
| Prisioneiro de Bugbear | 60 - 100  | 50 |
| Ração de Dragão | 120 - 200 | 100  |
| Orgulho de Beholder |  220 - 300 | 150 |
| Coveiro de Lich | 310 - 400 | 200 |
| Caçador de Tarrasque | 410 - 500  | 250 |
| Lenda Viva | Livre para o mestre definir  | Livre para o mestre definir |

> ##### Exemplo de loot
> O mestre fez uma quest para 5 filhotes de kobold, Filhote I , Filhote II, Filhote III, Neto I e Neto II. A quest durou 8h e 30m.
>
> Cada um ganhou 2 aventuras, pelo tempo de sessão. Filhote II se destacou no roleplay, e ganhou mais uma. Durante a sessão, Filhote III teve de se ausentar por 30 minutos para atender o papagaio que tinha caido do telhado, Neto II se irritou com uma rolagem baixa, e saiu da mesa, e Filhote I acabou fazendo muito metagame.
> 
> O grupo achou 125 PO em item/moedas, e o contratante pagou 35 PO's pelo contrato.
>
> Partindo disso, a recompensa para seus jogadres foram as seguintes:

> Filhote I ganhou 32 PO e 1 aventuras.

> Filhote II ganhou 32 PO e 3 aventuras.

> Filhote III ganhou 32 PO e 2 aventuras, pois o mestre não achou que a ausência dele era motivo de penalidade.

> Neto I ganhou 32 PO e 2 aventuras.

> Neto II não ganhou nada. Como o loot é de (125 + 35) PO, o grupo pode redistribuir o gold que Neto II ganharia, caso o mestre permita, aumentando o gold ganho em 6.4 peças.

##### Itens no loot

Caso queira, pode-se adicionar itens ao loot. Apenas retire de peças de ouro, o valor do item, adicionando-o ao loot final.

Ex: Uma espada mágica custa 300 PO. O loot final do grupo **originalmente** era 900 PO. Com a espada mágica, o loot final fica \"600PO + Uma espada mágica\".
<div class='pageNumber auto'></div>
\page


##### Sistema de Level por Aventuras
| Level | Aventuras (Acumulado)|           Rank         | 
|:-----:|:--------------------:|:---------------------: |
|   1   |          0           | Filhote de Kobold      |
|   2   |          1           | Filhote de Kobold      |
|   3   |          3           | Filhote de Kobold      |
|   4   |          5           | Prisioneiro de Bugbear |
|   5   |          8           | Prisioneiro de Bugbear |
|   6   |         11           | Prisioneiro de Bugbear |
|   7   |         14           | Ração de Dragão        |
|   8   |         17           | Ração de Dragão        |
|   9   |         20           | Ração de Dragão        |
|  10   |         23           | Orgulho de Beholder    |
|  11   |         26           | Orgulho de Beholder    |
|  12   |         30           | Orgulho de Beholder    |
|  13   |         34           | Coveiro de Lich        |
|  14   |         38           | Coveiro de Lich        |
|  15   |         42           | Coveiro de Lich        |
|  16   |         46           | Caçador de Tarrasque   |
|  17   |         50           | Caçador de Tarrasque   |
|  18   |         55           | Caçador de Tarrasque   |
|  19   |         60           | Lenda Viva             |
|  20   |         65           | Lenda Viva             |



### 2. Gerenciamento de ficha

Toda vez que terminar sua quest, anote com calma seus ganhos e mencione o gerente de Log para que o mesmo possa atualizar seu histórico.


Para fazer isso, basta seguir modelo abaixo:


> ##### Invocando o Gerente de Log
> 
@Gerente das Log Sheet
<div>Aventuras ganhas: +1 aventura(total 5)</div><div>Vida ganha: (20) + 6+3 (total 29)</div><div>Ouro ganho: 14PO 8PC </div><div>Itens ganhos: 1 espada vorpal</div><div>Nivel ganho: +1 nível de Paladino(total Paladino 3 / Ladino 1)</div><div>Recursos de classe ganhos: 2 pontos de ki/1 ponto de feiticeiro</div>
Demais observações: qualquer coisa que você obtenha a mais com a classe, talentos, melhoria de pontos de atributo, magia e outras coisas.



### 3. Profissões

O projeto conta com um material extra chamado _\"Guia de Profissões\"_. Todo conteúdo relacionado a profissões se encontra neste guia, e deve ser utilizado em conjunto com a cartilha do jogador.

A profissão pode ser escolhida **somente** enquanto o personagem for _Filhote de Kobold_.

```
```

### 4. Crafting

Para criar itens você deve consultar a tabela da respectiva profissão. O tempo e valor de criação, além das regras gerais e específicas de cada profissão estão listados no _Guia de Profissões_.

Utilize o seguinte modelo ao utilizar a área de craft:
<br>


> ##### Pedido de Craft
>@Seu nome, fabrica: Nome do item + valor de fabricação + categoria que pertence + tempo de duração. @Trsytam

<div>

O responsável pelo craft irá ver seu chamado, anotar seu pedido no calendário e descontar seu
gold no momento que o chamar. Após iniciar, se o trabalho for cancelado, ele reiniciará do
zero.
Ao concluir, o item será adicionado à sua ficha.
</div>

#### Comércio

Os preços são tabelados, e não negociáveis, exceto para menos. Deve-se atentar as peculiaridades de cada profissão.

Os produtos fabricados, conseguidos em missões assim como comprados de outros jogadores, ou do livro do jogador (exceto itens Muito Raros e Lendários), podem ser adquiridos pelos jogadores, e vendidos através da área de comércio.

Pra vender algo, você oferta a 80% do valor total do item e então o _Trystam_ automaticamente adiciona o ouro na sua conta e o item é vendido. Salvo seja comprado por outro player, ou pela guilda, considera-se que foi vendido para o mercado de Neverwinter.

<div class='pageNumber auto'></div>
\page


>##### asd do asd + tipo de item + valor) @trystam.

### 5. Biblioteca

<div>

A biblioteca usada pelos jogadores depende da liberação de assuntos pelo mestre. Sendo assim, o jogador somente poderá pesquisar o que o mestre demandar/apresentar (não haverão pesquisas aleatórias).
As pesquisas poderão ser feitas de segunda a sábado e as respostas virão de domingo até segunda.

Existem dois tipos de pesquisas, condicionadas ao bônus de inteligência do jogador, conforme abaixo.

</div>

> ##### Pesquisa única: 
> Poderá pesquisar um único assunto, por semana. Fazendo isso, conseguirá um bônus maior.
> <div></div>
> ##### Pesquisa Dupla:
> Poderá pesquisar dois assuntos por semana, Fazendo isso, embora aumente a quantidade de itens pesquisados, a atenção é dividida, resultando em bônus menores na hora de lançar o dado.
> <div></div>
> <div></div>
> _O jogador que escolher um tipo de pesquisa, não poderá utilizar o outro durante a semana._

<br>
#### Tabelas de Bônus para pesquisa

| Mod Int | Dupla | Unica |  
|:-------:|:------:| :---: |
| -1 |  +2  | +4 | 
|  0 |  +5 | +10 |
| +1 |  +6 | +12 |
| +2 |  +7 |+14 |
| +3 |  +8 |+16|
| +4 |  +9 |+18|
| +5 |  +10 |+20|

<br>
<div class='descriptive'>##### Rolando um Crítico ou Falha Crítica:

<p>No (20), o pesquisador pode fazer uma pergunta ao mestre ao terminar a pesquisa.
Porém, no (1), o mestre irá informar que aquele assunto não existe, e caso seja uma pesquisa única, o livro contendo o assunto se torna indisponível na biblioteca. Caso seja dupla, o livro ainda está disponível para futuras pesquisas.

</div><div style='margin-top:140px'></div>




#### Pesquisando na prática
O jogador escolhe o assunto lançado pelo mestre e o marcará na pesquisa. Após escolher o(s) assunto(s), determinará se a pesquisa é única ou dupla (para determinar seus bônus de lançamento dos dados), e lançará o D20 somado ao respectivo
bônus (vide tabela).

<div> 
</div>
<br>


>#####  Realizando uma pesquisa
(Seu nome), pesquisa: @(mestre), assunto, pesquisa única,
Bônus +14. (e rola o dado).

<br>

<div class='descriptive'>
##### Resultado das pesquisas


| Rolagem (c/ bônus) | Rank | O que sabe |
|:--:|:-------------| :--- |
| 10 | Amador | O básico |
| 15 | Veterano | Algo a mais|
| 20 | Especialista | Muito |
| 25 | Excepcional | Quase tudo |
| 30 | Mestre | Tudo |



</div>
### 6. Itens Mágicos\t

Na medida que evoluem, os personagens vão ganhando itens. Basta atender ao quesito de nível, de acordo com a tabela segunte e as devidas ressalvas.

Itens Muito Raros e Lendários serão obtidos (comprados ou não) através de uma quest, que servirá de Background do item. O jogador deverá comprar um pergaminho de item (vendido pelos escribas, ou pelo dobro do preço no mercado), e comunicar a um mestre, que então fará uma aventura que será voltada a obtenção do item.

| Rank | Categoria do Item |
|:----|:-------------|
| Prisioneiro de Bugbear  | Incomum |
| Ração de Dragão  | Incomum |
| Orgulho de Beholder | Raro |
| Coveiro de Lich | Muito Raro |
| Caçador de Tarrasque | Lendário |
| Lenda Viva | Surpresa | 

<div class='pageNumber auto'></div>
\page

<div>
# Lista de preços de itens Mágicos
</div>
<br>

<div class='classTable wide'>
##### Comuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 50 | Consumível | 40 |
| Menor| 150 | Menor | 120 |
| Maior | 150 | Maior | 120 |
| Arma | 300 | Arma | 240  |
| Armadura | 300 + Armadura | Armadura | 240 + Armadura|
</div>

<br>

<div class='classTable wide'>
##### Incomuns
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 150 | Consumível | 120 |
| Menor| 800 | Menor | 640 |
| Maior | 1300 | Maior | 1040 |
| Arma | 1500 | Arma | 1200  |
| Armadura | 1500 + Armadura | Armadura | 1200 + Armadura||
</div>

<br>

<div class='classTable wide'>
##### Raros
|  | Preço de Compra || Preço de Venda  |
|:---|:---:|:---|:---:|
| Consumível | 300 | Consumível | 240 |
| Menor| 4000 | Menor | 3200 |
| Maior | 6000 | Maior | 4800 |
| Arma | 8000 | Arma | 6400  |
| Armadura | 8000 + Armadura | Armadura | 6400 + Armadura||
</div>

<div class='pageNumber auto'></div>

\page


## Credits
**Designer/Produtor:** AlwaysLearning
**Cover Illustrator:** Chris Dien


**Context:** Dungeons and Dragons 5th Edition by Wizards of the Coast, LLC
**The Homebrewery:** An amazing tool by <a href=\"https://www.patreon.com/stolksdorf\">Scott Tolksdorf</a>
<img src='http://dfwroleplayers.com/wp-content/uploads/2012/01/dice-polyhedral-stipple.png'
style='position:absolute;mix-blend-mode:multiply;left:0px;bottom:57px;width:53%;' />





<div class='pageNumber auto'></div>`

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a few months and it is assumed the problem was solved.

@AlwaysLearning55 If you are still experiencing this issue, feel free to reopen and provide information.
