### ISSUE TITLE
Scrolling exception: Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by schemen** [stolksdorf/homebrewery#733]
## Description

For context, I have a lot of spare hosting infrastructure and I am trying to dockerize & rehost several applications so we have some back up in case or offer the services for other dnd tool developers.

I am trying to host it, because it seems that the original author is not updating the website anymore.  I have dockerized the application, currently running at https://homebrewery.hoengg.tech with version 2.8.0. The main issue is that I do not understand react/node as much as basic work with it, I package applications into containers and run them.

I am currently running into the problem when I scroll, I receive the error:

`Uncaught TypeError: Cannot read property 'scrollTop' of null`

**How to reproduce** :
The introduction letter is enough already, if visit https://homebrewery.hoengg.tech you can try to scroll on the preview window and it will immediately crash, you have some lines of console output.

**Comment by AlexeySachkov** [comment]
Hi,

My guess: root cause of the bug is the react version.
As I can see in console: 
```
libs.js:3181 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

From `package.json`:
```
"react": "^16.3.1"
```

Try to remove this `^` and rebuild application.

**Comment by schemen** [comment]
I see! I'll try that and see what happens

**Comment by schemen** [comment]
@AlexeySachkov This has sadly not helped with the scrolling issue. Any other idea what this might be?

**Comment by AlexeySachkov** [comment]
@schemen, I have no other ideas, sorry. I'm not really familiar with all of these node.js/react/other stuff. 
Maybe @Rae2che5 can help you.

**Comment by Rae2che5** [comment]
Thanks for the ping, @AlexeySachkov.

@schemen, firstly, great idea to provide Docker images -- I think we'd be happy to accept PRs for `Dockerfile`s to make it easier.

I can indeed reproduce the problem on the version hosted by you, but not in a local dev build. Could you share the dockerfile, and/or push the image somewhere I can pull it from?

**Comment by schemen** [comment]
@Rae2che5 Yes of course!

This is the docker file:
```
FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

ENV NODE_ENV=docker

# For some reason it requires a --force else it has issue with fsevent
RUN npm install --force
RUN npm run build

EXPOSE 8000
CMD [ "npm", "start" ]
```
I've created a docker.json config file in the config folder to connect it to the mongodb.

**Comment by Rae2che5** [comment]
Thanks, tracked it down -- one of those "how did this ever work?" cases. #735 should fix it.

**Comment by Rae2che5** [comment]
Also opened #734 for basic docker support; further refinements welcome!

**Comment by schemen** [comment]
I can now confirm that it is indeed working, I've also done some refinements to the docker image and I will provide a PR or add some information to #734 soon!

The running example is https://homebrewery.hoengg.tech, hosted on a docker swarm cluster :)
