### ISSUE TITLE
Homebrewery website is messed up

### ISSUE THREAD

**Issue by QueenLilly** [stolksdorf/homebrewery#741]
The site worked fine for me a week ago, but the other day when I went to start a new project I found this. On Chrome, Edge, and even on another computer get the same resutls. The d20 is massive and the text/links are listed below in plain text. All the links give similar results.
![image](https://user-images.githubusercontent.com/42725710/44635888-8bb61080-a976-11e8-8c33-8c308f1a9bae.png)

**Comment by QueenLilly** [comment]
Unfortunately, refreshing does not solve it for me. Also neither does clearing my cache, logging out, using different browsers, using my phone, and using other internet.

**Comment by LeviRosol** [comment]
Try a forced refresh - cmd+shift+r in OSX, or ctrl+f5 in windows.

**Comment by QueenLilly** [comment]
Sweet, it worked! Thank you!
