### ISSUE TITLE
Bug with Descriptive Box

### ISSUE THREAD

**Issue by kappa95** [stolksdorf/homebrewery#742]
Hi, i report this bug during the printing in PDF. When I'm saving my file in PDF the border of the descriptive box looks like the photo attached.
![schermata da 2018-08-27 14-14-20](https://user-images.githubusercontent.com/42738531/44659752-86ec6d80-aa05-11e8-9576-302b4faa29e8.png)

**Comment by calculuschild** [comment]
Looks like a duplicate of #683.

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400).
