### ISSUE TITLE
Make note at the end of the page

### ISSUE THREAD

**Issue by marcuswallace1991** [stolksdorf/homebrewery#743]
Hello, I'd like to know how to make note at the end of the page (I need to insert credit for pictures, because I use big pictures and I cannot insert the name under them), can someone help me? 
Ty

**Comment by ericscheid** [comment]
Like this:

```
<div class='footnotes wide'>
Image credits:
1. credit for first image
2. another credit
</div>

<style>
.phb .footnotes {
    position: absolute;
    bottom: 32px;
    z-index: 150;
    font-size: .7em !important;
    color: #666  !important;
  }    
.phb .footnotes p { 
  margin:0;
  padding:0;
  }
</style>
```

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @marcuswallace1991
