### ISSUE TITLE
PDF not saving correctly

### ISSUE THREAD

**Issue by TheLadyLoon** [stolksdorf/homebrewery#745]
## Description
I've created a brew and clicked the "Get PDF" button. It created the file on a separate tab that looked great. I went to "Print" and selected the PDF option. The final output didn't look like the page, but started with a blank page and then all the features were listed in a single column on one side of the page. 

http://homebrewery.naturalcrit.com/print/BJwPULNvX?dialog=true

**Comment by Hu3diger** [comment]
Hello, I also had the same problem, clicking "Get PDF", redirects to a page, where it appears all right (http://homebrewery.naturalcrit.com/print/H1rEugvPm?dialog=true), but when clicking print, it is in a totally strange way.

**Comment by thistlemilly** [comment]
I'm finding the document is not updating as i'm putting new information in and the auto save function is sitting on "saving..." without actually completing the action. http://homebrewery.naturalcrit.com/edit/rJ45QcAXrX

**Comment by TheLadyLoon** [comment]
Thanks, but that didn't seem to help.

**Comment by misthero** [comment]
can you explay what happen when you say " it is in a totally strange way."

**Comment by misthero** [comment]
@TheLadyLoon in your case you are using too much column breaks

```
```
![image](https://user-images.githubusercontent.com/3662610/44954046-76bd0e00-ae9d-11e8-96fe-6c16d3f5d8e0.png)

**Comment by TheLadyLoon** [comment]
Thanks Luca... I've cleaned those up. However, it still isn't printing
properly.
The first page endges up being blank, then the next page only has the first
left column, and I can see the top of the right column at the bottom. So it
isn't actually keeping the columns in their places.
Page one - blank
page two - left column
page three - blank
page four - left column
page five - blank
etc.etc.etc

TIA

**Comment by misthero** [comment]
I think you have to choose A4 page format in print dialog

![image](https://user-images.githubusercontent.com/3662610/44954257-a79e4280-ae9f-11e8-9419-73a468fea050.png)

![image](https://user-images.githubusercontent.com/3662610/44954284-f21fbf00-ae9f-11e8-8580-6d6f2e836897.png)


you also have to include the code I pasted before https://github.com/stolksdorf/homebrewery/issues/745#issuecomment-417870383

since your table is going to break up

**Comment by TheLadyLoon** [comment]
That didn't change anything. For whatever reason, it isn't maintain the
columns when printed. I must be missing something in there.

I'm using windows, if that makes any difference. Your print dialogue is
different to mine. It was already set to A4.

**Comment by TheLadyLoon** [comment]
It appears the issue has to due with using Firefox. Microsoft edge seems to
be "working" although it doesn't include the background with the print.
I'll play with it more, but a least it's in a better spot now.

**Comment by misthero** [comment]
wait.. firefox? edge? you MUST use chrome for the hombrewery site to work...

**Comment by TheLadyLoon** [comment]
It would be helpful if that was actually mentioned somewhere on the
website. But nevermind. Thanks for your help.

**Comment by misthero** [comment]
it is, the orange warning in the screenshot appear when you enter the site on the wrong browser. If you close it will never bother you again unless you clear your cookies.

anywhay glad to help

**Comment by Hu3diger** [comment]
Hello,
This code  
`<style>
.phb .classTable {
border-collapse: separate;
border-image-repeat: stretch;
}
</style>`
helped, but at the bottom of the page is a white stripe, could anyone tell me what it could be?

**Comment by TheLadyLoon** [comment]
I think it's a difference between printing formats. A4 is not 8x10 so
you'll need to put in the right dimensions for the print.... that's my
assumption.

**Comment by Hu3diger** [comment]
Thanks, I put the Letter format and it's 100%.
Thank you again.

**Comment by TheLadyLoon** [comment]
Cool, no problem.

**Comment by AlexeySachkov** [comment]
@Hu3diger, You can print it as A4, but you need to insert an `A4 pagesize` macro into your brew: look at `Print` menu in Homebrewery editor.

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
