### ISSUE TITLE
Pdf not displaying correctly

### ISSUE THREAD

**Issue by iastreb** [stolksdorf/homebrewery#748]
When I convert a brew into pdf, I consistently have two problems. Class tables/wide tables come out looking distorted, with the framing reversed in places, and cutting into the lines and the text.

A similar thing happens to the "notes" feature. The content is still readable, but the notes "box" comes out with a series of unconnected dots that look like quotation marks, instead of a solid perimeter line.

**Comment by iastreb** [comment]
Addenda:

1) I tried the patch for the class table recommended in another thread for the class table, and that seems to have fixed that specific problem.

2) The second problem concerned the tan "descriptive text box", not the green "notes" feature. The quote-like dots appear on every side of the box, connected by a line on the left and right, and without such a line on the top and bottom.

**Comment by AlexeySachkov** [comment]
Hi, @iastreb, could you please put a `share` link to your brew here?

**Comment by iastreb** [comment]
Actually, I figured out how to fix it, thanks. You just have to put the
same patch at the start of the brew, and replace 'classTable' with
'descriptive'.
