### ISSUE TITLE
Hey man, love the site, been using it for a while to help unify the notes on my own DnD world. Just wondering if it was possible to create a column changing feature to alter some pages as 3 column rather than 2. I've been trying to format a new spell list much like the one from "Xanathars Guide" but am currently limited by the tools available. Regards,

### ISSUE THREAD

**Issue by Cassattack** [stolksdorf/homebrewery#749]
## Before you submit

- Support questions are better asked on the subreddit [r/homebrewery](https://www.reddit.com/r/homebrewery/)
- Read the [contributing guidelines](https://github.com/stolksdorf/homebrewery/blob/master/contributing.md).
- If it's an issue, please make sure it's reproducible
- Ensure the issue isn't already reported.

*Delete the above section and the instructions in the sections below before submitting*

## Description

If this is a *feature request*, explain why it should be added. Specific use-cases are best.

For *bug reports*, please provide as much *relevant* info as possible.

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
Try adding the following to the top of your brew:

`
    .phb{
        -webkit-column-count: 3;
        -webkit-column-width: 5cm;
    }
`

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Cassattack
