### ISSUE TITLE
Different account

### ISSUE THREAD

**Issue by Themuffinbeha** [stolksdorf/homebrewery#752]
So i love the website, how ever me being a giant doof, I by accident created 2 different accounts, and i cant seem to find the log off button.

**Comment by AlexeySachkov** [comment]
Hi, @Themuffinbeha 

Please proceed to [naturalcrit.com/login](http://www.naturalcrit.com/login): there is a `logout` link under the login form

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

@Themuffinbeha  If you are still experiencing this issue, feel free to reopen and provide information.
