### ISSUE TITLE
Preview not working, only pdf

### ISSUE THREAD

**Issue by Rikart1397** [stolksdorf/homebrewery#757]
3/4hs ago I was editing my file and all went well. I shared the file with my friend, and around 10 min ago he wrote and he said that he couldn't see anything. I checked and the code is the same, but the preview (the actual page) is gone, and I had to send him the pdf. How do I fix it? It happens only for this file, and copy-pasting the code doesn't fix it. 

[https://i.imgur.com/oxAdE8o.png](url) 
In this pic you can see that it says "1/7" pages, but nothing is shown.

**https://homebrewery.naturalcrit.com/share/BkQFEz59dm** :

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# Regolamento 
Benvenuti nel GDR free di Disenchantment, moderato da gente brutta e scritto da gente ancora più brutta. 
Ogni aborto partorito qui sotto è di proprietà intellettuale di chiunque ammette che Petyr Baelish è il personaggio migliore di Game of Thrones insieme a Tywin. Ora che ci siamo tolti gli avvocati dalle spalle, inizio a spiegarvi come si gioca.

## Come si gioca?
Bella domanda Me del passato. Ovviamente il gioco segue le solite regole del mettere un'azione tra asterischi, pensiero tra virgolette e testo senza nulla per dialogo. Per quanto riguarda però ogni azione non consueta e il combattimento ci sono molti fattori che devono essere presi in considerazione. 

Iniziamo dalle cose basilari: le statistiche.

### Statistiche
Esistono 3 statistiche in questo mondo: Vigore, Prontezza e Intelletto.
Per fare degli esempi, un guerriero avrà il Vigore molto alto, un ladro la Prontezza e un mago l'Intelletto.

- ** il Vigore ** indica quanto forte e robusto sia un personaggio. Resistenza, costituzione, solidità e forza fisica fanno riferimento a questa caratteristica. Il Vigore non è di per sé legato alla taglia, ma è un parametro assoluto. Il Vigore governa un ampio spettro di azioni; forzare una porta, viaggiare per giorni senza nutrirsi e resistere alle malattie. È anche il primo indicatore di quanto danno fisico possa sopportare una creatura. Personaggi forti, resistenti e propensi a combattere dovrebbero preferire questa caratteristica alle altre.

- ** la Prontezza ** descrive quanto agile e fisicamente coordinato sia un personaggio. Comprende la rapidità, il movimento, la destrezza e i riflessi. La Prontezza governa azioni molto diverse fra loro, come schivare un attacco, muoversi silenziosamente o lanciare oggetti con precisione. Personaggi agili, furtivi o veloci, come pure quelli che combattono a distanza, propenderanno per una buona Prontezza.

- ** l'Intelletto ** determina l'astuzia, il grado di erudizione e in una certa maniera il fascino del personaggio. Comprende l'intelligenza, la saggezza, il carisma, l'educazione, il discernimento, la forza di volontà e il fascino. Si usa per raccontare menzogne convincenti, usare poteri magici e creare oggetti magici. Personaggi che interagiscono col prossimo, studiosi e sapienti di artefatti magici dovrebbero poter contare su un elevato Intelletto.

___
#### Riserve
Tutto chiaro, spero. Questi punteggi avranno una Riserva attuale e una Riserva massima ( 7/13 ad esempio). Ogni azione complessa o l'uso di arti marziali o magiche comporta l'uso di punti dalla vostra Riserva, che non verranno ripristinati prima di un riposo o con l'uso di pozioni varie. 

Quasi ogni azione può essere "potenziata", usando punti extra della vostra riserva; se si decide di potenziare un'azione, si tolgono 3 punti dalla Risorsa di competenza e la difficoltà viene abbassata di un grado. Per abbassarla ulteriormente è possibile impiegare altri livelli di potenziamento cumulativi pagando 2 per ogni livello. Ogni livello extra equivale un grado di difficoltà in meno. 

#### Danni
Quando un attacco colpisce un bersaglio di solito questi subisce dei danni che vanno sottratti da una delle sue Riserve di Caratteristica, il più delle volte quella di Vigore. Ogni volta che un attacco infligge semplicemente "danni", senza specificare alcunché, sono danni inflitti alla Riserva di Vigore. Danni psichici, frutto di attacchi mentali, sottraggono punti alla Riserva di Intelletto; quelli alla Prontezza sono prevalentemente danni Fisici, ma sono rari gli attacchi che possono infliggerli.

#### Come si muore?

Dopo che hai portato a 0 una Riserva, si passa a far danni alla Riserva di Vigore, poi della Prontezza e poi dell'Intelletto.
Ovviamente se una di queste stava già a 0 la salti.

##### Indebolito

Appena una Riserva va a 0 sei indebolito, e ogni livello di potenziamento costa 1 punto in più. È lo status di chi sia stato ferito o leso. 

##### Debilitato

Con due Riserve a 0 diventi debilitato, uno stato di salute critico, dove la tua unica azione è quella di muoversi strisciando. Se la Riserva della Prontezza è a 0 non puoi neanche muoverti.

##### Morto

A 3 riserve a 0 sei Morto. Fine. Capolinea. Niente rimborsi.

#### Recuperare Punti nelle Riserve

Per non essere uno zombie che cammina o semplicemente me quando mi sveglio la mattina presto, dovete riposare. Dopo 8h di sonno senza grandi interruzioni vengono ripristinate tutte le Riserve, a meno che un Admin o Moderatore non dice il contrario perchè magari siete stati maledetti o avete ricevuto ferite gravi. 

È possibile anche recuperare punti in determinate Riserve con pozioni apposite, anche se molto molto rare. 

\page

# Assassino
___
E quindi sei un'assassino o un bandito, cresciuto nell'illegalità e senza scrupoli.

## Cose fighe che puoi fare

Essendo un Assassino sei specializzato nelle seguenti cose. Il grado difficoltà per ogni azione legata ad esse viene ridotto di uno.

<div class='classTable'>
##### Le caratteristiche dell'Assassino
| Caratteristica | Riserva Iniziale |
|:---:|:---:|
| Vigore | 10 |
| Prontezza | 11 |
| Intelletto | 7 |
</div>

<div class='descriptive'>
Oltre ai punti qui sopra hai 6 punti caratteristica da distrubuire come vuoi te.
</div>

#### Competenze
** Strumenti** : nessuno </br>
** Azioni** : Scegli tre tra: Acrobazie, Creare trappole, Intimidire , Nascondersi, Raggirare. </br>
** Armi ed Armature ** : Armi leggere, Armature Leggere.

## Sbloccare nuove abilità
Ogni settimana passata, si guadagna un Punto Maestria(PM) da spendere per imparare nuove abilità speciali. 
Si inizia con due Punti Maestria.

#### Abile scalatore
L'assassino è abituato a vivere nelle città, e dalla sua esperienza ha imparato come muoversi al meglio tra gli edifici per sfuggire alla giustizia. è considerato addestrato in ogni azione compiuta per arrampicarsi o saltare da un tetto ad un altro. Facoltà.

#### Addestrato senz'Armatura 
L'assassino è addestrato nelle azioni difensive riguardanti la Prontezza quando non insossa armature. Facoltà.

#### Addestrato alle Armature Medie
L'assassino può indossare armature medie per lunghi periodi senza affaticarsi, e sa compensare l'impaccio dato dalle imbottiture. Diminuisce il costo in Vigore all'ora delle armature medie, e la riduzione della Riserva di Prontezza, di 2. Facoltà.

</br></br></br>

#### Affondo (1 punto Vigore )
Una stoccata poderosa con un'arma in mischia, che infligge 1 danno aggiuntivo se l'arma ha un'estremità affilata o appuntita. Azione.

#### Competenza nelle Armi
L'assassino è addestrato ad attaccare con un tipo di armi leggere o medie. Facoltà.

#### Maestro dell'inganno
L'assassino si è addestrato nel raggirare e nel mascherarsi agli occhi inesperti, aumentando di uno il grado difficoltà per scoprirlo. Facoltà.

#### Maestro dello scasso
L'assassino dopo aver passato molto tempo nell'ambiente criminale ha imparato alcuni trucchi del mestiere. Diventa addestrato nello scasso, riducendo di uno la difficoltà nell'aprire serrature. Facoltà.

#### Perforare ( 1 punto Prontezza )
Un attacco a distanza preciso e penetrante, che infligge 1 danno aggiuntivo se l'arma ha un'estremità appuntita. Azione.

#### Tutt'uno con le ombre ( 1 punti Prontezza)
Quando si trova in penombra o oscurità, l'assassino può sparire alla vista dell'occhio non allenato. Il tiro compiuto dall'assassino per nascondersi ha 2 gradi in meno di difficoltà. Azione.

#### Fendente ( 2 punti Prontezza )
Un attacco rapido con un'arma affilata o appuntita, dal quale è difficile difendersi. La difficoltà dell'attacco viene diminuita di un grado, ma in caso di successo, l'attacco infligge 1 danno in meno del normale. Azione.

#### Finta ( 2 punti Prontezza )
Se l'assassino usa un'azione per creare un diversivo e confondere l'avversario, nel round successivo ne trattà vantaggio. La difficoltà dell'attacco in mischia verrà diminuita di 1 grado e, in caso di successo, l'attacco infliggerà 4 danni aggiuntivi. Azione.

#### Ricaricare ( 1 punto Prontezza )
Quando usa un'arma che normalmente richiederebbe di essere ricaricata (come nel caso di una balestra), l'assassino può invece ricaricare e far fuoco come parte della stessa azione. Facoltà.

#### Vipera della morte
L'assassino si è allenato nell'uso di veleni e pozioni, imparando ad unirli con le sue arti. Non ha più bisogno di fare un tiro per evitare di avvelenarsi quando ricopre lame o munizioni con del veleno, ed è capace di creare veleni basilari se ha accesso ai materiali. Facoltà.

\page

#### Attacco in Salto ( 5 punti Vigore )
L'assassino effetta un salto come parte di un attaco. Se l'attacco va a segno infligge 3 danni aggiuntivi e getta per terra il nemico. In caso contrario, l'assassino può comunque sferrare l'attacco, ma senza infliggere danni aggiuntivi e gettare atterra il nemico. Azione.
</br></br></br></br></br></br></br></br>
#### Competenza nelle armi
L'assassino è addestrato ad attaccare con un tipo di armi, anche uno con cui sia già addestrato. Può scegliere tra armi leggere o medie. Se è già addestrato negli attacchi con quel tipo di armi diventa specializzato, abbassando di un altro grado la difficoltà delle azioni con quell'arma. Facoltà.

#### Colpo di Grazia ( 5 punti Vigore )
Se un nemico è prono, stordito, malfermo o comunque incapace di difendersi al momento dell'attacco, usando questa tecnica l'assassino infligge 6 danni aggiuntivi con un attacco. Facoltà.

#### Guerriero capace
Gli attacchi dell'assassino infliggono 1 danno aggiuntivo. Facoltà.

# Guerriero
___
Combattenti versatili, che hanno fatto delle arti marziali la sua vita. Spada e scudo, spadone o mazzafrusto, innumerevoli sono le armi da loro usate con maestria.

## Cose fighe che puoi fare

<div class='classTable'>
##### Le caratteristiche del Guerriero
| Caratteristica | Riserva Iniziale |
|:---:|:---:|
| Vigore | 11 |
| Prontezza | 10 |
| Intelletto | 7 |
</div>

<div class='descriptive'>
Oltre ai punti qui sopra hai 6 punti caratteristica da distrubuire come vuoi te.
</div>

#### Competenze
** Strumenti ** : nessuno </br>
** Azioni ** : Scegli tre tra: Addestrare Animali e Cavalcare, Arrampicarsi, Atletismo, Intimidire, Sopravvivenza. </br>
** Armi ed Armature ** : Tutte le armi non esotiche, Armature Leggere, Medie e Pesanti. </br>

## Sbloccare nuove Abilità 
Ogni settimana passata, si guadagna un Punto Maestria(PM) da spendere per imparare nuove abilità speciali. Si inizia con due Punti Maestria. 

#### Abituato alle armature
Il guerriero può indossare armature per lunghi periodi di tempo senza affaticarsi, e sa compensare l'impaccio arrecato dalle corazze. Diminuisce il costo in Vigore all'ora delle armature, e la riduzione della riserva di Prontezza, di 2. Facoltà.

#### Addestramento fisico
Il guerriero è addestrato in un'abilità a sua scelta tra: nuotare, saltare, scalare, nelle azioni di equilibrio o azioni simili. Facoltà.

#### Addestrato senza armatura
Il guerriero è addestrato nelle azioni difensive di Prontezza quando non indossa armature. Facoltà.

#### Affondo ( 1 punto Vigore )
Una stoccata poderosa con un'arma in mischia, che infligge 1 danno aggiuntivo se l'arma ha un'estremità affilata o appuntita. Azione.

#### Il Corpo è la mia arma
Gli attacchi senz'armi del guerriero vengono considerati come armi medie anzichè armi leggere. Facoltà.

#### Perforare ( 1 punto Prontezza )
Un attacco a distanza preciso e penetrante, che infligge 1 danno aggiuntivo se l'arma ha un'estremità appuntita. Azione.

#### Schianto ( 1 punto Vigore )
Un attacco in mischia contundente, che infligge 1 danno in meno ma frastorna il bersaglio per un round, durante il quale le difficoltà di tutte le sue azioni vengono aumentate di 1 grado. Azione.

#### Allungo ( 2 punti Vigore)
Una difficile mossa di combattimento, volta a colpire un punto scoperto nelle difese del nemico tramite un affondo misurato. La difficoltà dell'attacco è aumentata di un grado, ma se l'attacco ha successo, infligge 4 danni aggiuntivi. Azione.

\page

#### Colpo disarmante ( 2 punti Prontezza )
Il guerriero tenta di disarmare il suo avversario, sfidandolo in una prova di Prontezza contrapposta. Se il guerriero supera il suo nemico, entra in possesso della sua arma, e può lanciarla ad una distanza media come parte di questa stessa azione. Azione.

#### Competenza nelle armi
Il guerriero è addestrato ad attaccare con un tipo di armi, anche uno con cui sia già addestrato. Può scegliere tra armi leggere o medie. Se è già addestrato negli attacchi con quel tipo di armi diventa specializzato, abbassando di un ulteriore grado la difficoltà delle azioni con quell'arma. Facoltà.

#### Addestrato nella difesa
Il guerriero è addestrato in un tipo di difesa (Vigore, Prontezza, Intelletto). Questa tecnica di combattimento può essere selezionata fino a 3 volte, scegliendo ogni volta un tipo diverso di difesa. Facoltà.

#### Fendente ( 2 punti Prontezza )
Un attacco rapido con un'arma affilata o appuntita, dal quale è difficile difendersi. La difficoltà dell'attacco viene diminuita di un grado ma, in caso di successo, l'attacco infligge 1 danno in meno del normale. Azione.

#### Fracassare ( 2 punti Vigore )
Un poderoso colpo con un'arma contundente, sferrato a due mani (o con entrambe le braccia o gambe, se è un attacco senz'armi). Quando usa questa tecnica di combattimento il guerriero subisce una penalità di -1 al tiro per colpire, ma infligge 3 danni aggiuntivi. Azione.

#### Incalzare ( 2 punti Prontezza )
Quando il guerriero abbatte un nemico può sferrare immediatamente un altro attacco, nello stesso turno, contro un altro nemico entro la sua portata. Questa facoltà può essere usata sia con armi da mischia che a distanza. Facoltà.

#### Squarciare ( 2 punti Vigore )
Un fendente tremendo con un'arma tagliente, sferrato ruotando le braccia (l'arma deve essere impugnata con entrambe le mani). Quando usa questa tecnica di combattimento il guerriero subisce una penalità -1 ai tiri per colpire, ma infligge 3 danni aggiuntivi. Azione.

#### Attacco Roteante ( 5 punti Prontezza )
Il guerriero può attaccare fino a cinque bersagli in mischia entro la sua portata, ciascuno come parte della stessa azione, in un round. Deve effettuare tiri separati per ogni attacco. Qualsiasi cosa modifichi il tiro per colpire o i danni si applica a tutti gli attacchi. Azione.

#### Esperto d'armatura
I benefici della capacità *Abituato alle Armature* incrementano: ora il guerriero diminuisce il costo in Vigore all'ora per indossare armature e la riduzione della riserva di Prontezza di 3. 

#### Guerriero capace
Gli attacchi del guerriero infliggono 1 danno aggiuntivo. Facoltà.

#### Provetto difensore
Il guerriero ottiene bonus +1 all'Armatura quando ne indossa una. Facoltà.

#### Parata  ( 5 punti Prontezza )
Il guerriero può deflettere rapidamente gli attacchi. Quando usa questa tecnica il glaive diminuisce di un grado, per 10 round, la difficoltà di tutte le azioni difensive di Prontezza. Facoltà.
 
 

# Cacciatore
___
I cacciatori, combattenti delle terre selvagge, sono specializzati nel dare la caccia ai mostri che minacciano i confini del mondo civilizzato, che si tratti di razziatori umanoidi, bestie e mostruosità inferocite, terribili giganti o letali draghi. Imparano a seguire le tracce delle loro prede allo stesso modo di un predatore, aggirandosi furtivamente nelle terre selvagge e nascondendosi tra arbusti e detriti.

## Cose fighe che puoi fare

<div class='classTable'>
##### Le caratteristiche del Cacciatore
| Caratteristica | Riserva Iniziale |
|:---:|:---:|
| Vigore | 9 |
| Prontezza | 11 |
| Intelletto | 8 |
</div>

<div class='descriptive'>
Oltre ai punti qui sopra hai 6 punti caratteristica da distrubuire come vuoi te.
</div>

#### Competenze
** Strumenti ** : Coltello da falegname (ti fai le frecce e simili) </br>
** Azioni ** : Scegli tre tra: Addestrare Animali e Cavalcare, Conoscenze Geografiche, Nascondersi, Percezione, Sopravvivenza. </br>
** Armi ed Armature ** : Armi leggere, archi e balestre, Armature Leggere e Medie. </br>

## Sbloccare nuove Abilità 
Ogni settimana passata, si guadagna un Punto Maestria(PM) da spendere per imparare nuove abilità speciali. Si inizia con due Punti Maestria. 

\page

#### Abituato alle Armature
Il cacciatore può indossare armature per lunghi periodi di tempo senza affaticarsi, e sa compensare l'impaccio arrecato da esse. Diminuisce il costo in Vigore all'ora delle armature, e la riduzione della riserva di Prontezza, di 2. Facoltà.

#### Compagno Animale
Durante i suoi viaggi il cacciatore ha trovato una bestia alla quale si è affezionato. Questa bestia obbedisce ai comandi del cacciatore al meglio delle sue possibilità. Gli admin vi odieranno ma parlate con loro per le statistiche della bestia. Facoltà.

#### Creare Trappole
Usando anche i materiali più basilari, il cacciatore è in grado di creare trappole. Da discutere con un admin per la difficoltà nella creazione della trappola, che varia con lo scopo della trappola, la qualità dei materiali usati e la facilità nel reperirli. Facoltà.

#### Mimetismo ( 1 punto Intelletto )
Con i suoi anni passati nelle foreste, il cacciatore è in grado di mimetizzarsi quasi alla perfezione in un bioma naturale a lui familiare, abbassando di 2 gradi la difficoltà di ogni suo tiro per nascondersi. Se si muove tanto veloce quanto un uomo in corsa, il Mimetismo perde parte dell'effetto, riducendo solo di 1 grado la difficoltà nel nascondersi. Facoltà.

#### Perforare ( 1 punto Prontezza )
Un attacco a distanza preciso e penetrante, che infligge 1 danno aggiuntivo se l'arma ha un'estremità appuntita. Azione.

#### Primo Soccorso
Spesso da solo, il cacciatore si è dovuto ingegnare per tenersi in vita. Sa creare impacchi medicamentosi con erbe che una persona normale considererebbe inutili, facendo recuperare 4 punti alla Riserva Vigore. Si deve tirare un dado a 20 facce per trovare le erbe; in base al bioma ed alla situazione la difficoltà varia, a discrezione dell'admin. Facoltà.

#### Ricaricare ( 1 punto Prontezza)
Quando si usa un'arma che normalmente richieredebbe un'azione per essere ricaricata (come nel caso di una balestra pesante) il cacciatore può invece ricaricare e fare fuoco come parte della stessa azione. Facoltà.

#### Bersagliare ( 2 punti Prontezza)
Se l'arma che usa per attaccare può sparare più colpi senza dover essere ricaricata (un arco o balestra a ripetizione), il cacciatore può scagliare più munizioni contro un bersaglio per aumentare le probabilità di colpirlo. Questa tecnica consuma 1d6+1 munizioni. La difficoltà dell'attacco è diminuita di un grado ma, in caso di successo, l'attacco infligge 1 danno in meno del normale. Azione.

#### Competenza nelle armi
Il cacciatore è addestrato ad attaccare con un tipo di armi, anche uno con cui sia già addestrato. Può scegliere tra armi leggere o medie. Se è già addestrato negli attacchi con quel tipo di armi diventa specializzato, abbassando di un ulteriore grado la difficoltà delle azioni con quell'arma. Facoltà.

#### Fendente ( 2 punti Prontezza )
Un attacco rapido con un'arma affilata o appuntita, dal quale è difficile difendersi. La difficoltà dell'attacco viene diminuita di 1 grado ma, in caso di successo, l'attacco infligge 1 danno in meno del normale. Azione.

#### Tiratore Scelto ( 2 punti Prontezza )
Se il cacciatore usa un'azione per prendere la mira, nel round successivo potrà compiere un tiro di precisione a distanza. La difficoltà dell'attacco verrà diminuita di 1 grado e, in caso di successo, esso infliggerà 4 danni aggiuntivi. Azione.

#### Tiro in Movimento ( 2 punti Prontezza )
Come parte della stessa azione, il cacciatore può muoversi di una distanza media e sparare un colpo verso un bersaglio ma la difficoltà dell'attacco viene aumentata di 1 grado. Azione.

#### Tiro Strategico ( 2 punti Prontezza )
Il cacciatore può effettuare un attacco a distanza contro due bersagli, l'uno a distanza ravvicinata dall'altro, come parte della stessa azione. Deve effettuare tiri separati contro ogni bersaglio, e la difficoltà di ogni tiro è aumentata di 1 grado. Azione.

#### Bombardare ( 3 punti Prontezza)
Se l'arma che usa per attaccare può sparare più colpi senza dover essere ricaricata (un arco o balestra a ripetizione), il cacciatore può colpire fino a tre bersagli alla volta, purchè adiacenti l'un all'altro. Deve effettuare tiri separati per ogni attacco e la difficoltà di ogni tiro è aumentata di 1 grado. Azione.

#### Legame con Compagno Animale Migliorato ( 5 punti Intelletto )
Dopo il tempo speso insieme, il cacciatore ha imparato ad usare la forza stessa della natura per comunicare con il suo compagno, riuscendo a dar vita ad un legame psichico tra se stesso e la creatura a lui fedele. L'animale inoltre sviluppa un'intelligenza pari a quella di un bambino umano, ed è possibile trasmettere immagini e sensazioni tramite il legame telepatico. I punti Intelletto vanno spesi solo la prima volta che ci si lega con la creatura. Facoltà.

#### Magia Druidica
Sfruttando il suo legame con la natura, il cacciatore ha imparato a incalanare l'energia primordiale presente nel mondo, ed usarla per incantesimi basilari. Il cacciatore ha accesso a varie magie che hanno a che fare con la natura e simili. 
*work in progress*

\page
# Demone
I demoni, creature provenienti da un altro piano, presenti nel nostro solo tramite legami con mortali o usando ampie risorse magiche. Ogni Demone deve o legarsi ad un mortale o consumare abbastanza energia o anime per non venir bandito dal piano materiale, tornando nell'Abisso. 
Ci sono vari tipi di demoni, ed ognuno assume una forma diversa quando vengono evocati nel nostro piano.

## Cose fighe che puoi fare

<div class='classTable'>
##### Le caratteristiche del Demone
| Caratteristica | Riserva Iniziale |
|:---:|:---:|
| Vigore | 7 |
| Prontezza | 7 |
| Intelletto | 14 |
</div>

<div class='descriptive'>
Oltre ai punti qui sopra hai 6 punti caratteristica da distrubuire come vuoi te.
</div>

#### Competenze
** Strumenti ** : kit da falsario. </br>
** Azioni ** : Scegli tre tra: Diplomazia, Nascondersi, Raggirare, Intimidire, Intuizione. </br>
** Armi ed Armature ** : Armi leggere. </br>

## Seconda forma
Per muoversi in pubblico molti demoni assumono forme di mortali, per cercare di confondere e sviare gli esorcisti, il loro vero ed unico nemico. 
Seppure da un punto di vista di bilanciamento anche i Demoni hanno dei limiti, possono essere distrutti solo se lanciati in un Vulcano magico (Mt. Piping Hot Suckhole, non so come l'abbiano tradotto in ita e non lo trovo con una veloce googlata). 

> ### ** Importante**
> La forma usata nel piano materiale va scelta ad inizio campagna, e non può essere cambiata se non con magie e rituali costosi. 

## Sbloccare nuove Abilità 
Ogni settimana passata, si guadagna un Punto Maestria(PM) da spendere per imparare nuove abilità speciali. Si inizia con due Punti Maestria. 

#### Creatura dell'Oscurità ( 1 punto Intelletto )
Essendo nato nell'abisso, è corretto pensare che le ombre siano alleate di ogni demone. Quando in semi-oscurità o oscurità totale, il tiro compiuto dal demone per nascondersi ha 2 gradi in meno di difficoltà. Azione.

#### Genio nella Lampada ( 3 punti Intelletto )
Grazie al tuo legame con il mortale, puoi nasconderti dentro di esso e diventare effettivamente immune ad ogni tipo di danno. Non puoi entrare con forza nel corpo di un mortale con il quale non hai un contratto.

#### Mille Volti. O meglio, Musi. ( 2 punti Intelletto )
Usando magia nera, il demone è in grado di trasformarsi agli occhi di tutti tranne altri demoni, esorcisti o persone legate a se stesso, in una creatura di taglia piccola, come un topo, gatto, cane o simili. La trasformazione dura per massimo 1h, dopodiché deve essere lanciata di nuovo. Azione.

#### Parole Tonanti
Grazie anche all'ausilio di magia nera, ogni minaccia fatta da un demone risulta più spaventosa di quella di un qualsiasi mortale. Vengono abbassate di 2 gradi tutte le prove per Intimidire le persone. Facoltà.

#### Parole Velenose
Dopo millenni dal primo contatto con il piano materiale, la parlantina dei demoni è conosciuta a tutti i mortali, ma non per questo è meno efficace. Vengono abbassate di 2 gradi tutte le prove per Raggirare le persone. Facoltà.

#### Persuasivo
Studiando i mortali e le loro caratteristiche, il demone si è oramai abituato a manipolarli come vuole, restando però fedele in parte a ciò che dice. Vengono abbassate di 2 gradi tutte le prove Diplomatiche con le persone. Facoltà.

#### Maestro delle Illusioni ( 3 punti Intelletto )
Grazie agli studi nelle arti oscure, il demone è in grado di creare illusioni, grandi massimo 2mx2m, che durano fino a 2h. Queste illusioni sono in grado di muoversi e essere fonte di suoni, ma ogni interazione con esse le rivelerà per ciò che sono realmente. Per capire se un qualcosa è un'illusione oppure no, bisogna fare un tiro su Percezione, che il proprietario dell'illusione contesterà con un tiro su Raggirare. Azione.
\page

#### Padronanza sul Fuoco ( 2 punti Intelletto )
Dopo anni passati a bruciare tra le fiamme dell'abisso, il demone ha imparato a sfruttarle a suo piacimento. Diventa immune ai danni da fuoco e può controllare fiamme preesistenti, infliggendo danni elementali se colpiscono creature o oggetti. Facoltà e Azione se si controllano le fiamme.

#### Sadico
Se le persone vicino al demone non hanno le Risorse al massimo, il demone può ricaricarsi le proprie attaccandoli con le parole, ruolando con l'obiettivo di farli sentire peggio di quanto non siano ora. 

#### Tormentatore ( 5 punti Intelletto )
Per invidia, odio o più semplicemente noia, il demone ha deciso di maledire una persona legandola a sè per l'eternità, lasciando un marchio indelebile su essa finchè il demone stesso non viene distrutto. Buona fortuna alla povera anima colpita da questa maledizione. Azione.

#### Contratto  ( ? punti Intelletto )
Le specifiche del contratto, spesa, fine e pagamento, son tutte da stabilire con un admin prima di poter essere offerte in game ad una vittima. </br>
Se questo contratto non viene rispettato l'anima del colpevole verrà condannata eternamente nell'abisso, aspettando di essere torturata personalmente dal demone che l'ha maledetta.

#### Presenza Diabolica
Grazie alla tua aura di malvagità, ogni creatura che interagisce con te a lungo subisce una penalità di 1 grado difficoltà in più ad ogni azione altruista che compie, e un bonus di 1 grado in meno ad ogni azione compiuta a scapito del prossimo. Facoltà.

#### Sto volando Jack! ( 7 punti Intelletto )
Padroneggiando il tuo sangue demoniaco, riesci a sfruttare la magia nera per farti crescere due ali momentanee sulla schiena, con le quali puoi portare un altro umanoide della tua taglia in volo, reggendolo con entrambe le mani; il limite del peso è gestito dal buonsenso. Le ali spariscono dopo 1h, ed hanno una velocità pari a un uomo in corsa. Azione.

# Roba a caso che non ho messo in ordine

<div class='descriptive'>

##### <div class='wide'>
|Grado difficoltà | Definizione | Numero bersaglio | Spiegazione |
| :--: | :--: | :--: | :--: |
|0 | Consuetudinaria | 0  | Chiunque può farcela, sempre
|1 | Semplice        | 3  | Quasi tutti possono farcela, sempre
|2 | Ordinaria       | 6  | Tutti possono farcela con una certa attenzione
|3 | Onerosa         | 9  | C'è il 50% di farcela con una certa attenzione
|4 | Difficile       | 12 | Chi è addestrato ha il 50% di farcela
|5 | Impegnativa     | 15 | Anche chi è addestrato di solito fallisce 
|6 | Impressionante  | 18 | Le persone normali non ce la fanno quasi mai
|7 | Spaventosa      | 21 | Impossibile senza capacità o grande tenacia
|8 | Eroica          | 24 | Un'impresa degna di essere narrata per anni
|9 | Leggendaria     | 27 | Un'impresa leggendaria, ricordata per una vita
|10| Impossibile     | 30 | Impossibile per le personi normali (sebbene l'azione in sè non sfidi le leggi della fisica)
</div>
</div>

<div class='descriptive'>

##### Armature
| Tipo | Protezione | Costo in Vigore/h | Riduzione di Prontezza se indossata |
| :-- | :--: | :--: | :--: |
| Leggera | 1 | 1| 2 |
| Media | 2 | 3 | 3 |
| Pesante | 3 | 2 | 5 |

##### Armi
| Tipo | Danno | Mod grado difficoltà  | Esempi |
| :-- | :--: | :--: | :--: |
| Leggera | 2 | -1 |  Cerbottana, coltello, frusta, lama da polso, pugnale, stocco|
| Media | 4 | 0 | Arco, ascia da battaglia, balestra, flagello, martello, spada, mazza |
| Pesanti | 6 | +1 | Ascia a due mani, balestra pesante, maglio, picca, spadone |

</div>

> ### Scudi
>Che fa lo scudo? Diminuisce di 1 grado la difficoltà nelle azioni difensive di Prontezza.

</pre></code></details>

**Comment by FabrizioFioretti** [comment]
Did someone respond to you? I am having the same problems

**Comment by Rikart1397** [comment]
> Did someone respond to you? I am having the same problems

The problem was with the last tables, I had to rewrite the whole file with the exception of them, and it worked fine. 

It seemed kinda glitchy and I don't really know why it worked afterwards, but it works.
