### ISSUE TITLE
Title cannot be changed?

### ISSUE THREAD

**Issue by rob2ee** [stolksdorf/homebrewery#769]
## Before you submit

- Support questions are better asked on the subreddit [r/homebrewery](https://www.reddit.com/r/homebrewery/)
- Read the [contributing guidelines](https://github.com/stolksdorf/homebrewery/blob/master/contributing.md).
- If it's an issue, please make sure it's reproducible
- Ensure the issue isn't already reported.

*Delete the above section and the instructions in the sections below before submitting*

## Description

If this is a *feature request*, explain why it should be added. Specific use-cases are best.

For *bug reports*, please provide as much *relevant* info as possible.

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
In the gray bar right under the "NaturalCrit" and "The Homebrewery" text at the top of the page (the same gray bar that has the "Editor", "PHB", "Tables", and "Print" menus), there is a hamburger button you can click to expand the brew metadata. You can change the title of your brew there.

![image](https://user-images.githubusercontent.com/10881828/47067115-7f1c9e80-d1e8-11e8-882a-254458ede547.png)

**Comment by calculuschild** [comment]
This looks like it's solved. Closing.
