### ISSUE TITLE
Uh, I might be just stupid, but uh...

### ISSUE THREAD

**Issue by PhoenixFyre078** [stolksdorf/homebrewery#771]
I need some help with this table. I want it to stretch horizonally accross the screen, and I feel like it's really obvious, what I'm doing wrong. Screenshot:
![the homebrewery - naturalcrit - mozilla firefox 10_9_2018 9_26_16 pm](https://user-images.githubusercontent.com/44011970/46709858-2dce4700-cc0b-11e8-9f17-5666ebeb735e.png)

**Comment by ericscheid** [comment]
I've recreated that part which is visible in the screencap but it is behaving correctly. 

Could you post the share link for this brew? Maybe there is a style tag elsewhere confusing things.

**Comment by PhoenixFyre078** [comment]
Sure thing. Uh.. if i can figure it out. should be as easy as that right?  https://homebrewery.naturalcrit.com/share/BkLr5AHqQ

**Comment by ericscheid** [comment]
OK, that's the link.

Hmm ... the table is showing as wide in my browser. What does the brew look like in your share link? (i.e. not editor tab)

**Comment by PhoenixFyre078** [comment]
It looks the same as the screenshot. The Spell slots are clipping through the barrier because it's too small. So from what youre saying it might be just my browser?

**Comment by PhoenixFyre078** [comment]
I'll try chrome instead

**Comment by calculuschild** [comment]
Seems to be solved. Closing.
