### ISSUE TITLE
Work the title with other colors (white, red, etc.)

### ISSUE THREAD

**Issue by marcuswallace1991** [stolksdorf/homebrewery#775]
Hello guys. 
I'd like to change the normal colour of the written, because I need a different colour for the first page (for the different color of the cover). 
Can someone help me? Ty

**Comment by ericscheid** [comment]
You can change the styles via CSS, and you can target a given page by including a #p<n> selector, where <n> is the page number.

Thus:

```
<style>
.phb#p1 {color: red;}
</style>
```

This won't affect the headings though, so you might want

```
<style>
.phb#p1 h1,
.phb#p1 h2,
.phb#p1 h3,
.phb#p1 h4,
.phb#p1 h5,
.phb#p1 {color: red;}
</style>
```

**Comment by marcuswallace1991** [comment]
Ty very much!

**Comment by HeruAsatru** [comment]
the `p1` after the `.phb#` is the page. so if you want to change the color of the headers on, say, page 1 and 5, you need to do the following:

```
<style>
.phb#p1 h1,
.phb#p5 h1,
.phb#p1 h2,
.phb#p5 h2,
.phb#p1 h3,
.phb#p5 h3,
.phb#p1 h4,
.phb#p5 h4,
.phb#p1 h5,
.phb#p5 h5,
.phb#p1,
.phb#p5 {color: red;}
</style>
```

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
