### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by PSDNDFUN** [stolksdorf/homebrewery#777]
I guess this isn't a large problem like everything else but how do you get homebrewery to upload pictures from your hard drive?  If that is impossible can you do it with google drive?  I know it says imgur but I don't use imgur.  I was just wondering the way to do it without it.  Sorry if this was covered before.

**Comment by PSDNDFUN** [comment]
Yeah I tried google drive but for some reason it didn't work out for me.  Did you try something you didn't mention?  Do I have to change something in the settings?  Thank you for your response.

**Comment by AlexeySachkov** [comment]
> Yeah I tried google drive but for some reason it didn't work out for me. 

Could you please explain "didn't work out for me"? Are you able to get a link to your image hosted on google drive? If so, could you please paste "share" link to your brew here?

> Did you try something you didn't mention?

No, I listed all steps I performed to get it working

>  Do I have to change something in the settings?

Not sure, I expect that all should work fine out of the box.

**Comment by PSDNDFUN** [comment]
For the brew link I just tested it on the main page or the beginning page for the brew so http://homebrewery.naturalcrit.com/
nothing spectacular.  I didn't save it or anything.  Instead for the picture it is just the picture of a broken image or something.

I guess I can try imgur or something.

**Comment by calculuschild** [comment]
Imgur is known to work. For Google Drive there are some weird things you have to do to get a direct link to your image. You can use a tool such as https://gdurl.com/ to get a direct image link that should work.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @PSDNDFUN
