### ISSUE TITLE
Add header at the bottom of the page 

### ISSUE THREAD

**Issue by marcuswallace1991** [stolksdorf/homebrewery#778]
Hi, I want add header at the bottom of the page different from classical "page Number and Part 1/ blabla", because I need add a long sentece. 

For example, I'd like to do the same in this example 
http://homebrewery.naturalcrit.com/share/ryWPitPlig 
(I want add note at bottom of the page as the note in this example, under the yellow lane "Designed by /u/QalarValar[↗] using The Homebrewery[↗]. Derived from /u/Rex_Gunn's Wishcrafter Sorcerous Origin[↗]")

**Comment by marcuswallace1991** [comment]
Can anyone help me?

**Comment by AlexeySachkov** [comment]
Hi @marcuswallace1991,

Looking at the [source](http://homebrewery.naturalcrit.com/source/ryWPitPlig) of the brew you mentioned I found how it is done there. The following html-block is added to the end of the page:
```
<div class='footnote' STYLE="position:absolute; TOP:1035px; LEFT:50px; WIDTH:520px; color:#C9A968;">Designed by [/u/QalarValar](http://reddit.com/u/QalarValar)[↗] using [The Homebrewery](http://homebrewery.naturalcrit.com/)[↗]. Derived from [/u/Rex_Gunn's Wishcrafter Sorcerous Origin](https://www.reddit.com/r/UnearthedArcana/comments/5idk0i/wishcrafter_sorcerer/)[↗]</div>
``` 

Position of the block is calculated using offsets in pixels starting from top left corner of the containing page.

By default links will be blue and underlined. To change colors add the following snippet (somewhere in the beginning of your brew):
```
<style>
a    {color:#C9A968;}
a    {text-decoration:none;}
</style>
```

BTW, there is a [subreddit for homebrewery](https://www.reddit.com/r/homebrewery/) where you can also ask for help. AFAIK, @HeruAsatru (u/Thurse) is active there.

**Comment by marcuswallace1991** [comment]
Ok, ty very much for the help! I solved the problem

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
