### ISSUE TITLE
Why does it underline words?

### ISSUE THREAD

**Issue by PSDNDFUN** [stolksdorf/homebrewery#780]
I typed in the word Defaced and it underlined it for some reason.  Why this word?

**Comment by HeruAsatru** [comment]
the homebrewery doesn't have spell checking, so i would assume you activated it in chrome, and chrome is underlining it.

in chrome, click on the three dotes in the top right corner, select "settings". scroll down and click "advanced". scroll further down to "Languages" and "Spell Check". See if it's activated and turn it off if you don't want it. You can also add "Defaced" as an accepted word via "Customised spelling"

**Comment by calculuschild** [comment]
Assuming this was solved since we haven't heard anything back. Closing.

@PSDNDFUN If you are still experiencing this issue, feel free to reopen and provide information.
