### ISSUE TITLE
No shadows when printing to pdf

### ISSUE THREAD

**Issue by Dugahst** [stolksdorf/homebrewery#783]
Currently when I print my brew as a pdf, none of the shadowing comes out.

[Image](https://i.imgur.com/MViPvFc.jpg)

This is using chrome and i've tried various DPI settings and both with 'background' images selected and not.

The preview reflects that there is no shadowing, but if i close the print panel and scroll through the pages it shows it in the browser.

**Comment by Dugahst** [comment]
Thank you, looks like it worked beautifully!

**Comment by HeruAsatru** [comment]
Glad I could help. Please close this issue.

**Comment by calculuschild** [comment]
FYI, the shadows _should_ be printing without needing that extra bit of code now. Can we verify that that the latest update has that working again?

**Comment by calculuschild** [comment]
Closing this. The shadows work fine now from my end. Yay!
