### ISSUE TITLE
Metadata can't be edited

### ISSUE THREAD

**Issue by HeruAsatru** [stolksdorf/homebrewery#795]
Metadata on a brew can't be edited. Input into Textboxes is not possible. Clicking the checkboxes also yields no result.

Things I tried that didn't work:
- Tried normal and incognito mode.
- No difference between new and existing brews.

Console output:
Trying to type in the title input or the description textarea, or clicking one of the checkboxes, gives the following error in the dev console:

```
Uncaught TypeError: Cannot read property 'target' of undefined
```

**Comment by calculuschild** [comment]
Interesting. Something in Stolksdorf's changes to v2.8.0 must have renamed a variable somewhere. I will look into it.

**Comment by calculuschild** [comment]
Found the issue. Try it now.

**Comment by AlexeySachkov** [comment]
I'm able to update description of my brews now

**Comment by HeruAsatru** [comment]
Yup, works, thank you very much!
