### ISSUE TITLE
Problem with press

### ISSUE THREAD

**Issue by Marcobertini6** [stolksdorf/homebrewery#798]
Hi, 
I printed my Homebrew and I have a problem with white empty spaces that appear in the page. I choose "Letter" option in print page, and in the print Preview I don't see white space and any problems. But when I print it's a disaster.  
Can you help me? 
Ty
![prova](https://user-images.githubusercontent.com/44923954/48301898-095cd780-e4f5-11e8-8983-a70e9adfcf07.jpg)

**Comment by calculuschild** [comment]
Which size paper does your printer actually use? Is it A4?

**Comment by Marcobertini6** [comment]
![formato](https://user-images.githubusercontent.com/44923954/48305266-dc75e800-e527-11e8-996d-a51ce71d5c4e.jpg)
No Letter! (I add the photo)

**Comment by calculuschild** [comment]
Yes, so you are telling your printer to use Letter, but what size is the actual sheet of paper? I see you don't have English as your default language, so I assume the paper in your printer is actually A4, which is longer than Letter. Even if you tell the printer to print Letter size, the physical paper in your printer is probably A4.

You can change the format of your document to be taller and thinner, which will better match the A4 sheet size if you click the "Print" tab and then "A4 Pagesize". It will add a small bit of code to your homebrew so it fits on the different size paper.

![image](https://user-images.githubusercontent.com/5878534/48306518-0e775200-e508-11e8-832e-c3a7037f75c8.png)

**Comment by Marcobertini6** [comment]
I didn't see it! Ty very  much! 
yes the language is italian =) 
Ok, I see if I insert the code all pages change resolution. Now I must adapte all the pictures but it is enough? Now it will work? 
Ty very much for the help, very helpful!!!!!

**Comment by calculuschild** [comment]
Glad I could help. I'm going to go ahead and close this. If you have more questions you can open this back up.

**Comment by Marcobertini6** [comment]
Ty, It's better but there is a little space white in bottom of the page (0.2-0.3cm), in which way I can avoid this?
