### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wkramer0615** [stolksdorf/homebrewery#98]
Greetings,

I recently discovered your Homebrew page design site and I am eager to begin using it to create my own home brew pages.  I would prefer to create a more digest-styled version with the same fonts, design and background, a la the first set of 4E Essentials books.  Is it possible to do so with your Homebrew design, or am I restricted to the two-column design layout?

I truly appreciate all the work that you have put into this template, and as soon as I am able I would be very happy to "buy you a beer" for all of your hard work; maybe even a whole six-pack.

I look forward to hearing from you.  

Thanks again,

William

  **Browser Type/Version**: [Google Ultron v90.01]

**Operating System**: [GLaDOS v34.5.8]

**Issue Description**: [The thing won't thing]

**Markdown code to reproduce**:

```
# thing
> thing 2
```

**Related Images** :

**Comment by stolksdorf** [comment]
Thank you for the kind words, they mean a lot. I think I have a simple solution for you. try adding this bit of code at the top of your brew.

```
<style>
  .phb>*{ column-span : all };
</style>
```
